department-of-veterans-affairs/content-build

- src/site/layouts/va_form.drupal.liquid
Adds an alert to forms rendered by forms detail page with an issue date before 3/1/2022
closes https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11022
Tested from local preview build and reviewed in review instance
1. Navigate to form 22-5490 from find-forms
- Observe that the form is unchanged, there is no alert
2. Navigate to form 10-0386/
- Observe that the alert renders as expected
> Adds alert to old form detail pages

- src/site/stages/build/drupal/page.js
The Lovell VA Policies page was missing its switch link. This was due to some page logic where it adds in a breadcrumb path if it's missing, which inadvertently removed any properties that were `breadcrumb` or `url`. This change keeps any other properties already there to preserve that data, including switch links.
closes [#11691](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11691)
Visually, see below.
What needs to be checked to prove this works?
Build Lovell locally and check the [Lovell VA Policies page.](http://localhost:3002/lovell-federal-va-health-care/policies/) The switch link should be at the top of the page.
What needs to be checked to prove it didn't break any related things?
Check the Lovell Tricare Policies page (the switch link) and other Lovell pages …
> [VA-11691] Keep Switch links for pages with missing breadcrumbs

- src/site/stages/build/drupal/static-data-files/generate.js
Closes https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11658
This PR is a follow-on to [a previous PR](https://github.com/department-of-veterans-affairs/content-build/pull/1363) that implemented essentially the entirety of the heavy lifting regarding the caching of static data files.
The logic we ultimately needed (not implemented by previous PR but implemented by this PR) is to pull from Drupal in either of these situations:
1. `--pull-drupal` flag is present
2. The cached data found
Because the cache never previously existed for these static data files, the second condition above would have always been true, and the build would have attempted to pull from Drupal. Since review instances cannot pull from Drupal (no SOCKS access), we cannot have this situation. …
> VACMS-11658: Phase 2 of static-data-file caching

- src/site/includes/common-tasks.drupal.liquid
This PR swaps the background colors of the Search / Top links section of the new homepage design.
closes department-of-veterans-affairs/va.gov-cms/issues/11831
Sibling PR:  https://github.com/department-of-veterans-affairs/vets-website/pull/22945
Visually / manually checking again screenshots in ticket. 
Navigate to `/new-home-page` and see the Search / Top Links. Search block should have white background. Top Links menu should have light blue background.
In both mobile and desktop, 
- [n/a] Events are logged appropriately
- [n/a] Documentation has been updated, if applicable
> 11831 Switch background colors for new homepage search section

- src/site/stages/build/drupal/process-lovell-pages.js
Lovell federal pages should be checked if they have `va` in the CMS URL. This could potentially be creating a bug where federal pages aren't being properly cloned for the Tricare side, hence why so many of those pages have correct menu links but no actual pages.
This PR checks if a page is a Federal page, and if the URL is already the opposite of the page variation being built (for example, the Tricare variation of a federal page but it already has `va` in the URL). This resets the URL to remove the variation so it can have the proper URL set and go through the rest of the page build steps without issue.
relates to [#11026](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11026)
Confirmed it locally.
Rebuild Lovell locally with `yarn build --pull-drupal …
> Fix URLs for Lovell federal pages with 'va'

- src/site/includes/hero.drupal.liquid
Adds new link to “Learn how an account helps you” link in the hero section of `/new-home-page`
closes department-of-veterans-affairs/va.gov-cms/issues/11771  
Manually verified URL of link. Page is not yet published. (see Preview: http://preview-prod.vfs.va.gov/preview?nodeId=51915)
* https://prod.cms.va.gov/resources/creating-an-account-for-vagov
Mouse over link or check page source. Observe that the href attribute value of link is: "/resources/creating-an-account-for-vagov"
> 11771 adds account info link to new homepage

- src/site/assets/robots.txt
Closes https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11989
> VACMS-11989: disallow new lovell paths from robots.txt

- src/site/stages/build/drupal/home.js
~~BLOCKED:  do not merge until~~ Dave provided Chris J signoff: https://dsva.slack.com/archives/C03NSH4SLQY/p1671475928807869
closes department-of-veterans-affairs/va.gov-cms/issues/11652
Blocked by merge of https://github.com/department-of-veterans-affairs/content-build/pull/1406
Manual testing via building content-build locally and seeing the page builds as expected still. 
Will need to be verified in production to be 100% sure.
- Build content-build locally and seeing the page builds as expected still. 
-Will need to be verified in production to be 100% sure.
- This change has little to no risk of effecting other things.
What variations of circumstance thes (users, …
> 11652 remove environment conditional for building new homepage in prod

- script/github-actions/check-broken-links-blocks.js
- script/github-actions/check-broken-links.js
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12040
This reverts these scripts back to older, deprecated syntax to restore broken link checking. A follow-up ticket will be made to migrate the scripts to become proper custom actions.
> Revert to older output setting syntax for broken link checking.

- src/site/layouts/health_care_region_page.drupal.liquid
closes [#11940](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11940)
Lovell TRICARE region page: http://localhost:3002/lovell-federal-tricare-health-care/
Lovell TRICARE Facility Page
http://localhost:3002/lovell-federal-tricare-health-care/locations/captain-james-a-lovell-federal-health-care-center/
Lovell VA region page
http://localhost:3002/lovell-federal-va-health-care/
Lovell VA facility page
http://localhost:3002/lovell-federal-va-health-care/locations/captain-james-a-lovell-federal-health-care-center/
Non-Lovell region page
http://localhost:3002/new-mexico-health-care/
Non-Lovell facility page
http://localhost:3002/new-mexico-health-care/locations/raymond-g-murphy-department-of-veterans-affairs-medical-center/
- …
> Fix spotlight section header for lovell region pages

- src/platform/static-data/footer-links.json
closes  https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12012
Manual testing locally
Confirm bottom rail of footer link is changed in production to va.gov/accessibility-at-va/
> 12012 change footer rail accessibility link

- src/site/includes/operatingStatusFlagsLinks.drupal.liquid
There's extra white space above the Facility operating status alerts, which is removed by getting rid of the extra top margin. This change is made on all three of the different operating status alerts.
closes [#12023](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12023)
Visual, see below screenshots.
**What needs to be checked to prove this works?** The operating status focus indicator has equal space around all sides. 
**What needs to be checked to prove it didn't break any related things?** No other focus indicators now have unequal spacing.
1. Do a local build and go to a facility page, like [Gainesville](https://www.va.gov/north-florida-health-care/locations/gainesville-twenty-third-avenue-va-clinic/)
> VA-12023: Remove white space above facility operating status alerts

- src/site/layouts/health_care_region_page.drupal.liquid
closes [#11967](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11967).
Removes "manage health block" for Lovell TRICARE system. Updates title of "manage healthy block" for Lovell VA system. Unchanged for other VA system pages.
Lovell TRICARE system, no block
Lovell VA system, updated title ("Manage your VA health online")
Non-Lovell VA system, no change to title
**What needs to be checked to prove this works?**  
- View Lovell system pages for TRICARE and VA.
- http://localhost:3002/lovell-federal-tricare-health-care/
- http://localhost:3002/lovell-federal-va-health-care/
**What needs to be checked to prove it didn't break any related things?**  
- View a system page for a non-Lovell VA system
- http://localhost:3002/new-mexico-health-care/
> VACMS-11967 update manage health block for lovell system pages

- src/site/tests/lovell/switch-links.cypress.spec.js
Lovell switch links are important to test, both as a feature and a quick health check of Lovell's structure. This adds Cypress tests to some of the key Lovell pages.
closes [#11995](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11995)
relates to [#11026](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11026)
Visual, Cypress, see local results below.
**What needs to be checked to prove this works?** Do a local Lovell build with `yarn build --pull-drupal --drupal-address=https://main-liqqgmzl7tsyfbwyulbkuborufuuttav.demo.cms.va.gov/`, then run cypress tests locally with `yarn cy:run`.
**What needs to be checked to prove it didn't break any related things?** Click through a few other Lovell pages to ensure they're still working normally.
**What …
> VACMS-11995 Add Lovell switch link Cypress tests

- src/site/stages/build/drupal/process-lovell-pages.js
- src/site/stages/build/drupal/tests/lovell/fixtures/listing-pages/federal/events.json
- src/site/stages/build/drupal/tests/lovell/fixtures/listing-pages/federal/news.json
- src/site/stages/build/drupal/tests/lovell/fixtures/listing-pages/federal/stories.json
- src/site/stages/build/drupal/tests/lovell/fixtures/listing-pages/tricare/events.json
- src/site/stages/build/drupal/tests/lovell/fixtures/listing-pages/tricare/news.json
- src/site/stages/build/drupal/tests/lovell/fixtures/listing-pages/tricare/stories.json
- src/site/stages/build/drupal/tests/lovell/fixtures/listing-pages/va/events.json
- src/site/stages/build/drupal/tests/lovell/fixtures/listing-pages/va/news.json
- src/site/stages/build/drupal/tests/lovell/fixtures/listing-pages/va/stories.json
- src/site/stages/build/drupal/tests/lovell/fixtures/sidebar.json
- src/site/stages/build/drupal/tests/lovell/listingPages.unit.spec.js
closes https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11996
Listing pages (stories, events, news) for Lovell Health Care are created by combining the entities from the Lovell Federal listing pages with the entities from the Lovell Tricare and Lovell VA listing pages. Entities on Lovell Federal should ultimately be displayed on both Lovell Tricare and Lovell VA listing pages so that a listing page for Lovell Tricare, for example, is comprised of entities that are specific to Tricare _combined with_ entities that are defined at the Federal level.
This PR adds unit tests to confirm that the Lovell-specific processing correctly handles things as described above.
This PR is entirely focused on creating tests. The tests all pass with the created fixtures.
Locally
1. `yarn …
> VACMS-11996: adds unit tests for Lovell listing pages

- src/site/layouts/health_care_local_facility.drupal.liquid
Patient satisfaction scores aren't available for Tricare pages, but the widget for them is still on the pages. This causes an infinite spinner since it waits for data that will never come.
This pull request puts a conditional around the facility satisfaction scores so they only appear for appropriate endpoints. Tricare pages don't have the widget, and the functional VA ones have the widget (it doesn't load properly on my device only due to a local API issue, it won't affect the overall functionality).
closes [#12069](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12069)
**What needs to be checked to prove this works?** Lovell Tricare location pages need not to show the patient satisfaction scores widget.
**What needs to be checked to prove it didn't break any related …
> VA-12069: Only show patient satisfaction scores for vha API endpoints

- src/site/stages/build/drupal/process-lovell-pages.js
The "opposite variant" URL checks need to be applied to menu links as well as page links. This change puts that logic into a function that can be applied to both and fix the broken Tricare links that would otherwise bring links back to the VA pages.
closes [#12011](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12011)
relates to [#11026](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11026)
Visual testing. See URLs from the highlighted menu links in the bottom left of each screenshot.
Tricare menu links, and they link to other Tricare pages.
The menu links on VA pages still link to VA pages, and the switch links still work …
> VACMS-12011 Fix Lovell Tricare Menu links

- src/site/includes/common-tasks.drupal.liquid
This PR adds attributes of "role='list'" to the new Homepage's Other Search Tools and Top Pages list of links for improved accessibility
closes department-of-veterans-affairs/va.gov-cms/issues/11392
Check the UL elements for both the Other Search Tools and Top Pages lists and validate that they both have the role="list" attribute. 
- [n/a] Events are logged appropriately
- [n/a] Documentation has been updated, if applicable
> 11392 adds role=list to search tools and top pages lists

- src/site/includes/news-spotlight.drupal.liquid
The ordering of the News Spotlight section of the new homepage needed to be reversed to allow the text content to come before the image in the markup, thus allowing a better screen reader experience. 
The solution was to reverse the flec-order of the containing row and then to place the image column second in the mark up. This allowed for screenreaders to catch to relavent h2 before attempting to read the image alt-text.
closes department-of-veterans-affairs/va.gov-cms/issues/12100
closes department-of-veterans-affairs/va.gov-team/issues/51185
Manual visual testing to assure order is visually the same, but semantically reversed
Assure that visually the image comes before the text content, but in the mark up, the text content comes first.
- [n/a] Events are logged appropriately
- [n/a] …
> 12100 Change order of new spotlight block columns for better 508

- src/site/includes/news-spotlight.drupal.liquid
This PR adds additional screen reader-only text to specify the destination of the Call To Action link at the end of the Homepage News Spotlight section.
closes department-of-veterans-affairs/va.gov-cms/issues/11823
Validate that Screen reader-only text has been added that reads "Read the full article about [Article Title]"
- [n/a] Events are logged appropriately
- [n/a] Documentation has been updated, if applicable
> 11823 adds sr-only text for news spotlight cta

- src/site/paragraphs/facilities/list_of_link_teasers_facility.drupal.liquid
closes [#12064](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12064)
Updates the "In the spotlight" header to be an h2, with existing h3 styles.
Verified that the header size for this section was an h2 instead of h3, but styled as it was still an h3.
- Check system pages for Lovell TRICARE, Lovell VA, and non-Lovell system and see the "In the spotlight" is the correct size while also being a semantically correct h2.
http://localhost:3002/lovell-federal-tricare-health-care/
http://localhost:3002/lovell-federal-va-health-care/
http://localhost:3002/new-mexico-health-care/
> VACMS-12064 update "in the spotlight" facility header

- .github/workflows/continuous-integration.yml
Pointing non-production builds at Staging rather than https://cms-content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov
> Point nonprod builds at Staging.

- .github/workflows/continuous-integration.yml
Cut logspam by not showing progress in the S3 upload.  This is already in-place on the content-build, but not for the CI steps apparently.
> Don't show progress when uploading build.

- src/site/stages/build/drupal/tests/lovell/fixtures/generateSidebar.js
- src/site/stages/build/drupal/tests/lovell/listingPages.unit.spec.js
- src/site/stages/build/drupal/tests/lovell/sidebarLocations.unit.spec.js
- src/site/stages/build/drupal/tests/lovell/utils.js
Adds unit tests to confirm existence and proper sorting of facility-location links in the sidebar menus on Lovell pages.
The structure here is as follows:
- Added some fixture code to generate sidebar data for various cases (i.e. edge cases).
- Generate sidebar data to plug into an otherwise empty `drupalData` object to test only this sidebar data.
- Call `processLovellPages` for each test case and confirm the generated sidebar is as expected (essentially, the initial data moved into new sidebar properties under `drupalData.data`.
closes https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11997
relates to https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11650
This PR introduces some new tests. They pass locally and need to pass in the review instance …
> VACMS-11997: Adds unit tests for lovell sidebar locations

- .github/CODEOWNERS
Add cms-infrastructure as an overall codeowner, in order to facilitate PRs.
> Add cms-infrastructure as overall codeowner.

- src/site/layouts/va_form.drupal.liquid
This PR removed entirely the Find Forms results pages.
closes department-of-veterans-affairs/va.gov-cms/issues/12138
Manual testing
1. Visits /find-forms  and perform a search for any form.
2. Then click thru the form detail page.
3. Then validate Acceptance Criteria from issue department-of-veterans-affairs/va.gov-cms/issues/12138
> 12138 Removed PDF Expiration Alert

- src/site/includes/common-tasks.drupal.liquid
- src/site/includes/email-update-signup.drupal.liquid
- src/site/includes/hero.drupal.liquid
- src/site/includes/news-spotlight.drupal.liquid
relates to #12065
Local testing in console with AdSwerve
Click the changed links and verify the GA events work with either the AdSwerve extention or dev tools network tab
> Updated GA events

- .github/workflows/a11y.yml
This reverts a part of #1140 which changed how certs are handled in content-build workflows. We're restoring the working behavior for the a11y workflow.
> Restore older version of cert used for a11y container.

- src/site/filters/liquid.js
- src/site/paragraphs/collapsible_panel.drupal.liquid
Fix accordion header levels on Burial Benefits detail pages. Allows for the use of h5 header levels when for collapsible panel components
closes 12183
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12183
1. Navigate to the following links and verify that header levels are correct:
- /burials-memorials/eligibility/
- /burials-memorials/eligibility/burial-in-private-cemetery/
- /burials-memorials/memorial-items/headstones-markers-medallions/
2. Only accordion components on these pages should see changes
> Entity ID for h5s added

- src/site/includes/footer.html
This PR adds the capability to respect a `minimalFooter` parameter in the [application registry](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/applications/registry.json). When present, the `footerNav` element will have the attributes `data-minimal-footer=true`, which otherwise defaults to false.
Paired with [this PR to the footer application](https://github.com/department-of-veterans-affairs/vets-website/pull/23135), they will cause the footer to look like this:
| mobile | desktop |
| ------- | -------- |
| ![Screenshot 2023-01-23 at 16 49 26](https://user-images.githubusercontent.com/101649/214177821-3b6335e4-704d-437d-a7db-752cb8a16392.png) | ![Screenshot 2023-01-23 at 16 49 31](https://user-images.githubusercontent.com/101649/214177859-045c8a0f-6826-4bf7 …
> Add registry variable for minimal footer

- .github/workflows/continuous-integration.yml
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11402
The CI workflow contains a job for running Cypress tests. This job runs as root and takes possession of some shared directories, which are then left behind when the job finishes.
Later jobs which do not run as root - which is almost all of them - can no longer use the instance in question. This causes job failures elsewhere in other content-build workflows.
This PR adds spinning up an on-demand runner for the Cypress tests, to isolate the Cypress job's effects on the directory. The runner is torn down after use.
This same code was added to a test workflow, which ran successfully as far as Cypress was concerned: https://github.com/department-of-veterans-affairs/content-build/actions/runs/4026878503
This PR will run …
> Spin up an ondemand runner to use for Cypress tests.

- src/site/includes/news-spotlight.drupal.liquid
Modifies new promo block GA events for the new home page
closes #12065
Local testing
Verify that GA events are firing correctly from new-home-page
> updated GA events for news promo component

- src/site/blocks/promo.drupal.liquid
- src/site/layouts/landing_page.drupal.liquid
Updates header levels on the benefit hub rail without changing visual presentation
closes #12169
- Navigate to a benefit hub landing page (eg /health-care) 
- Verify that header levels are appropriate for hub rail.
- Verify that there are no visual changes
> Adjusted header levels bene hub-rail (12169)

- .github/workflows/a11y-heading-order.yml
- .github/workflows/a11y.yml
- .github/workflows/content-release.yml
- .github/workflows/continuous-integration.yml
- .github/workflows/deploy-content-preview-server.yml
- .github/workflows/manual-deploy-dev-staging.yml
Relates to https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11402
We are looking to isolate the runners which run the Continuous Integration:Cypress Tests job from all other jobs.
#1450 moved the Cypress Tests job to use its own on-demand runner. Previously it had specified the `asg` label, picking a runner from the ASG pool.
This PR moves any job running self-hosted to use the `asg` label. This should prevent all these jobs from ever using the same runner as the Cypress Types job.
> Specify ASG label for all self-hosted that is not on-demand.

- src/applications/registry.json
The breadcrumb on the [Health Care application](https://www.va.gov/health-care/apply/application/introduction) has incorrect casing for the "Health care" segment. It currently reads "Health Care", but should have a lower case "c" on "care". This PR updates the breadcrumb overrides for the application to correct this casing.
- department-of-veterans-affairs/va.gov-team#31767
> Fix incorrect breadcrumb casing for health care application

- .github/workflows/content-release.yml
Reverts work from #1450 and #1452 out for content release.
> Remove usage of asg runners from content release.

- .github/CODEOWNERS
- .github/workflows/a11y-heading-order.yml
- .github/workflows/a11y.yml
- .github/workflows/content-release.yml
- .github/workflows/continuous-integration.yml
- .github/workflows/deploy-content-preview-server.yml
- .github/workflows/manual-deploy-dev-staging.yml
Response to issues with #1450 and #1452. Moves back to no longer specifying the `asg` label for most self-hosted jobs that are not on-demand. 
Cypress testing in a11y.yml will continue to use the `asg` since it uses the most runners by far, by volume.
This PR also adds cms-infrastructure and FE COP as co-owners of the files currently previously owned by qa-standards.
> Revert out most usage of asg instances for job running; grant cms-infra and FE COP co-ownership of qa-standards files.

- src/site/stages/build/drupal/tests/lovell/fixtures/listing-pages/federal/events.json
- src/site/stages/build/drupal/tests/lovell/fixtures/listing-pages/federal/news.json
- src/site/stages/build/drupal/tests/lovell/fixtures/listing-pages/federal/stories.json
- src/site/stages/build/drupal/tests/lovell/fixtures/listing-pages/tricare/events.json
- src/site/stages/build/drupal/tests/lovell/fixtures/listing-pages/tricare/news.json
- src/site/stages/build/drupal/tests/lovell/fixtures/listing-pages/tricare/stories.json
- src/site/stages/build/drupal/tests/lovell/fixtures/listing-pages/va/events.json
- src/site/stages/build/drupal/tests/lovell/fixtures/listing-pages/va/news.json
- src/site/stages/build/drupal/tests/lovell/fixtures/listing-pages/va/stories.json
- src/site/stages/build/drupal/tests/lovell/fixtures/sidebar.json
- src/site/stages/build/drupal/tests/lovell/listingPages.unit.spec.js
- src/site/stages/build/drupal/tests/lovell/utils.js
Lovell naming conventions have changed. This PR updates mock data and tests to align with the changed naming conventions.
/lovell-federal-va-health-care
/lovell-federal-tricare-health-care
/lovell-federal-health-care-va
/lovell-federal-health-care-tricare
Lovell Federal VA health care
Lovell Federal TRICARE health care
Lovell Federal health care - VA
Lovell Federal health care - TRICARE
closes https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12241
Ran updated unit tests locally. All passed.
What needs to be checked to prove this works?
See original issue
> VACMS-12241: Updates Lovell mock data and tests to align with name change

- src/site/assets/robots.txt
Robots.txt has some disallow paths for Lovell to accommodate dual state. Those paths have changed, and this PR updates to accommodate those changes.
closes https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12382
This is difficult to test. It's a very small change and I'm comfortable pushing this with a few eyes confirming we all agree. We should then confirm in production that the file is what we expect.
See original ticket.
> VACMS-12382: Updates robots.txt with new Lovell disallow paths.

- .github/workflows/content-release.yml
The GovDelivery callback is not critical to the Content Release process to the point that it should cause the job to fail.
> Do not fail the job if the GovDelivery callback fails.

- src/site/components/fullwidth_banner_alerts.drupal.liquid
See [here](https://dsva.slack.com/archives/CT4GZBM8F/p1675437134276429).
This appears to be a working fix.
Ran a content-build with it in place and verified that the `alert-box-headline` value was processed the same.
> Run a `escape` filter on alert-box-headline.

- src/site/stages/build/drupal/lovell/helpers.js
- src/site/stages/build/drupal/lovell/update-page.js
- src/site/stages/build/drupal/process-lovell-pages.js
- src/site/stages/build/drupal/tests/lovell/listingPages.unit.spec.js
- src/site/stages/build/drupal/tests/lovell/sidebarLocations.unit.spec.js
The Lovell `getModifiedLovellPage` function is big and confusing. This PR does a few things to simplify it and make things easier to manage.
* The code for changing each property (title, URL, switch link, etc) was extracted to individual functions so each one has a single, clear purpose.
* Each of these functions has been moved to a separate `lovell/update-page.js` file.
* These functions have been made into pure functions, so they only return values without changing them. This makes it more explicit in `process-lovell-pages.js` what properties are being changed and under what conditions. This also makes them easier to edit and understand.
* The page variables needed by all these functions are created by a single function, and are passed to all the above functions as a single object to be …
> [VA-12013] Refacter `getModifiedLovellPage` function

- src/site/assets/js/record-event.js
- src/site/includes/common-tasks.drupal.liquid
- src/site/includes/email-update-signup.drupal.liquid
- src/site/includes/hero.drupal.liquid
- src/site/includes/news-spotlight.drupal.liquid
Addresses events for ticket https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12412
Adds support for multiple GA events, and adds them to the elements on the new-home-page
Tested locally with adswerve extention
1. Navigate to new home page
2. Verify that gta events are sent correctly either in adswerve or network tab
> Added support for multiple GA events on homepage

- src/applications/registry.json
Enabling My Health Secure Messaging in prod environment. Entire functionality is behind a feature flag `mhv_secure_messaging_to_va_gov_release`, this will not affect current flow. `/my-health/secure-messaging` will still be unaccessible to public. Users will be redirected to an existing static page at `/health-care/secure-messaging`. 
Releasing for testing in preparation to Phase 0 release
Once this is enabled, QA account will be whitelisted under a feature flag above, and will conduct testing prior to Phase 0 release
> SM to VA.gov MHV-35899 MHV secure messaging enable vagovprod

- src/site/includes/news-spotlight.drupal.liquid
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12412
Local testing with adswerve
Verify that GA event fires on new homepage
> Updated news promo GA event name

- src/site/includes/homepage-benefits.drupal.liquid
- src/site/stages/build/drupal/graphql/homePage.graphql.js
- src/site/stages/build/drupal/home.js
This PR moves to using a Drupal menu for controlling the _new_ home page hub list links. This builds on the Drupal work that adds a new menu for managing the links. The original home page is using Benefit Hub Landing Page nodes, but we are moving to using a menu for the new home page to allow for non-BHLP links to be included while maintaining canonical management in the CMS.
This PR depends on the Drupal menu work: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11968
relates to https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12351  
CMS: https://cms-7kaomxlwh9vfmuyg1u9xup0etcqzmggi.demo.cms.va.gov/
WEB: https://web-7kaomxlwh9vfmuyg1u9xup0etcqzmggi.demo.cms.va.gov/
1. Visit the new nome page at …
> VACMS-12351: Home page v2 hub list menu

- src/site/components/phone-number.drupal.liquid
- src/site/components/phone.drupal.liquid
- src/site/facilities/health_care_local_health_service.drupal.liquid
- src/site/facilities/service_address.drupal.liquid
- src/site/facilities/vha_facility_nonclinical_service.drupal.liquid
- src/site/facilities/vha_facility_nonclinical_services.drupal.liquid
- src/site/paragraphs/service_location.drupal.liquid
Subheadings on VAMC facility service locations are inconsistent. "Contact Information" is an h4, and everything underneath that can logically be considered as a subheading beneath that h4, so they should all be h5.
Importantly, the template used here is also used elsewhere. The other place it is currently being used is to render non-clinical services (i.e. Billing and Insurance). On the non-clinical services pages, this information is presented slightly differently, so the header levels are not the same. 
For this PR to be valid, we need to ensure that the health-service accordions render correctly **and** that there is no regression in the presentation of non-clinical services.
This PR introduces a slight (desired) change to some conditional display of headers. Previously, there was a …
> VACMS-12068: Updates header levels on service-location template.

- src/applications/registry.json
* Scaffold new landing page for MHV on va.gov
* `"vagovprod": false`
* @vfs-mhv-integration will be code owners, per [related PR](https://github.com/department-of-veterans-affairs/vets-website/pull/23321)
* https://github.com/department-of-veterans-affairs/va.gov-team/issues/53194
* https://github.com/department-of-veterans-affairs/va.gov-team/issues/52804
* https://github.com/department-of-veterans-affairs/vets-website/pull/23321
None, app scaffolding only at this time.
None. Axe tests should pass on initial app scaffolding PR, but testing will be updated and increased in future implementation PRs.
> Add mhv landing-page registry entry

- script/heading-order-violations.js
These changes do not affect the greater content-build process; they're part of a script that is only executed on CMS preview environments.
Executed script in Tugboat environment and verified correct behavior.
> Expands metrics and adds metrics to heading_order_violations.html

- .github/workflows/a11y-heading-order.yml
closes __   
1. Do this
2. Then
> Allow a11y Heading Order Cypress container to use host SSL certs

- src/site/stages/build/plugins/download-drupal-assets.js
relates to https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12543
We sometimes see failures on vets-website review instances due to attempts to download images without a proper network connection. These changes downgrade failure due to inability to download images to a console warning for localhost environments only, which includes review instances.
Built locally, including turning off the proxy during the Download Drupal Assets step
* With proxy on, Download Drupal Assets proceeds as normal
* With proxy off, Download Drupal Assets gives warnings, but does not terminate the process.
1. Pull down the branch locally. Make sure your proxy is turned on.
2. Run `yarn build --pull-drupal`.
3. Let content build run until step 51, Download Drupal Assets. This should manifest as …
> Do not fail out if Drupal downloads fail on localhost.

- src/site/stages/build/drupal/lovell/helpers.js
- src/site/stages/build/drupal/lovell/update-page.js
- src/site/stages/build/drupal/process-lovell-pages.js
closes [#12776](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12776) and closes [#12690](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12690)
Visual, see below. Titles, content, and breadcrumb are updated/corrected.
1. Check that the Tricare and VA pages have the right information
> [VA-12776] Lovell Federal System Page Cloning Exception

- src/site/includes/covid-status.drupal.liquid
- src/site/stages/build/drupal/graphql/facilities-fragments/healthCareLocalFacility.node.graphql.js
- src/site/stages/build/drupal/graphql/healthCareLocalFacilityPage.graphql.js
- src/site/stages/build/drupal/graphql/healthCareRegionPage.graphql.js
- src/site/stages/build/drupal/graphql/locationsListingPage.graphql.js
- src/site/stages/build/drupal/graphql/locationsOperatingStatus.graphql.js
- src/site/stages/build/drupal/graphql/vamcOperatingStatusAndAlerts.graphql.js
Facilities can have COVID info specific to them that should be displayed instead. This pull request adds the extra GraphQL query to the ones with COVID precaution info and shows it in place of the regular COVID info if it's present.
Closes [#12570](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12570)
Blocked by [#12403](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/12403) since it relies on new CMS data that the GraphQL queries need.
Checking some facilities locally and making sure that the facility COVID data still shows up as expected.
Build the repo locally with `yarn build --pull-drupal --drupal-address=https://pr12403-yjq5zexhavmhassuj4kctou3kauqjue2.ci.cms.va.gov/`
1. The new COVID status data is queried in needed facilities pages
2. Confirm …
> [VA-12570] Update COVID status field with facility-specific supplemental info

- src/site/stages/build/plugins/modify-dom/force-correct-accordion-headers.js
- src/site/stages/build/plugins/modify-dom/index.js
closes 12342
Local testing on various headers.  
- Pull down branch
- Rebuild content-build
- verify various links from the accordion heading QA dock: https://docs.google.com/spreadsheets/d/1j1FgW1D78gFpVjPYTjsd0DpiDfCATYUf9xG_09-BeOQ/edit#gid=132464158
2. Then validate Acceptance Criteria from issue
> Rebuilt header plugin for accordion headers

- src/site/includes/hero.drupal.liquid
- src/site/stages/build/drupal/graphql/homePage.graphql.js
- src/site/stages/build/drupal/home.js
Uses Drupal content for the create account block in the new home page hero.
relates to https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12532
Tested using existing Production Drupal 'CTA with Links' block created in the previous sprint.
1. Visit /new-home-page
> VACMS-12532: Drupalizes the create-account hero block on the new home page

- src/site/stages/build/drupal/process-lovell-pages.js
In Lovell Stories, the "View All" link on federal stories link isn't adjusted for the variant URL. It still works on the VA page but not the Tricare page. This updates the links in question so they have the proper variants included and aren't broken anymore.
closes [#12807](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12807)
Visually, see the updated URLs circled below:
1. Rebuild the repo locally
2. Check the [federal Tricare story page](http://localhost:3002/lovell-federal-health-care-tricare/stories/test-story-for-both-lovell/)
3. Check the [federal TVA story page](http://localhost:3002/lovell-federal-health-care-va/stories/test-story-for-both-lovell/)
> VA-12807: Update Lovell Story "View All" links

- src/site/stages/build/drupal/home.js
Updates title for new home page.
relates to https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12770  
Manual testing
1. Visit /new-home-page
2. Then visit /
> VACMS-12770: Updates new home page title.

- .github/workflows/preview-environment-cleanup.yml
- script/github-actions/pe-cleanup.js
- Adds support for environment list cleanup.
- Updates directories to be current with structure in the infra manifests repository
- https://app.zenhub.com/workspaces/platform-tech-team-4-633b069d2920b776613c93d8/issues/gh/department-of-veterans-affairs/va.gov-team/54825
Tested with push trigger and sample values - behaved as expected
Preview Environments MVP
> Update cleanup script for content build

- src/site/stages/build/drupal/process-lovell-pages.js
Lovell listing pages have a combination of Tricare/VA and federal events. The Federal event links need the appropriate Tricare/VA variations in their URLs to keep users in a consistent section. But links that should be Tricare have VA in the URL. This pull request adds an extra adjustment to listing page data so the URLs are correct.
closes [#12806](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12806) 
Visual, see below.
1. Go to a VA listing page
2. Go to a Tricare listing page
> VA-12806: Update Lovell listing links for variants

- src/site/stages/build/drupal/process-lovell-pages.js
Staff-profile pages have a link to a "Leadership" page for the VAMC System. That link is broken on Lovell pages. It points to the Federal level rather than the TRICARE/VA page. That Federal level doesn't exist.
closes https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12943   
Locally.
1. Pull this branch
2. Build (pull Lovell data from Prod or Lovell Tugboat)
4. Visit: http://localhost:3002/lovell-federal-health-care-va/staff-profiles/robert-buckley/ and ensure that "Leadership" link in left sidebar goes to http://localhost:3002/lovell-federal-health-care-va/about-us/leadership/
5. Visit: http://localhost:3002/lovell-federal-health-care-tricare/staff-profiles/robert-buckley/ and ensure that "Leadership" link in left sidebar goes to …
> VACMS-12943: Fixes broken "Leadership" links on Lovell staff profile pages

- .github/workflows/content-release.yml
closes __   
1. Do this
2. Then
> Set bash Pipefail and Exit Before Yarn Build Command

- .github/workflows/preview-environment-deployment.yml
This PR adds creating a GitHub deployment during the PE Deployment workflow. This will be necessary once the Jenkins-triggered deployments are switched off after the new PEs replace Review Instances.
Needs to be merged to main to see if vets-website receives this accordingly.
- Workflow correctly sends a deployment ID to the vets-website workflow that finishes the deployment.
> Generate github deployment on PE deployment and pass to next workflow

- src/site/stages/build/drupal/tests/lovell/fixtures/updatePage.js
- src/site/stages/build/drupal/tests/lovell/helpers.unit.spec.js
- src/site/stages/build/drupal/tests/lovell/updatePage.unit.spec.js
This adds unit tests to the Lovell pure functions to ensure proper functionality. Tests have been added to all the `updatePage.js`, but only most of `helpers.js` since a few of them are so simple they don't need tests.
closes [#12904](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12904)
Testing suite
Run `yarn test:unit src/site/stages/build/drupal/tests/lovell/updatePage.unit.spec.js src/site/stages/build/drupal/tests/lovell/helpers.unit.spec.js` to run unit tests on both the added files to ensure they pass.
> [VA-12904] Increase Lovell test coverage

- src/applications/registry.json
Set Supplemental Claims to build in production
Part of [#48138](https://github.com/department-of-veterans-affairs/va.gov-team/issues/48138)
Feature flag disabled in production
What variations of circumstances (users, actions, values) need to be checked?
> Set Supplemental Claims for production build

- src/applications/registry.json
This PR toggles the `vagovprod` flag for the 26-4555 form to true so that we can roll out the form to production.
- department-of-veterans-affairs/va.gov-team-forms#25
> Update 26-4555 vagovprod flag

- src/applications/registry.json
Fixes text of bread crumbs for the Pre need application on Va.gov. The current text incorrectly uses: Pre need Eligibility Determination instead of Pre-need Eligibility Determination as well as Memorials and Burials being incorrectly in title case instead of sentence case. (Memorials and Burials should be Burials and memorials).
Application: Pre-need
change text of bread crumbs
“Pre need Eligibility Determination” to “Pre-need Eligibility Determination”
“Memorials and Burials” to “Memorials and burials”
> Fix typography on pre-need

- src/site/filters/fixtures/sidebarData.json
- src/site/filters/liquid.js
- src/site/filters/liquid.unit.spec.js
closes https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11174
Tested locally. Updated unit tests run locally.
- Links to published content should appear ✔️ 
- Links to draft content should appear ✔️ 
- Links to archived content should NOT appear ❌ 
1. Pull down branch `VACMS-11174-sidebar-filter`
2. Remove cached sidebar data: `rm .cache/localhost/preview-server/nonNodeContent.json`
3. `yarn preview --drupal-address=https://cms-ogvo5d8kyveonzymjllajdl4credcmvw.demo.cms.va.gov`
4. Wait for sidebar data (non-node content) to be rebuilt.
5. In browser, navigate to http://localhost:3002/preview?nodeId=7912 and locate the "Locations" menu.
6. In browser, navigate to http://localhost:3002/preview?nodeId=7920 and locate the "Jobs and careers" menu.
- Links to published content …
> VACMS-11174: expands filtering unpublished links in sidebar

- src/site/facilities/health_care_local_health_service.drupal.liquid
- src/site/filters/liquid.js
Facility health services have phone numbers that are improperly formatted. This uses our existing `va-telephone` component which fixes these formatting issues and gets it set up for better maintainability.
closes [#12717](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12717)
Visual, see below
1. Do a new build with this pull request
2. Check that the [Jamaica Plain VA Medical Center](http://localhost:3002/boston-health-care/locations/jamaica-plain-va-medical-center/) "Blind and Low Vision Rehabilitation" section phone number is correct
> VA-12717: Facility health services use phone number component

- src/site/includes/above-footer-elements.drupal.liquid
On small screen sizes the feedback button can overlap the last updated text. This PR makes the container responsive so that at smaller screen sizes the container has display block and the text and button don't overlap.
closes [55368](https://app.zenhub.com/workspaces/platform-tech-team-2-633efe4ca5a428e5294d7ade/issues/gh/department-of-veterans-affairs/va.gov-team/55368)
Before:
After:
Verify that at small screen sizes the last updated text and feedback button do not overlap
> switch feedback button container's display to block on mobile

- src/platform/static-data/footer-links.json
relates to https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13276
TBD
Go to content-build on staging or a tugboat instance and click on the Social Media footer link. It should go to https://digital.va.gov/web-governance/social-media/social-media-sites/
> VACMS-13276: Fix footer social media link

- src/applications/registry.json
Add breadcrumbs for form 21-4142
closes https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team-forms/199
relates to form 21-4142 (not yet prod)
BEFORE:
AFTER:
1. Navigate to `/health-care/medical-release-form` in the deployed branch
> Add breadcrumbs for form 21-4142

- src/site/layouts/press_release.drupal.liquid
closes https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13205
Built locally with the changes; the page mentioned in the ticket has a corrected link. 
Local url: http://localhost:3002/northern-california-health-care/news-releases/va-northern-california-provides-free-support-to-survivors-of-military-sexual-trauma/
Outcome (note link in bottom left corner): 
1. Run a content release with this branch.
2. For the content release in question, view the page `/northern-california-health-care/news-releases/va-northern-california-provides-free-support-to-survivors-of-military-sexual-trauma/`
3. Scroll down and check the link "[If You Have Experienced MST, VA Can Help](https://youtu.be/N9XvzKACbfM)"; it should contain a working link …
> Correct syntax on liquid case statement in press release.

- src/site/facilities/facility_health_service.drupal.liquid
Previously, [we did work](https://github.com/department-of-veterans-affairs/content-build/pull/1416) to hide the patient-satisfaction widget div on TRICARE services. This PR implements the same ([quick](https://github.com/department-of-veterans-affairs/content-build/pull/1416#pullrequestreview-1233148208)) solution for the wait-time widget on TRICARE services.
closes https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13398
relates to https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12069
See screenshots in QA steps
1. /lovell-federal-health-care-va/locations/captain-james-a-lovell-federal-health-care-center/
2. Expand "Ophthalmology"
- Notice that wait times appear
3. /lovell-federal-health-care-tricare/locations/captain-james-a-lovell-federal-health-car …
> VACMS-13398: Doesn't render wait-time widget div on TRICARE services.

- src/site/facilities/tests/lovell/lovell-pages.cypress.spec.js
Lovell menus vanished without notice until the change was in production. This adds End To End tests to ensure the menus are still present in Lovell. They specifically check the "About Us" pages for VA and Tricare for the following elements:
* There are three menu "sections" and each has a header for a label
* There are top level menu links present
* There are at sublevel menu links present (for "About Us")
This amount of testing ensures that the menu is present along with some of the key elements to make sure everything is there, not just the wrapper.
closes [#13252](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13252)
relates to [#13244](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13244)
Successfully ran the new tests locally
What needs to be …
> VA-13252: E2E test for presence of Lovell Menus

- .github/workflows/authenticated-cms-request/action.yml
- .github/workflows/content-release.yml
relates to https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12640
This updates Content Release to use updated actions that were outdated. We are only updating Content Release here as a trial of the updated actions on an active workflow.
This was run in a test workflow with the department-of-veterans-affairs/action-inject-ssm-secrets@latest action added:
https://github.com/department-of-veterans-affairs/content-build/actions/runs/4813362548/jobs/8569822352
> Update actions that are outdated.

- .github/workflows/a11y-heading-order.yml
- .github/workflows/a11y.yml
- .github/workflows/build.yml
- .github/workflows/codeql.yml
- .github/workflows/continuous-integration.yml
- .github/workflows/daily-production-release.yml
- .github/workflows/daily-release-warning.yml
- .github/workflows/deploy-content-preview-server.yml
- .github/workflows/manual-deploy-dev-staging.yml
- .github/workflows/manual-review.yml
- .github/workflows/preview-environment-cleanup.yml
- .github/workflows/preview-environment-deployment.yml
- .github/workflows/slack-notify/action.yml
[relates to https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12640  ](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12640)
This work was done by @tonytaylor ; I am creating this PR in order to move the source branch to the main content-build repo.
Many of these actions updates have already been merged into content-release.yml and are working successfully there. See for example https://github.com/department-of-veterans-affairs/content-build/actions/runs/4814028957
Actions need to run correctly. This is hard to test for most workflows, unfortunately, but the underlying changed actions have been tested.
I very much recommend immediately rolling a revert PR when this is merged, in the event that there are issues with any of the workflows.
> Updating content-build's remote actions for GHA deprecations

- src/site/layouts/faq_multiple_q_a.drupal.liquid
- src/site/stages/build/drupal/graphql/faqMultipleQa.graphql.js
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11448
When duplicate Q&A accordions are used, their IDs are the same (for the `faq_multiple_q_a.drupal.liquid` template). This causes accessibility issues and conflicts when linking directly to an accordion's answer from another page.
The solution was to retrieve the group ID via GraphQL and concatenate that with the existing ID.
Tested locally with `/resources/the-pact-act-and-your-va-benefits`
1 of 2 duplicated content blocks
2 of 2 duplicated content blocks
1) navigate to `/resources/the-pact-act-and-your-va-benefits`
2) scroll to the section for Gulf War era and Vietnam era Veteran eligibility
3) note that there is a question in the Gulf War era section that is …
> VACMS-11448 Fix accessibility issue (dupe IDs) on reusable Q&A

- .github/workflows/preview-environment-deployment.yml
Preview environments will not support content-build at MVP for a variety of infrastructure-related reasons. While support will be added later, having this workflow active in the interim is creating failed dispatches to vets-website that we'd like to disable for the time being. Code is being left commented as it will be needed post-MVP.
N/A
N/A
> deactivate PE workflow til content build is supported

- src/site/assets/js/medallia/vagovstaging.js
- src/site/filters/liquid.unit.spec.js
- src/site/filters/medalliaStagingSurveys.json
This PR changes the Medallia survey number on staging for [staging.va.gov/contact-us/virtual-agent/](https://staging.va.gov/contact-us/virtual-agent/) and closes [department-of-veterans-affairs/va.gov-team/issues/57382](https://github.com/department-of-veterans-affairs/va.gov-team/issues/57382)
Tested on review instance
1. navigate to /contact-us/virtual-agent/ on the review instance
2. scroll to the bottom of the page and click the FEEDBACk button
3. The Medallia survey modal should appear
> changed survey number

- src/platform/site-wide/tests/accessible-modal.cypress.spec.js
This lint issue popped up in an unrelated pull request. This PR should fix it.
> Fix lint issue in Accessible Modal

- src/applications/registry.json
Modify the URL per IA. Remove intermediate breadcrumb until that page is built by content team.
Closes: https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team-forms/279
Tested locally with vets-website. Shows proper breadcrumb (note: local does not display VA home breadcrumb)
(not necessary for non prod)
1. Pull down these changes and those in the [vets-website branch](https://github.com/department-of-veterans-affairs/vets-website/pull/24233). Run `yarn build` then `yarn watch` and navigate to `localhost:3001/supporting-forms-for-claims/release-records-to-va-form-21-4142`
Note: The 'Home' Breadcrumb appears in deployed environments
- [devops](https://github.com/department-of-veterans-affairs/devops/pull/13021 …
> Modify breadcrumbs and url per IA for form 21-4142 (non prod)

- src/site/assets/robots.txt
closes [VACMS-11990](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11990)   
N/A
> VACMS-11990: Remove Lovell disallow lines for full state

- package.json
- yarn.lock
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13635
Intended to mitigate this Dependabot issue: https://github.com/department-of-veterans-affairs/content-build/security/dependabot/53
loader-utils only exists in our build because it is a dependency of cache-loader:
```
❯ yarn why loader-utils
yarn why v1.22.19
[1/4] 🤔  Why do we have the module "loader-utils"...?
[2/4] 🚚  Initialising dependency graph...
warning Resolution field "lodash@4.17.21" is incompatible with requested version "lodash@^2.4.1"
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "loader-utils@1.4.0"
info Reasons this module exists
- "cache-loader" depends on it
- Hoisted from "cache-loader#loader-utils"
info Disk size without dependencies: "84KB"
info Disk size with unique …
```
> Remove cache-loader.

- .github/workflows/preview-environment-cleanup.yml
1. [ ]  ~~[`aws-actions/configure-aws-credentials@v1`](https://github.com/aws-actions/configure-aws-credentials) - Can be replaced with `@v2`; see https://github.com/aws-actions/configure-aws-credentials/issues/489~~
Already correct
3. [ ] ~~[`marvinpinto/action-inject-ssm-secrets`](https://github.com/marvinpinto/action-inject-ssm-secrets) - [No apparent updates forthcoming](https://github.com/marvinpinto/actions/issues/543); the maintainer appears to be absent. This is **widely** used: https://github.com/search?q=org%3Adepartment-of-veterans-affairs+action- …
> Updated gh-actions for set-output deprecation

- src/site/stages/build/plugins/modify-dom/add-id-to-subheadings.js
relates to https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13769
No functional changes, only adding comments.
What needs to be checked to prove it didn't break any related things?
> Add note to keep parity with CMS on heading ids.

- src/site/filters/events.js
- src/site/filters/liquid.js
- src/site/stages/build/drupal/lovell/featured-items.js
- src/site/stages/build/drupal/lovell/helpers.js
- src/site/stages/build/drupal/process-lovell-pages.js
- src/site/stages/build/drupal/tests/lovell/featuredItems.unit.spec.js
- src/site/stages/build/drupal/tests/lovell/fixtures/homepages/tricare.json
- src/site/stages/build/drupal/tests/lovell/fixtures/homepages/va.json
- src/site/stages/build/drupal/tests/lovell/fixtures/listing-pages/federal/events.json
- src/site/stages/build/drupal/tests/lovell/fixtures/listing-pages/federal/stories.json
- src/site/stages/build/drupal/tests/lovell/fixtures/listing-pages/tricare/events.json
- src/site/stages/build/drupal/tests/lovell/fixtures/listing-pages/tricare/stories.json
- src/site/stages/build/drupal/tests/lovell/fixtures/listing-pages/va/events.json
- src/site/stages/build/drupal/tests/lovell/fixtures/listing-pages/va/stories.json
- src/site/stages/build/drupal/tests/lovell/helpers.unit.spec.js
See https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11941
This PR adds featured stories and events to the Lovell VA and TRICARE homepages.
**Sorted Federal then TRICARE**
**Sorted by date (next upcoming event listed first)**
**Sorted Federal then VA**
**Sorted by date (next upcoming event listed first)**
1. `yarn build --pull-drupal --drupal-address=https://main-ogvo5d8kyveonzymjllajdl4credcmvw.demo.cms.va.gov/ --use-cached-assets`
2. http://localhost:3002/lovell-federal-health-care-tricare/
3. http://localhost:3002/lovell-federal-health-care-va/
See original ticket.
> VACMS-11941: Lovell featured items on homepages

- script/preview.js
Adds preview support for Lovell pages, with some exceptions:
- Listing pages will not work. These require merging with Federal listing pages, which will not be fetched when building only a single page.
- Homepages will work but will not include umbrella featured items. Getting those items is done by grabbing them from the listing pages, which will not be built when building only the single page.
Note: There's a [related draft PR](https://github.com/department-of-veterans-affairs/content-build/pull/1576) that gets most or all of the way to adding support for these other pages. I've opted for the simpler solution to satisfy this issue, as the larger solution feels like some scope creep. The more robust solution can be considered for a later date if there is a strong need for this support. …
> Adds preview support for most Lovell pages.

- src/site/stages/build/drupal/graphql/homePage.graphql.js
Changes the image style for the V2 (new) home page news promo block. The current design expects a 1:1 aspect ratio, but today we are using the 'large' Drupal image style which maintains the existing aspect ratio of the image.
relates to #13843
Manual testing locally. Will also test in Tugboat and RI (if RI is functional).
1. Visit /new-home-page on the FE
> VACMS-13843: Use the square image style for homepage news promo block query

- src/site/tests/home/00-required.cypress.spec.js
Context: https://dsva.slack.com/archives/C52CL1PKQ/p1685654781892969
All this does is disable the Cypress tests for homepage until the PW team decides how best to handle them.
> Disable the homepage cypress test.

- .github/workflows/content-release.yml
Add Slack notification to the failure step.
Addresses https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13964
> Notify Slack when there is a failure.

- src/applications/registry.json
Adding breadcrumbs to the Income Limits app.
Sketch file: https://www.sketch.com/s/a8506c94-a5bd-4a69-91ff-fe06545f3126
Ticket: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13588
Desktop:
Mobile:
1. Load `/health-care/income-limits-temp`.
2. Validate that the breadcrumbs are present and the same on every page
a. Desktop structure: `Home` > `Your health care costs` > `Check income limits`
b. Mobile structure: `Your health care costs`
> VACMS-13588 Add breadcrumbs (Income Limits)

- src/site/filters/liquid.js
- src/site/layouts/vet_center_locations_list.drupal.liquid
The Vet Center Satellite locations are organized alphabetically, but the outstations should be shown before the others. This makes the outstation vet centers appear first in the list (alphabetically), followed by the others (also alphabetically).
Closes [#12096](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12096)
1. Run a local build of this branch
2. Check locations for Elken Vet Center at http://localhost:3002/elkton-vet-center/locations/
3. Check locations for Great Falls Vet Center at http://localhost:3002/great-falls-vet-center/locations/
> [VA-12096] Reorganize Vet Center Satellite Locations

- src/applications/registry.json
Update breadcrumbs and URL per final IA review
[Ticket](https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team-forms/315)
Ran locally with [vets-website changes](https://github.com/department-of-veterans-affairs/vets-website/pull/24430). Verified the new route worked.
Pull vets-website branch linked above. Run with `yarn watch --env entry=21-4142-medical-release`.
Navigate to `http://localhost:3001/supporting-forms-for-claims/release-information-to-va-form-21-4142` and verify it loads.
> Update form 21-4142 breadcrumbs and url per IA

- src/site/stages/build/drupal/graphql/facilities-fragments/healthCareRegionNonClinicialServices.node.graphql.js
closes https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13199
Archived non-clinical services are showing on VAMC top-task pages. They shouldn't be showing. This PR fixes that.
In the [CMS data used to test](https://main-ogvo5d8kyveonzymjllajdl4credcmvw.demo.cms.va.gov/), there are two archived pieces of content to note:
1. [O'Neill VA Clinic VAMC Facility node](https://main-ogvo5d8kyveonzymjllajdl4credcmvw.demo.cms.va.gov/nebraska-western-iowa-health-care/locations/oneill-va-clinic) is archived
2. [The billing-and-insurance VAMC Facility Non-clinical Service node tied to Omaha VA Medical Center](https://main-ogvo5d8kyveonzymjllajdl4credcmvw.demo.cms.va.gov/nebraska-western-iowa-health-care/locations/omaha-va-medical-center/billing-and-insurance) is archived.
As a …
> VACMS-13199: Adds node-status filter to subqueries for non-clinical services

- src/site/includes/facilityListing.drupal.liquid
- src/site/layouts/health_care_local_facility.drupal.liquid
- src/site/layouts/vamc_operating_status_and_alerts.drupal.liquid
This removes the COVID health status from the needed VAMC pages on the content-build.
Related to [#13673](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13673)
Visual, confirmed the health status is gone on the following local pages after these steps:
1. Do a local build by running `yarn preview`
2. Check the page at http://localhost:3002/illiana-health-care/operating-status/
3. Check the page at http://localhost:3002/preview?nodeId=2802
4. Check the page at http://localhost:3002/illiana-health-care/locations/springfield-va-clinic/
1. Check all above local pages
> [VA-13673] Remove COVID tracker from VAMC pages

- src/site/layouts/home-sandbox.drupal.liquid
- src/site/layouts/home.drupal.liquid
- src/site/stages/build/drupal/home-sandbox.js
- src/site/stages/build/drupal/home.js
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13955
- Cleans up feature toggle logic for the home page
- Removes all old home page code
- Renames all home preview things to "home sandbox." 
Tested locally.
- Check `/` and ensure features are working such as search typeahead, links & buttons in hub, footer, news spotlight, header.
- Check `/new-home-page` and ensure features are working such as search typeahead, links & buttons in hub, footer, news spotlight, header.
> VACMS-13955 Clean up homepage code post-launch

- src/applications/registry.json
Removing breadcrumb configuration in the application registry as it is preferred to use the design system component in the application side (vets-website) instead.
This is just removing code for an application that is not in production yet. You can test that everything still works at `/health-care/income-limits-temp` locally (without breadcrumbs).
> VACMS-13588 Removing breadcrumbs configuration from Income Limits application

- src/site/includes/vet_centers/featured_content.liquid
- src/site/paragraphs/link_teaser_featured_content.drupal.liquid
Spotlight section links don't have underlines, and they need to be underlined more in line (no pun intended) with accessibility and design system guidelines.
relates to [#13808](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13808)
Visual, checked below local pages.
[VA Dublin Health Care](http://localhost:3002/dublin-health-care/health-services/)
[Los Angeles Vet Center](http://localhost:3002/los-angeles-vet-center/)
1. Check Spotlight on a VAMC page
2. Then check Spotlight on a Vet Center page
> [VA-13808] Add underlines to links in Spotlight sections

- src/applications/registry.json
- Change prod flag to true to enable form route in production (form visibility controlled by flipper, so it won't appear for everyone right away)
- Update breadcrumb to use hex code for dash since regular dash wasn't showing up in deployed environments (see screenshots)
- This is based on what teams like [pre-need have done to get their breadcrumb dash to render](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/applications/registry.json#L327)
- [pre-need staging link](https://staging.va.gov/burials-and-memorials/pre-need/form-10007-apply-for-eligibility) for reference
[ticket](https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team-forms/339)   
Form 21-4142 in staging. …
> Enable form 21-4142 route and fix breadcrumb

- .devcontainer/Dockerfile
This fixes codespace creation (The VA internal certificate installation step was failing and breaking codespaces builds). A [similar PR](https://github.com/department-of-veterans-affairs/vets-website/pull/24582) was recently merged into vets-website.
> Fix codespaces build

- src/applications/registry.json
I am making some changes to prevent deep-linking to parts of the Income Limits form (i.e. navigating directly to `/health-care/income-limits/zip`). This requires an entry in the `devops` repository to enable client-side routing. I'm adding the up-to-date URL (`/health-care/income-limits` rather than `/health-care/income-limits-temp`) there so I need to make the update here.
> VACMS-13593 Update Income Limits URL

- src/site/layouts/event.drupal.liquid
Event pages have extra whitespace between the city and state in the **Where** block, see e.g. https://www.va.gov/outreach-and-events/events/57259/ which looks like this:
Tested on review instance, see e.g.:
- /outreach-and-events/events/57259/
- /outreach-and-events/events/57122/
- /outreach-and-events/events/57384/
Event pages at `outreach-and-events/events/*/`
Also event pages, not aware of anything else.
Content does not vary for logged in users.
> Remove trailing whitespace from event locality

- src/site/components/phone-number.drupal.liquid
- src/site/components/phone.drupal.liquid
- src/site/facilities/health_care_local_health_service.drupal.liquid
- src/site/paragraphs/service_location.drupal.liquid
closes https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13705
This PR resolves two problems with phone numbers on health-service accordions: 
1. Some phone number labels set in the CMS were not making their way to the front end.
2. When an editor selected to show the facility phone number, that phone number was not showing at all.
Before:
After:
1. `yarn preview --drupal-address=https://main-ogvo5d8kyveonzymjllajdl4credcmvw.demo.cms.va.gov`
2. http://localhost:3002/preview?nodeId=2030
3. - [ ] Expand 'Mental health care' accordion and confirm displayed data matches [CMS …
> VACMS-13705: Fixes phone number bugs on health services

- src/site/facilities/facility_social_links.drupal.liquid
The "get updates from <system>" links should open in the same tabs, but instead open in new ones. This edits the anchor tags to fix this.
relates to [#11848](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11848)
Visual, see below QA steps
1. Do a local build and [visit "VA Sheridan health care"](http://localhost:3002/sheridan-health-care/) to check links are updated
> VA-11848: Open facility social links in same tab

- .github/workflows/content-release.yml
- .github/workflows/continuous-integration.yml
In response to this workflow run: https://github.com/department-of-veterans-affairs/content-build/actions/runs/5465140738/jobs/9955066284#step:9:1
If this callback fails, it is not cause for failing the entire workflow.
> Add continue-on-error to CI workflow.

- src/applications/registry.json
Set `vagovprod` to true in `src/applications/registry.json` for form-app 21-10210, to [enable this form in Prod](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/issues/307).
NOTE: Flipper `form2110210` is currently OFF in Prod, so this PR can be safely merged without accidental publication.
N/A -- this a config for an external React app.  The app itself [in vets-website repo] has been successfully tested and reviewed by Platform.
> Turn on 21-10210 form-app in Prod

- src/site/includes/directions-google-maps.liquid
- src/site/includes/facilityListing.drupal.liquid
- src/site/includes/vet_centers/address_phone_image.liquid
- src/site/layouts/health_care_local_facility.drupal.liquid
- src/site/layouts/vet_center.drupal.liquid
closes https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12085
closes https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13837
- Google Maps directions links are implemented in multiple places. This adds a reusable abstraction (template) for this component.
- The links themselves needed two tweaks:
- Visually, they now read, "Get directions on Google Maps"
- For screen readers, they add the title of the facility that the directions are to
These changes allows consistency across the website. Previously, these were being handled in multiple ways.
```
<div>
<a href="https://maps.google.com?saddr=Current+Location&amp;daddr=113 Comanche Road, Fort Meade, SD 57741-1002" hreflang="en">
Get directions on Google Maps <span class="sr-only">to Fort Meade VA Medical …
```
> Refactors Google Maps directions links

- src/applications/registry.json
closes https://github.com/department-of-veterans-affairs/vets-website/pull/25089
relates to https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team-forms/287
browser testing and comparison vs mocks
new address should work http://localhost:3001/mock-form-patterns/
should not be activated in production
What variations of circumstances (users, actions, values) need to be checked?
> add new mock form for patterns

- src/site/filters/liquid.js
- src/site/filters/liquid.unit.spec.js
This PR adds the ability to A/B test the Medallia VFS survey. When you scroll to the bottom of the main content on any page and click the FEEDBACK button, there's a 50% chance you will receive one of two Medallia surveys.
relates to [#62606](https://github.com/department-of-veterans-affairs/va.gov-team/issues/62605)
Note: These changes are for staging only to demo for stakeholders.
Tested on review instance
What needs to be checked to prove this works? 
Scroll to the bottom of the main content on 5-10 pages and click FEEDBACK button. Determine you receive one of two different survey modals each time.
> testing abTestSurveyNumber

- src/site/facilities/facility_health_service.drupal.liquid
- src/site/facilities/health_service.drupal.liquid
- src/site/layouts/campaign_landing_page.drupal.liquid
- src/site/layouts/faq_multiple_q_a.drupal.liquid
- src/site/layouts/health_care_local_facility.drupal.liquid
- src/site/layouts/landing_page.drupal.liquid
- src/site/paragraphs/q_a.collapsible_panel.drupal.liquid
Ticket: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11354
When linking to an accordion using a fragment (e.g. `/health-care#what-are-my-benefit-options`), the page was not jumping to the correct content and opening the accordion. This was partly due to a Design System bug that is now fixed; the accordion was missing the `open` property when this scenario happened. But the reason the page wasn't jumping was because the `<va-accordion-item>`s were not labeled with the correct IDs.
`campaign_landing_page.drupal.liquid`
`health_care_local_facility.drupal.liquid`
`landing_page.drupal.liquid`
`faq_multiple_q_a.drupal.liquid`
`q_a.collapsible_panel.drupal.liquid`
What needs to be checked to prove this works?  Go to a page that uses one of these templates, copy an ID off …
> VACMS-11354 Add IDs to accordions

- src/site/filters/liquid.js
- src/site/filters/liquid.unit.spec.js
This PR adds the ability to A/B test the Medallia VFS survey on production. When you scroll to the bottom of the main content on any page and click the FEEDBACK button, there's a 50% chance you will receive one of two Medallia surveys.
relates to [#62606](https://github.com/department-of-veterans-affairs/va.gov-team/issues/62605)
Updated unit tests.
Scroll to the bottom of the main content on 5-10 pages and click FEEDBACK button. Determine you receive one of two different survey modals each time.
> Medallia - Add A/B test for rating scale in production surveys

- src/site/includes/lovell-switch-link.drupal.liquid
This PR makes the info banner conform to the desired warning style banner for the Lovell liquid  switch link.
closes #14479
old:
new "warning":
new "warning" as VA beneficiary
1. Do this
2. Then
> Transitions the Lovell VA/TRICARE banner switcher from info->warning status

- src/applications/registry.json
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13147
The breadcrumbs on the Resources & Support search results should match the `h1`.
Before
After
1. Go to `/resources/search/?query=disability`
2. Validate that the Breadcrumbs match the **After** screenshot from above.
> VACMS-13147 Resources and Support breadcrumbs fix

- src/site/stages/build/plugins/modify-dom/add-id-to-subheadings.js
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14747
When we added unique IDs to `va-accordion-item`s for linking to fragments (i.e. `/resources/the-pact-act-and-your-va-benefits/#can-i-apply-now`), it created a duplicate ID issue. The `h3`s inside of the `va-accordion-item` were automatically getting IDs assigned by `add-id-to-subheadings.js`.
Since we do not need IDs on the `h3`s inside `va-accordion-item`s, this code removes that automatic ID addition.
Before, in production
<br/>
<br/>
After
<br/>
1. Go to one of the URLs below
2. Inspect one of the accordions
3. Note the ID value on the `va-accordion-item`
4. Inspect the `h3` (may or may not have `slot="headline"`) in the `va-accordion-item`
5. Note the `h3` (with or without `slot="headline"`) should not have an …
> VACMS-14747 Fix duplicate ID issue on va-accordion-item

- .github/workflows/close-stale-pull-requests.yml
- src/site/stages/build/drupal/menus.js
- src/site/stages/build/plugins/create-header-footer.js
- src/site/stages/build/plugins/tests/create-header-footer.unit.spec.js
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14697
When we built the Drupalized footer previously, we used `link.description` to populate the link title rather than `link.label`. This uses the `Menu link title` field instead so we can ensure that if the description is not filled out, the link will still be populated.
I also checked how the megamenu / header was being populated. It has a different GraphQL setup where the `title` field corresponds to the `Menu link title`. No issues there.
I created a test link in Drupal in the footer bottom rail. In the `Menu link title` field, I put `This is the menu link title` and in the description field, I put `This is the description`.
I tested the build locally after pulling the data from Drupal. Note: `This is the menu link …
> VACMS-14697 Use footer label instead of description to populate footer titles

- src/site/layouts/faq_multiple_q_a.drupal.liquid
- src/site/layouts/page.drupal.liquid
- src/site/layouts/support_resources_detail_page.drupal.liquid
- src/site/paragraphs/q_a.collapsible_panel.drupal.liquid
- src/site/paragraphs/q_a_group_collapsible_content.drupal.liquid
- src/site/stages/build/drupal/graphql/paragraph-fragments/qaGroup.paragraph.graphql.js
For this ticket we encountered a defect where the accordion option for reusable Q&As was not adding the feature properly across all implementations. This PR will account for the accordion display flag and also will account for the QA group introduction that was also not included in initial implementation. 
- Updated graphQL to pass in `fieldAccodionDisplay` flag
- Added accordion specific template for reusable QAs
Relates to [#14814](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14814)
Tugboat Instances: 
https://web-nooftw96f8qss9vj2uw4a78vfp0ukbkv.ci.cms.va.gov/resources/qa-group-for-rs-page/
https://web-nooftw96f8qss9vj2uw4a78vfp0ukbkv.ci.cms.va.gov/qa-group-with-accordions/
Verify on R&S and Benefit Detail Pages …
> VACMS-14814: Add new functionality for QA groups to allow for accordions

- src/site/filters/liquid.js
- src/site/filters/liquid.unit.spec.js
- src/site/layouts/basic_landing_page.drupal.liquid
- src/site/paragraphs/alert.drupal.liquid
- src/site/paragraphs/expandable_text.drupal.liquid
The Vet Center centralized content alert and expandable text content aren't rendering the content from the CMS properly. These changes to the front-end template should get the content rendering properly.
relates to [#14647](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14647)
**What needs to be checked to prove this works?** That the alert and expandable text render properly with the expected content.
**What needs to be checked to prove it didn't break any related things?** The entire page where this content is rendered.  
**What variations of circumstances (users, actions, values) need to be checked?** None 
1. Go to the [White Oak Vet Center page](https://web-spvbjheoe12isfu1maky120fjrnm7ivg.demo.cms.va.gov/brooklyn-vet-center/) and check that the alert and …
> VACMS-14670: Fix centralized content Alert and Expander Text 

- .devcontainer/Dockerfile
- Dockerfile
I'm not sure that this is pressing. I'm not sure the root Dockerfile is even in use. I don't know how the other one is used.
So this PR might be stupid. It's a risk I'm willing to take, to stand up for what is good and true and consistent in Dockerfiles.
> Adds certs for newer RCAs to Dockerfiles.

- .github/workflows/prune-self-hosted-runners.yml
- package.json
- script/prune-self-hosted-runners.js
- yarn.lock
Closes department-of-veterans-affairs/va.gov-cms#14693.
This PR introduces a script and associated GitHub Actions workflow to manage the lifecycle of our self-hosted runners on EC2 instances controlled by an ASG. The primary goal is to gracefully handle runners that might run out of resources or become unresponsive over time.
Node.js Script (`prune-self-hosted-runners.js`):
- Queries GitHub to determine the status of each runner.
- Interacts with AWS to fetch the age of each EC2 instance.
- Identifies old, idle instances (those that have been running for more than a set threshold and have no busy runners).
- Deregisters runners from GitHub and marks the associated EC2 instances as unhealthy.
GitHub Actions Workflow (`prune-runners.yml`):
- Scheduled to run on a manual trigger …
> Adds a GHA workflow and JS script to delete old, idle self-hosted runners.

- src/applications/registry.json
Add PACT Act wizard to the application registry.
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14729
> VACMS-14729 Add PACT Act to application registry

- .github/workflows/prune-self-hosted-runners.yml
Normal GitHub token doesn't seem to have sufficient privileges for pruning self-hosted runners (see #1676). I believe what I need is the VSP GitHub bot token.
Pls lemme know if I should use a different one.
> Use VSP GitHub token, not default token, for managing runners.

- src/site/includes/directions-google-maps.liquid
- src/site/layouts/event.drupal.liquid
- src/site/stages/build/drupal/graphql/nodeEvent.graphql.js
For this ticket we are adding a new address format along with google maps link to direction. To accomplish this, we have added an update to the graphQL query to add the fieldAddress to the fieldFacilityLocation to pull the address into the event data obj. And we made the necessary changes on the FE drupal templates for events.
Testing URLs:
/outreach-and-events/events/60333/
/outreach-and-events/events/60524/
Before:
After:
Verify that event pages have new address format and link to google maps. 
Verify that VA and non VA facility events both show the new formatted address. 
Verify that event pages are still working properly.
> VACMS-13222: Display new 'Where' format for events

- src/applications/registry.json
We plan to build an app to allow our team to more easily perform user testing in staging. This app will _never_ be released into production. 
See [#64388](https://github.com/department-of-veterans-affairs/va.gov-team/issues/64388)
N/A
> Add appeals testing app

- src/site/paragraphs/contact_information.drupal.liquid
- src/site/paragraphs/default_contact.drupal.liquid
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13137
On the Resources & Support pages, there is a Contact Information widget used to add phone numbers to the bottom of those pages. When there's only the default (MyVA411) contact information provided, we needed to render a paragraph instead of an unordered list.
I saw that we were also rendering an `<li>` regardless of whether the default contact information for email and phone number is provided, resulting in a blank `<li>` that is still read by the screen reader. This is fixed as well.
```
/resources/can-i-plan-ahead-for-my-burial-in-a-va-national-cemetery/
/resources/compare-va-education-benefits/
```
<br />
<br />
```
/resources/how-to-get-free-language-assistance-from-va/
```
<br />
<br />
1. Navigate to one of …
> VACMS-13137 Conditional List for template

- src/site/includes/metatags.drupal.liquid
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14967
Previously, we added an iOS mobile app promo banner to a set of specific pages. It was controlled by a feature flag and by an environment check (to be viewed in staging only). We are removing the environment check so the feature can be viewed in production.
[See here](https://github.com/department-of-veterans-affairs/content-build/blob/8d975732f87abf1cb9113cd9513396e0e85e865b/src/site/filters/liquid.js#L1597) for the pages included in this feature. The feature flag remains.
Not able to test this locally or in the review instance.
> VACMS-14967 Launch iOS mobile app banner

- src/site/layouts/basic_landing_page.drupal.liquid
#15076 was a bug caused by [this pull request,](https://github.com/department-of-veterans-affairs/content-build/pull/1653) which fixed a bug that occurs when two alerts appear on a single page. However, the layout change negatively affected the width of other pages like a list of links.
As [Steve pointed out in a Slack discussion thread,](https://dsva.slack.com/archives/C0FQSS30V/p1693940186357309?thread_ts=1693601589.812439&cid=C0FQSS30V) the main layouts where the two alerts are likely to appear already have the needed layout classes that fixed the layout adjusted in the PR. This confirms that those layouts should avoid the same bug as the layout from the pull request.
Since the page using the layout from the pull request was a test page no longer being used, this pull request reverts …
> [VA-15076] Remove limited width from basic landing page

- src/site/filters/liquid.js
- src/site/filters/liquid.unit.spec.js
This PR turns off the A/B test for the Medallia survey rating scale
closes [#64865  ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/64865)
relates to #1648  
What needs to be checked to prove this works? 
When you click the FEEDBACK button at the bottom of main content on every page, the same rating scale appears
> Turn off Medallia rating scale A/B test

- src/site/facilities/health_service.drupal.liquid
- src/site/filters/liquid.js
- src/site/stages/build/drupal/graphql/healthServicesListingPage.graphql.js
Services in health service accordions should be re-ordered in a specific way. This orders them based on the ticket specifications:
1. Main Clinic
2. Alpha Clinics (clinics that are not any of the other options)
3. Community Living Centers (CLCs) & Domiciliary Residential Rehabilitation Treatment Programs (DOMs)
4. Mobile Clinics
relates to [#13941](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13941)
Checked at http://localhost:3002/houston-health-care/health-services/ and confirmed that the main clinic (Michael E. DeBakey) has moved to the front. All the other clinics are alpha clinics
**What needs to be checked to prove this works?** That the health services are sorted properly
**What needs to be checked to prove it didn't break any related things?** The other …
> [VA-13941] VAMC health service "Available at these locations" list sort order

- src/applications/registry.json
This PR fixes a breadcrumb name for 21-0972, per feedback from the collaboration cycle.
I've also updated the `appName` to be consistent. Is there any risk to doing this? I've checked and, with this update, it is consistent with the `appName` in the `vets-website` repo.
closes https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team/64660
> Fix breadcrumb name in form 21-0972

- .github/workflows/prune-self-hosted-runners.yml
- script/prune-self-hosted-runners.js
I made a tweak to the prune-self-hosted-runners script to retrieve up to 100 runners (bugfix!) and also to schedule it for regular execution. I've been using the script locally to prune old, idle runners for a few days and haven't encountered any unexpected issues.
I don't want to merge this just yet, though, as I'd like to see how stable the runners are in their current arrangement.
> Schedule the prune-self-hosted-runner script.

- src/site/layouts/event.drupal.liquid
There was a defect filed that the format for description of the event is not showing up in the proper place for non-VA location events. This change to the styles will take care of that. 
Validated that non-VA locations have the correct layout for description. Also verified that other events are not affected by this change.
> update formatting issue for event detail page

- src/site/navigation/sidebar_nav.drupal.liquid
Added a aria-label secondary to sidenav for accessibility concerns about not having a unique label.
> VACMS-14870: Add aria-label "Secondary" to sidenav

- src/applications/registry.json
Update app-registry to enable Third-Party Authorization (21-0845) form-app in Production
part of the form's Slow-Rollout [#555](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/issues/555)
Flipper `form210845` ON in Staging only; OFF in [Prod](https://api.va.gov/flipper/features).  End-date TBD.
N/A; this is just an app-registry prop-change.  The form still won't load in Prod just yet &mdash; we have a Flipper feature-flag that hasn't been turned on in Prod.
> 21-0845 -Enable in Prod

- src/site/facilities/health_service.drupal.liquid
On the health services page we have `h2` headings with the same id as the accordion id's. This change will add a prefix of `item-` to the va-accordion items. Allowing for deep linking to these accordions and not breaking the header `On this Page `functionality.  
`/boston-health-care/health-services/#item-primary-care`
Verify that deep-linking works and that there are no identical ids on the page specifically the headers and va-accordion-items.
> VACMS-14910: Add unique identifier to va-accordion-item id for healh services

- src/site/includes/header.html
Remove the hidden attribute when clicking the skip to content button
Verified that the hidden attribute is not being added to the skip to content link. Tabbing back through the content shows the skip to content link again.
Old Behavior:
https://github.com/department-of-veterans-affairs/content-build/assets/42885441/4c05f381-8938-4ea7-a9be-a3862dec9567
New Behavior:
https://github.com/department-of-veterans-affairs/content-build/assets/42885441/9817c778-7c57-4d1c-b9fd-e34dfe6a60da
1. Go to any page on VA.gov, for example: https://www.va.gov/health-care/about-va-health-benefits/
2. Start tabbing through the page immediately
3. You will see the Skip to content link appear once you focus on it
4. Hit enter to activate the link and jump down to the main content portion of the page
5. Now tab …
> VACMS-13555: Remove hidden attribute for skip to content

- src/applications/registry.json
This PR updates the Burial and Pension bread crumbs from `"Apply for burial benefits"` and `"Apply for pension benefits"` to say `"Review burial benefits application"` and `"Review pension benefits application"` to accommodate the temporary Review pages while the forms are deactivated. This was done as overrides.
- Manual / Accessibility
What variations of circumstances (users, actions, values) need to be checked?
> Updated Pension & Burial Breadcrumbs

- src/site/layouts/vba_facility.drupal.liquid
- src/site/stages/build/drupal/graphql/CountEntityTypes.graphql.js
- src/site/stages/build/drupal/graphql/GetLatestPageById.graphql.js
- src/site/stages/build/drupal/graphql/vbaFacility.graphql.js
- src/site/stages/build/drupal/individual-queries.js
This pull request should add a working query that pulls data about the VBA Facility pages. This query should pull in available data from those pages without breaking the build.
relates to [#14948](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14948)
When pulling from a tugboat instance with published Facility pages, I confirmed that a local build pulls the data in without breaking the build.
I also confirmed that the page data is present in `.cache/localhost/drupal/pages.json`, which proves the query was successful.
What needs to be checked to prove this works? **That the query pulls in the needed data without breaking the build.** 
What needs to be checked to prove it didn't break any related things? **The local build process and local `pages.json` file.**
What …
> [VA-14948] Add VBA Facility GraphQL Query

- src/applications/registry.json
VAOS is going LIVE with our url changes tomorrow at 10am ET. This PR updates the root url to our new root url and removes the workaround we had in place for testing the new url in staging.
> update vaos root url in prod

- src/applications/registry.json
The coronavirus vaccine expansion app is no longer in use, having [been redirected](https://github.com/department-of-veterans-affairs/devops/blob/69e0a7da36a4f8004fae5ed5821b6fd2efe18c9d/ansible/deployment/config/revproxy-vagov/vars/redirects.yml#L4881C12-L4881C48).
I've also verified that no 200s have been served for [/health-care/covid-19-vaccine/sign-up](https://www.va.gov/health-care/covid-19-vaccine/sign-up/introduction)* in [the past week](https://grafana.vfs.va.gov/explore?orgId=1&left=%5B%22now-7d%22,%22now%22,%22Loki%20(Prod)%22,%7B%22expr%22:%22%7Bapp%3D%5C%22revproxy%5C%22%7D%20%7C%3D%20%5C%22GET%20%2Fhealth-care%2Fcovid-19-vaccine%2Fsign-up%5C%22%22%7D%5D) (but [plenty of 301s](https://grafana.vfs.va.gov/explore?orgId=1&left=%5B%22now-7d%22,%22now%22,%22Loki%20(Prod)%22,%7B%22e …
> Deprecate coronavirus vaccine expansion app

- src/applications/registry.json
closes department-of-veterans-affairs/va.gov-team-forms#616  
relates to [previous PR](https://github.com/department-of-veterans-affairs/content-build/pull/1730) \[w/ incorrect breadcrumb-paths\] 
Local browser testing was successful
> 40-0247 - Fix app-registry breadcrumb-paths

- src/applications/registry.json
relates to: https://github.com/department-of-veterans-affairs/vets-website/pull/25875
Tested local environment and confirmed app 28-8832 is removed and 25-8832 continues to stay live with the proper content.
Test w/ https://github.com/department-of-veterans-affairs/vets-website/pull/25875
What needs to be checked to prove this works? 
- Ensure careers-employment/education-and-career-counseling/apply-career-guidance-form-28-8832 does not load 
- Ensure careers-employment/education-and-career-counseling/apply-career-guidance-form-25-8832 still loads correctly
See above
What variations of circumstances (users, actions, values) need to be checked?
> CH36 Forn Name Change Cleanup

- src/site/includes/tests/homepage.cypress.spec.js
- src/site/includes/tests/mocks/features.js
`vets-website` had an outdated homepage test that was reviewing `/new-home-page`. Since we released the new home page in June 2023, we've added a redirect from `/new-home-page` to `/`, causing this Cypress test to fail. In order to add value by testing our existing home page, Cypress tests must be added in `content-build`. This is because `vets-website` does not have `content-build` data available in its CI, so all that can be tested there is the header and footer.
Ticket: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15414
Cypress test passes locally.
> VACMS-15414 Add Cypress tests for homepage

- src/applications/registry.json
Enabling the MHV Medical Records application to support UAT testing and eventual release to Phase 0. The application will be hidden behind the `mhv_medical_records_to_va_gov_release` flag. The path /my-health/medical-records will be controlled by that flag. Disallowed users will be redirected to the MHV homepage.
There are two related PRs to create a Flipper toggle for the MHV MR application:
- https://github.com/department-of-veterans-affairs/vets-website/pull/26106
- https://github.com/department-of-veterans-affairs/vets-api/pull/14084
> In order for UAT to take place in a production environment, MR must be visible in production.
> 
> It is not linked from any other part of the VA.gov website, so will be "dark deployed." Only those participating in UAT will know to browse there.
Testing …
> MHV-50152 Allow MHV MR to be visible in production

- src/site/layouts/landing_page.drupal.liquid
The `div` that contains the Veteran portraits on Benefits Hub landing pages (i.e. `/health-care`) is not contained by a landmark (the `<main>` element). This moves it into that element.
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14307
Tugboat to review: https://web-1wtvtqpercm3v5ybkwhzw7ai8277jd1u.demo.cms.va.gov/health-care/
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
1. Navigate to `/health-care`
2. Inspect the Veteran banner at the bottom of the page
3. Confirm the `.veteran-banner` element is contained within `main`
4. Run the axe DevTools scan (Chrome plugin)
5. Validate that the `All page content should be contained by landmarks` category either doesn't exist or does not contain `veteran-banner` if it does exist
> VACMS-14307 Contain Veteran banner in main element

- src/site/layouts/campaign_landing_page.drupal.liquid
- src/site/stages/build/drupal/graphql/nodeCampaignLandingPage.graphql.js
Add Reusable Q&As to Campaign Landing Pages.
Tugboat for testing: https://web-vjbjvpfgrmddgcl975iwjghzeudgmgkq.demo.cms.va.gov/initiatives/clp-test-title/
CMS test CLP entry: https://cms-n5953dtomqw1xd0rkphemtf55dby0uer.demo.cms.va.gov/node/62291/edit
1. Go to the above Tugboat URL (with SOCKS on, and socks, if you prefer)
2. Under the FAQ section, verify that you see 3 Page-specific Q&As (verify questions and answers appear) in accordions
3. Scroll down to Reusable QA (Accordion) and verify that you see 3 sets of questions and answers in accordions
4. Scroll down to Reusable QA (normal display) and verify that you see 3 sets of questions and answers laid out on the page
> VACMS-10939 Add Reusable Q&As to Campaign Landing Pages

- .github/workflows/content-release.yml
added step for content release workflow to send alert to Datadog when release is successful.
[ticket #15539](https://app.zenhub.com/workspaces/vagov-cms-team-5c0e7b864b5806bc2bfc2087/issues/gh/department-of-veterans-affairs/va.gov-cms/15539)
Test from branch passed [https://github.com/department-of-veterans-affairs/content-build/actions/runs/6566972118](https://github.com/department-of-veterans-affairs/content-build/actions/runs/6566972118)
> add datadog content-release success notification

- src/site/layouts/event.drupal.liquid
- src/site/layouts/faq_multiple_q_a.drupal.liquid
- src/site/layouts/health_care_local_facility.drupal.liquid
- src/site/layouts/news_story.drupal.liquid
- src/site/layouts/person_profile.drupal.liquid
- src/site/layouts/press_release.drupal.liquid
- src/site/layouts/q_a.drupal.liquid
- src/site/layouts/step_by_step.drupal.liquid
- src/site/layouts/support_resources_detail_page.drupal.liquid
- src/site/layouts/va_form.drupal.liquid
- src/site/stages/build/drupal/graphql/nodeEvent.graphql.js
- src/site/stages/build/drupal/graphql/pressReleasePage.graphql.js
Related to #15565
The changes to breadcrumb data that are implemented in https://github.com/department-of-veterans-affairs/va.gov-cms/pull/15572 require some changes to Content Build to conform to the new data model. 
* Checked broken links and other tests, made sure that build succeeded
* Checked examples of every content type against their production equivalents to make sure they remained consistent
* Some links that were unnecessarily dependent on the breadcrumbs data shifted to a more stable mechanism
Links to example pages from each affected content type. Unless noted, what should be checked is the breadcrumb.
**Events**
Specifically check that the 'See more events' link works
* https://www.va.gov/lovell-federal-health-care-tricare/events/55993/
* …
> VACMS-15565 breadcrumb data changes

- src/site/filters/liquid.js
Removed the FE banner flag so that it unblocks CMS removal.
> VACMS-15694: Remove mobile promo banner flag in FE

- .github/workflows/content-release.yml
closes [#15540](https://app.zenhub.com/workspaces/vagov-cms-team-5c0e7b864b5806bc2bfc2087/issues/gh/department-of-veterans-affairs/va.gov-cms/15540)
[https://github.com/department-of-veterans-affairs/content-build/actions/runs/6614918906/job/17967099012](https://github.com/department-of-veterans-affairs/content-build/actions/runs/6614918906/job/17967099012)
> report content release failures to Datadog separately

- src/applications/registry.json
Adding a new entry for the rated-disabilities application. The goal is to move the application folder in `vets-website` and update the `entryName` at the same time. Once this PR is merged and I've confirmed that both routes are working in production, I will swap the routes on the entries and test again. If that is successful, then I will remove the unneeded entry.
- https://github.com/department-of-veterans-affairs/vets-website/pull/26240
- What needs to be checked to prove this works? 
Visiting both of these routes (`/disability/view-disability-rating/my-rating` and `/disability/view-disability-rating/rating`) while authenticated should result in the rated disabilities react app rendering
1. Do this
2. Then
> Adding new entry for rated disabilities application

- src/applications/registry.json
Swapping the `rootUrls` for the two Rated Disabilities application entries. Once I have verified that the swap worked correctly, I will make a follow-up PR to remove the old entry
relates to:
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/66061
> Swapping rootUrls for the old entry and new Rated Disability application entries

- .github/CODEOWNERS
Platform support request Slack: https://dsva.slack.com/archives/CBU0KDSB1/p1698336681097449
I have 2 teams, Sitewide Public Websites & Facilities. We have a variety of Github teams and I'd like help understanding how they are managed / if we can make some changes.
* https://github.com/orgs/department-of-veterans-affairs/teams/vfs-facilities/members - what is this team used for? (Lindsey Hattamer is maintainer.)  I see this Team listed as codeowners in vets-api, and it includes researchers.
* https://github.com/orgs/department-of-veterans-affairs/teams/vsa-facilities-frontend/members -- this is the correct group of people for vets-api / vets-website / content build code reviewers. Is it possible to EOL the @vfs-facilities team and rename this team to be @vfs-facilities?
* …
> Codeowners: Sitewide team name changes

- src/site/stages/build/drupal/graphql/nodeEvent.graphql.js
- src/site/stages/build/drupal/graphql/nodeEventListing.graphql.js
- src/site/stages/build/drupal/health-care-region.js
- src/site/stages/build/drupal/metalsmith-drupal.js
Relates to:
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15856
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15641
In https://github.com/department-of-veterans-affairs/va.gov-cms/pull/15761 we are adding a new field to the CMS to support adding an Event to multiple Event Listings, without changing the cardinality of field_listing to unlimited.
This PR adds the additional field query to the existing Event List GraphQl query, and assembles the data together before handing off to the event listing, providing the related feature toggle is enabled.
Relates to:
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15641
[Jill](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15641#issuecomment-1773419429) and Laura …
> VACMS-15641: Adds 'add to National Outreach Calendar' checkbox

- src/applications/registry.json
Enabling the MHV Medications application to support UAT testing and eventual release to Phase 0. The application will be hidden behind the `mhv_medications_to_va_gov_release` flag. The path /my-health/medications will be controlled by that flag. Disallowed users will be redirected to the MHV homepage.
There are two related PRs to create a Flipper toggle for the MHV MR application:
- https://github.com/department-of-veterans-affairs/vets-website/pull/26362
- https://github.com/department-of-veterans-affairs/content-build/pull/1584
> In order for UAT to take place in a production environment, Mx must be visible in production.
> 
> It is not linked from any other part of the VA.gov website, so will be "dark deployed." Only those participating in UAT will know to browse there.
Testing has …
> Turn on medications for prod

- .github/workflows/content-release.yml
- .github/workflows/continuous-integration.yml
- src/site/stages/build/plugins/download-drupal-assets.js
Closes department-of-veterans-affairs/va.gov-cms#15883. Should make life easier for people trying to find reasons for failure in the action log.
Before:
After:
Verified we can still see full info with debug enabled:
Saved almost 70K lines.
> VACMS-15883: Don't log every file download message.

- src/site/facilities/facility_social_links.drupal.liquid
relates to https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11848
current (with noreferrer):
new (without noreferrer):
1. Do this go to: http://f22710de9318b08e12f9f2a74848a690.review.vetsgov-internal/sheridan-health-care
> remove noreferrer

- src/applications/registry.json
Removing a no longer needed entry for the rated-disabilities application. The new entry has `entryName: "rated-disabilities"` and the rootUrl for the entry being removed is not one used in VA.gov links
- department-of-veterans-affairs/va.gov-team/issues/66061
1. Do this
2. Then
> Removing no longer needed entry for rated-disabilities

- src/site/facilities/facility_social_links.drupal.liquid
- src/site/stages/build/drupal/graphql/facilities-fragments/healthCareSocialMedia.fields.graphql.js
This adds the YouTube channel link to any facilities that include data for it.
relates to [#15465](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15465)
Local, see screenshot below.
What needs to be checked to prove this works?
1. Create a local build with this branch, and with the command `yarn build --pull-drupal --drupal-address=https://cms-ewako3qasxgcgkwsgdkkb3tlsr09jost.ci.cms.va.gov/ username=max.antonucci@agile6.com password=drupal8`
2. Confirm that the page where a YouTube link was added shows it on the front-end
> [VA-15465] Add YouTube link to VAMC Facility social links

- src/site/includes/tests/homepage.cypress.spec.js
Adjust homepage Cypress tests. content-build is not responsible for much of the content on the home page, so we're doing a simple smoke test to ensure the sections have loaded.
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15699
Cypress tests passing.
> VACMS-15699 Adjust homepage Cypress tests

- package.json
- yarn.lock
Closes https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16036 . Will give time to upgrade Review Instances and CMS Staging servers to the right GCC version level to accommodate this package.
Discussion here:
https://dsva.slack.com/archives/CJT90C0UT/p1699300432617899
CMS tests of Content-build fail on Staging servers with:
> VACMS-16036: Downgrade node-libcurl to v2.3.4

- src/applications/registry.json
In a previous PR (listed below) I update the URL for the current entry for the rated-disabilities application. I forgot to make sure that the breadcrumb URLs were update to match the change. This PR fixes that
- department-of-veterans-affairs/content-build/pull/1763
department-of-veterans-affairs/va.gov-team#66061
Rated Disabilities Application
> Fixing issue with breadcrumb URL

- package.json
- yarn.lock
Updating Cypress to 13.5 which is the latest for now.
- [Update Cypress to Latest Version](https://github.com/department-of-veterans-affairs/va.gov-team/issues/68227)
* I consulted migration guides for Cypress 11,12, and 13. Nothing jumped out as a deal breaker.
* Cypress tests are passing locally.
N/A
None
None
> update cypress to 13.5

- package.json
- yarn.lock
Upgrading mochawesome to the latest version (7.1.3).
[Update Mochawesome to Latest Version in `content-build`](https://github.com/department-of-veterans-affairs/va.gov-team/issues/68229)
Cypress tests pass locally -- hooray
Mochawesome reports generated in CI still look good and are getting uploaded to S3 successfully.
N/A
None
> update mochawesome to 7.1.3

- package.json
- yarn.lock
Upgrading mocha to the latest version (10.2.0).
[Update Mocha to Latest Version in `content-build`](https://github.com/department-of-veterans-affairs/va.gov-team/issues/68228)
Unit tests pass locally
None
> update mocha to 10.2.0

- src/applications/registry.json
This PR fixes a minor typo in a breadcrumb override for the 10-10EZR application.
department-of-veterans-affairs/va.gov-team#70193
- Breadcrumbs contain no typos that would cause a broken link
> Fix typo in breadcrumb link for 10-10EZR application

- src/site/includes/header.html
Moves promo banner under the header. Checked and this will not impact injected header. 
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15943
Tested the header markup to make sure the promo banner element is inside the header tag
Header
> VACMS 15943: Move promo banner into header tag

- src/applications/registry.json
Enable production route for simple forms 21-0966, Intent to File.
https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team-forms/403
[vets-website PR](https://github.com/department-of-veterans-affairs/vets-website/pull/26602)
[vets-api PR](https://github.com/department-of-veterans-affairs/vets-api/pull/14442)
> Enable form 21-0966

- src/applications/registry.json
This updates the ITF app name to the appropriate name for the <form> tag. It also disables the 4555 form in production.
department-of-veterans-affairs/va.gov-team-forms#805
> Update the appName for 21-0966 and disable 4555 in production

- src/site/stages/build/drupal/graphql/vbaFacility.graphql.js
The VBA Regional Facility page has been merged to production. Two fields for the query on `vbaFacility.graphql.js` are referenced but do not yet exist on the Drupal side, which causes an error on [this staging page.](https://staging.cms.va.gov/get-help-from-a-va-accredited-representative-or-vso) Production is not broken (see [this Slack thread](https://dsva.slack.com/archives/CT4GZBM8F/p1701179249804799) for more details).
This pull request removes the two fields creating the error for the time being. The template will still render properly, just with a few missing elements, so that can be left alone for now to minimize the code being changed. Once this is merged, I'll open up a draft PR adding the fields back. It will be marked as "do not merge" and left alone until Drupal adds those two …
> [VA-14940] Remove unavailable Spotlight CC fields

- src/site/filters/liquid.js
- src/site/layouts/health_care_region_page.drupal.liquid
- src/site/stages/build/drupal/graphql/healthCareRegionPage.graphql.js
Pulled filter logic from graphQL to the browser in drupal liquid filters. Now there is a `filterAndSortEvents` that we will use to take in all events for a health care region(up to 1000 events) and filter then sort the events based on most upcoming event. 
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10716
Tested in tugboat env to check for event staleness. Was able to see all events are being passed through to the FE, not just 10 and most upcoming event is being shown.
> VACMS-10176: Fix Featured events when no featured event is live on Health Care Region Pages

- src/site/assets/sass/style.scss
- src/site/layouts/campaign_landing_page.drupal.liquid
- src/site/stages/build/drupal/graphql/nodeCampaignLandingPage.graphql.js
Campaign Landing Pages currently use a 7:2 aspect ratio that causes problems for rendering the image at various breakpoints.
Current design:
Design put together a new 1:1 design for Campaign Landing Pages so the text and the image would be side by side.
New design:
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15632
Tugboat: https://web-5wyecacp4hjlvfcfmw4varhtjij1vruu.demo.cms.va.gov/
Tested local build on:
- /initiatives/protecting-veterans-from-fraud
- /initiatives/veterans-experience-action-centers
- /initiatives/national-buddy-check-week-talk-to-10-veterans
- /initiatives/sign-in-securely-with-logingov
- /initiatives/covid-flu
- /initiatives/veteran-trust-in-va
- /initiatives/end-of-life-benefits/
- /initiatives/emergency-room-911-or-urgent-care
- …
> VACMS-15632 Campaign Landing Pages image aspect ratio fix

- src/applications/registry.json
We are looking to remove the my-health section from the site map while we are in the early stages of the rollout. We believe that setting a project to `private:false` should remove it form the site. 
This PR removes on the my-health tools to test the theory that its removed form the site map
No issue, but this was covered in a private slack channel
Not sure how to test the site map locally 
No UI changes
/my-health/medications
Tests in CI
N/A
N/A
N/A
> (my-health) Update registry.json to remove medications from the sitemap

- src/site/layouts/event.drupal.liquid
- src/site/stages/build/drupal/graphql/nodeEvent.graphql.js
This ticket is in support of this [CMS change](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/16173/) We are adding a new register CTA that can add a mailto: option to open a user's local email application when a email register for event option is selected in the CMS.
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15411
Tested changes in tugboat env for registration required events with new CTA of email.
https://web-fwlvssypud9glye0p1gfv4hmamkufgpi.ci.cms.va.gov/puget-sound-health-care/events/63747
(Tugboat: https://tugboat.vfs.va.gov/655bd8ab1df1f2e9e200a940
CMS: https://cms-fwlvssypud9glye0p1gfv4hmamkufgpi.ci.cms.va.gov/)
Also verified that other register CTAs are not affected by this change.
Events
> VACMS-15411: Event CTA addition of Email Register button functionality

- src/site/stages/build/drupal/health-care-region.js
Removes use of FEATURE_EVENT_OUTREACH_CHECKBOX.
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16517
Verified content-build build succeeded.
Checked that content build succeeds. Also performed 
There are no behavior changes in this PR.
Events
Visit /outreach-and-events/outreach-materials/
Visit /alaska-health-care/stories/learn-how-to-cook-with-healthy-teaching-kitchen
Verify the 
Visit /lovell-federal-health-care-va/events/
> VACMS-16517: Remove use of FEATURE_EVENT_OUTREACH_CHECKBOX.

- .github/CODEOWNERS
- src/site/includes/vet_centers/address_phone_image.liquid
- src/site/layouts/vet_center.drupal.liquid
- src/site/stages/build/drupal/graphql/vetCenterLocations.graphql.js
Veterans may know and search for their closest Vet Center by a common name, rather than an official name. This shows the common names alongside the official names when available on location listings and location details pages.
**Note:** The ticket covers three examples of current name behavior that needs to change. Examples 1 and 3 are covered by these changes. Example 2 needs changes made to `vets-website` and `vets-api` due to the data being pulled in differently. …
> [VA-15424] Add common and official names to Vet Center locations

- src/applications/registry.json
The coronavirus vaccination app is no longer in use, having [been redirected](https://github.com/department-of-veterans-affairs/devops/blob/69e0a7da36a4f8004fae5ed5821b6fd2efe18c9d/ansible/deployment/config/revproxy-vagov/vars/redirects.yml#L4878).
I've also verified that no 200s have been served for [/health-care/covid-19-vaccine/stay-informed](https://www.va.gov/health-care/covid-19-vaccine/sign-up/introduction)* in [the past week](https://grafana.vfs.va.gov/explore?orgId=1&left=%5B%22now-7d%22,%22now%22,%22Loki%20(Prod)%22,%7B%22expr%22:%22%7Bapp%3D%5C%22revproxy%5C%22%7D%20%7C%3D%20%5C%22GET%20%2Fhealth-care%2Fcovid-19-vaccine%2Fstay-informed%5C%22%22%7D%5D) (but [plenty of 301s](https://grafana.vfs.va.gov/explore?orgId=1&left=%5B%22now-7d%22,%22now%22,%22Loki%20(Prod)%22,%7B%22expr%22 …
> Remove coronavirus-vaccination app

- src/site/filters/events.js
- src/site/filters/liquid.js
- src/site/filters/liquid.unit.spec.js
Improve Events test coverage in `content-build`. I removed `filterPastEvents` because this was not being used at all. Tests existed for the current event modifications functions, so I just made sure they were as robust as they are in `vets-website` now.
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14116
Unit tests run
> VACMS-14116 Improve Events test coverage

- .github/workflows/continuous-integration.yml
Closes department-of-veterans-affairs/va.gov-cms#16544.
> Notify `@cms-devops-engineers` when content build main branch CI fails.

- src/applications/registry.json
In the Find a Representative staging review, it was recommended that we update our app title to "Find a VA accredited representative or VSO".
To make this change without breaking any releases, this PR tentatively removes the application from the registry. Once the name has been updated in our manifest.json (and merged to the vets-website), we will reintroduce the app to the content-build registry with its updated name.
Find a Representative was enabled in production, but it currently lives behind a feature flag and has not gone live. Removing it from the registry should not impact any user experience.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/72527
> Temporarily removing Find a Representative from app registry (while updating its name in vets-website)

- src/applications/registry.json
- src/site/includes/vba_facilities/banner.liquid
- src/site/includes/vba_facilities/spotlight_content.liquid
- src/site/layouts/tests/vba/template/fixtures/vba_banner_informational_dismissible.json
- src/site/layouts/tests/vba/template/fixtures/vba_banner_warning.json
- src/site/layouts/tests/vba/template/fixtures/vba_banner_warning_dismissible.json
- src/site/layouts/tests/vba/template/vba_banner_test.unit.spec.js
- src/site/layouts/vba_facility.drupal.liquid
- src/site/stages/build/drupal/graphql/vbaFacility.graphql.js
- Adds banner dependent on CMS banner completion for a VBA Facility. Only shows the banner when form is complete on CMS (even though CMS doesn't let you save an incomplete form -- cannot test this edge case).  
- No flippers
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14937
- Tested banner is created for informational type (unit)
- Tested banner is created for warning type (unit)
- Tested banner can be made dismissible (unit)
- e2e tests will have to be made after VBA facilities are published on prod
Mobile:
Just the VBA Regional Office pages
View:
> VACMS 14937 Add Banner to vba template

- src/applications/registry.json
- The appName of **Find a Representative** is changing to **Find a VA accredited representative or VSO**
- Initially removed the entry from content-build entirely, but that resulted in failing e2e tests in vets-website
- The appName has **not** yet been updated in our manifest.json in vets-website ([PR link](https://github.com/department-of-veterans-affairs/vets-website/pull/27330))
> Reintroducing "Find a VA accredited representative or VSO" to app registry

- src/site/paragraphs/table.drupal.liquid
Recently we switched over to va-table for the content-build repo's reusable component. This PR adds back the captions for tables that was missing in the switch.
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16725
Tested pages that have the table component. Now seeing the caption showing properly
**Before**
**After**
All pages with table components.
> VACMS-16725: Fix captions for all table integrations

- .github/CODEOWNERS
This started bc I realized that the va_police layout wasn't set for Facilities as codeowner. Give a mouse a cookie. 🐭 🍪 
Done: 
* Specified which layouts for which products belong to PW vs. Fac. That will be useful as AP team moves forward, for knowing who to coordinate with about what.
* Specified Test folders that are owned by Facilities.
* Grouped Facilities-owned items into product buckets (VAMC/VBA/Vet Centers)
* Added @department-of-veterans-affairs/ap-admins as codeowners of Events, so they'll get notified of any changes to the Events liquid template. Can remove this once PW owns the Next implementation and we have a path to Prod. 
Didn't do: Anything else, including but not limited to: 
* paragraphs
* navigation
* includes that aren't in a subfolder
* blocks
Looking at those …
> Codeowner updates for Facilities/PW ownership in layouts/tests folders

- src/site/layouts/faq_multiple_q_a.drupal.liquid
This PR removes duplicate back to top buttons that no longer are needed with the newer web components of the button.
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16039
Tested that the buttons are no longer showing in the page markup
Pages using the faq_mulitple_q_a drupal template.
> VACMS-16039: Remove duplicate back to top buttons

- src/site/layouts/faq_multiple_q_a.drupal.liquid
- src/site/paragraphs/q_a.drupal.liquid
- src/site/paragraphs/q_a_group_collapsible_content.drupal.liquid
For this ticket we addressed header tags for accordions based on if we have a header title or not. There were multiple implementations of these reusable Q&As so we created tugboat content for each. 
```
FAQs
Resources & Support
Benefit Detail Pages
CLPs
```
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15717
Tugboat Env: main-dyel3cg3kniaoc6nrizjhqazkfgueref.demo.cms.va.gov/
CLP: https://web-dyel3cg3kniaoc6nrizjhqazkfgueref.demo.cms.va.gov/initiatives/this-is-my-clp
FAQs: https://web-dyel3cg3kniaoc6nrizjhqazkfgueref.demo.cms.va.gov/reso …
> VACMS-15717: Change reusable Q&As header structure  

- src/site/layouts/campaign_landing_page.drupal.liquid
- src/site/stages/build/drupal/graphql/nodeCampaignLandingPage.graphql.js
In a [previous ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15632) ([PR here](https://github.com/department-of-veterans-affairs/content-build/pull/1810/), we updated the CLP landing page hero images to use a square crop rather than be a full-width banner. This included adding a hard-coded size to the image because the `CROPSQUARE` derivative from Drupal was sending images through at <400px, and the design was closer to 500px. We got a new derivative created that sends the images back at 500px, so we can remove the hard-coded size and update the GraphQL query.
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16361
Tested and in Tugboat.
Full list of prod Campaign Landing Pages to verify in Tugboat:
- …
> 16361 clp derivative

- src/site/paragraphs/react_widget.drupal.liquid
- src/site/tests/static-pages/static-page-widgets.unit.spec.js
The design system team has deprecated the Formation style for `.va-button-primary` in favor of the va-button web component or other alternative like the action link depending on the scenario.
In this case, the usage of `.va-button-primary` was being used with a link. When clicked, the behavior of this link changes the URL. 
This means that it should not be presented as a button so I have removed that style and add the [action link](https://design.va.gov/storybook/?path=/docs/components-action-link--primary) class instead.
Reference [Links vs …
> Replace deprecated .va-button-primary class

- src/applications/registry.json
Updated the title of the MHV on VA.gov landing page to "My HealtheVet" - this adds a space after `My` and removed the `on VA.gov`. Removed the `on VA.gov` per direction that the title should be the App name.
https://app.zenhub.com/workspaces/mhv-on-vagov-top-level-view-62619a987d74510018ecc546/issues/gh/department-of-veterans-affairs/va.gov-team/73155
Manual testing to check the title.
There are no updates to the UI, but to the title:
Before: 
After:
- /my-health landing page only
- <title> tag in the html header has a space between "My" and "HealtheVet"
> Update to MHV on VA.gov title

- src/site/includes/metatags.drupal.liquid
Add `nonce` to smart banner script in hopes of getting through the content security policy errors in staging.
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15318
Locally on iOS Chrome, Safari (regression check), Android Chrome and Android Firefox.
> VACMS-15318 Add nonce to smartbanner script

- src/applications/registry.json
- Enable Presidential Memorial Certificate (40-0247) form-app in application registry
- Flipper ON in Staging, OFF in Prod.  End-date TBD.
- _Link to ticket created in va.gov-team-forms repo_
department-of-veterans-affairs/va.gov-team-forms#484
- N/A &mdash; just a Cypress config-enhancement to enable reporting locally.
This form ONLY
> 40-0247 - Enable form in app-registry

- src/site/includes/metatags.drupal.liquid
Smart banners are ready for release to production for testing. Removing the environment check so we are not isolated to staging.
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15318
Staging tests in Android Chrome/Firefox and iOS Chrome (also tested iOS Safari for regressions)
> VACMS-15318 Remove environment check for smart banners

- src/applications/registry.json
Added a temporary CPAP form redirect app to the registry. This app will facilitate the migration of the CPAP form from the old path of `/health-care/order-hearing-aid-or-CPAP-supplies-form.` to the new one of `/my-health/order-hearing-aid-or-CPAP-supplies-form`. This entry will be removed once the migration is complete.
https://app.zenhub.com/workspaces/mhv-on-vagov-top-level-view-62619a987d74510018ecc546/issues/gh/department-of-veterans-affairs/va.gov-team/70757
N/A
N/A
None. This is a new app.
- `/my-health/order-hearing-aid-or-CPAP-supplies-form` gets redirected to `/health-care/order-hearing-aid-or-CPAP-supplies-form`
> Added temporary CPAP form redirect to registry.json

- src/site/blocks/promo.drupal.liquid
- src/site/filters/liquid.js
- src/site/paragraphs/linkTeaser.drupal.liquid
- src/site/paragraphs/link_teaser_featured_content.drupal.liquid
Remove code associated with feature_single_value_field_link feature flag that is no longer in use.
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15758
> VACMS-15758: Remove feature toggle for single value link

- src/site/assets/js/smartbanner/smartbanner.js
- src/site/filters/liquid.js
Our mobile app promotional banners for Android Chrome & Firefox and iOS Chrome were released to production last week successfully. But the banners were also showing on Windows desktop (for any machine that was also touchscreen). We added a fix to check specifically for iPhone, iPad and Android platforms to avoid Veteran confusion.
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16969
Testing conducted via ngrok with the team on [this thread](https://dsva.slack.com/archives/C52CL1PKQ/p1706119034838499).
> VACMS-16969: Mobile banner fix for touchscreen laptops

- src/applications/registry.json
Continue the migration of the CPAP React app from `/health-care/order-hearing-aid-or-CPAP-supplies-form` to `/my-health/order-hearing-aid-or-cpap-supplies-form`.
This change makes it so the registry has two entries for the CPAP app pointing to the new and old URLs. The result of this is that the app can be accessed by using either URL, but the URL in the browser will change to the URL specified in the manifest.json of the app. This essentially acts as a redirect from one URL to the other. The next step after this is to change the URL in the manifest.json to the new URL to continue the migration.
https://app.zenhub.com/workspaces/mhv-on-vagov-top-level-view-62619a987d74510018ecc546/issues/gh/department-of-veterans-affairs/va.gov-team/70757
- Manual testing: Verify the CPAP ordering app can …
> Migrate CPAP ordering app to new URL

- src/site/filters/liquid.js
- src/site/includes/metatags.drupal.liquid
With the launch of the smartbanner mobile promo banner we no longer need the feature flag to be used in the code base.
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15345
> VACMS-15345: Remove feature flag code for mobile app promo banner

- src/applications/registry.json
The `appName` for form 4142 was incorrect in `registry.json` which was causing some titles to display incorrectly. This fixes that error.
department-of-veterans-affairs/va.gov-team-forms#959
> Update registry.json to correct appName for form 4142

- .github/workflows/daily-production-release.yml
- .github/workflows/daily-release-warning.yml
Closes department-of-veterans-affairs/va.gov-cms#17117.
February 21, `vets-website` will begin deploying two hours earlier in the day. This significantly impacts how `content-build` must be developed, reviewed, and merged. 
The transition between current and new CMS teams in mid-February means that the team responsible for support requests and problems that might arise in content releases will likely be still onboarding and without benefit of the current CMS team's accrued experience.
This PR preëmptively shifts `content-build` daily deploys earlier in the day so that this change is less likely to cause problems.
> Shifts daily deployment time two hours earlier.

- src/site/components/informational_alert.drupal.liquid
- src/site/components/merger-social-sco.html
- src/site/includes/health_services_listing_services.liquid
- src/site/includes/lovell-switch-link.drupal.liquid
- src/site/includes/vet_centers/services.liquid
- src/site/layouts/health_care_local_facility.drupal.liquid
- src/site/layouts/vet_center.drupal.liquid
This adds an opt-out property to all the `content-build` components that we want to avoid automatically going from `v1` to `v3`. These are accordions and alerts (buttons and modals were also mentioned but aren't in this repo). This locks them into version 1.
N/A. This is a collective effort to address all the front-end USWDS tickets in Sprint 103 that need work on the `content-build`.
Visual, local. Go to [this Lovell TriCare Health Services page](http://localhost:3002/lovell-federal-health-care-tricare/health-services/) to see V1 alerts and accordions in action and confirm they still function.
All areas of `content-build` that use accordions and alerts.
> Opt Out of V3 Component Updates

- src/site/components/merger-social-sco.html
Fixes a bug where links in the Resources for Schools sidebar always opened in a new browsing context, despite specifying otherwise.
**To reproduce the bug, please follow these steps:**
1. Do not pull the changes in this PR.
2. Open `pages/school-administrators.md`.
3. Give some `links` in the metadata `external: true`, some `external: false`.  Set the key but not the value (`external:`) for some, and omit the attribute from other links.
4. Build the project and view the page.
5. Observe that all of the links you changed unexpectedly open in a new tab.
The solution is to provide an else statement that explicitly sets the link to open in the same tab. The current Liquid conditional appears to be sound, but links end up with `target="_blank"` anyway, suggesting that some other process is …
> Resources for Schools - Fix issue where links open in new tab

- src/site/layouts/vba_facility.drupal.liquid
- src/site/stages/build/drupal/graphql/vbaFacility.graphql.js
The VBA Regional Facilities pages have a "Prepare for your Visit" section but no content. This pull request shows that information on the page. If there's no information for this section, it and its header aren't added to the page.
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16921
Visual. See [this regional facility page on my tugboat](https://web-txcrk8bym4a0ivw3xfr8xvdhezmls36f.demo.cms.va.gov/cleveland-va-regional-benefit-office/locations/cleveland-va-regional-benefit-office/#prepare-for-your-visit) that, as of this writing, has an example of the displayed data.
All regional facilities pages (not currently published)
> [VA-16921] Add Prepare for Visit to VBA Facility Page

- src/site/assets/sass/style.scss
- src/site/paragraphs/table.drupal.liquid
Margin was removed from the design system component of the va-table. This adds back the 2em top and bottom margin for the va-table usage in content-build.
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16852
Tested instances of the table to check the margin.
Before
After
> VACMS-16852: Update margin for tables

- src/site/blocks/alert.drupal.liquid
- src/site/layouts/landing_page.drupal.liquid
Upgrade the `va-accordion` and `va-alert` component for the Benefit Hub landing pages.
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16981
Tested locally at `/health-care` and `careers-employment`.
> VACMS-16981 v3 upgrade for Benefit Hub Landing Page

- src/site/components/phone-number.drupal.liquid
- src/site/facilities/facility_health_service.drupal.liquid
- src/site/facilities/health_care_local_health_service.drupal.liquid
- src/site/filters/liquid.js
- src/site/paragraphs/service_location.drupal.liquid
If the facility's mental health care chooses "Use the general facility phone number," it will show the facility's mental health care number, not their main phone number. It also updates the phone number partial being used so it includes `aria-describedby` with the label.
department-of-veterans-affairs/va.gov-cms#16652
Visual. Checked all available services on [Hot Springs VA Medical Center](http://deb34fb5e1a35391d2628af88f742060.review.vetsgov-internal/black-hills-health-care/locations/hot-springs-va-medical-center/#health-care-offered-here) and [Cheyenne VA Medical Center](http://deb34fb5e1a35391d2628af88f742060.review.vetsgov-internal/cheyenne-health-care/locations/cheyenne-va-medical-center/#health-care-offered-here) in my tugboat …
> [VA-16652] Align Main mental health phone number with service contact info

- src/site/facilities/vba_social_links.drupal.liquid
- src/site/filters/liquid.js
- src/site/layouts/vba_facility.drupal.liquid
- src/site/stages/build/drupal/graphql/vbaFacility.graphql.js
- Updates graphql query. Uses correct source for intro text and updates newsletter content.
- Processes centralized content for intro text.
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14933
- Checked content on tugboat. Checked at multiple viewport sizes.
| Benefits mobile  |   <img width="393" alt="Screenshot 2024-02-20 at 9 17 16 PM" src="https://github.com/department-of-veterans-affairs/content-build/assets/5606931/c2ded707-42f9-4c92-8e3a-193e1c4ff76c">    |   <img width="393" alt="Screenshot 2024-02-23 at 1 14 34 PM" src="https://github.com/department-of-veterans-affairs/content-build/a …
> Fixes Newsletter and the intro text which is not introtext in VBA it is Centralized Content

- src/site/components/phone-number.drupal.liquid
- src/site/filters/liquid.js
- src/site/includes/vba_facilities/service_location.liquid
- src/site/layouts/vba_facility.drupal.liquid
[A pull request for using VBA facility mental health numbers in the mental health service accordions](https://github.com/department-of-veterans-affairs/content-build/pull/1907) was recently merged. However, the phone number component needs to have the phone number's extension separated from the number for it to display correctly.
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16652
Locally, on tugboat build.
See the services at the [Hot Springs VA Medical Center](https://web-txcrk8bym4a0ivw3xfr8xvdhezmls36f.demo.cms.va.gov/black-hills-health-care/locations/hot-springs-va-medical-center/#health-care-offered-here) (no mental health phone number extension) and the [Fayetteville VA Medical …
> VA-16652: separate phone extension for mental health numbers

- src/applications/registry.json
Updates the copy for the breadcrumbs across all Pension form pages to be: `Apply for Veterans Pension benefits`.
It was `Apply for Veterans' pension benefits`, but the style guide says to use "Veterans Pension" with capitalized P and no apostrophe.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/74451
- Ran `yarn build` and `yarn watch` locally for `vets-website`. Confirmed that the breadcrumbs matched the new copy.
| Desktop |    <img width="650" alt="Screenshot 2024-03-01 at 9 29 22 AM" src="https://github.com/department-of-veterans-affairs/content-build/assets/21046714/24530f99-4636-4bc2-a20f-067a7adb2746">    |    <img width="750" alt="Screenshot 2024-03-01 at 9 15 21 AM" …
> Update Pensions breadcrumb title

- src/site/facilities/facilities_health_services_buttons.drupal.liquid
- src/site/facilities/main_buttons.drupal.liquid
- src/site/filters/liquid.js
- src/site/stages/build/drupal/graphql/bannerAlerts.graphql.js
- src/site/stages/build/drupal/graphql/bioPage.graphql.js
- src/site/stages/build/drupal/graphql/facilities-fragments/healthCareLocalFacility.node.graphql.js
- src/site/stages/build/drupal/graphql/healthCareLocalFacilityPage.graphql.js
- src/site/stages/build/drupal/graphql/healthCareRegionDetailPage.graphql.js
- src/site/stages/build/drupal/graphql/healthServicesListingPage.graphql.js
- src/site/stages/build/drupal/graphql/leadershipListingPage.graphql.js
- src/site/stages/build/drupal/graphql/locationsListingPage.graphql.js
- src/site/stages/build/drupal/graphql/pressReleasesListingPage.graphql.js
- src/site/stages/build/drupal/graphql/storyListingPage.graphql.js
- src/site/stages/build/drupal/graphql/vaPolice.graphql.js
- src/site/stages/build/drupal/graphql/vamcPoliciesPage.graphql.js
- src/site/stages/build/drupal/static-data-files/vamcEhrSystem/index.js
- Pages with fieldAdministration of Lovell TRICARE now show MHS Genesis Patient Portal link instead of link to Make an appointment page. Things remain the same for Lovell VA and Lovell Federal pages (Program pages except ones that have Lovell TRICARE as fieldAdministration)
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17299
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17416
- Top task link to Make an appointment was visible on all Lovell TRICARE pages
- Checked all pages as Lovell TRICARE user in staging/localhost build and vagovprod build
| Mobile  | …
> Lovell TRICARE pages now present MHS site when cerner/cerner_staged

- src/applications/registry.json
This PR removes ```burials_poc_v6``` from ```/registry.json```. The ask came from this [Zenhub Ticket](https://app.zenhub.com/workspaces/identity-5f5bab705a94c9001ba33734/issues/gh/department-of-veterans-affairs/va.gov-team/77051)
> removes-burial-v6

- src/site/components/merger-social-sco.html
Removes an undesired heading element. Affected text should instead match as regular body copy.
I work for the IIR Team. We are the owners of Resources For Schools.
Related to [vagov-content PR #925](https://github.com/department-of-veterans-affairs/vagov-content/pull/925).
This static site does not have testing.
Before (Links are wrapped in H4s):
After (Links match regular body copy style):
Only effects Resources For Schools ([https://www.va.gov/school-administrators/](https://www.va.gov/school-administrators/)).
> 430 - Remove undesirable heading element

- .github/workflows/continuous-integration.yml
- Change the timeout length to give development environment long enough to complete the build.
> increase timeout for continuous integration workflow

- src/applications/registry.json
Remove breadcrumbs prop from Discharge Upgrade Wizard application registry so we can use the web component for breadcrumbs in vets-website.
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17252
Testing done locally from vets-website.
> VACMS-17252 Discharge Upgrade Wizard breadcrumbs update

- src/site/includes/lovell-switch-link.drupal.liquid
- Since TRICARE /make-an-appointment page was decided to be excluded in favor of direct links to the TRICARE MHS Genesis page, we should prevent people from accessing the existing page because it is only valid for VA consumers.
- Prevents creation of TRICARE experience switcher on VA make-an-apppointment page
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17469
- Checked that switcher is removed only from Lovell VA `/make-an-appointment` page.
| Mobile  |    <img width="390" alt="Screenshot 2024-03-08 at 4 30 10 PM" src="https://github.com/department-of-veterans-affairs/content-build/assets/56 …
> Fixes to have VA Make appointment page not able to change to TRICARE

- src/site/includes/vba_facilities/service_location.liquid
- src/site/includes/vba_facilities/services.liquid
- src/site/layouts/vba_facility.drupal.liquid
This adds event tracking to the VBA Regional Facilities pages, and any button and links used in that page's partials. The page views and scroll depth are automatically tracked by Google Analytics. This pull request adds specific event tracking for the links and buttons.
[department-of-veterans-affairs/va.gov-cms#16311](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16311)
Visual, made sure the page built properly and there was no improper code in the affected elements.
VBA Regional Facilities pages
> [VA-16311] Add analytics to Regional Facilities pages

- .github/workflows/continuous-integration.yml
Encountered the following error during a run of `continuous-integration` workflow
`An error occurred (ExpiredToken) when calling the PutObject operation: The provided token has expired.`
Adjusting the role session duration to verify if that is the cause for the token expiration mid-deploy
- https://dsva.slack.com/archives/CT4GZBM8F/p1710255732049039
> fix(): Increase the role-duration-seconds for AWS cred step in deploy

- src/site/filters/liquid.js
- src/site/includes/README-pagination.md
- src/site/includes/pagination.drupal.liquid
- src/site/layouts/press_releases_listing.drupal.liquid
- src/site/layouts/story_listing.drupal.liquid
- src/site/layouts/support_resources_article_listing.drupal.liquid
- src/site/paragraphs/lists_of_links.drupal.liquid
Upgrade the custom pagination code with the v3 pagination design system web component. This required creating a `script` for adding the `pageSelect` event handler and using `localStorage` to store the current page number since pagination on static pages requires a full page reload when navigating.
This pagination template is used on Resources & Support taxonomy, story listings and press release pages.
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17199
Tested these URLs locally:
- `/resources`
- `/resources/va-account-and-profile`
- `/north-texas-health-care/stories`
- `/clarksburg-health-care/news-releases/` (one page only)
- `/sheridan-health-care/news-releases/`
<details>
<summary>Pagination</summary>
</details>
<details>
<summary>Article headers (search …
> 16986 Resources & Support taxonomy pages pagination

- src/site/blocks/promo.drupal.liquid
In support of the v1 -> v3 component upgrades, upgrade the link in Featured Content promo blocks to use `<va-link>`.
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17486
Tested locally at `/service-member-benefits`.
> VACMS-17486 Featured content block link upgrade

- .github/workflows/continuous-integration.yml
- pointed vagovstaging build at second prod mirror 
- This was identified because vagovdev and vagovstaging were both pointed t the same tugboat instance and were both running into 504 errors. 
- adding a second prod mirror gives both vagovdev and vagovstagin their own tugboat instance to query against
- CMS Team
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17510
| Mobile  | …
> pointed vagovstaging at different prod mirror

- src/site/layouts/va_form.drupal.liquid
- src/site/paragraphs/linkTeaser.drupal.liquid
- src/site/paragraphs/lists_of_links.drupal.liquid
Finish up Find a Form link conversion to web components.
Also includes accessibility adjustments: remove `role="presentation"` on icons that already have `aria-hidden="true"`.
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17188
Tested locally at `/find-forms`.
> VACMS-17188 Remaining Find Forms links fixes and accessibility fixes

- src/site/layouts/landing_page.drupal.liquid
- src/site/paragraphs/linkTeaser.drupal.liquid
Benefit hub landing template component upgrade v1 to v3
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17280
Tested new components locally
`/health-care/`
Benefit Hubs
> VACMS-17280: benefit hub component upgrade

- .github/workflows/continuous-integration.yml
- We are temporarily removing concurrency from the builds for content-build CI workflow. This is a short-term fix while we work on the longer-term fix. A single PR build and a single prod push will be allowed at one time. 
- This workflow has been overwhelming the content-build prod mirror tugboat, causing 504 and 502 errors. 
- This solution will reduce the load on the tugboat prod mirror while we work on a more permanent fix. 
- CMS Team
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17538
> removing concurrency

- src/site/filters/liquid.js
- src/site/filters/liquid.unit.spec.js
- src/site/includes/README-pagination.md
- src/site/includes/pagination.drupal.liquid
- src/site/layouts/press_releases_listing.drupal.liquid
- src/site/layouts/story_listing.drupal.liquid
- src/site/layouts/support_resources_article_listing.drupal.liquid
- src/site/stages/build/plugins/create-resources-and-support-section.js
The new implementation of the pagination v3 web component has its downsides. The three templates that use it (Resources & Support, Story Listings, and Press Releases) are all implemented differently and have to be individually handled in the pagination logic. I added separate logic for the Story Listings as they do not use the paginator and we needed a way to know how many total results there are in order to display the correct number of page numbers at the bottom.
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17526
- /resources/va-account-and-profile/
- /resources/decision-reviews-and-appeals/
- /resources/disability/
- /resources/education-and-training/
- /resources/health-care
- /resources/other-topics-and-questions
- /greater-los-angeles-health-care/stories
- …
> VACMS-17526 Fix pagination issues with story listings

- .github/workflows/continuous-integration.yml
- Adding parallel builds back into the CI workflow
- CMS Team
> adding parallel builds back in

- src/applications/registry.json
- Removing app `mhv-inherited-proofing` form registry.json
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17580
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/74148
> removed mhv-inherited-proofing from registry

- src/site/includes/lovell-switch-link.drupal.liquid
- src/site/tests/cypress/vamc-lovell.cypress.spec.js
- Adds testing now that EHR system is cerner on all platforms. Tests that MHS Genesis link is present on all necessary pages and Make an appointment link on VA pages. Tests that a user shouldn't be able to travel from VA Make an appointment page to TRICARE counterpart.
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17107
- Added cypress E2E testing for Lovell pages/links on TRICARE and VA
No visual changes. Just testing.
Does not impact the site.
Check that tests pass in CI
> VACMS 17299 Lovell TRICARE MHS Genesis portal link and VA Make an appointment link testing

- src/site/includes/social-share.drupal.liquid
- src/site/layouts/event.drupal.liquid
- src/site/teasers/event.drupal.liquid
Update individual event template with web components where they exist.
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17057
Tested a couple of events pages locally:
- `/minneapolis-health-care/events/64415/`
- `/outreach-and-events/events/53182/`
> VACMS-17057 Events detail page web component upgrades

- .github/workflows/wait-for-cms-ready/action.yml
- We extended the wait timeout period for CMS Ready portion of the CI Workflow to account for `staging.cms.va.gov` to be in the midst of deploying. 
- CMS Team
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17610
> extended timeout period to 4200 seconds

- src/site/facilities/health_care_region_detail_content.drupal.liquid
This removes top task links from the Programs pages.
Facilities team.
department-of-veterans-affairs/va.gov-cms#15567
Locally, visual testing.
- https://web-txcrk8bym4a0ivw3xfr8xvdhezmls36f.demo.cms.va.gov/chicago-health-care/programs/covid-19-vaccines/jesse-brown-va-post-acute-sequelae-of-covid-19-long-covid-program/
- https://web-txcrk8bym4a0ivw3xfr8xvdhezmls36f.demo.cms.va.gov/lovell-federal-health-care-tricare/programs/immunizations/
All Programs pages, including Lovell.
> VA-15567: Remove Top Task Links for Programs pages

- .github/workflows/ecr-password-update.yml
- src/applications/registry.json
…ntative replacement (#1983)
- We were hitting rate limits for the docker image used for cypress testing. We moved the image into the proved ECR repo under `/cypress-io`. This adds a new workflow to update the ECR password. A second PR will implement the change in the CI workflow. 
- CMS Team
https://dsva.slack.com/archives/C04CYC4LMU6/p1711382453727949
> cypress image moved to private repo

- src/applications/registry.json
Pensions team has been asked to change the root url of the site from:
pension/application/527EZ
to:
pension/apply-for-veteran-pension-form-21p-527ez
Testing done
Made the changes, tested locally.
> Added entry for new URL

- src/site/filters/liquid.js
- src/site/filters/liquid.unit.spec.js
- src/site/layouts/event.drupal.liquid
Use the field `fieldEventRegistrationrequired` coming from Drupal to add appropriate information to event templates:
- If registration is required, it should say `Registration: Required`
- If you must apply, it should say `Application: Required`
- If you need to RSVP, it should say `RSVP: Required`
- If none of these are true ("More details"), there should be no mention of anything required
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16578
https://web-qyrx3kbwmz09ov7ewb8jhxyrcgjfgftb.demo.cms.va.gov/
Tested these URLs:
- `/outreach-and-events/events/66665/` (Apply)
- `/outreach-and-events/events/64652/` (Register)
- `/outreach-and-events/events/66435/` (More details)
- `/outreach-and-events/events/65961/` (RSVP)
- `/poplar-bluff-health-care/events/66486/` (None) …
> VACMS-16578 Add registration required for events

- .github/workflows/content-release.yml
- package.json
- The `build` command started running out of heap memory. 
- Run `yarn build` with `--max-old-space-size=6000`
- increase heap to `--max-old-space-size=8192`
- CMS Team
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17760
- Tested locally; increase allowed build to run without errors.
> increase heap for build command

- src/applications/registry.json
The Health Enrollment (1010) team has been asked to update the root URL of the Health Care Application to meet [VA.gov URL standards](https://design.va.gov/content-style-guide/url-standards). This PR adds a duplicate entry to the registry with the updated root URL to begin the process of migrating the app to the new URL.
**NOTE:** Once the URL update process is complete, the original entry will be removed.
department-of-veterans-affairs/va.gov-team#31768
- The current URL is `/health-care/apply/application`
- The new URL is `/health-care/apply-for-health-care-form-10-10ez`
- Tested locally to verify the app was successfully rendering with the updated URL (see screenshot)
With current URL: 
With new URL:
-  Health care application successfully renders with updated root URL.
> Add entry for Health Care Application URL update

- src/site/includes/above-footer-elements.drupal.liquid
- src/site/layouts/landing_page.drupal.liquid
Pages that use the `landing_page.drupal.liquid` template have a right sidebar:
<br/><br/>
<br/>
<br/>
The feedback button is at the end of the page content on the left side:
<br/>
<br/>
<br/>
This results in a strange experience on mobile where the feedback button appears between the content for the left side and the right:
<br/>
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/76306
Tested **many** templates (all for regression except `landing_page.drupal.liquid`:
<details>
<summary>Templates</summary>
- (health_care_local_facility) /south-texas-health-care/locations/audie-l-murphy-memorial-veterans-hospital/
- (health_care_region_detail_page) /loma-linda-health-care/work-with-us/internships-and-fellowships/pharmacy-residency/
- (health_care_region_page) …
> VACMS-76306 Adjust feedback button positioning on landing pages

- src/site/facilities/health_service.drupal.liquid
- src/site/includes/health_services_listing_services.liquid
- Updates va-accordion and va-accordion-item to `uswds="true"` for Health Service templates
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16997
- Tested on local build on http://localhost:3002/boston-health-care/health-services/ and http://localhost:3002/minneapolis-health-care/health-services/
- Checked using the extension for VA web components and visual test of opening accordion items
<details>
<summary>former- desktop</summary>
</details>
<details>
<summary>new- desktop</summary>
</details>
<details>
<summary>former- mobile</summary>
</details>
<details>
<summary>new- mobile</summary>
</details>
VAMC Health Service pages
> Health Service template update accordions to v3

- src/site/paragraphs/service_location.drupal.liquid
THIS IS BRANCHED OFF Service Location Paragraph integration branch so tests will not pass
- Makes main number conditional for appointments and contact info in Service Location Paragraphs and always shows optional numbers if they exist for both appointments and contact.
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17511
- tested locally and on Service Location integration site
<details>
<summary>Billing Service Location (new) with multiple contact numbers and Main Number checked</summary>
</details>
<details>
<summary>Clinical Service Location with appointment number and main number Off</summary>
</details>
Updated Service Location Paragraph type …
> VACMS 17511 fix use main facility phone 3rd time is the charm

- src/applications/registry.json
I removed the mhv medical records test app config from the registry. 
This config was for a test app that was the same as the app that exists in the vets-website repo at src/applications/mhv/medical-records. It was copied to src/applications/mhv-medical-records to test isolated app deployments. It is no longer needed. 
https://jira.devops.va.gov/browse/MHV-55413
> ### Isolated Apps - MR - Re-point the application to the new location
> Description
> Isolated Apps - MR - Re-point the application to the new location
The new medical records test app was successfully tested on staging and can now be replaced with the real app. 
No UI changes.
MHV Medical records new test app
MHV Medical records new test app has been removed from registry.json now that testing is complete.
> MHV-55413: Removed mhv mr test app config

- src/site/includes/lovell-switch-link.drupal.liquid
This updates the alerts on the Lovell pages from v1 to v3.
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17108
Visual, below
Lovell
> [VA-17108] Update Lovell components to V3

- src/applications/registry.json
Turns on the feedback button for the check-in teams applications. This includes pre-check-in, day-of check-in, and travel-claim.
department-of-veterans-affairs/va.gov-team#79934
n/a
n/a
pre-check-in, day-of check-in, and travel-claim applications.
> Turn feedback button on for check-in applications.

- src/site/layouts/va_form.drupal.liquid
On the "About ___ Form" pages, there is an optional section called "When to use this form." If that section does not exist, the next header is "Downloadable PDF," but it should be an `<h2>` when the "When to use this form" section does not exist. This fixes the header hierarchy.
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14652
Tested these pages locally:
<details><summary>/find-forms/about-form-10-10cg/</summary>
</details>
<details><summary>/find-forms/about-form-21-4142/</summary>
</details>
<details><summary>/find-forms/about-form-10-10sh/</summary>
</details>
<details><summary>/find-forms/about-form-10-0491j/</summary>
</details>
> VACMS-14652 About Form header fix

- src/site/includes/support_resources_cta_list.drupal.liquid
- src/site/layouts/basic_landing_page.drupal.liquid
- src/site/layouts/checklist.drupal.liquid
- src/site/layouts/faq_multiple_q_a.drupal.liquid
- src/site/layouts/media_list_images.drupal.liquid
- src/site/layouts/media_list_videos.drupal.liquid
- src/site/layouts/q_a.drupal.liquid
- src/site/layouts/step_by_step.drupal.liquid
- src/site/layouts/support_resources_detail_page.drupal.liquid
- src/site/paragraphs/alert_single.drupal.liquid
On Resources & Support pages that only have one CTA, we should not be using a list element to display them. This fixes that (on the top of the page and at the bottom where they can be repeated).
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17094
<details><summary>/resources/deciding-how-much-life-insurance-to-get/</summary>
</details>
<details><summary>/resources/va-covid-19-debt-relief-options-for-veterans-and-dependents/</summary>
</details>
<details><summary>/resources/how-to-check-your-va-claim-appeal-or-decision-review-status-online/</summary>
</details>
<details><summary>/resources/commissary-and-exchange-privileges-for-veterans/</summary>
</details>
<details><summary>/resources/can-i-get-free-health-care-and-prescriptions-as-a-veteran/</summary>
</details>
> VACMS-17094 Resources & Support CTA fix

- src/site/includes/veteran-banner.html
- src/site/layouts/home.html
The `shifted-vets-banner` (in vets-website) was used on the previous homepage design:
Our current Veteran banner at the bottom of the page is built in content-build and does not use `shifted-vets-banner`.
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15312
Tugboat for testing the changes to vets-website and content-build: ([content-build PR here](https://github.com/department-of-veterans-affairs/content-build/pull/2029))
https://web-qt5d33etm65pqwd8kjkoisn1yauzdt4d.demo.cms.va.gov/
Tested desktop locally (this banner does not appear on mobile).
Home page only. Though nothing should really be affected since we're removing code that isn't used.
> VACMS-15312 Remove shifted-vets-banner references

- src/applications/registry.json
- Removes the useLocalStylesAndComponents key from the pre check in app
- [department-of-veterans-affairs/va.gov-team#72870](https://github.com/department-of-veterans-affairs/va.gov-team/issues/72870)
Locally Pre check in imports css and components properly
Check-in -> Pre Check-in
> remove useLocalStylesAndComponents

- src/site/includes/vba_facilities/service_location.liquid
- src/site/includes/vba_facilities/services.liquid
- src/site/paragraphs/service_location.drupal.liquid
The VBA "Schedule an Appointment Online" link goes to the VAMC scheduling link. This fixes it by pointing it to VERA.
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17710
Local, see below screenshot
VBA Services
> [VA-17710] Update VBA "Schedule An Appointment Online" link

- src/site/layouts/tests/vet_center/vet_center_locations_operating_status.unit.spec.js
- Fixes random failing Vet Center test
- Run Vet Center Operating Status tests multiple times and it will occasionally fail.
- Modify tests to change expected values in each run for the centralized fixture JSON.
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17994
- Test would fail when 4th test ran before 3rd
- Test that tests run in multiple orderings.
N/A
Testing of Vet Center Operating Status
Check that tests run in any order
> Vet Center test fix

- src/applications/registry.json
Summary
This PR adds 7959f-2 to registry.json so we can build the form out.
Related issue(s)
Testing done
Manual testing
Screenshots
What areas of the site does it impact?
This form only
Acceptance criteria
Quality Assurance & Testing
I fixed|updated|added unit tests and integration tests for each feature (if applicable).
No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs
Linting warnings have been addressed
Documentation has been updated ([link to documentation](https://github.com/department-of-veterans-affairs/content-build/pull/2037#) *if necessary)
Screenshot of the developed feature is added
[Accessibility testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-te …
> 10-7959f-2 Registry

- package.json
- yarn.lock
Updates packages that rely on @babel/core. 
Resolves https://github.com/department-of-veterans-affairs/content-build/security/dependabot/83
> Resolve critical alerts due to babel/traverse.

- src/site/layouts/vamc_operating_status_and_alerts.drupal.liquid
Add web components where possible to VAMC operating status pages.
For some reason, this page also had a duplicated `<ul>` for "On this page" content after the `<va-on-this-page>`. I removed the plain `<ul>` and we are just using the web component for "On this page" now.
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16998
Tested most things locally on `/boston-health-care/operating-status/` and `/minneapolis-health-care/operating-status/`. Though it is difficult to try to find VAMCs where facilities are currently not operating or in some sort of alert mode. The slim alert banners and the emergency status notifications (subscription) have been forced to show up in the screenshots below.
Note: I had to force this to show up locally, I'm not aware of a page that …
> VACMS-16998 Operating status web components

- src/site/layouts/vamc_operating_status_and_alerts.drupal.liquid
Facility names must be encoded in the templates as they can sometimes contain special characters (particularly double quotes).
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16998
Tested at `/miami-health-care/operating-status/`
Facilities Operating Status pages
> VACMS-16998 Fix operating status double quotes

- src/site/layouts/vamc_system_medical_records_offi.drupal.liquid
- Adds back-to-top va web component to the vamc medical records template
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16960
- ran local test suite
VAMC medical records pages
> add back-to-top to med records template

- src/applications/registry.json
The Health Enrollment team recently completed an update to the root URL for the 10-10EZ (Application for Health Benefits). In order to complete that update without any downtime, a duplicate registration needed to be added with the new root URL. This PR removes the original registration record for the `hca` app.
department-of-veterans-affairs/va.gov-team#31768
- Registry is free of duplicate app entries for the Health Care Application
> Remove duplicate registration of Health Care Application

- src/site/includes/vba_facilities/spotlight_content.liquid
- updates spotlight components to use VR cards in vba template
- updates classes to match desired styling
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17095
- local testing
-test suites
Set up and confirm local build works
- Run yarn build --pull-drupal --drupal-address=https://cms-txcrk8bym4a0ivw3xfr8xvdhezmls36f.demo.cms.va.gov/ username=max.antonucci@agile6.com password=drupal8 to build site with needed data. Confirm the build is successful.
- Run yarn serve to view site locally.
- Confirm VBA Facility page is active by visiting http://localhost:3002/cleveland-va-regional-benefit-office/ …
> 17095 spotlight converted to card

- src/site/layouts/vamc_system_billing_insurance.drupal.liquid
- Adds va-back-to-top to Billing and Insurance top-task page
- https://app.zenhub.com/workspaces/sitewide-facilities-639f5253e4b702a32376339e/issues/gh/department-of-veterans-affairs/va.gov-cms/16962
- Manual check that DS component appears. Tested that component brings user back to top content on page in mobile and desktop.
<details>
<summary>Desktop page</summary>
</details>
<details>
<summary>Mobile page</summary>
</details>
Billing and Insurance VAMC top-task pages
See that component appears either in images or on RI
> VACMS 16962 Adds back to top to Billing and Insurance pages

- src/site/includes/vba_facilities/services.liquid
The "Manage Your Benefits Online" link for each VBA service is added if they have the "online self-service" field is filled out. Most of the code was already there, but it needed some tweaking to get it correct.
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17598
Visual, see below
https://github.com/department-of-veterans-affairs/content-build/assets/10790736/b90151d1-d1e5-4bd6-92cf-101569f4c371
* [Link to Tugboat CMS where services were updated.](https://cms-txcrk8bym4a0ivw3xfr8xvdhezmls36f.demo.cms.va.gov/admin/structure/taxonomy/manage/health_care_service_taxonomy/overview?page=1)
* [Link to regional facility page where services are shown.](https://web-txcrk8bym4a0ivw3xfr8xvdhezmls36f.demo.cms.va.gov/cleveland-va-region …
> [VA-17598] Show VBA "Manage Your Benefits Online" (2)

- src/site/layouts/va_form.drupal.liquid
Update the `<i>` elements in the content-build portion of the Find Forms app to `<va-icon>`. This is only for the form detail pages. vets-website handles the search / search results portion of this app.
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17815
Tested locally at `/find-forms/about-form-10-10m/`. The content-build portion of this application is the Form detail pages only.
> 17815 find forms icons

- .github/workflows/daily-production-release.yml
- Changes the crontab value to run 4 hours earlier in the day
- In response to [other deployments announced](https://dsva.slack.com/archives/C03R5SBELQM/p1713293704245769) to be running earlier in the day
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18061
> Run the Daily Production Release at 11AM EDT

- src/site/includes/vba_facilities/spotlight_content.liquid
- Fixes an issue with vba facility spotlight cards not having proper margins.  
- Testable at `/cleveland-va-regional-benefit-office/`
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17095
- local visual testing
> card margin issue fixed

- src/applications/registry.json
This PR updates the root url of form app 10-7959c per guidance from our product team.
- Updated URL in registry
- Flipper: NA
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/82026
- https://github.com/department-of-veterans-affairs/vets-website/pull/29759
- Manual
Form app 10-7959c only
NA
> Update root url of form 10-7959c

- src/applications/registry.json
- src/site/layouts/va_form.drupal.liquid
- src/site/stages/build/drupal/graphql/vaFormPage.graphql.js
This PR adds a form upload widget entrypoint to the find a form detail page and a form upload flow application to the registry.
https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team-forms/1242
I've run and tested this locally.
Unauthenticated:
Authenticated:
**Note:** The `vets-website` changes are not yet in effect.
> Add form upload flow

- src/site/assets/sass/style.scss
- src/site/filters/liquid.js
- src/site/filters/liquid.unit.spec.js
- src/site/layouts/landing_page.drupal.liquid
Update all Benefit Hub landing page icons to use `<va-icon>`.
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17816
Tested all benefit hubs locally across breakpoints:
```
/health-care
/disability
/education
/careers-employment
/pension
/housing-assistance
/life-insurance
/burials-memorials
/records
/service-member-benefits
/family-member-benefits
```
</details>
> VACMS-17816 Benefit Hub landing page icon updates

- src/site/components/browse-by-audience.drupal.liquid
- src/site/layouts/media_list_images.drupal.liquid
- src/site/paragraphs/lists_of_links.drupal.liquid
Update Resources & Support icons on the content-build side to `va-icon`.
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17817
Tested locally.
In order to test the `media_list_images` template, you need to run `yarn preview` locally and go to `localhost:3002/?preview?nodeId=6954`. There is no production content for this template, but it only exists on the R&S page and we do have some content in lower environments.
The icon in the `list_of_links` template was left behind when we converted the `Go to all articles` links to active va-links. The icon wasn't showing up visually, but it is in the DOM in prod. See screenshots in the below section. This can be tested at `/resources`.
The `browse_by_audience` template isn't used in prod, but when it is implemented, it looks …
> VACMS-17817 Resources & Support va-icon cleanup

- src/site/includes/social-share.drupal.liquid
- src/site/layouts/event.drupal.liquid
relates to https://github.com/department-of-veterans-affairs/vets-website/pull/29769
- Updates events recurring event icon to va-icon
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17822
- local visual
> event icon updated

- src/site/assets/sass/style.scss
- src/site/layouts/campaign_landing_page.drupal.liquid
- src/site/layouts/landing_page.drupal.liquid
Update all the icons on Campaign Landing pages to use `<va-icon>`.
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17821
Tested locally these CLPs:
- `/initiatives/vote/`
- `/initiatives/veterans-experience-action-centers/`
- `/initiatives/protecting-veterans-from-fraud/`
- `/initiatives/veteran-trust-in-va/`
- `/initiatives/covid-flu/`
- `/initiatives/end-of-life-benefits/`
- `/initiatives/sign-in-securely-with-logingov/`
- `/initiatives/emergency-room-911-or-urgent-care/`
> VACMS-17821 Campaign Landing Pages va-icon update

- src/site/components/fullwidth_banner_alerts.drupal.liquid
- src/site/layouts/health_care_region_page.drupal.liquid
- src/site/teasers/news_story.drupal.liquid
Add v1 and v3 web components to VAMC system pages where possible. Converts the "See all (locations/stories/events)" buttons to active links.
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16952
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15598
Tested locally on `/boston-health-care` and `/minneapolis-health-care`.
<details><summary>See all (locations/stories/events) to active link</summary>
</details>
<details><summary>"Manage your health online" icons</summary>
</details>
<details><summary>Full width banners</summary>
</details>
<details><summary>Back to top</summary>
</details>
<details><summary>Related links</summary>
</details>
> VACMS-16952 VAMC System pages web components

- src/site/assets/sass/style.scss
- src/site/blocks/alert.drupal.liquid
- src/site/facilities/health_care_region_detail_content.drupal.liquid
- src/site/layouts/health_care_region_detail_page.drupal.liquid
- src/site/paragraphs/downloadable_file.drupal.liquid
- src/site/paragraphs/process.drupal.liquid
Use web components on VAMC detail pages where possible.
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16999
Tested locally at these routes:
- /boston-health-care/make-an-appointment/
- /boston-health-care/contact-us/
- /boston-health-care/about-us/
- /boston-health-care/work-with-us/
- /minneapolis-health-care/make-an-appointment/
- /minneapolis-health-care/contact-us/
- /minneapolis-health-care/about-us/
- /minneapolis-health-care/work-with-us/
Also tested a page [**via Tugboat**](https://web-v9l0sy4euftr8m5pebq4pxezfbvbxcnz.demo.cms.va.gov/western-colorado-health-care/about-us/important-useful-information/) for the process list web component.
<details><summary>Additional info inside alert component</summary>
</details>
<details><summary>Back to top …
> VACMS-16999 VAMC Detail page web components

- src/site/layouts/landing_page.drupal.liquid
Fix syntax issue with social media links on Benefit Hub landing pages.
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18265
Tested locally at several benefit hubs:
- `/health-care`
- `/disability`
- `/education`
> VACMS-18265 Fix social links on Benefit Hub landing pages

- src/applications/registry.json
- Makes our feature (BTSSS Travel Claim Status Page) URL consistent with other MHV pages
- BTSSS Travel Pay VA.gov Migration
- department-of-veterans-affairs/va.gov-team#81927
- Previously: Navigate to https://<FE_ENV_URL>/health-care/file-travel-claim
- Now: Navigate to https://<FE_ENV_URL>/my-heath/travel-claim-status
> Changed root url per department-of-veterans-affairs/va.gov-team#81927

- src/site/facilities/vba_social_links.drupal.liquid
Update social media icons on pre-prod VBA pages to use va-icon.
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17886
Tested icons and links locally.
Using `yarn preview`:
`http://localhost:3002/preview?nodeId=4171` 
This is /albuquerque-va-regional-benefit-office [in CMS](https://staging.cms.va.gov/node/4171/edit)
[Here's the Tugboat URL](https://web-uogdy7lphgtldsuoaduvsz3rqjpp6mms.demo.cms.va.gov/honolulu-va-regional-benefit-office-at-spark-m-matsunaga-department-of-veterans-affairs-medical-center/) you can use to test this with pre-prod data.
> VACMS-17886 VBA Office social media icons update

- src/site/includes/education-sco.html
- src/site/layouts/home.html
- Removing no-longer-needed hub-icons from legacy template files
- Relates to [#2879](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2879)
- None
N/A
Affects two legacy files, removing code that was no longer being utilized.
> 2879 - Removing no-longer-needed hub-icons from legacy template files

- src/site/layouts/va_form.drupal.liquid
Update find forms page to use va-link instead of `<a/>`. Also by doing this we will default to use the built in GA and remove custom GA from all initial implementations. 
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18202
Tested in review instance with url `/find-forms/?q=526ez`
<details>
<summary>Change your direct deposit information</summary>
</details>
<details>
<summary>Change your address in your VA gov profile</summary>
</details>
<details>
<summary>Get your VA records and documents online</summary>
</details>
<details>
<summary>Request your military records, including DD214</summary>
</details>
<details>
<summary>File a VA disability claim</summary>
</details>
VA find forms page
> VACMS-18202: Update to remove custom ga for va-link

- src/site/stages/build/drupal/graphql/bannerAlerts.graphql.js
- src/site/stages/build/drupal/graphql/banners.graphql.js
- src/site/stages/build/drupal/graphql/entityElementsForPages.graphql.js
- src/site/stages/build/drupal/graphql/facilities-fragments/healthCareRegionNewsStories.node.graphql.js
- src/site/stages/build/drupal/graphql/file-fragments/outreachAssets.graphql.js
- src/site/stages/build/drupal/graphql/nodeEvent.graphql.js
- src/site/stages/build/drupal/graphql/promoBanners.graphql.js
- src/site/stages/build/drupal/graphql/vamcPoliciesPage.graphql.js
- src/site/stages/build/drupal/graphql/vetCenter.graphql.js
- src/site/stages/build/drupal/graphql/vetCenterLocations.graphql.js
- Adds the fieldLastSavedByAnEditor to Drupal entity pages queries to allow this date to make its way to the sitemap. The corresponding change to incorporate this field into the sitemap has already been made, this PR just adds the field to existing GraphQL queries that reflect nodes with this field present.
Relates to: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16333
- Tested that new sitemap reflects the field_last_saved_by_an_editor value for a sampling of nodes 
Sitemap
GraphQL queries for Drupal detail pages
**All testing to be perfomred on [this Tugboat](https://tugboat.vfs.va.gov/6661edf417e38363d3d17ac5), not the RI on this PR.**
Nodes Last Changed By A Script:
| Type | Node ID | Changed | Editor Last Changed |
|--------|--------|--------|--------|
| Event …
> VACMS-18065: Adds fieldLastSavedByAnEditor to entities for sitemap.

- src/site/includes/operation_status_information.liquid
- src/site/layouts/health_care_facility_status.drupal.liquid
- src/site/paragraphs/staff_profile.drupal.liquid
- Removes fontawesome and replaces with va-icon
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18326
- Checked manually. Forced display of some of the features locally to expose (could not find example of staff_profile without a photo)
- Check manually on tugboat (will try to create a staff profile with no image)
<details>
<summary>Staff Profile without images with PR</summary>
</details>
<details>
<summary>Staff Profiles past - fontawesome</summary>
</details>
<details>
<summary>(outdated should be removed)Operation Status page - old</summary>
</details>
<details>
<summary>(outdated should be removed)Operation Status page - with PR (follows pattern from operating status page)</summary>
</details>
*(Describe what parts of the site are impacted …
> VACMS 18326 content-build fontawesome removal

- src/site/layouts/campaign_landing_page.drupal.liquid
The va-link component has been enhanced to provide destination and can be used now for applicable Campaign Landing Page features, along with removal of the GA custom events.
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18186
Testing done in review instance at urls listed below
/initiatives/covid-flu
/initiatives/vote/
/initiatives/protecting-veterans-from-fraud/
/initiatives/protecting-veterans-from-fraud/
(What you can do) "Learn how to get your flu shot"
(Spotlight) "Why is VA helping Veterans to vote?"
(Stories) "Staying safe when considering employment with a foreign organization" 
(VA Benefits) "VA health Benefits" 
CLP Pages
> VACMS-18186: CLP GA update to remove custom analytics from va-links

- .github/workflows/content-release.yml
- increases the timeout of the build step. This has been hitting its timeout limit recently.
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18362
There is no testing to do; it raises the limit.
> VACMS-18362: raise content-release build step time to 50m.

- src/site/assets/sass/style.scss
- src/site/includes/education-sco.html
- src/site/layouts/landing_page.drupal.liquid
A pull request to remove an old iconography stylesheet was merged into vets-website on June 18. Pull request here: https://github.com/department-of-veterans-affairs/vets-website/pull/30301/files#diff-6edcebe654b6b37d8ce2d75bc03d32652f25c62de02dc452bac87e63604dd8ac
As we've seen in many cases, content-build uses styles from vets-website that are otherwise unused in vets-website (likely some tech debt leftover from when content-build and vets-website were a single repo). This caused an oversight when removing that stylesheet and created the style regression seen on Benefit Hub landing pages:
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18364
Tested all benefit hub pages locally:
- localhost:3002/health-care
- localhost:3002/disability
- localhost:3002/education
- …
> VACMS-18364 Fix style issue with icons on Benefit Hub landing pages

- src/site/filters/liquid.js
- src/site/includes/vba_facilities/spotlight_content.liquid
- src/site/layouts/vba_facility.drupal.liquid
- The shimming of the Centralized Content and non-fetched VBA was not resolving correctly. Made conditional for both types to be displayed (one may come with a path nested key in the `url` and one may not.
- Any CTA was not displaying on VBA.
- Modified the liquid filter to make sure at least one or the other appears if the `url` is present and added a conditional to test and fallback if it isn't.
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18235
- Checked that tests covered conditions
- Manually tested VBAs and Vet Centers which both use the spotlight processing
- Checked that links work for regular links and node links
<details>
<summary>VBA …
> Vacms 18235 cta not showing

- src/applications/registry.json
- Remove old mock alternate header form
department-of-veterans-affairs/va.gov-team-forms#1382
vets-website removal: https://github.com/department-of-veterans-affairs/vets-website/pull/30426
> remove old mock alternate header form

- src/site/components/hub-page-link-list.html
- src/site/components/navigation-sidebar.html
- src/site/includes/common-and-popular.html
- src/site/includes/directions-google-maps.liquid
- src/site/layouts/campaign_landing_page.drupal.liquid
- src/site/layouts/home.html
- src/site/layouts/va_form.drupal.liquid
Per Design System guidance, links should only open in a new tab if the user will lose some data or progress. This PR includes updates to:
**Find Forms**
- Removes `target` and `rel` attributes from download links
- Removes new tab from GSA Forms Library link as the user will not lose data from an empty search results page
**Hub pages sidebar**
- Removes target behavior on sidebar links. There's no way to set this data in Drupal (as these are statically-generated sidebars), so this property wouldn't be used.
**Old homepage**
- Removes target behavior from `common-and-popular.html`, which is a file used on the old homepage (before the launch of the redesign in June 2023).
**Campaign Landing Page**
- Removes new tab from "See more stories" link in the stories section (no prod examples)
- …
> VACMS-18287 Remove new tab behavior per DST guidelines

- src/site/layouts/va_form.drupal.liquid
With the release of the action link support from DST we want to update our action links to use the new component.
This PR changes the action-link for the find forms go to the online tool <a>
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18346
Tested locally at ` /find-forms/about-form-21-526ez/`
Find Forms
> VACMS-18346: Update go to the online tool link in VA Froms

- src/site/layouts/campaign_landing_page.drupal.liquid
Removes custom Google Analytics events from Campaign Landing pages links wherever we can convert to a `va-link` or `va-link-action` (and inherit the baked-in analytics from the web component).
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18345
Tested locally across several CLPs:
- `/initiatives/veterans-experience-action-centers/`
- `/initiatives/covid-flu/`
- `/initiatives/emergency-room-911-or-urgent-care/`
- `/initiatives/sign-in-securely-with-logingov/`
- `/initiatives/protecting-veterans-from-fraud/ `
We didn't have any prod examples of events on CLP pages, so I added a couple for this CLP on Tugboat: https://web-pwutmkwvjamnjxaxwctdwffyc9ynclqr.demo.cms.va.gov/initiatives/emergency-room-911-or-urgent-care/ …
> 18345 Campaign Landing Pages: remove custom GA events where possible

- src/site/filters/liquid.js
- src/site/filters/liquid.unit.spec.js
- src/site/includes/vba_facilities/services.liquid
- src/site/layouts/vba_facility.drupal.liquid
VBA services needed to be alphabetized. We couldn't follow the simple pattern of adding the liquid sortObjectBy utility because the data objects for services are of two different flavors. One has a key `facilityService` and the other has a key of `regionalService`. sortObjectBy requires a consistent key to be passed in, so I made a utility function specifically for this "dynamic keys" purpose.
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18213
Published these two VBA facilities and their services in a Tugboat and tested locally:
- https://web-pwutmkwvjamnjxaxwctdwffyc9ynclqr.demo.cms.va.gov/national-capital-region-va-regional-benefit-office/
- https://web-pwutmkwvjamnjxaxwctdwffyc9ynclqr.demo.cms.va.gov/honolulu-va-regional-benefit-office-at-spark-m-matsunaga-depar …
> VACMS-18213 Alphabetize VBA services

- src/applications/registry.json
- The update to the registry.json for renaming the EZR breadcrumb affects all EZR pages using breadcrumbs and potentially other site areas depending on the file's dependencies.
- _Link to ticket created in [va.gov-team repo_
department-of-veterans-affairs/va.gov-team#0000](https://app.zenhub.com/workspaces/10-10-health-apps-5fff0cfd1462b6000e320fc7/issues/gh/department-of-veterans-affairs/va.gov-team/84964)
| ------- | -------- | -------- |
| Desktop |    ![image](https://github.com/department-of-veterans-affairs/content-build/assets/131277002/e431c9ae-2eb7-4d6b-a2df-a28f2361e89a)    |   ![image](https://github.com/department-of-veterans-affairs/content-build/assets/131277002/a0bfab21-723e-47b9-8415-8f09b244aa66)   |
The update to the registry.json in the …
> Updated EZR My Health breadcrumb

- src/applications/registry.json
This app was moved to `health-care-supply-reordering` some time ago and needs to be cleaned up. 
All requests for the old path are redirected, see: 
https://vagov.ddog-gov.com/logs?query=order-form-2346%20service%3Aelb&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=desc&viz=stream&from_ts=1718732940319&to_ts=1720028940319&live=true
> Remove old supply reordering entry

- src/site/paragraphs/service_location.drupal.liquid
- Italics is not approved styling. Changed text to normal styling for additional office hours info.
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17686
- No tests cover italics. No tests added since it doesn't change conditional logic.
<details>
<summary>Prior additional info</summary>
</details>
<details>
<summary>PR additional info</summary>
</details>
Service Location paragraphs (VAMC and VBA)
Check on tugboat on https://web-codylbelkq0gdivw6x7tykigmeqloewe.demo.cms.va.gov/philadelphia-va-regional-benefit-office/
See Disability Compensation service with hours
> VACMS 17686 - regular text for additional office hours info

- src/site/assets/sass/style.scss
- src/site/navigation/sidebar_nav.drupal.liquid
It was discovered that the close icon in the sidenav mobile menu wasn't rendering correctly. This PR fixes that by using va-icon and a custom css class specifically inside content-build
Bug ticket - https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2991
<details><summary>va-icon correctly rendering</summary>
</details>
<details><summary>screen capture</summary>
[Screencast from 07-05-2024 10:28:00 AM.webm](https://github.com/department-of-veterans-affairs/content-build/assets/15097156/72dbfb4a-8eb0-45fc-a0c1-0a3060651cee)
</details>
>  Mc sidenav icon fix

- src/applications/registry.json
The Health Enrollment team recently completed an update to the root URL for the 10-10CG (Application for Caregiver Benefits). In order to complete that update without any downtime, a duplicate registration needed to be added with the new root URL. This PR removes the original registration record for the `caregivers` app.
department-of-veterans-affairs/va.gov-team#81588
- Registry is free of duplicate app entries for the Caregiver Benefits Application
> Remove duplicate registry entry for caregiver application

- src/site/includes/benefit-hubs-links.drupal.liquid
- src/site/includes/related-information.drupal.liquid
This PR changes Resources & Support Detail Page va-links to use built in analytics since va-link can now support link destination
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18417
Tested that ga events are being captured locally and markup is va-link.
`/resources/can-i-get-a-replacement-gi-bill-benefit-certificate-of-eligibility/`
`/resources/can-i-plan-ahead-for-my-burial-in-a-va-national-cemetery/`
VA Benefits hub link 
Related information links
> VACMS-18417: Update links for Resources & Support Detail Page to use ga built in analytics

- src/site/layouts/va_form.drupal.liquid
This PR adds a `<div>` with some text to the find a form page if the form has the Form Upload flow enabled.
https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team/86813
Before:
After:
> Add text on find-form page for form upload flow

- src/site/navigation/facility_no_drupal_page_sidebar_nav.drupal.liquid
Accessibility fixes:
1. Add an `aria-label="Secondary"` label to the `<nav>` element on Staff Profile sidebars to differentiate it from other navigations on the same page.
2. Conditionally render the `<ul>` element in the `<nav>`, only if deep links exist
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16062
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16063
Tested locally at `/salem-health-care/staff-profiles/allen-r-moye/`:
1. Visit the above page and inspect the sidebar navigation
2. Verify the `<nav>` element has `aria-label="Secondary"`
3. Verify the `<nav>` element does not have an empty `<ul>` inside it
4. Use Mac Voiceover or another screen reader to validate that the aria label is read aloud when getting to this element and no empty …
> VACMS-16062, 16063 Accessibility fixes for VAMC Staff Profile pages

- src/site/paragraphs/service_location.drupal.liquid
Hours on VBA service accordions were not showing up. We were also missing complete contact information. One of the services had two email addresses added, and only one of them appeared. This pointed me to a syntax issue with the `<va-link>` being used for email that allowed the template to fail silently and not complete rendering the rest of the code.
This fixes the syntax error and renders the missing contact information and the hours (and any other information that would come after the contact information in this template).
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18393
Tested locally with a Tugboat instance:
https://web-cmugn5ieupsmz1cyrrmcwiwcawfidlrx.demo.cms.va.gov/philadelphia-va-regional-benefit-office/
1. Go to …
> VACMS-18393 VBA hours fix

- .github/workflows/content-release.yml
Increases the timeout of the deploy step of content-release.yml to 25m for temporary mitigation of content release issues.
> increase Deploy timeout to 25m.

- src/site/assets/sass/style.scss
- src/site/layouts/health_care_region_page.drupal.liquid
For this PR we are adding 2 new links under the Manage your health care section.
Download VA Health Chat and Connect to VA Care.
Also we changed the header as well to an h2 to fix an a11y defect.
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17436
Tested locally at `/greater-los-angeles-health-care/`
Verified links are working and redirecting to correct address.
VA Health Care system pages
> VACMS-17436: Update links for manage your health care section

- src/site/includes/health_services_listing_services.liquid
- src/site/includes/vet_centers/health_services.liquid
- src/site/layouts/health_care_local_facility.drupal.liquid
- src/site/layouts/vet_center.drupal.liquid
- Adds text below header to identify that a user should select a topic for more information in the form of the statement: "Select a topic to learn more."
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13937
- Manually tested several VAMC and Vet Center locations
<details>
<summary>VAMC Prepare for your visit (desktop) - in PR</summary>
</details>
<details>
<summary>VAMC Prepare for your visit (mobile) - in PR</summary>
</details>
<details>
<summary>VAMC Prepare for your visit (desktop) - current</summary>
</details>
<details>
<summary>VAMC Health Services (desktop) in PR</summary>
</details>
<details>
<summary>VAMC Health Services (mobile) in PR</summary> …
> VACMS 13937 - VAMC and Vet Center Accordions with text to select a subject

- .github/workflows/daily-release-warning.yml
- .github/workflows/gha-metrics.yml
- This adds a new workflow that sends workflow metrics for the Content Release workflow to Datadog upon Content Release completion. 
- Also corrects some problems found with the Daily Release Warning workflow. 
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18715
> VACMS-18715: content release datadog metrics

- src/site/layouts/vba_facility.drupal.liquid
- Remove the Lovell switcher include in template for VBA
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17904
- Checked VBA facility (Portland) post change
- Go to VBA page, there should be no difference visibly or code-wise
No rendered code changes, only liquid changes
VBA Page liquid templates
View template and rendered page. See that rendered page does not change (either on local dev or RI)
E.g. compare
http://3d87d1c04b6d897bac2787eb7bccfe54.review.vetsgov-internal/portland-va-regional-benefit-office/
and 
https://va.gov/portland-va-regional-benefit-office/
> VACMS 17904 - Remove Lovell switcher include in VBA pages

- package.json
- yarn.lock
- _Updating node-sass package to pass some WASA scans on dependency packages_
- _not a bug_
- _Solution is to update node-sass to higher version and the cascading dependencies will fix issue_
- _I work for VACMS_
- _No flippers used_
- Ticket created: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18055
- Related epic: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17647
- _Nothing should change other than WASA scans passing the old failure on scss-tokenizer_
- _Load up site, make sure nothing has changed or is …
> VACMS-18055-updating-scss-tokenizer: Package updates for WASA scan ticket. Upgrading node-sass to 7.0.3.

- src/site/layouts/vamc_operating_status_and_alerts.drupal.liquid
Remove duplicate (custom) Google Analytics event from facility name links under "Facility operating statuses" on the operating statuses page.
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18504
Tested locally at `/tuscaloosa-health-care/operating-status/` using the [Adswerve plugin](https://chromewebstore.google.com/detail/adswerve-datalayer-inspec/kmcbdogdandhihllalknlcjfpdjcleom).
Facility operating status pages
> VACMS-18504 Remove duplicate GA event from facility operating status page

- src/site/layouts/press_release.drupal.liquid
Remove duplicate (custom) Google Analytics event from "See all news releases" link at the bottom of the Press Releases page.
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18505
Tested locally at `/kansas-city-health-care/news-releases/pact-act-awareness-event-at-honor-va-clinic-for-all-veterans-on-march-6/` using the [Adswerve plugin](https://chromewebstore.google.com/detail/adswerve-datalayer-inspec/kmcbdogdandhihllalknlcjfpdjcleom).
Press releases page
> VACMS-18505 Remove duplicate GA event from Press Releases page

- src/site/includes/operatingStatusFlagsLinks.drupal.liquid
This PR removes custom analytics from previously converted va-link components. This will make sure we only capture GA once.
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18518
Tested locally that only events are being recorded once.
VAMC Location Pages
> VACMS-18518: Remove dupe analytics from VAMC location pages

- .github/PULL_REQUEST_TEMPLATE.md
- src/site/includes/common-tasks.drupal.liquid
- src/site/includes/hero.drupal.liquid
- src/site/includes/homepage-benefits.drupal.liquid
- src/site/includes/news-spotlight.drupal.liquid
- src/site/includes/tests/hero/hero.unit.spec.js
Removed custom analytics from most of the home page's elements.
- Hero banner: "Learn what the PACT Act means for you" link
- Hero banner: "Learn how an account helps you" link
- Hero banner: "Create account" button
- Hero banner fallback: "Learn how an account helps you" link
- Hero banner fallback: "Create an account" button
- Other search tools links
- Top pages links
- News: "VA's mission to better serve all" link
- News: "Read the full article" link
- News: "More VA news" link
- Hub links
Also removed the Teamsites section of the PR template since we don't need to worry about this from a content-build perspective anymore.
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18416
Tested the homepage locally using the [Adswerve …
> VACMS-18416 Homepage custom analytics removal

- src/site/components/merger-social-sco.html
Remove custom GA events from social media links on the right rail of the Resources for Schools page (`/school-administrators`).
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18522
Tested locally at http://localhost:3002/school-administrators/.
`/school-administrators` only. This markdown file is used to build this page: https://github.com/department-of-veterans-affairs/vagov-content/blob/main/pages/school-administrators.md?plain=1 and `merger-social-sco.html` is part of the parent template (`education-sco.html`).
> VACMS-18522 Education social right rail custom events removal

- src/site/includes/directions-google-maps.liquid
- src/site/layouts/event.drupal.liquid
This PR updates the events detail page to remove duplicative ga events and change the directions for google maps links.
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18512
Tested locally `/durham-health-care/events/69410/`
Event Detail Page
> VACMS-18512: Update va-link for event details page to remove duplicate events

- src/site/includes/decision-reviews-rum.html
- src/site/layouts/landing_page.drupal.liquid
- src/site/layouts/page.drupal.liquid
- src/site/layouts/step_by_step.drupal.liquid
- src/site/layouts/support_resources_detail_page.drupal.liquid
- src/site/stages/build/drupal/page.js
> We want to add DataDog Real User Monitoring session to this list of static pages (in impact section). This PR updates the liquid template for each template and adds a new includes file which initializes RUM sessions on the page. This PR will be initially opened in draft mode to allow updates to the variable & add feature toggles. The RUM initialization code is also incomplete, and will be provided once we get data on traffic and percentage of sessions to record.
- _(If using a flipper, what is the end date of the flipper being …
> Add DataDog RUM init to decision review templates

- src/site/components/banners.drupal.liquid
Remove duplicate Google Analytics event on the `<va-promo-banner>` in content-build. There are no prod (or lower environment) examples for this that I could find, so I put one on a Tugboat for testing.
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18783
Tested on this Tugboat: https://web-w4azz2khpzdi53uymp1gxkpi0fbqdlqu.demo.cms.va.gov/ on the homepage. There's a promo banner at the bottom of the screen.
> VACMS-18783 Promo Banner duplicate event removal

- src/site/layouts/health_services_listing.drupal.liquid
- src/site/layouts/vba_facility.drupal.liquid
- src/site/layouts/vet_center.drupal.liquid
- In the spotlight used to have the name of the facility following it in the h2. It no longer does on VBA, Vet Center, and VAMC Listing pages
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18729
- Manually tested several facilities of each type (VBA, VAMC Listing, and Vet Center)
- Checked that each only showed "In the spotlight" and that the jumplinks were the same (generated by h2 content so they must be).
<details>
<summary>VBA old</summary>
</details>
<details>
<summary>VBA new</summary>
</details>
<details>
<summary>VAMC Listing old</summary>
</details>
<details>
<summary>VAMC Listing new</summary>
</details>
<details>
<summary>Vet Center old</summary>
</details>
<details>
<summary>Vet Center new</summary>
</details>
Vet Centers, VAMC Listing …
> VACMS 18729 - In the spotlight without facility name

- src/site/includes/directions-google-maps.liquid
This PR adjusts changed made to the get directions on google maps link that will only show an aria-label for locations with a title.
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18822
Tested locally
```
/minneapolis-health-care/events/69858/
/minneapolis-health-care/events/69316/
```
Event with title
Event without location title
Event Details
> VACMS-18822: Make label conditional for Google Directions 

- src/site/stages/build/drupal/static-data-files/config.js
- src/site/stages/build/drupal/static-data-files/config.unit.spec.js
- src/site/stages/build/drupal/static-data-files/digitalForm/fragments/digitalForm.graphql.js
- src/site/stages/build/drupal/static-data-files/digitalForm/fragments/digitalForm.graphql.unit.spec.js
- src/site/stages/build/drupal/static-data-files/digitalForm/fragments/nameAndDateOfBirth.graphql.js
- src/site/stages/build/drupal/static-data-files/digitalForm/fragments/nameAndDateOfBirth.graphql.unit.spec.js
- src/site/stages/build/drupal/static-data-files/digitalForm/index.js
- src/site/stages/build/drupal/static-data-files/digitalForm/index.unit.spec.js
- src/site/stages/build/drupal/static-data-files/digitalForm/postProcessDigitalForm.js
- src/site/stages/build/drupal/static-data-files/digitalForm/postProcessDigitalForm.unit.spec.js
Creates the `data/cms/digital-forms.json` endpoint to statically generate all published Digital Forms in Drupal.
- department-of-veterans-affairs/va.gov-team#87714
- Created unit tests for the `static-data-files` config, the `digitalForm` query object, its query fragments, and the new post processor.
- Tested the new data file type against a PR CMS environment and successfully pulled down published Digital Forms.
None at the moment as the Digital Forms frontend is not currently live in the production environment.
Normalization of the Drupal data will come in department-of-veterans-affairs/va.gov-team#88634
> VATEAM-87714: Add KISS configuration for Digital Forms

- .github/workflows/continuous-integration.yml
This points Content Build Continuous Integration GovDelivery tests at the same domain that is used for content-build. 
Handles https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18875
- ~CI should run to completion without error being reported from the GovDelivery callback.~
- ~CI may need to be explicitly run against this branch in order for this test to work correctly; check the workflow file attached to the PR CI run.~
This cannot be run unless it is merged to main. 
This is ultimately preventing Content Build code changes from being used in production in some cases.
> Point govdelivery tests at the same domain as content-build tests.

- src/site/stages/build/drupal/static-data-files/digitalForm/index.unit.spec.js
- src/site/stages/build/drupal/static-data-files/digitalForm/postProcessDigitalForm.js
- src/site/stages/build/drupal/static-data-files/digitalForm/postProcessDigitalForm.unit.spec.js
Normalizes how a Digital Form object looks for post-processing.
```
{
"data": {
"nodeQuery": {
"entities": [
{
"nid": 71159,
"entityLabel": "Form with One Step",
"fieldVaFormNumber": "1111111",
"fieldOmbNumber": "1111-1111",
"fieldChapters": [
{
"entity": {
"entityId": "158252",
"type": {
"entity": {
"entityId": "digital_form_name_and_date_of_bi",
"entityLabel": "Name and Date of Birth"
}
},
"fieldTitle": "The Only Step",
"fieldIncludeDateOfBirth": true
}
}
]
},
{
"nid": 71160,
"entityLabel": "Form with Two Steps",
"fieldVaFormNumber": "2121212",
"fieldOmbNumber": "1212-1212",
"fieldChapters": [
{
"entity": {
"entityId": "158253",
"type": {
"entity": {
"entityId": "digital_form_name_and_date_of_bi",
"entityLabel": "Name and Date of Birth"
}
},
"fieldTitle": "First Step", …
```
> VATEAM-88634: Create a normalization layer for Digital Forms

- src/site/includes/vba_facilities/services.liquid
- src/site/layouts/vba_facility.drupal.liquid
Updates the IDs on `va-accordion-item`s on VBA pages to match the title of the accordion. This enables editors to use a simpler and more reliable deep link (to an accordion item) on a page rather than trying to target a random ID generated for the accordion item.
On prod currently (note random numbers in the IDs):
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17986
1. Go to `/portland-va-regional-benefit-office/`
2. Inspect each accordion item's ID and validate that it is a kebab case version of the title (e.g. an accordion with the title "Disability compensation" should have an ID  of "disability-compensation")
3. Verify that a deep link to an accordion (e.g. `/portland-va-regional-benefit-office/#disability-compensation`) jumps to the accordion with that title at …
> VACMS-17986 VBA accordion IDs fix

- src/site/teasers/event_featured.drupal.liquid
- src/site/teasers/news_story_page_feature.drupal.liquid
- Changed `<a>` tags to `<va-link>` tags and encoded text attributes and removed recordEvent for featured event (unused) and news story (unused)
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18497
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18500
- Used anchor tags with recordEvents
- Unable to manually test, due to lack of usage
- We don't include these partial templates anywhere
Doesn't impact an existing area of the site, affects featured event and featured news story but not the teasers on VAMC region pages, those are updated already.
Check code. Unable to display partial templates due to lack of usage, but potential usage in the future (teasers for featured events and news)
> VACMS 18497 and 18500 - changed to va-link components, encoded text, and removed recordEvents

- src/site/facilities/facility_health_service.drupal.liquid
- src/site/facilities/health_service.drupal.liquid
- Removes span with italics font style on common conditions
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17954
- Old behavior was italics text for the words "Common conditions" in health services
| Service Accordions |    <img width="762" alt="Screenshot 2024-08-14 at 1 55 07 PM" src="https://github.com/user-attachments/assets/2dcd17c4-bcc0-4017-9c7a-96b92ccc8584">    |       <img width="741" alt="Screenshot 2024-08-14 at 1 54 50 PM" src="https://github.com/user-attachments/assets/f622f96e-c34e-4880-b39c-c1f56f11b232"> |
Health Services of region and VAMC facility. 
Check …
> VACMS 17954 - remove italics from common conditions

- src/applications/registry.json
We are rolling out the Travel Pay Reimbursement status page and need to set the "vagovprod" flag to true in order to do a friends/family test.
> Turn on production flag for rollout

- src/site/stages/build/drupal/static-data-files/config.js
- src/site/stages/build/drupal/static-data-files/generate.js
- src/site/stages/build/drupal/static-data-files/vaHealthcareServices/index.js
- src/site/tests/static-files/static-files-exist.cypress.spec.js
- Adds query taxonomyTermQuery from drupal CMS to JSON file (different structure due to postprocessing). Filters by existing uses and sorts by number of uses.
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18909
- Manually tested (verified from CMS view)
- Added testing to cover the creation of `va-healthcare-services.json` with a cypress test
N/A KISS data source
Adds KISS data source
Check that on tugboat the file is created at https://web-codylbelkq0gdivw6x7tykigmeqloewe.demo.cms.va.gov/data/cms/va-healthcare-services.json
> VACMS 18909 KISS autosuggest data for services from taxonomies

- src/site/facilities/health_service.drupal.liquid
- Adds hash to open accordion at hash reference id of taxonomy name, when clicking on facility name from inside a system-level Health Service
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13910
- Tested all facility service links on `/pittsburgh-health-care/health-services/`
- Manually clicked on all links to determine if any would fail. The hash naming convention is the same for the id, so expected that it would not and confirmed.
<details>
<summary>PR's links on Health Service listings</summary>
</details>
<details>
<summary>First link clicked on Audiology and speech</summary>
</details>
<details>
<summary>Second link clicked</summary>
</details>
System Health Service List pages
Check on RI `/pittsburgh-health-care/health-services/`
> VACMS 13910 - Direct links to hash reference id in system Health Service list

- src/applications/registry.json
This PR updates the appName for 7959f-1 to match the H1 which says  Register for the Foreign Medical Program (FMP).
https://github.com/department-of-veterans-affairs/va.gov-team/issues/91903
e2e and unit
this form only 
NA
> 10-7959f-1 Update Title to match H1

- src/site/filters/liquid.js
- src/site/includes/breadcrumbs.drupal.liquid
Two templates use the `constructLcBreadcrumbs` flag when generating breadcrumbs:
- basic_landing_page.drupal.liquid (only maps to `/resources`)
- checklist.drupal.liquid
Two other templates use this flag, but do not have any prod usage:
- media_list_images.drupal.liquid
- media_list_videos.drupal.liquid
The utility function that formatted breadcrumbs with the `constructLcBreadcrumbs` flag removed any crumbs with a `/resources` path because (according to a comment in the code) they pulled in the Drupal page title. Then, the utility pushed the proper Resources & Support home page breadcrumb into the array (but at the end). **Then**, it would take the current path's breadcrumb and add it to the end.
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18876
Tested the …
> VACMS-18876 Fix breadcrumbs on checklist pages

- src/site/stages/build/drupal/static-data-files/digitalForm/fragments/digitalForm.graphql.js
- src/site/stages/build/drupal/static-data-files/digitalForm/fragments/digitalForm.graphql.unit.spec.js
- src/site/stages/build/drupal/static-data-files/digitalForm/postProcessDigitalForm.js
- src/site/stages/build/drupal/static-data-files/digitalForm/postProcessDigitalForm.unit.spec.js
- Normalizes the OMB info fields created by department-of-veterans-affairs/va.gov-cms#19078
```json
{
"formId": "12345",
// ...
"ombInfo": {
"expDate": "8/29/2025",
"ombNumber": "1234-5678",
"resBurden": 30
},
"chapters": [
// ...
]
}
```
- department-of-veterans-affairs/va.gov-team#90733
- Added OMB info unit tests to the Digital Form post processor and the Digital Form GraphQL query
Only affects the output of digital-forms.json, which is not currently generated in production.
I made the decision to format the Expiration Date at this stage. As far as I can tell, we won't need it as anything other than a formatted string in the Form Renderer app, and this seems like the least expensive place to do that …
> VATEAM-90733: Normalize OMB info fields

- src/site/components/va_related_form.drupal.liquid
- src/site/filters/liquid.js
- src/site/layouts/va_form.drupal.liquid
In [this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/28068) we inadvertently removed the download modal from form detail pages. This PR plus [its companion vets-website PR](https://github.com/department-of-veterans-affairs/vets-website/pull/31395) add that modal back and changes the links on the form detail page to buttons since they now trigger a modal.
Uses a feature toggle (`FEATURE_FIND_FORMS_MODAL`) to reduce risk on a paired deploy.
To run the build locally with the feature toggle on, point to this Tugboat in your `.env`: https://cms-ciyktotgoqohism0kiuuviu13oifigrz.demo.cms.va.gov/.
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18855
See [this vets-website PR](https://github.com/department-of-veterans-affairs/vets-website/pull/3139 …
> VACMS-18855 Add Find Forms download modal back to form detail page

- src/applications/registry.json
- _Adds 10-7959f-1-FMP  to registry 
- _Sets deploy flag to true
This  is in preparation  for production testing, At time of deploy,  feature flag should be off or accessible only  by specific users.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/91311
> Adds 10-7959f-1-FMP  to registry

- src/site/layouts/va_form.drupal.liquid
Currently, for each form we display `Form last updated` with a month and year. The date for that field can draw from either the **revision date** or the **issued date**. The **revision date** is the date the form was created. The **issue date** is the date that the updated form is uploaded to the form DB. The **issue date** increments any time the **revision date** increments, and may also increment for background changes that do not change the **revision date**, such as updating Adobe certificates for the PDF.
It was reported that some field offices use this `Form last updated` information to verify whether a Veteran has filled out the correct copy of the form. If a Veteran did fill out the correct copy of the form, but the form recently had Adobe certificates updated (for example), it …
> VACMS-11047 Change form last updated language

- src/site/layouts/checklist.drupal.liquid
Adds language toggles widget to checklist pages in support of https://github.com/department-of-veterans-affairs/va.gov-team/issues/92454.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/92454
Tested while also running vets-website on the branch in this PR: https://github.com/department-of-veterans-affairs/vets-website/pull/32035
URL: `/resources/what-to-bring-to-create-your-online-sign-in-account/`
> VACMS-92454 Add i18 widget to checklist pages

- src/site/stages/build/drupal/static-data-files/config.js
- src/site/stages/build/drupal/static-data-files/config.unit.spec.js
- src/site/stages/build/drupal/static-data-files/digitalForm/fragments/digitalForm.graphql.js
- src/site/stages/build/drupal/static-data-files/digitalForm/fragments/digitalForm.graphql.unit.spec.js
- src/site/stages/build/drupal/static-data-files/digitalForm/fragments/nameAndDateOfBirth.graphql.js
- src/site/stages/build/drupal/static-data-files/digitalForm/fragments/nameAndDateOfBirth.graphql.unit.spec.js
- src/site/stages/build/drupal/static-data-files/digitalForm/index.js
- src/site/stages/build/drupal/static-data-files/digitalForm/index.unit.spec.js
- src/site/stages/build/drupal/static-data-files/digitalForm/postProcessDigitalForm.js
- src/site/stages/build/drupal/static-data-files/digitalForm/postProcessDigitalForm.unit.spec.js
This PR tracks an integration branch for the Form Engine proof of concept.
Individual PRs merged into this integration branch:
- https://github.com/department-of-veterans-affairs/content-build/pull/2213
- https://github.com/department-of-veterans-affairs/content-build/pull/2215
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/87958
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/87714
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/88634
Unit tests added for individual PRs. 
Manual smoke tests to ensure expected new behavior and existing behavior:
Note: This must be done locally or on a Tugboat environment where Digital Node content type exists.
N/A
This code creates a new KISS data file. It should not impact any other …
> Integration branch for Form Engine POC

- src/site/includes/facilityListing.drupal.liquid
- src/site/includes/hours.liquid
- src/site/includes/vet_centers/address_phone_image.liquid
- src/site/layouts/health_care_local_facility.drupal.liquid
- src/site/layouts/press_release.drupal.liquid
- src/site/layouts/vba_facility.drupal.liquid
- src/site/layouts/vet_center.drupal.liquid
- src/site/teasers/news_story.drupal.liquid
This PR will migrate the breakpoint names for the [flex utility classes](https://design.va.gov/foundation/utilities/flexbox).
| Current VADS Name | USWDS v3 Name |
| --------------------------- | ------------------------- |
| xsmall-screen (320px)          | mobile (320px) |
| small-screen (480px) | mobile-lg (480px) |
| small-desktop-screen (1008px) | desktop (1024px) 
| large-screen (1200px) | desktop-lg (1200px) |
- https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3208
- confirmed locally that the new breakpoint …
> Migrate breakpoint names for flex utility classes

- .github/workflows/content-release.yml
The build step is currently set to 50 minutes maximum and has timed out occasionally recently. It is not consistently over 50 minutes, but network conditions can lead it to rise above that timing.
This lifts the 50 minute timeout. The build job (all the surrounding work that goes along with the build) is set in this PR at 75 minutes. Again, this is for outliers runs where network conditions slow down the build.
No testing needed; these are simply timing changes.
> Lift 50 minute timeout on build step and raise build job to 75 minutes.

- src/site/paragraphs/facilities/list_of_link_teasers_facility.drupal.liquid
- Updates DST analytics back to custom event but adds the correct title for the section
- Collect/assign the correct title to a string to send to analytics
- Sitewide team (we own facilities pages)
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18501
- Checked several VAMC pages for the list of link teasers (Manual testing)
<details>
<summary>View of console from click on link in list</summary>
</details>
VAMC Facility pages
Check section in a VAMC page like:
`/philadelphia-health-care/locations/corporal-michael-j-crescenz-department-of-veterans-affairs/#other-services-at-va-philadelp`
Or
`/philadelphia-health-care/#other-services-at-va-philadelp`
> VACMS 18501 - working correct title and custom event

- .github/CODEOWNERS
In support of handing off the header/footer ownership to the Design System team, we need some updates to the codeowners file.
> Update codeowners for header/footer handoff

- package.json
- src/site/assets/sass/style.scss
- src/site/includes/hours-item.liquid
Service hours on several Facilities templates are wrapping unnecessarily. This isolates the class that it is using (instead of coming from vets-website) to its own class with the proper styles applied.
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19239
Tested the following URLs locally:
- /washington-dc-health-care/locations/washington-va-medical-center
- /togus-va-regional-benefit-office-at-togus-va-medical-center
- /boston-health-care/register-for-care/
To test, expand all the accordions and search for the "Service hours" to make sure you identify all use cases of this template.
VAMC services, VAMC non-clinical, VBA services
> VACMS-19239 Fix service hours wrapping issue

- src/site/filters/medalliaSurveysConfig.js
- src/site/includes/how-do-you-rate.drupal.liquid
Update success message after a user submits good/bad rating on Resources & support pages to encourage higher participation in completing Medallia survey.
Slack thread for context: https://dsva.slack.com/archives/CNCEXNXK4/p1726076748485399
- Removed `uswds` from components as that is default now
- Removed the `buildtype` check to alternatively render a vets-website React widget as this widget does not exist, and not sure it ever did? Here's a DSVA Github search for the `how-do-you-rate`, noting that there are no instances in vets-website where this widget would connect.
- https://github.com/search?q=org%3Adepartment-of-veterans-affairs%20how-do-you-rate&type=code
- This widget code was added 3 years ago in [this PR](https://github.com/department-of-veterans-affairs/content-build/commit/8cf …
> 19090 Good/bad rating messaging update

- src/site/stages/build/drupal/static-data-files/digitalForm/fragments/address.graphql.js
- src/site/stages/build/drupal/static-data-files/digitalForm/fragments/address.graphql.unit.spec.js
- src/site/stages/build/drupal/static-data-files/digitalForm/fragments/digitalForm.graphql.js
- src/site/stages/build/drupal/static-data-files/digitalForm/fragments/digitalForm.graphql.unit.spec.js
- src/site/stages/build/drupal/static-data-files/digitalForm/postProcessDigitalForm.js
- src/site/stages/build/drupal/static-data-files/digitalForm/postProcessDigitalForm.unit.spec.js
- Normalizes the Address Paragraph type created by department-of-veterans-affairs/va.gov-cms#19331
```json
{
"id": 161347,
"chapterTitle": "Veteran's mailing information",
"type": "digital_form_address",
"pageTitle": "Digital Form: Address",
"militaryAddressCheckbox": true
}
}
```
- department-of-veterans-affairs/va.gov-team#92265
- Added unit tests to the Digital Form post processor, the Digital Form GraphQL fragment, and the `address` GraphQL fragment
- Pulled local Drupal data and confirmed the resulting output from content-build
Only affects the output of `digital-forms.json`, which is not currently generated in production.
- Page titles currently have a "Digital Form: " prefix. That will be addressed by department-of-veterans-affairs/va.gov-team#94290
> VATEAM-92265: Normalize Address Digital Form pattern output

- src/applications/registry.json
- Removes the `coronavirus-research` and `coronavirus-research-update` apps from the registry, as they have been deprecated and are now redirected:
```
OITECHRolleA@HAC-LT3537169 OITECHRolleA % curl -s -D - https://www.va.gov/coronavirus-research/volunteer|grep '^HTTP\|^Location'
HTTP/1.1 301 Moved Permanently
Location: https://www.research.va.gov/for_veterans/
OITECHRolleA@HAC-LT3537169 OITECHRolleA % curl -s -D - https://www.va.gov/coronavirus-research/volunteer/update|grep '^HTTP\|^Location'
HTTP/1.1 301 Moved Permanently
Location: https://www.research.va.gov/for_veterans/
```
This is being done ahead of removing the vets-website apps [per guidance](https://github.com/department-of-veterans-affairs/vets-website/blob/main/.github/PULL_REQUEST_TEMPLATE.md). …
> Remove coronavirus apps from registry

- src/site/stages/build/drupal/static-data-files/digitalForm/postProcessDigitalForm.js
- src/site/stages/build/drupal/static-data-files/digitalForm/tests/fixtures/queryResult.json
- src/site/stages/build/drupal/static-data-files/digitalForm/tests/fragments/address.graphql.unit.spec.js
- src/site/stages/build/drupal/static-data-files/digitalForm/tests/fragments/digitalForm.graphql.unit.spec.js
- src/site/stages/build/drupal/static-data-files/digitalForm/tests/fragments/identificationInformation.graphql.unit.spec.js
- src/site/stages/build/drupal/static-data-files/digitalForm/tests/fragments/nameAndDateOfBirth.graphql.unit.spec.js
- src/site/stages/build/drupal/static-data-files/digitalForm/tests/index.unit.spec.js
- src/site/stages/build/drupal/static-data-files/digitalForm/tests/postProcessDigitalForm.unit.spec.js
We added a "Digital Form:" prefix to all the Paragraph types we are creating in Drupal to avoid name confusion with other content type builders. This PR strips that prefix out of our `content-build` output.
It also moves all digital form tests to a `tests` directory and extracts the test entities into fixture files.
```json
{
"id": 161347,
"chapterTitle": "Veteran's mailing information",
"type": "digital_form_address",
"pageTitle": "Digital Form: Address",
"militaryAddressCheckbox": true
}
}
```
```json
{
"id": 161347,
"chapterTitle": "Veteran's mailing information",
"type": "digital_form_address",
"pageTitle": "Address",
"militaryAddressCheckbox": true
}
}
```
- department-of-veterans-affairs/va.gov-team#94290
- Added unit tests to the Digital …
> VATEAM-94290: Remove "Digital Form:" from content-build output

- src/site/assets/sass/style.scss
- src/site/includes/how-do-you-rate.drupal.liquid
Updated CSS for abbreviated day to have left align hours of operation.
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19239
/washington-dc-health-care/locations/washington-va-medical-center/#laboratory-and-pathology
> VACMS-19239: Update css for day wrapping Part 2

- src/site/filters/liquid.unit.spec.js
- src/site/filters/medalliaSurveysConfig.js
This PR changes the target Medallia feedback button survey on `/my-health/medical-records/summaries-and-notes/visit-summary/**`
After UAT with the survey team, an issue was identified with the survey. Reverting changes made [in this PR](https://github.com/department-of-veterans-affairs/content-build/pull/2295/).
department-of-veterans-affairs/va.gov-team#94851
Note: Will need to merge in order to test in staging.
N/A
The Feedback button on `/my-health/medical-records/summaries-and-notes/visit-summary/` and subpaths
-[x] Afterv-visit summary feedback button changed back to sitewide default survey
-[x] Update unit test
> [Medallia Digital Surveys] Revert AVS Feedback Button Survey

- src/site/includes/metatags.drupal.liquid
Hardcode a metadata description for the homepage to adjust to federal website standards for HTML
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18020
Tested in RI for homepage metadata
> VACMS-18020: Add metadata description for homepage

- src/site/paragraphs/contact_information.drupal.liquid
Remove extra colon (`:`) from CSS class to fix padding on R&S pages (contact information at the bottom).
Test page: `/resources/signing-in-to-vagov/`
Current:
Fixed:
> Fix padding issue on R&S pages contact information

- src/site/stages/build/drupal/static-data-files/digitalForm/fragments/digitalForm.graphql.js
- src/site/stages/build/drupal/static-data-files/digitalForm/fragments/phoneAndEmail.graphql.js
- src/site/stages/build/drupal/static-data-files/digitalForm/postProcessDigitalForm.js
- src/site/stages/build/drupal/static-data-files/digitalForm/tests/fixtures/queryResult.json
- src/site/stages/build/drupal/static-data-files/digitalForm/tests/fragments/digitalForm.graphql.unit.spec.js
- src/site/stages/build/drupal/static-data-files/digitalForm/tests/fragments/phoneAndEmail.graphql.unit.spec.js
- src/site/stages/build/drupal/static-data-files/digitalForm/tests/postProcessDigitalForm.unit.spec.js
- Normalizes the Phone and Email Address Paragraph type created by department-of-veterans-affairs/va.gov-cms#19464
```json
{
"id": 161355,
"chapterTitle": "Veteran's contact information",
"type": "digital_form_phone_and_email",
"pageTitle": "Phone and email address",
"includeEmail": true
}
}
```
- department-of-veterans-affairs/va.gov-team#93401
- Added unit tests to the Digital Form post processor, the Digital Form GraphQL fragment, and the `phoneAndEmail` GraphQL fragment
Only affects the output of `digital-forms.json`.
> VATEAM-93401: Normalize Phone and Email Digital Form pattern output

- src/applications/registry.json
- src/site/filters/liquid.js
- src/site/filters/liquid.unit.spec.js
- Remove hyphen filter to avoid improper output in breadcrumbs.
Original:
Fixed:
> Fix hyphens

- .github/workflows/content-release.yml
The conditions that required this change have passed, and we do want the timeout to alert us if content-release is taking too long.
Reverts department-of-veterans-affairs/content-build#2321
> Revert "Remove build timeout until we know why content release is slow."

- src/site/components/va_related_form.drupal.liquid
- src/site/filters/liquid.js
- src/site/layouts/va_form.drupal.liquid
In https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18855, we re-added the download modal to form detail pages. This required implementing a feature toggle for the content-build changes and a feature toggle for the vets-api changes. This work is for removing the feature toggle used for the form detail page.
The markup for the form detail page should be a `<button>` and never an `<a>`.
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19255
- Regression testing for the form search results (nothing changed; this only changes the form detail pages)
- Tested the modal opening for a form detail page with one modal trigger
- Tested the modal opening for a form detail page with multiple modal triggers (e.g. has related forms)
- Tested the errors for when …
> VACMS-19255 Remove CMS feature toggle from Find Forms

- src/site/layouts/vet_center.drupal.liquid
- src/site/stages/build/drupal/graphql/vetCenter.graphql.js
- Adds mission explainer query to graphQL and pulls it into the layout for Vet Centers.
- Sitewide team (owns Vet Center facility pages and queries)
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18724
- No mission explainer prior
- Verify mission explainer exists on Vet Center pages that have the centralized content (in some tugboats there may be some that do not have it, but in prod and staging all do now)
<details>
<summary>Vet Center Page with mission explainer (Boston Vet Center) - Desktop (above 768px)</summary>
</details>
<details>
<summary>Vet Center Page with mission explainer (Boston Vet Center) - below 768px</summary>
</details>
<details>
<summary>Vet Center Page missing mission explainer in tugboat (looks exactly the same as current Vet Center) - fixed …
> VACMS 18724 - Adds mission explainer to Vet Centers

- src/site/filters/liquid.unit.spec.js
- src/site/filters/medalliaSurveysConfig.js
This PR changes the target Medallia feedback button survey on /my-health/medical-records/summaries-and-notes/visit-summary/**
department-of-veterans-affairs/va.gov-team#93127
Note: Will need to merge in order to test in staging.
N/A
The Feedback button on /my-health/medical-records/summaries-and-notes/visit-summary/ and subpaths
-[x] Afterv-visit summary feedback button changed back to sitewide default survey
-[x] Update unit test
> [Medallia Digital Surveys] Update After-Visit-Summary Feedback Button

- src/site/components/banners.drupal.liquid
- Add a situation updates banner to be utilized by vets-website to provide up quickly updatable banners
- No flipper involved as this element will not be visible to any users. The vets-website javascript that will interact with this will be kept behind a feature flag `banner_use_alternative_banners`.
- Removes aria labels to keep empty elements hidden from assistive tech
- Issue: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19449
- Epic: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19302
- Verified new element does not appear to users viewing page
No changes to UI.
This affects most pages as it is included in the header element throughout the site
Element is available for vets-website to manipulate but is not visible to users
> [VACMS-19449]Add situation updates banner for vets-website to manipulate

- src/site/stages/build/drupal/static-data-files/digitalForm/fragments/digitalForm.graphql.js
- src/site/stages/build/drupal/static-data-files/digitalForm/fragments/yourPersonalInformation.graphql.js
- src/site/stages/build/drupal/static-data-files/digitalForm/postProcessDigitalForm.js
- src/site/stages/build/drupal/static-data-files/digitalForm/tests/fixtures/queryResult.json
- src/site/stages/build/drupal/static-data-files/digitalForm/tests/fragments/digitalForm.graphql.unit.spec.js
- src/site/stages/build/drupal/static-data-files/digitalForm/tests/fragments/yourPersonalInformation.graphql.unit.spec.js
- src/site/stages/build/drupal/static-data-files/digitalForm/tests/postProcessDigitalForm.unit.spec.js
- Normalizes the "Your personal information" Paragraph type created by department-of-veterans-affairs/va.gov-cms#19534
```json
{
"id": 162013,
"type": "digital_form_your_personal_info",
"chapterTitle": "Your personal information",
"pages": [
{
"pageTitle": "Name and date of birth",
"includeDateOfBirth": true
},
{
"pageTitle": "Identification information",
"includeServiceNumber": true
}
]
}
```
- department-of-veterans-affairs/va.gov-team#94709
- Added unit tests to the Digital Form post processor, the Digital Form GraphQL fragment, and the `yourPersonalInformation` GraphQL fragment
Only affects the output of `digital-forms.json`.
This PR introduces a `pages` array to the normalized output. I notably did …
> VATEAM-94709: Normalize Your Personal Information chapter

- src/site/assets/sass/style.scss
- src/site/filters/liquid.js
- src/site/includes/email-update-signup.drupal.liquid
- src/site/layouts/home.drupal.liquid
Add the CMS feature toggle and empty `<div>` for the React widget for the email signup form.
**Note**: Feature toggle is currently **ON** in staging and production which means when this code is deployed to prod, we should continue to see the current/existing email form and not the new design.
Ticket: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19516
1. Run `content-build` on the `19516-email-signup-widget` branch
1a. comment everything but `...getNodePageQueries(entityCounts)` out in `individual-queries.js` to speed up the build
1b. Point your CMS in the `.env` to `DRUPAL_ADDRESS=https://staging.cms.va.gov`
2. Run `vets-website` on `main`
3. Go to `localhost:3002` and validate that the original/current `Sign up to get the latest VA updates` form appears at the …
> VACMS-19516 Add container and toggle for Email Signup React widget

- src/site/stages/build/drupal/static-data-files/vaHealthcareServices/index.js
- Michelle M and Michael S discussed moving the commonly treated conditions to (when present) CSV in place of "and" terminated list
- Sitewide
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18910
- Manually tested from CMS
N/A
JSON creation postprocessing of Drupal loaded data
- See vets-website PR https://github.com/department-of-veterans-affairs/vets-website/pull/32930
Check that `.cache/localhost/drupal/static-data-files/va-healthcare-services.json` is created with a second value per array that is now an array of strings.
> VACMS 18910 - Michelle M/Product is moving commonly treated conditions to CSV value

- src/site/includes/email-update-signup.drupal.liquid
Adjust the container structure of the email signup widget. The current version has a lot of nested `div`s that make it difficult to properly center the form with the proper length of the text input intact. The current/original version is unchanged, I simply isolated those extra `div`s to that version and simplified the implementation of the new React widget so I could style it properly.
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19516
Since the React widget code has not been merged yet, it is more important to validate this style/structure change against the existing email form. But I did add screenshots of the React widget form because I have a branch of that code locally.
Homepage email signup widget only.
> VACMS-19516 Adjust email container structure and spacing

- src/site/stages/build/drupal/static-data-files/digitalForm/fragments/digitalForm.graphql.js
- src/site/stages/build/drupal/static-data-files/digitalForm/fragments/listLoop.graphql.js
- src/site/stages/build/drupal/static-data-files/digitalForm/postProcessDigitalForm.js
- src/site/stages/build/drupal/static-data-files/digitalForm/tests/fixtures/queryResult.json
- src/site/stages/build/drupal/static-data-files/digitalForm/tests/fragments/digitalForm.graphql.unit.spec.js
- src/site/stages/build/drupal/static-data-files/digitalForm/tests/fragments/listLoop.graphql.unit.spec.js
- src/site/stages/build/drupal/static-data-files/digitalForm/tests/postProcessDigitalForm.unit.spec.js
- Normalizes the List & Loop Paragraph type created by department-of-veterans-affairs/va.gov-cms#19816
```json
{
"id": 162032,
"type": "digital_form_list_loop",
"optional": true
},
"chapterTitle": "Veteran's employment history",
"pageTitle": "List & Loop"
}
```
- Closes department-of-veterans-affairs/va.gov-team#93614
- Added unit tests to the Digital Form post processor, the Digital Form GraphQL fragment, and the `listLoop` GraphQL fragment
Only affects the output of `digital-forms.json`.
I'm not even sure if we'll need a `pageTitle` attribute for list and loops, but it's not doing any harm at the moment.
> VATEAM-93614: Normalize List and Loop pattern output

- src/applications/registry.json
- Changes the appName so that it is read correctly by screen readers.
- https://github.com/department-of-veterans-affairs/tmf-auth-exp-design-patterns/issues/163
- Tested locally to verify that app title appears in browser tab correctly and is read by screen reader
No UI changes
Authenticated Experience Design Patterns mock form app. No changes being shipped to prod
Title updated
> Update appName to correct title for Authenticated Experience Design Patterns

- src/applications/registry-schema.json
- src/applications/registry.json
We created a workspace in https://github.com/department-of-veterans-affairs/vets-website/pull/33036 pr but the changes were not being merged into Staging. 
Found [this](https://depo-platform-documentation.scrollhelp.site/developer-docs/guide-for-engineers#WorktreeandWorkspaceSetupGuide-src/platformcodeworkspaces:) platform doc about workspaces and realized we were missing our dependency in the `nohoist` section so we added that but we still weren't seeing our changes in staging. 
After investigating @micahchiang found that the `component-library` 43.0.2 …
> CST - Added useLocalStylesAndComponents to the claims-status app

- src/site/includes/header.html
This pull request removes the conditional style.css import in the header when `useLocalStyleAndComponents` is present. We're removing it because no apps are opting out of the global stylesheet.
> remove conditional style.css

- src/applications/registry-schema.json
- src/applications/registry.json
- src/site/includes/header.html
> Rebase 2351

- src/applications/registry.json
Adds an entry to registry.json for a new app added in vets-website (`simple-forms-form-engine/21-4140`).
Original ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/96075
vets-website PR with added app: https://github.com/department-of-veterans-affairs/vets-website/pull/32891
N/A. Simply a registry addition.
N/A
Simply a registry addition.
N/A
> Adds registry entry for new form app (21-4140).

- src/site/facilities/facilities_health_services_buttons.drupal.liquid
- src/site/tests/cypress/vamc-lovell.cypress.spec.js
Update the "Pharmacy" text to "Learn about pharmacy services," and also update the links to `va-link-action` instead.
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19913
Tested these URLs:
- /northeast-ohio-health-care/locations/sandusky-va-clinic/
- /northeast-ohio-health-care/health-services/
- /lovell-federal-health-care-va/health-services/
- /lovell-federal-health-care-tricare/health-services/
Also regression checked via Cypress (since I converted the links to `<va-link-action>`)
- /lovell-federal-health-care-tricare/
- /lovell-federal-health-care-tricare/locations
- /lovell-federal-health-care-tricare/locations/captain-james-a-lovell-federal-health-care-center/
- /lovell-federal-health-care-va/
- /lovell-federal-health-care-va/locations/ …
> VACMS-19913 Pharmacy text update for health services and VAMC pages

- .github/workflows/continuous-integration.yml
- .github/workflows/install/action.yml
- This brings the Cypress testing mechanism in line with what vets-website is doing
- The main change is that it runs the container and Cypress testing steps on GHA-hosted infrastructure rather than VA-hosted
- This is being done in response to the Cypress executable no longer being downloadable on the VA network. This is a error we first noticed on Dec 2, 2024. An example: https://github.com/department-of-veterans-affairs/content-build/actions/runs/12120500910/job/33814202119#step:6:226
For reference, here is the vets-website implementation of this:
- https://github.com/department-of-veterans-affairs/vets-website/blob/main/.github/workflows/continuous-integration.yml#L663
- https://github.com/department-of-veterans-affairs/vets-website/blob/main/.github/workflows/install/action.yml
- …
> Source Cypress from Va-internal S3.

- src/site/components/banners.drupal.liquid
- src/site/includes/header.html
- Puts div for React widget injection next to full width banners in header.html and makes it conditional based on CMS toggle
- CMS toggle `FEATURE_BANNER_USE_ALTERNATIVE_BANNERS`
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19842
- Conditionally renders the div with the widget type for using vets-website banner when toggled feature is on and uses standard existing div with va-banner from graphql if off.
- Manually tested two builds on a tugboat
<details>
<summary>Build with FEATURE_BANNER_USE_ALTERNATIVE_BANNERS: true but tugboat doesn't build the new v-w so div is blank (but still no full-width-banner from liquid template)</summary>
</details>
<details>
<summary>Build with FEATURE_BANNER_USE_ALTERNATIVE_BANNERS: false</summary>
</details>
Affects …
> VACMS 19842 - conditional rendering of data-widget-type div or full-width-banners based on CMS toggle

- src/applications/registry.json
Turns Production Flag ON for application survivor-dependent-education-benefit-22-5490
Enables application survivor-dependent-education-benefit-22-5490 in Production
> Enable Prod flag for 5490 fry/dea application

- src/site/constants/brokenLinkIgnorePatterns.js
- src/site/stages/build/drupal/graphql/CountEntityTypes.graphql.js
- src/site/stages/build/drupal/graphql/GetAllPages.graphql.js
- src/site/stages/build/drupal/individual-queries.js
- src/site/stages/build/plugins/modify-dom/check-broken-links/helpers/isBrokenLink.js
Currently a test: put into PR form to test CI and on Tugboat against CMS. 
This removes Event and Event Listing pages from being output by Content Build. Broadly, this has 2 parts:
- remove the queries, including removing Events from the node count queries
- update the broken link checker to ignore Event pages, since they are no longer available to be checked
Events are being removed because they are now deployed to production by Next Build. 
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19811
- Multiple content-releases on Tugboat using this branch
- Tested that output completed successfully
- Tested that Event & Event Listings were not included
- Tested that pages that incorporate Events within them do still render correctly
- Checked that the broken link check is …
> Remove Event page queries from Content Build

- src/site/includes/facilityListing.drupal.liquid
- src/site/layouts/health_care_local_facility.drupal.liquid
- src/site/layouts/person_profile.drupal.liquid
- src/site/layouts/press_release.drupal.liquid
- src/site/layouts/vamc_system_billing_insurance.drupal.liquid
- src/site/paragraphs/service_location.drupal.liquid
- src/site/paragraphs/staff_profile.drupal.liquid
- src/site/stages/build/drupal/graphql/facilities-fragments/healthCareLocalFacility.node.graphql.js
- src/site/stages/build/drupal/graphql/facilities-fragments/healthCareRegionStaffBios.node.graphql.js
- src/site/stages/build/drupal/graphql/healthCareLocalFacilityPage.graphql.js
- src/site/stages/build/drupal/graphql/leadershipListingPage.graphql.js
- src/site/stages/build/drupal/graphql/paragraph-fragments/staffProfile.paragraph.graphql.js
- src/site/stages/build/drupal/graphql/pressReleasePage.graphql.js
- src/site/teasers/bio.drupal.liquid
- Removes toggle usage and uses only the new fields that have been used in production
- Will be removing CMS toggle soon
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19968
- Manually tested in tugboat and RI
<details>
<summary>Staff profile</summary>
</details>
<details>
<summary>Leadership page</summary>
</details>
<details>
<summary>Kind of cut off MH phone on VAMC System Locations page</summary>
</details>
<details>
<summary>VAMC Facility MH Number</summary>
</details>
<details>
<summary>MH Service Location Main MH Num</summary>
</details>
<details>
<summary>Press release number using Bio number</summary>
</details>
Affects code (but no visible difference from prod)
- Staff profile phone number
- Leadership page phone numbers
- MH Phone number …
> VACMS 19968 - remove CMS toggle usage for phone number migration and use only new fields

- src/site/constants/brokenLinkIgnorePatterns.js
- src/site/stages/build/drupal/graphql/CountEntityTypes.graphql.js
- src/site/stages/build/drupal/graphql/GetAllPages.graphql.js
- src/site/stages/build/drupal/individual-queries.js
- src/site/stages/build/plugins/modify-dom/check-broken-links/helpers/isBrokenLink.js
Reverts department-of-veterans-affairs/content-build#2386
This puts the Event & Event Listing removal back in place.
> Revert "Revert "Remove Event page queries from Content Build""

- src/applications/registry.json
This ticket/PR involves updating the `Last update` field on the SCO page in the footer to `2024-12-10`. It will show on the UI as `December 10, 2024`. 
- https://jira.devops.va.gov/browse/VEBT-911
**As a...**
VEBT Developer
**I want…**
To update the last updated date of the SCO page
**So that…**
The SCO page can reflect the latest date
**Acceptance Criteria**
Update the 'Last Updated' date to December 10, 2024.
To be confirmed shortly -> On the top, remove the yellow box entirely. 
**Technical Details:**
Dependencies: 
Feature Flag needed: No
Demo needed: No
UAT needed: No
Additional Notes:  
**Testing Details:**
( X ) Quick Turn Around/Direct to Production
(  ) Remains in Staging
(  ) Staging Environment unavailable, coordinate w/ developer
**Requested by and when:**
Kate, 12/09 …
> VEBT-911 SCO - Update 'Last Updated' date

- src/site/stages/build/drupal/graphql/bioPage.graphql.js
- src/site/stages/build/drupal/graphql/vamcBillingAndInsurancePage.graphql.js
- Removes 2 more uses from GQL that were missed in the first PR
- This was noticed because of a removal of a CMS toggle and field
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19968
- Manually tested
Just GQL data that was excluded from liquid templates in the past, so no visible changes
Graphql data
GQL download completes
Check that GQL download completes from: https://pr20101-3l0mof51ngr1hdlfew7vcusi6oi5unbr.ci.cms.va.gov/
e.g. `yarn build --use-cached-assets --pull-drupal --drupal-address=https://pr20101-3l0mof51ngr1hdlfew7vcusi6oi5unbr.ci.cms.va.gov/`
> VACMS 19968 - remove 2 extra uses of old phone numbers

- src/site/facilities/main_buttons.drupal.liquid
- src/site/includes/support_resources_cta_list.drupal.liquid
- src/site/layouts/campaign_landing_page.drupal.liquid
- src/site/layouts/vamc_operating_status_and_alerts.drupal.liquid
- src/site/paragraphs/action_link.drupal.liquid
- src/site/paragraphs/react_widget.drupal.liquid
- src/site/paragraphs/service_location.drupal.liquid
- src/site/tests/cypress/vamc-lovell.cypress.spec.js
- src/site/tests/static-pages/static-page-widgets.unit.spec.js
Updated the remainder of old action links to `<va-link-action>`.
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18456
1. [main_buttons.drupal.liquid](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/facilities/main_buttons.drupal.liquid) is used for:
<details><summary>Health Care Region Detail Pages</summary>
Tested at `/boston-health-care/contact-us`
| Before | After |
| ------ | ----- |
| <img width="648" alt="Screenshot 2024-12-17 at 11 47 29 AM" src="https://github.com/user-attachments/assets/951e36ef-49ce-4e26-a927-c958b33be45e" /> | <img width="644" alt="Screenshot 2024-12-17 at 11 47 06 AM" src="https://github.com/user-attachments/assets/84da9b9b-6f40-4a5c-83f2-1ce871624238" /> |
| <img width="374" alt="Screenshot 2024-12-17 at …
> VACMS-18456 Update legacy action links to DS action links

- src/site/facilities/health_service.drupal.liquid
Adjust hard-coded service accordion interior headings to be `<h4>` instead of `<h3>`.
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12082
Tested at http://localhost:3002/boston-health-care/health-services/, http://localhost:3002/lovell-federal-health-care-va/health-services/ and http://localhost:3002/lovell-federal-health-care-tricare/health-services/.
<br />
<br />
<br />
VAMC Health Services pages
> VACMS-12082 Fix service accordions headers

- src/site/filters/liquid.js
- src/site/includes/email-update-signup.drupal.liquid
Removes old email signup widget and the feature toggle that would display it, defaulting to the new React widget in vets-website.
The `FEATURE_EMAIL_UPDATE_WIDGET` feature toggle is currently **off** in staging and production CMS (screenshots below), so the behavior locally and in the review instance should match what is in staging and production (show the new widget).
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19888
Homepage email signup widget only.
> VACMS-19888 Remove old email signup widget and feature toggle

- src/applications/registry.json
This PR updates the title text of the HCA application to match the H1 tag and current breadcrumb for the app page. This update was based on a finding from Staging review of other team app that uncovered the mismatch.
department-of-veterans-affairs/va.gov-team#99709
- Page title text matches the current breadcrumb and H1 tag on the page
> Update title text for the HCA app entry

- script/preview.js
- src/site/stages/build/drupal/metalsmith-drupal.js
- src/site/stages/build/drupal/process-manila-pages.js
- src/site/stages/build/drupal/tests/process-manila-pages.unit.spec.js
- Corrects the page links for Manila VA Clinic Profile Pages
- Enable a bio page for a leadership profile in the Manila VA Clinic, then while viewing said profile click the leadership link on the left side nav and find it leads to a 404 page for a non-existing system
- Process Manila VA Clinic pages for links that are pointing to this non-existent node and correct the URL's path
- Sitewide Team
- This work is not behind a flipper
- Issue: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19992
- This has been setup on Tugboat [here](https://tugboat.vfs.va.gov/676b1e9b5134c90ada0881b4), if that is still live, head over to https://web-8zpd9j4sobjcc5dutp67lq4xmmmsj3x2.demo.cms.va.gov/manila-va-clinic/staff-profiles/john-stelsel/ and verify the leadership link leads to the …
> [VACMS-19406]Correct Manila Profile Page Leadership Links

- src/site/components/fullwidth_banner_alerts.drupal.liquid
- Removes the aria-labelledby from fullwidth banner alerts
- This was generating errors in AMP due to it creating labels without corresponding ids
- These fullwidth banner alerts are behind a flipper as a backup to real-time banners from the vets-api
- Issue: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19506#issuecomment-2552199034
- Confirmed when the flipper to use alternative banners is disabled, content build creates fullwidth-banner-alerts without the corresponding aria-labelledby attributes.
The no longer utilized VAMC fullwidthBannerAlerts
> [VACMS-19506]Remove aria-labelledby from fullwidth banner alerts

- src/applications/registry.json
This PR updates the title text of the EZR application to match the H1 tag and current breadcrumb for the app page. This update was based on a finding from Staging review of other team apps that uncovered the mismatch.
department-of-veterans-affairs/va.gov-team#99784
- Page title text matches the current breadcrumb and H1 tag on the page
> Update title text for the EZR app entry

- src/applications/registry.json
This PR sets IVC CHAMPVA form 10-7959f-2 to go to production. The form is currently behind a feature toggle and will not be available to the public.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/99965
- NA
NA
This form only
NA
> 99965 Set FMP2 to deploy to production - form 10-7959f-2

- src/site/includes/accredited-representative-portal/head.html
- src/site/includes/header.html
- removed references to fa-solid-900.woff, as the file is no longer being generated
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/20219
Generated files no longer attempt to load fa-solid-900.woff
> Remove fa-solid-900.woff references.

- .github/workflows/daily-production-release.yml
- This adds a VA holiday checker action in front of Daily Production Release to halt production tagging if in a code freeze
- It can be manually overridden in the Github interface
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19910
This was tested by attempting to run the workflow from this branch, both without and then with the override. The overridden version was halted before completing in order to not violate code freeze.
- Without Override (halted itself without completing due to being in code freeze): https://github.com/department-of-veterans-affairs/content-build/actions/runs/12486388271
- With override (continued successfully to later parts of the workflow): https://github.com/department-of-veterans-affairs/content-build/actions/runs/12486397868
> Adds holiday checker in front of daily production tag, including override.

- src/applications/registry.json
This PR updates the title text of the Caregivers application to match the H1 tag and current breadcrumb for the app page. This update was based on a finding from Staging review that uncovered the mismatch.
department-of-veterans-affairs/va.gov-team#99039
- Page title text matches the current breadcrumb and H1 tag on the page
> Update title text for Caregivers app entry

- src/site/navigation/sidebar_nav.drupal.liquid
In this PR we add markup to the div containing the accordion dropdown to allow the cursor in iOS to stay once the drawer is open.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/28709
Hard to test this in iOS. But checked that the new markup is showing locally.
> VACMS-28709 in this section a11y iOS fix

- src/site/layouts/health_care_local_facility.drupal.liquid
If a YouTube link is added to a VAMC, it appears on the region page, but it hasn't been appearing on the local facility page. This is because it isn't explicitly passed to the social links template for some reason.
This PR adds the YouTube link to the social links template so the links will be consistent across the region pages and local facility pages.
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/20243
Tested on `/greater-los-angeles-health-care/` (where it is currently appearing in prod) and `/greater-los-angeles-health-care/locations/west-los-angeles-va-medical-center/` (where it was added).
Can also be tested on `/minneapolis-health-care/` and `/minneapolis-health-care/locations/minneapolis-va-medical-center/`.
_Note: This field is mandatory for UI changes …
> VACMS-20243 Add YouTube link to local facility pages

- src/site/layouts/va_form.drupal.liquid
The **Form revision date** and **Related to** data are in opposite order on the form detail page and the form search results. We want to update the form detail page to make these consistent. ([Slack thread](https://dsva.slack.com/archives/C03LFSPGV16/p1736804106855099)).
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/20274
Tested on `/find-forms/about-form-10-0003k/` and `/find-forms`.
Search results on `/find-forms`, for reference:
Form detail page:
| Before | After |
| ------ | ----- |
| <img width="674" alt="Screenshot 2025-01-14 at 9 45 34 AM" src="https://github.com/user-attachments/assets/096cd132-a695-4fe4-a18d-122c06362418" /> | <img width="611" alt="Screenshot 2025-01-14 at 9 45 15 AM" src="https://github.com/user-attachments/assets/65d1ffa0-c69b-4230-b504-aca …
> VACMS-20274 Reorder form details on detail page for consistency

- src/site/stages/build/drupal/process-manila-pages.js
- Makes it so that even when published, system nodes for Manila's VA Clinic will not be built
- It was desired to put this in as a safety net in case future editors accidentally publish this system node
- Sitewide Team
- No Flipper
-  Issue: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19406
- Archived Manila System Node to have a clean Manila VA clinic node
- Created Tugboat [here](https://tugboat.vfs.va.gov/678ac1a85134c90ada6b552b) for testing
- On tugboat's CMS did a content-build with this branch
- Then published Manila VA System
- No changes appear https://web-iqtwo8u4khq2nt7e1xd8m7yjtc7ohro9.demo.cms.va.gov/manila-va-clinic/ it remains identical to https://www.va.gov/manila-va-clinic/
Manila System Node
> [VACMS-19406]Don't build health care region pages for Manila

- src/applications/registry.json
- Remove 'too' from end of ask-va url
- I am on the Ask VA team (this app is not in production)
- Link to ticket here: https://github.com/orgs/department-of-veterans-affairs/projects/1033/views/11?pane=issue&itemId=88550012&issue=department-of-veterans-affairs%7Cask-va%7C1348
- N/a
- This only impacts the Ask VA form
> AskVA-1348: Configure app url for Ask VA to remove too

- .github/workflows/continuous-integration.yml
Updates upload/download artifact action usage in Github Actions. See deprecation notice: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/20338
- The changes are entirely in the CI job, so successful CI completion of this workflow will be sufficient testing.
> Update upload/download artifact actions to 4.x versions.

- src/applications/registry.json
This PR changes the `rootUrl` for the Form Upload tool, in accordance with the changes in [this `vets-website` PR](https://github.com/department-of-veterans-affairs/vets-website/pull/34208).
https://github.com/orgs/department-of-veterans-affairs/projects/1443/views/3?sliceBy%5Bvalue%5D=Thrillberg&pane=issue&itemId=94053329&issue=department-of-veterans-affairs%7Cva.gov-team%7C101254
> Update form upload rootUrl

- src/applications/registry.json
- Update minimal header form to also use minimal footer
department-of-veterans-affairs/va.gov-team-forms#1958
- Browser
minimal header mock form
> Use minimal footer for minimal header mock form

- src/applications/registry.json
Adding new application to registry
- Latest ticket
department-of-veterans-affairs/va.gov-team/issues/99407
- _New app PR on `vets-website`_
department-of-veterans-affairs/vets-website/pull/33332
Manual testing complete
- _Exclusively stating 'Specs and automated …
> Adding dispute debt to registry

- src/site/includes/hours.liquid
- Updated the displaying of 24/7 facility hours to be more inline with the styles as well as provide a clear message to veterans
- Not a bug, just copy changes
- Sitewide team owns and maintains this component
- No flippers for this copy change 
- Issue: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/20282
- Prior to this change, visiting a VAMC w/ 24/7 hours like [Minneapolis](http://localhost:3002/minneapolis-health-care/locations/minneapolis-va-medical-center/), will display the existing Clinical hours h2 along with no warning. On this branch with a fresh content build you will find Clinical adjust to Facility at the more appropriate h3 size along with a warning about hours differing depending on services required.
_Note: This field is mandatory for UI changes …
> [VACMS-20282]Update facility hours copy, size, and add sub message

- src/applications/registry.json
- This is work for the VA-IIR team.
- Our team owns this form/application, the Welcome VA Setup Review Information form.
- It updates (shortens) the URL for our form, which is not yet in production.
- This work closes ticket [1384](https://github.com/orgs/department-of-veterans-affairs/projects/1360/views/3?pane=issue&itemId=94058167&issue=department-of-veterans-affairs%7Cva-iir%7C1384).
- Related work is being completed in [1383]([1383](https://github.com/orgs/department-of-veterans-affairs/projects/1360/views/3?pane=issue&itemId=94058094&issue=department-o …
> [VA-IIR 1384] update form URL based on feedback

- src/site/stages/build/drupal/health-care-region.js
All this does is log when a Facilities page does not have a URL in its second breadcrumb component, rather than throwing an error. Please see discussion https://dsva.slack.com/archives/CT4GZBM8F/p1737124609714199
1. _Facilities or helpdesk: Please fill in instructions for how to recreate the data situation that led to the error._
2. Run a content-build on this Tugboat instance with the data from step 1. 
Expected: You should see `WARNING: CMS error while building breadcrumbs` in the log output.
Expected: The build should still complete.
> Log when Facilities cannot find a URL from its breadcrumb rather than erroring.

- .github/workflows/content-release.yml
- .github/workflows/continuous-integration.yml
- .github/workflows/install/action.yml
- .github/workflows/manual-review.yml
Updating actions/cache in Github Actions workflows to most recent version due to previous version deprecation.
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/20394
Github actions are untestable.
> Update actions/cache to most recent and non-deprecated version.

- .github/workflows/authenticated-cms-request/action.yml
- .github/workflows/build.yml
- .github/workflows/content-release.yml
- .github/workflows/continuous-integration.yml
- .github/workflows/daily-production-release.yml
- .github/workflows/deploy-content-preview-server.yml
- .github/workflows/gha-metrics.yml
- .github/workflows/manual-deploy-dev-staging.yml
- .github/workflows/manual-review.yml
- .github/workflows/preview-environment-cleanup.yml
- .github/workflows/preview-environment-deployment.yml.bak
- .github/workflows/prune-self-hosted-runners.yml
- .github/workflows/slack-notify/action.yml
We have been seeing problems with various GHA workflows failing on the configure-aws-credentials action. This brings it up-to-date across the board. This seems to help the failures.
Action ran correctly in this test: https://github.com/department-of-veterans-affairs/content-build/actions/runs/13145802541/job/36683541816
> Update aws-credentials action to current version.

- src/applications/registry.json
- Confirmation page use full header instead of minimal for 4138
department-of-veterans-affairs/va.gov-team-forms#1538
- Browser testing
Before:
After:
> Confirmation page use full header instead of minimal for 4138

- src/site/facilities/health_service.drupal.liquid
Removes the regionOrOffice in the `health_service.drupal.liquid` template
[#13935](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13935)
> VACMS-13935: Remove html code for regionOrOffice for Available at these locations

- src/applications/registry.json
This PR sets IVC CHAMPVA form 10-7959c (OHI) to go to production. The form is behind a feature flag.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/103565
- NA
NA
IVC CHAMPVA form 10-7959c
NA
> 103565 - Deploy OHI to production - form 10-7959c

- src/site/stages/build/drupal/static-data-files/digitalForm/chapters.js
- src/site/stages/build/drupal/static-data-files/digitalForm/fragments/customStep.graphql.js
- src/site/stages/build/drupal/static-data-files/digitalForm/fragments/digitalForm.graphql.js
- src/site/stages/build/drupal/static-data-files/digitalForm/fragments/page.graphql.js
- src/site/stages/build/drupal/static-data-files/digitalForm/fragments/textInput.graphql.js
- src/site/stages/build/drupal/static-data-files/digitalForm/postProcessDigitalForm.js
- src/site/stages/build/drupal/static-data-files/digitalForm/tests/chapters.unit.spec.js
- src/site/stages/build/drupal/static-data-files/digitalForm/tests/fixtures/queryResult.json
- src/site/stages/build/drupal/static-data-files/digitalForm/tests/fragments/customStep.graphql.unit.spec.js
- src/site/stages/build/drupal/static-data-files/digitalForm/tests/fragments/digitalForm.graphql.unit.spec.js
- src/site/stages/build/drupal/static-data-files/digitalForm/tests/fragments/page.graphql.unit.spec.js
- src/site/stages/build/drupal/static-data-files/digitalForm/tests/fragments/textInput.graphql.unit.spec.js
- src/site/stages/build/drupal/static-data-files/digitalForm/tests/postProcessDigitalForm.unit.spec.js
- src/site/stages/build/drupal/static-data-files/digitalForm/tests/utils.unit.spec.js
- src/site/stages/build/drupal/static-data-files/digitalForm/utils.js
- Updates the GraphQL query to fetch the proper fields for Custom Step Paragraph entities.
- Normalizes fields for Custom Steps as well as their pages and the Text Input component.
```json
{
"id": 172736,
"type": "digital_form_custom_step",
"chapterTitle": "My custom step",
"pages": [
{
"bodyText": "My custom body text",
"components": [
{
"hint": "This is optional hint text",
"label": "My custom text input",
"required": true,
"type": "digital_form_text_input"
}
],
"pageTitle": "My custom page"
},
{
"bodyText": "With additonal body text",
"components": [
{
"hint": null,
"label": "A text input with no hint text",
"required": true,
"type": "digital_form_text_input"
},
{
"hint": "This text input is not required",
"label": "An optional text input",
"required": false,
"type": …
```
> VATEAM-101161: Normalize Custom Step with pages and components

- package.json
- src/site/tests/home/custom-elements.cypress.spec.js
- yarn.lock
- Updating web-components package
- None
N/A
Updates DST web components across the site.
> 2-27-25 Updating web-components package

- src/site/filters/liquid.js
- src/site/filters/liquid.unit.spec.js
- src/site/includes/metatags.drupal.liquid
Add hardcoded metadata description to Policies page. This involved writing a liquid filter to catch URLs ending with `/policies` and return a hardcoded description for those URLs. This is flexible enough to be used for other page paths as well.
No pages other than Policies pages should be affected.
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/20502
`/minneapolis-health-care/policies`
Regression check - homepage
Regression check - `/charleston-health-care/stories/vas-dr-ilana-stol-tapped-to-lead-the-charge-in-shaping-national-aging-policies/`
> VACMS-20502 Add hardcoded metadata to Policies pages

- src/applications/registry.json
- [] No, I'm not changing any `entryName`s (skip to Summary and delete the rest of this section)
If you are:
2. **Changing an entryName**: First search [vets-website](https://github.com/department-of-veterans-affairs/vets-website/) for references to this `entryName` that are _not_ in the app folder (particularly in `src/applications/static-pages/static-pages-entry.js` and …
> 102497 Update supply reordering app URL

- src/site/layouts/landing_page.drupal.liquid
The Ask VA widget name was not updated for benefit hub landing pages, resulting in the "Message us" area in the sidebar being blank because the widget was missing.
Related Slack thread: https://dsva.slack.com/archives/C03LFSPGV16/p1741972056662109
I updated the widget name, and the widget showed up. I also verified this is the only spot in the content-build code where this widget appears.
> Update Ask VA widget name

- src/site/stages/build/drupal/static-data-files/digitalForm/chapters.js
- src/site/stages/build/drupal/static-data-files/digitalForm/fragments/checkbox.graphql
- src/site/stages/build/drupal/static-data-files/digitalForm/fragments/date.graphql
- src/site/stages/build/drupal/static-data-files/digitalForm/fragments/page.graphql.js
- src/site/stages/build/drupal/static-data-files/digitalForm/fragments/radioButton.graphql
- src/site/stages/build/drupal/static-data-files/digitalForm/fragments/responseOption.graphql
- src/site/stages/build/drupal/static-data-files/digitalForm/fragments/textArea.graphql
- src/site/stages/build/drupal/static-data-files/digitalForm/tests/chapters.unit.spec.js
- src/site/stages/build/drupal/static-data-files/digitalForm/tests/fragments/checkbox.graphql.unit.spec.js
- src/site/stages/build/drupal/static-data-files/digitalForm/tests/fragments/date.graphql.unit.spec.js
- src/site/stages/build/drupal/static-data-files/digitalForm/tests/fragments/page.graphql.unit.spec.js
- src/site/stages/build/drupal/static-data-files/digitalForm/tests/fragments/radioButton.graphql.unit.spec.js
- src/site/stages/build/drupal/static-data-files/digitalForm/tests/fragments/responseOption.graphql.unit.spec.js
- src/site/stages/build/drupal/static-data-files/digitalForm/tests/fragments/textArea.graphql.unit.spec.js
- Updates the GraphQL query to fetch proper fields for all Custom Step components.
- Normalizes fields for all Custom Step components.
```json
{
"id": "172735",
"pageTitle": "A Custom Step page",
"bodyText": "With additional body text",
"components": [
{
"hint": "Optional hint text",
"id": "172738",
"label": "A text input",
"required": true,
"type": "digital_form_text_input"
},
{
"hint": null,
"id": "172747",
"label": "Custom text area",
"required": false,
"type": "digital_form_text_area"
},
{
"hint": null,
"id": "172741",
"label": "My custom date component",
"required": false,
"type": "digital_form_date_component",
"dateFormat": "month_year"
},
{
"hint": "This date component includes the day as well as the month and the year.",
"id": "172748",
"label": "Date with Day",
"required": true, …
```
> VATEAM-101164/101174/101167/101171: Normalize Custom Step components

- src/applications/registry.json
If you are:
2. **Changing an entryName**: First search [vets-website](https://github.com/department-of-veterans-affairs/vets-website/) for references to …
> [VA-IIR 1426] create entry for new version of VR&E form

- src/site/includes/datadog_rum/family-caregiver-benefit-hub.html
- src/site/includes/header.html
- src/site/layouts/page.drupal.liquid
Allows Datadog RUM for family caregiver rum on prod.
This pull request includes updates to the `src/site/includes` directory, focusing on the Datadog configuration and feature flag usage. The most important changes include specifying a version number for Datadog, adjusting the session replay sample rate, and modifying the feature flag condition for including the Datadog script.
Updates to Datadog configuration:
* [`src/site/includes/datadog_rum/family-caregiver-benefit-hub.html`](diffhunk://#diff-e07ef0e796a90f9290a5909d9cc5162bc106eba09f1fa6e6fac896d934cff0 …
> VACMS-15636 family caregiver rum

- src/applications/registry.json
If you are:
- searched, no references
Removes non-functional app that was created 5 years ago
Related vets-website PR: https://github.com/department-of-veterans-affairs/vets-website/pull/35340
> Remove unused efolders app

- src/applications/registry.json
- src/site/stages/build/drupal/static-data-files/digitalForm/fragments/digitalForm.graphql.js
- src/site/stages/build/drupal/static-data-files/digitalForm/postProcessDigitalForm.js
- src/site/stages/build/drupal/static-data-files/digitalForm/tests/fixtures/queryResult.json
- src/site/stages/build/drupal/static-data-files/digitalForm/tests/fragments/digitalForm.graphql.unit.spec.js
- src/site/stages/build/drupal/static-data-files/digitalForm/tests/postProcessDigitalForm.unit.spec.js
Added the plain language header to the digital form graphql fragment and relevant test files.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/104665
https://github.com/department-of-veterans-affairs/va.gov-team/issues/105059
```
yarn test:unit src/site/stages/build/drupal/static-data-files/digitalForm/**/*.spec.js
yarn run v1.19.1
$ node ./script/run-unit-test.js src/site/stages/build/drupal/static-data-files/digitalForm/tests/chapters.unit.spec.js src/site/stages/build/drupal/static-data-files/digitalForm/tests/fragments/address.graphql.unit.spec.js src/site/stages/build/drupal/static-data-files/digitalForm/tests/fragments/checkbox.graphql.unit.spec.js src/site/stages/build/drupal/static-data-files/digitalForm/tests/fragments/customStep.graphql.unit.spec.js …
```
> Add plain language header field to digital form graphql fragment

- src/site/stages/build/drupal/static-data-files/digitalForm/fragments/digitalForm.graphql.js
- src/site/stages/build/drupal/static-data-files/digitalForm/postProcessDigitalForm.js
- src/site/stages/build/drupal/static-data-files/digitalForm/tests/fixtures/queryResult.json
- src/site/stages/build/drupal/static-data-files/digitalForm/tests/fragments/digitalForm.graphql.unit.spec.js
- src/site/stages/build/drupal/static-data-files/digitalForm/tests/postProcessDigitalForm.unit.spec.js
- Updates the GraphQL query to fetch the following fields for the Introduction Page:
- Intro Paragraph
- "What to Know" bullet points
- Normalizes those fields for the JSON KISS file.
```json
[
{
"cmsId": 76353,
"formId": "21-4140",
"introParagraph": "This is the paragraph that will appear on the Introduction Page.",
"moderationState": "draft",
"title": "Employment Questionnaire",
"ombInfo": {
"expDate": "8/31/2027",
"ombNumber": "2900-0079",
"resBurden": 5
},
"whatToKnowBullets": [
"Adding test bullets",
"A second bullet",
"Maybe even a third bullet"
],
"chapters": [ ... ]
}
]
```
- department-of-veterans-affairs/va.gov-team#99169
- New/updated unit tests for the new and updated GraphQL fragments and the Digital Form post processor
- Pulled local Drupal data and confirmed the resulting …
> VATEAM-99169: Normalize Introduction Page fields

- src/site/layouts/event.drupal.liquid
- src/site/layouts/event_listing.drupal.liquid
This just adds a comment at the top of the files for Event and Event Listing layouts. Both of these content types are built using Next Build now, so changes to these templates won't affect production.
Relates to https://github.com/department-of-veterans-affairs/va.gov-cms/issues/20566
Relates to https://github.com/department-of-veterans-affairs/va.gov-cms/issues/20565
> Deprecate events and event listings

- src/site/includes/header.html
This PR adds a [preconnect hint](https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Attributes/rel/preconnect) for the vets-api URL for each environment. This should improve application load times at the margin, as most apps need to fetch at least the user & feature toggles endpoints before rendering. Downsides are unlikely since this is a separate origin and won't block TCP connection slots for the revproxy and S3 origins.
> add preconnect links for API urls

- script/install-repos.sh
Modified the install_repos.sh script to make 'treeless' rather than shallow clones of support repos. 'treeless' clones retain commit information without downloading the file contents, and will download file contents as needed (i.e. when checking a branch out). Shallow clones lose all history and therefore all branch information.
These support repos are used by CMS's review environments to build content-build within those environments. Moving to treeless checkouts will give us proper access to git branch history. No other process or repo calls this script.
This also removes cloning of next-build from this command. This dates from a development path that was abandoned. 
The following shows size difference for the treeless clone relative to a full clone or a shallow clone. Treeless clones do …
> Shift from shallow to treeless git clones of support repos.

- .github/workflows/continuous-integration.yml
- src/site/constants/brokenLinkIgnorePatterns.js
- src/site/layouts/news_story.drupal.liquid
- src/site/stages/build/drupal/graphql/CountEntityTypes.graphql.js
- src/site/stages/build/drupal/graphql/GetAllPages.graphql.js
- src/site/stages/build/drupal/individual-queries.js
Removes news_story from graphQL queries and adds comment on template.
This pull request removes support for "news_story" content types and updates related configurations, templates, and queries. Additionally, it introduces a new ignore pattern for stories in the broken link checker.
* [`src/site/stages/build/drupal/graphql/CountEntityTypes.graphql.js`](diffhunk://#diff-3365de6921597a2845b5e8683c845b2511685389aa35545bbbbe8024a6e26ad2L44-L53): Removed the query for counting "news_story" nodes.
* [`src/site/stages/build/drupal/graphql/GetAllPages.graphql.js`](diffhunk://#diff-28a6b9f0b78255b19344de34218b668f023e6e1cb87de132aae0a4ffa250d00dL114-L117): Removed the fragment for "newsStoryPage" from the list of GraphQL queries.
* [`src/site/stages/build/drupal/individual-queries.js`](diffhunk://# …
> VACMS-21021: Deprecate news_story

- src/site/filters/liquid.js
Content release is failing because a taxonomy term's name is null unexpectedly.
It _shouldn't_ be null, but it apparently is.
- [Slack thread](https://dsva.slack.com/archives/C02VD909V08/p1750888588337609)
- [Build failure](https://github.com/department-of-veterans-affairs/content-build/actions/runs/15887911920/job/44804306982)
> Fix: Allow for null values

- src/site/constants/brokenLinkIgnorePatterns.js
- src/site/layouts/press_releases_listing.drupal.liquid
- src/site/stages/build/drupal/graphql/GetAllPages.graphql.js
- src/site/stages/build/drupal/individual-queries.js
- Removes the News Release/Press Release listings from the queries
This pull request focuses on deprecating the `pressReleasesListingPage` functionality and updating related files to remove references to it. Additionally, it refines the description of ignored patterns for broken links in the site constants file.
* [`src/site/layouts/press_releases_listing.drupal.liquid`](diffhunk://#diff-a30fa8216e16006beebecb92aa9a21a2f712ce76754278845174997111f47025R2-R5): Added comments indicating that this template is no longer used for production content and advising to make changes in the Next Build environment.
* [`src/site/stages/build/drupal/graphql/GetAllPages.graphql.js`](diffhunk://#diff-28a6b9f0b78255b19344de34218b668f023e6e1cb87de132aae0a4ffa250d00dL116): Removed the …
> VACMS-21015: Excludes press release listings

- .github/workflows/continuous-integration.yml
- Change has been made to ensure that only one build of the main branch can be done at a time, in order to reduce the amount of times the CI Workflow runs. 
- Solution will be to set the spec.concurrency tag on the CI Workflow to 'cancel-in-progress: true' so that only one instance is being run and if others are run, the most recent will be run with the older ones cancelled.
- This fix would be maintained by DevOps
- [Ticket here](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/21477)
If you are:
1. **Deleting an entryName**: First search [vets-website](https://github.com/department-of-veterans-affairs/vets-website/) for references to this `entryName` that are _not_ in the app folder (particularly in …
> Forcing concurrency on main branch

- src/applications/registry.json
- We've confirmed with UX that we want to update the app name for Appointments tool pages under `/my-health/appointments`, see linked issue with discussion details.
- We need to coordinate the changes with those in vets-website [here](https://github.com/department-of-veterans-affairs/vets-website/pull/37629)
- Appointments FE Team
- This is not behind a flipper
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/113645
- I'm not sure how I would test this change so I'm open to suggestions
N/A
Appointments
> Update name for the Appointments tool

- Dockerfile
- _The Debian repo used by our Dockerfile has been archived.  Any branch of content-build without this fix will now show a failure with the Jenkins job._
- _This fix uses the same logic that resolved the problem in `vets-website`.  It simply points Jenkins to Debian's archives where the needed code now lives._
- _Link to support ticket where this issue was reported_
[Platform Support Ticket](https://dsva.slack.com/archives/CBU0KDSB1/p1752768055755399)
- _This same logic fixed the problem for `vets-website` 24 hours ago.  No issues have been reported._
- _This fix corrected the job failure in a VFS team PR's branch._
This is all CI, no site impact to be had.
If there is a better solution out there, I'd be happy to manage …
> Fix added to Dockerfile for the same problem occurring in vets-website CI

- .github/workflows/continuous-integration.yml
Reverts department-of-veterans-affairs/content-build#2586
The previous setup allows for CI to run against multiple branches at once, and we do need that. See discussion: https://dsva.slack.com/archives/CT4GZBM8F/p1753201673056799
> Revert "Forcing concurrency on main branch"

- src/applications/registry.json
- Remove SM Pilot app from registry.json. Note the app has already been deleted and a redirect is in place.
- Team: MHV on VA.gov
https://github.com/department-of-veterans-affairs/va.gov-team/issues/114617
N/A
N/A
MHV SM App
> Remove SM Pilot app from registry.json

- src/applications/registry.json
> Update root URL based on C/IA recommendations
> Changes include all these URLs:
> - `/manage-dependents/add-remove-form-21-686c` (v1)
> - `/manage-dependents/add-remove-form-21-686c-674` (v2)
> - `/view-change-dependents/view`
> - `/view-change-dependents/verify-dependents-form-21-0538`
>
> [Related Slack thread](https://dsva.slack.com/archives/C05NEL4DKMX/p1748884678144449) and [this slack thread about the additional URLs](https://dsva.slack.com/archives/C0547Q0K0LF/p1749566317444999)
> NOTE: This PR is tied to https://github.com/department-of-veterans-affairs/vets-website/pull/38407 - maybe adding 4 temp manifest.json files will allow having apps render at both the new and old URL, so there won't be any downtime? Will get …
> DMT | Add temp apps using new root URL for multiple apps

- src/applications/registry.json
- Added new registry entry for the 21-2680 House Bound Status application to support the development and deployment of a new form application
- This establishes the application's routing configuration, product ID, and template settings in the content-build registry
department-of-veterans-affairs/va.gov-team#
department-of-veterans-affairs/va.gov-team#
- [init(21-2680): Add Application for Examination for Housebound Status or Permanent Need for Regular Aid](https://github.com/department-of-veterans-affairs/vets-website/pull/38889)
- The old behavior was that the 21-2680 House Bound Status application was not registered in the system
- …
> init(21-2680): Add 21-2680 House Bound Status
