department-of-veterans-affairs/content-build

Jenkinsfile, jenkins/common.groovy, script/build.sh, src/site/stages/build/index.js
This PR does the following:
- Updates some references to `vets-website` with `content-build`
- Comments out code related to the Webpack build
- Comments out two of the three buildtypes
- Comments out Jenkins pipeline stages that aren't necessary right now
=> Configure basic Jenkins pipeline

package.json, yarn.lock
There is a `High severity` security vulnerability in the `content-build` repo, `axios`. Some of the packages that use this dependency do not have them upgraded to the required versions. Therefore, they have been added as package resolutions
Issue attached [18193](https://github.com/department-of-veterans-affairs/va.gov-team/issues/18193)
[vulnerability link](https://github.com/department-of-veterans-affairs/content-build/security/dependabot)
Locally
=> Add axios to resolutions

Jenkinsfile, jenkins/common.groovy
Now that the content build deploy is merged into the devops repo we need to test it out. I believe the revproxy probably needs to be updated as well
=> Uncommented dev deploy from jenkinsfile

jenkins/common.groovy, src/site/stages/prearchive/helpers.js, src/site/stages/prearchive/link-assets-to-bucket.js, src/site/stages/prearchive/tests/helpers.spec.js
Replicating this PR from vets-website: https://github.com/department-of-veterans-affairs/vets-website/pull/16276
=> refactor: refactor linkAssetsToBucket to use Cheerio

Jenkinsfile, Jenkinsfile.integration, jenkins/common.groovy
Matching vets-website behavior
=> Moving accessibility tests into a scheduled job to match vets-website

Jenkinsfile
Update runDeploy to content-build-staging to match file name in Devops repo
=> Update runDeploy to content-build-staging

package.json, script/install-repos.sh
Preemptively adding vets-website into the install repos script per request.
https://github.com/department-of-veterans-affairs/vets-website/pull/16486
=> Added vets-website into repo install script 

package.json
Review instances hook into this command, just syncing it with vets-website
=> [content-build] added http command for Review instances

package.json, yarn.lock
This PR resolves the `netmask` security [issue](https://github.com/department-of-veterans-affairs/content-build/security/dependabot/yarn.lock/netmask/open).
=> Resolve netmask vulnerability

Jenkinsfile.integration
=> updated daily a11y build command

composer.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/department-of-veterans-affairs/content-build/78)
=> Update Composer package to new name for content build separation

Jenkinsfile, config/nightwatch.docker-compose.js, jenkins/common.groovy
This PR updates the slack notification for `content-build`.
It'll need to be merged once the content separation has been launched.
This is a during `Launch` item from the [launch checklist](https://github.com/department-of-veterans-affairs/va.gov-team/issues/22451) for content-build separation
=> [release] - Enable slack for content-build

package.json, yarn.lock
This PR resolves the security vulnerability with the dependency `merge`.
=> Resolve lock file

src/site/layouts/tests/vamc/location_home.cypress.spec.js
Add the missing `location_home.cypress.spec.js` test to the repo. Stubbing the requests needed to be updated to use `cy.intercept()` to get the tests working.
=> Add location_home.cypress.spec.js test

src/site/stages/build/plugins/download-assets.js
Should exclude broken files from download
=> exclude file downloads from certain paths

script/preview.js
This PR updates the URL for fetching `headerFooter.json` in the preview server script.
=> Update url for headerFooter in preview server script

src/site/layouts/person_profile.drupal.liquid
Resolves https://github.com/department-of-veterans-affairs/va.gov-team/issues/24177
=> Fix quotes in sidebar data on person_profile pages.

src/site/filters/liquid.js, src/site/filters/liquid.unit.spec.js, src/site/includes/vet_center_health_services.liquid, src/site/layouts/tests/vet_center/fixtures/featuredContentData.json, src/site/layouts/tests/vet_center/fixtures/vet_center_escanaba_data.json, src/site/layouts/vet_center.drupal.liquid, src/site/paragraphs/q_a.accordion_panel.drupal.liquid, src/site/paragraphs/q_a.collapsible_panel.drupal.liquid
COMMIT SYNC FROM: https://github.com/department-of-veterans-affairs/vets-website/pull/17099
@brangi 
* Vet center - finalize centralized content
* Display fieldCcVetCenterFaqs
* minor
* fix
* fix prettier issue
* safty checks
* add some more testing
* fixes unit tests
* Update src/site/layouts/vet_center.drupal.liquid
Co-authored-by: Michael Pelz-Sherman <mpelzsherman@gmail.com>
* fixes
* rm unncessary check
* more unit tests
* fix
* cleanup
* fix heading id
Co-authored-by: Gibran Rodriguez <grodriguez@governmentcio.com>
Co-authored-by: Michael Pelz-Sherman <mpelzsherman@gmail.com>
Signed-off-by: Tim Wright <timwright12@gmail.com>
=> Vet center - finalize centralized content (#17099)

src/applications/registry.json
Breadcrumb update to go with https://github.com/department-of-veterans-affairs/vets-website/pull/17140
**Note!** Breadcrumb changes are made in vets-website.../registry.json. They are also made in content-build../registry.json.
Browser 👀
=> updates for kmi walk-in

package.json, yarn.lock
Update `chromedriver` to 90.0.0 to match current version of chrome.
=> Update chromedriver to 90.0.0

src/site/layouts/campaign_landing_page.drupal.liquid
This PR removes the top padding.
N/A
=> Remove top padding

src/applications/registry.json
This pull request updates the COE application path in registry.json
=> update coe path

src/site/layouts/campaign_landing_page.drupal.liquid, src/site/stages/build/plugins/create-environment-filter.js
This PR removes the feature flag and the passphrase prompt for CLP pages so we can publish https://www.va.gov/initiatives/veteran-trust-in-va.
Todo!
N/A
=> Launch Campaign Landing Page template

config/nightwatch.docker-compose.js
Commenting this out to try and troubleshooting selenium failures
=> comment out parallel nightwatch

jenkins/common.groovy
Updated the slack message with Jenkins URL
=> Added slack message for daily a11y tests

src/site/includes/image_and_static_map.liquid, src/site/includes/vet_center_address_phone_image.liquid, src/site/layouts/vet_center.drupal.liquid, src/site/layouts/vet_center_locations_list.drupal.liquid, src/site/stages/build/plugins/modify-dom/add-id-to-subheadings.js
resolves - https://github.com/department-of-veterans-affairs/va.gov-team/issues/23889
=> Add data layer for Vet centers

src/site/stages/build/drupal/menus.js
Per [Slack](https://dsva.slack.com/archives/C01512KN35G/p1620915961156200) conversation, having a bit more descriptive error message can help devs and what to try out.
=> More descriptive error message

src/site/includes/vet_center_address_phone_image.liquid
Resolves 
https://github.com/department-of-veterans-affairs/va.gov-team/issues/22728
=> Vet center css fixes

script/preview.js, src/site/README.md, src/site/layouts/leadership_listing.drupal.liquid, src/site/layouts/tests/leadership_listing_page/fixtures/data.json, src/site/layouts/tests/leadership_listing_page/leadership_listing_page.unit.spec.js, src/site/stages/build/drupal/graphql/GetLatestPageById.graphql.js, src/site/stages/build/drupal/graphql/leadershipListingPage.graphql.js, src/site/teasers/bio.drupal.liquid, src/site/teasers/tests/bio.unit.spec.js, src/site/teasers/tests/fixtures/bio_data.json
Resolves https://github.com/department-of-veterans-affairs/va.gov-team/issues/24708
=> Don't render unpublished bios on leadership_listing.drupal.liquid

src/site/components/banner_alerts.drupal.liquid, src/site/components/fullwidth_banner_alerts.drupal.liquid, src/site/includes/alerts.drupal.liquid
Reported a11y issues with improper aria-label usage on these elements
=> Fixed improper aria-label usage

package.json, yarn.lock
Syncing dependency from vets-website https://github.com/department-of-veterans-affairs/vets-website/pull/17368
=> Added dotenv dependency to content-build

src/site/includes/pagination.drupal.liquid, src/site/layouts/support_resources_article_listing.drupal.liquid
Reverts department-of-veterans-affairs/content-build#179
=> Revert "Ensure pagination does not show when only 1 page"

src/applications/registry.json
Adding the registry.json entry for the new check-in experience. 
- none? 
- [Spike](https://github.com/department-of-veterans-affairs/va.gov-team/issues/25214)
- [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/product-outline.md)
=> Health care checkin added app

.github/workflows/continuous-integration.yml, script/github-actions/check-broken-links.js, src/site/stages/build/plugins/modify-dom/check-broken-links/index.js
As part of ongoing migration to GitHub, following PR addresses the following:
- Create build for respective envs [vagov, vagovstaging, vagovprod]
- Checks if broken links are detected
- Notify channel based on severity
Reference to ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/24013
- Tested against github-actions
- Tested against vsp-github-action repo for slack bot
- Verification that communication between slack channel and bot are displaying message
=> Copy build from Jenkins to Github Action

src/site/assets/robots.txt
Resolves https://github.com/department-of-veterans-affairs/va.gov-team/issues/24985
=> A few edits to robots.txt

src/site/includes/vet_center_featured_content.liquid
Resolves https://github.com/department-of-veterans-affairs/va.gov-team/issues/25019
=> Make "In the spotlight" links H3's for a11y

src/site/layouts/vet_center.drupal.liquid
Partially resolves 25172. Remaining changes will be done in vets-website.
=> Move Other Locations below Hours, Clean up formatting

.gitignore, src/site/stages/build/options.js, src/site/stages/build/plugins/download-drupal-assets.js
Reverts department-of-veterans-affairs/content-build#205
…until we wrap the changes in an environment-defense clause.
=> Revert "Local builds do not re-download cached assets "

src/site/layouts/campaign_landing_page.drupal.liquid
This PR fixes a broken link on CLPs.
=> Add conditional rendering for see more stories button

src/site/includes/vet_centers/address_phone_image.liquid, src/site/layouts/vet_center.drupal.liquid
Resolves https://github.com/department-of-veterans-affairs/va.gov-team/issues/25006
=> Add more info to directions links

src/site/includes/vet_centers/address_phone_image.liquid, src/site/layouts/vet_center.drupal.liquid, src/site/stages/build/plugins/modify-dom/update-external-links.js
Resolves https://github.com/department-of-veterans-affairs/va.gov-team/issues/25006
=> Vet Centers - keep directions links in same tab

.github/CODEOWNERS, src/site/teasers/event_featured.drupal.liquid
Resolves https://github.com/department-of-veterans-affairs/va.gov-team/issues/25781
=> Show date/time data on featured events

src/site/layouts/vet_center.drupal.liquid
Resolves - https://github.com/department-of-veterans-affairs/va.gov-team/issues/24998
=> Fix - On this page navigation should have a unique accessible label

src/site/stages/build/plugins/create-environment-filter.js
This reverts commit 458a11c624d4b383edc631ea0abac9da410eb4b5.
=> Revert "Update pages to be omitted from production"

src/site/stages/build/drupal/graphql/facilities-fragments/healthCareLocalFacility.node.graphql.js
resolves - https://github.com/department-of-veterans-affairs/va.gov-team/issues/24987
=> Fix - Not all locations are included on the VAMC Locations page

src/site/includes/pagination.drupal.liquid, src/site/layouts/support_resources_article_listing.drupal.liquid
Reverts department-of-veterans-affairs/content-build#241
=> Revert "Pagination template fix"

src/site/filters/liquid.js
Resolves https://github.com/department-of-veterans-affairs/va.gov-team/issues/24700
=> Support normalized dynamic wysiwyg content

src/site/layouts/va_form.drupal.liquid, src/site/stages/build/drupal/graphql/vaFormPage.graphql.js
https://github.com/department-of-veterans-affairs/va.gov-team/issues/24282
Reskin'd the Forms Detail page!
Spun up preview server http://localhost:3002/preview?nodeId=5776
=> DT-24282 - VA_FORM - Detail pages UI reskin

src/site/includes/how-do-you-rate.drupal.liquid
**Slack:** https://dsva.slack.com/archives/C52CL1PKQ/p1623848551170700?thread_ts=1623695538.144000&cid=C52CL1PKQ
This PR promotes the how do you rate template to production.
=> Bump how do you rate to prod

src/site/includes/facilityListing.drupal.liquid, src/site/includes/tests/facilityListing.drupal.unit.spec.js, src/site/includes/tests/fixtures/facilityListingData.json, src/site/layouts/locations_listing.drupal.liquid, src/site/stages/build/drupal/graphql/GetLatestPageById.graphql.js, src/site/stages/build/drupal/graphql/facilities-fragments/healthCareLocalFacility.node.graphql.js
Resolves https://github.com/department-of-veterans-affairs/va.gov-team/issues/25479
Also makes locations pages previewable - see https://github.com/department-of-veterans-affairs/va.gov-team/issues/25940.
Developers: Use http://localhost:3002/preview?nodeId=6212 to preview Cheyenne.
=> Display Mobile clinics in a separate section on VAMC locations page

.github/workflows/daily-accessibility-scan.yml
Updating the slack notifications for the daily accessibility scan so it points to the real channel as we're ready to soft launch.
=> Updated slack channel ID for the daily accessibility scan

src/site/paragraphs/wysiwyg.drupal.liquid
Resolves https://github.com/department-of-veterans-affairs/va.gov-team/issues/26283
=> Adds support for dynamic fieldWysiwyg content as single-item-arrays or objects

src/site/facilities/health_service.drupal.liquid
Resolves https://github.com/department-of-veterans-affairs/va.gov-team/issues/26277
=> Omit unpublished locations in health service accordions

src/site/stages/build/drupal/page.js
Looks like a find-and-replace left a little bit of cruft behind.
=> Removes an unnecessary mapping operation.

src/applications/registry.json
adds medical copays to registry.json
=> 26205: [MCP] Add MCP to registry.json

src/site/layouts/campaign_landing_page.drupal.liquid
**Slack:** https://dsva.slack.com/archives/C52CL1PKQ/p1624397379238500
This PR fixes CLP stories images, which were previously not rendering.
=> Fix clp stories images

src/site/layouts/health_care_region_locations_page.drupal.liquid, src/site/layouts/locations_listing.drupal.liquid, src/site/layouts/tests/vamc/fixtures/health_care_region_page.json, src/site/layouts/tests/vamc/health_care_region_locations_page.unit.spec.js, src/site/layouts/tests/vamc/health_care_region_page.unit.spec.js
Sort all facilities by title, within each group.
=> Sort health clinic locations

script/preview.js, src/platform/utilities/data/clone.js, src/platform/utilities/data/cloneDeep.js, src/site/components/image.drupal.liquid, src/site/components/tests/image.drupal.unit.spec.js, src/site/includes/facilityListing.drupal.liquid, src/site/includes/tests/facilityListing.drupal.unit.spec.js, src/site/layouts/news_story.drupal.liquid, src/site/teasers/news_story.drupal.liquid, src/site/teasers/news_story_page.drupal.liquid, src/site/teasers/news_story_page_feature.drupal.liquid
Resolves https://github.com/department-of-veterans-affairs/va.gov-team/issues/25599
=> Make images optional on VAMC pages (Main, Location, News Stories)

src/site/components/tests/image.drupal.unit.spec.js
=> Fix test description for image.drupal.unit.spec.js

src/site/layouts/tests/vamc/health_care_region_locations_page.unit.spec.js
Broke a test somehow. This fixes it.
=> Fix AXE check unit test for health_care_region_locations_page

src/site/assets/robots.txt
resolves https://github.com/department-of-veterans-affairs/va.gov-team/issues/26242
=> Remove some dual-state VAMC's from robots.txt

src/site/layouts/campaign_landing_page.drupal.liquid
**Issue:** https://github.com/department-of-veterans-affairs/va.gov-team/issues/26001
This PR tweaks CLPs' styling based off [this Sketch file](https://www.sketch.com/s/df53b3cb-16dd-4969-acb4-0e4a233c4f9e/a/jgP9ROo).
Locally
=> Tweak CLP styling

src/site/stages/build/drupal/api.js, src/site/stages/build/drupal/graphql/GetAllPages.graphql.js, src/site/stages/build/drupal/queries.js
Reverts department-of-veterans-affairs/content-build#282
=> Revert "Remove useTomeSync"

src/site/components/image.drupal.liquid, src/site/components/tests/image.drupal.unit.spec.js, src/site/includes/image_and_static_map.liquid, src/site/includes/vet_centers/address_phone_image.liquid
Resolves https://github.com/department-of-veterans-affairs/va.gov-team/issues/25023
=> Remove links from Vetcenter locations images

src/site/layouts/campaign_landing_page.drupal.liquid
This PR resolves an a11y issue with the `Download (PDF)` links on CLPs.
=> Update alt with aria-label

src/site/includes/metatags.drupal.liquid, src/site/includes/metatags.liquid
This PR formats the metatags templates with proper indentation.
=> Formatting metatags template

src/site/components/fullwidth_banner_alerts.drupal.liquid, src/site/filters/liquid.js, src/site/filters/liquid.unit.spec.js, src/site/includes/vet_centers/featured_content.liquid, src/site/includes/vet_centers/services.liquid, src/site/layouts/event.drupal.liquid, src/site/layouts/vet_center.drupal.liquid, src/site/paragraphs/wysiwyg.drupal.liquid
Resolves https://github.com/department-of-veterans-affairs/va.gov-team/issues/21558
=> Vamc data layer alert links 21558

jenkins/common.groovy
Resolves https://github.com/department-of-veterans-affairs/va.gov-team/issues/16931
=> Removed findMissingQueryFlags() Slack alert

src/site/includes/vet_centers/address_phone_image.liquid, src/site/layouts/tests/vet_center/fixtures/vet_center_escanaba_data.json, src/site/layouts/tests/vet_center/vet_center.drupal.unit.spec.js, src/site/layouts/vet_center.drupal.liquid, src/site/stages/build/drupal/graphql/vetCenter.graphql.js, src/site/stages/build/drupal/graphql/vetCenterLocations.graphql.js
Resolves https://github.com/department-of-veterans-affairs/va.gov-team/issues/26544
=> Show address line 2 on Vet Center pages

src/site/assets/robots.txt
=> Removed disallow statements for 2 VAMCs

src/site/includes/vet_centers/address_phone_image.liquid, src/site/layouts/vet_center_locations_list.drupal.liquid
Resolves https://github.com/department-of-veterans-affairs/va.gov-team/issues/26689
=> Add mobile vet centers to locations page

src/site/filters/liquid.unit.spec.js, src/site/includes/vet_centers/services.liquid
Resolves https://github.com/department-of-veterans-affairs/va.gov-team/issues/26688
=> Format phone number links in Vet Center health service accordions

.github/workflows/daily-accessibility-scan.yml
This PR allows to create manual triggers. To create a manual trigger, go to Actions > Daily Accessibility Scan > `Run workflow`
N/A
Example of how dispatch workflow would look like
=> Add workflow dispatch for daily-accessibility

src/site/layouts/va_form.drupal.liquid
https://github.com/department-of-veterans-affairs/va.gov-team/issues/26826
We are going love with UI enhancements.
Spun up preview server to make sure the UI looks correct.
=> DT-26826 Removing flags on va form tamplate

.github/workflows/continuous-integration.yml, .github/workflows/daily-deploy-content-release.yml, .github/workflows/daily-deploy-production.yml, script/github-actions/check-broken-links.js
This PR changes the channel_id so it won't privately message me
N/A
N/A
=> Change channel_id for testing (continuous integration)

src/site/layouts/va_form.drupal.liquid
Fixing the things I broke LOL
Spun up local to make sure link was not there on preview server.
=> DT-26826 Find Form detail pages broken link fix 

src/site/filters/liquid.js, src/site/filters/liquid.unit.spec.js, src/site/includes/vet_centers/featured_content.liquid, src/site/layouts/tests/vet_center/vet_center.drupal.unit.spec.js
Resolved Issue linked below
Use Abilene VC to preview - http://localhost:3002/preview?nodeId=3886
Added template tests.
=> Vet center spotlight CTA 

.github/workflows/daily-accessibility-scan.yml
Pausing work on this since it's failing daily and notifying everyone
=> Removed the @here slack notification from a11y scan

src/site/includes/health_services_listing_services.liquid
Resolves Issue link below
To preview you can use - http://localhost:3002/preview?nodeId=7712
=> Sorted VAMC health services by name

src/applications/registry.json
- Update the URLs based on IA feedback
- [Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/26501)
- [Vets-Websites PR](https://github.com/department-of-veterans-affairs/vets-website/pull/17789)
- [IA Ticket](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/25561##)
=> updated url for Check in App 

src/site/filters/liquid.js, src/site/filters/liquid.unit.spec.js, src/site/includes/vet_centers/featured_content.liquid
To preview use Abilene - http://localhost:3002/preview?nodeId=3886
=> Fixed URL validation for featured content

src/site/stages/build/drupal/assets.js
Reverts department-of-veterans-affairs/content-build#332
=> Revert "Updated file path search for drupal assets"

Jenkinsfile, src/site/stages/build/drupal/assets.js
This reverts commit 64514f360def77366ef07b9a011264bb067c7364, to see if this will fix the issue with the review instance deploy links not showing up in Github.
=> Revert "Relocate review instance deployment in Jenkins"

src/site/includes/metatags.drupal.liquid
**Slack:** https://dsva.slack.com/archives/C52CL1PKQ/p1626113773008300?thread_ts=1626110204.499700&cid=C52CL1PKQ
This PR removes the explicit edge case written in the metatag template for the VAMC Pittsburgh, which was formatting the title like `VA Pittsburgh Health Care | Locations | Veterans Affairs` whereas it should have been formatted like: `Locations | VA Pittsburgh Health Care | Veterans Affairs` as per the [design system SEO documentation](https://design.va.gov/content-style-guide/seo).
```diff
Locations page:
- VA Albany health care
+ VA Albany Health Care | Veterans Affairs
```
```diff
Locations page:
- VA Alexandria health care
+ VA Alexandria Health Care | Veterans Affairs
```
```diff
Locations page:
- VA Altoona health care
+ VA Altoona Health Care | Veterans Affairs
``` …
=> Remove pittsburgh title edge case

.github/workflows/continuous-integration.yml
Test concurrency against master
=> Github Actions -- Test concurrency against master 

src/site/layouts/home.drupal.liquid, src/site/layouts/home.html, src/site/layouts/tests/home/fixtures/home.json, src/site/layouts/tests/home/home.unit.spec.js
fixes https://github.com/department-of-veterans-affairs/va.gov-team/issues/25823
Added `src/site/layouts/tests/home/home.unit.spec.js`
https://user-images.githubusercontent.com/3144003/125522809-c85c87c7-5346-4104-a426-b527e636deec.mov
Mobile:
https://user-images.githubusercontent.com/3144003/125674949-936389d7-df37-4d4a-a233-085118a2c7a6.mov
=> Move content id from top section to main

src/site/assets/robots.txt
=> Removed disallow statements for 4 VAMCs

src/site/layouts/health_care_local_facility.drupal.liquid, src/site/stages/build/drupal/graphql/facilities-fragments/healthCareSocialMedia.fields.graphql.js, src/site/stages/build/drupal/graphql/healthCareLocalFacilityPage.graphql.js, src/site/stages/build/drupal/graphql/healthCareRegionPage.graphql.js
=> Show social links on local facility pages

.eslintrc.js, script/eslint-plugin-va/index.js, script/eslint-plugin-va/package.json, script/eslint-plugin-va/rules/correct-apostrophe.js, yarn.lock
Migration from https://github.com/department-of-veterans-affairs/vets-website/pull/17902
=> Add typographical quote eslint rule 

.github/workflows/content-release.yml, .github/workflows/continuous-integration.yml, .github/workflows/daily-accessibility-scan.yml, .github/workflows/daily-deploy-production.yml
This PR adds ASG to self-hosted GHAs.
=> Add ASG to self-hosted GHAs

src/platform/testing/e2e/cypress/support/index.js
This PR fixes a script error seen in Cypress tests.
=> Fix Cypress script error on CI

src/platform/static-data/footer-links.json
Migrating this PR into content-build https://github.com/department-of-veterans-affairs/vets-website/pull/17060
=> [Footer] Fix for footer warning

.github/workflows/manual-review.yml
Duplicating similar changes from department-of-veterans-affairs/vets-website#17920.
=> Reduced duplicate PR workflow runs from edits and review requests.

src/site/assets/robots.txt
=> Removed disallow statements for 5 VAMCs

src/applications/registry.json
This pr updates the breadcrumb for view dependents
=> update view dependents breadcrumb

src/site/stages/build/plugins/create-sitemaps.js
This PR updates the last modified date in the sitemap to help with search results relevancy
manual testing
https://github.com/department-of-veterans-affairs/va.gov-team/issues/26726
=> update last mod date

src/site/layouts/health_care_region_page.drupal.liquid, src/site/layouts/tests/vamc/system_home.cypress.spec.js
Issue linked below
Example page to test - https://staging.va.gov/pittsburgh-health-care/
=> Added cypress test to VAMC system page image

src/site/filters/liquid.js, src/site/filters/liquid.unit.spec.js
Resolves https://github.com/department-of-veterans-affairs/va.gov-team/issues/27501
=> Wrap phone numbers with parentheses around the area code

src/site/facilities/health_service.drupal.liquid, src/site/facilities/tests/fixtures/healthServiceData.json, src/site/facilities/tests/health_service.drupal.unit.spec.js
Wrap phone numbers in VAMC accordions with links to make them clickable.
See https://github.com/department-of-veterans-affairs/va.gov-team/issues/27501
=> Wrap phone numbers in VAMC accordions

src/site/assets/robots.txt
Resolves https://github.com/department-of-veterans-affairs/va.gov-team/issues/28075
=> Remove some Disallow entries from robots.txt

src/site/filters/liquid.js, src/site/layouts/person_profile.drupal.liquid
=> Removed leadership url flag

package.json, src/site/includes/bioParagraph.drupal.liquid, src/site/includes/tests/bioParagraph.drupal.unit.spec.js, src/site/includes/tests/fixtures/bioParagraph.json, src/site/layouts/health_care_region_detail_page.drupal.liquid, src/site/stages/build/drupal/graphql/paragraph-fragments/staffProfile.paragraph.graphql.js
Resolves https://github.com/department-of-veterans-affairs/va.gov-team/issues/27755
=> Do not render unpublished staff profiles

src/site/assets/js/execute-axe-check.js, src/site/components/browse-by-audience.drupal.liquid, src/site/facilities/health_service.drupal.liquid, src/site/facilities/story_social_share.drupal.liquid, src/site/includes/benefit-hubs-links.drupal.liquid, src/site/includes/related-information.drupal.liquid, src/site/includes/social-share.drupal.liquid, src/site/layouts/basic_landing_page.drupal.liquid, src/site/layouts/campaign_landing_page.drupal.liquid, src/site/layouts/checklist.drupal.liquid, src/site/layouts/faq_multiple_q_a.drupal.liquid, src/site/layouts/health_care_local_facility.drupal.liquid, src/site/layouts/health_care_region_detail_page.drupal.liquid, src/site/layouts/health_services_listing.drupal.liquid, src/site/layouts/media_list_images.drupal.liquid, src/site/layouts/media_list_videos.drupal.liquid, src/site/layouts/page.drupal.liquid, src/site/layouts/press_release.drupal.liquid, src/site/layouts/support_resources_article_listing.drupal.liquid, src/site/layouts/support_resources_detail_page.drupal.liquid, src/site/layouts/va_form.drupal.liquid, src/site/layouts/vamc_operating_status_and_alerts.drupal.liquid, src/site/layouts/vamc_system_policies_page.drupal.liquid, src/site/layouts/vet_center.drupal.liquid, src/site/paragraphs/contact_information.drupal.liquid, src/site/paragraphs/lists_of_links.drupal.liquid, src/site/stages/build/plugins/inject-vale-linter.js
**Issue:** https://github.com/department-of-veterans-affairs/va.gov-team/issues/25005
This PR adds `role="list"` to all `ul` tags that have the class `usa-unstyled-list`.
https://github.com/department-of-veterans-affairs/content-build/pull/410
https://github.com/department-of-veterans-affairs/vets-website/pull/18082
=> Add role=list

.github/workflows/continuous-integration.yml
In an effort to reduce flakiness, adding retry to installation for build.
=> Github Actions (CI)  -- retry on install dependencies for build

src/applications/registry.json
Updated URLs and removed breadcrumbs settings for MCP following the pattern outlined in [IA Structure, URLs and Breadcrumbs](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/health-copays.md)
=> 28226: [MCP] update urls for medical copays

src/site/layouts/tests/vamc/commands.cypress.js, src/site/layouts/tests/vamc/location_detail.cypress.spec.js, src/site/layouts/tests/vamc/location_home.cypress.spec.js
Resolves https://github.com/department-of-veterans-affairs/va.gov-team/issues/28283
=> Add e2e test for VAMC locations page

src/site/assets/robots.txt, src/site/filters/liquid.unit.spec.js, src/site/layouts/page.drupal.liquid, src/site/layouts/va_form.drupal.liquid, src/site/paragraphs/linkTeaser.drupal.liquid
Resolves https://github.com/department-of-veterans-affairs/va.gov-team/issues/28076
=> Removed more systems from robots.txt

package.json, yarn.lock
=> Resolve path-parse

src/site/layouts/vamc_operating_status_and_alerts.drupal.liquid
Resolves https://github.com/department-of-veterans-affairs/va.gov-team/issues/27206
=> Use info icon for limited hours alert

package.json, yarn.lock
Remove an unused dependency. It's a diff tool that is no longer needed in this repo
Locally
=> Remove deep-diff dependency

.github/workflows/content-release.yml, .github/workflows/daily-deploy-production.yml, script/github-actions/validate-build-status.js
PR was recently committed and was failing the action due to syntax error. This PR replaces `with` --> `env`
[Run testing ENV output](https://github.com/department-of-veterans-affairs/content-build/runs/3373501868?check_suite_focus=true)
=> Github Actions (daily-deploy & content-release) -- Fix syntax error

src/site/assets/robots.txt
=> Updated disallow statements in robots.txt

src/site/components/banners.drupal.liquid, src/site/components/fullwidth_banner_alerts.drupal.liquid, src/site/filters/liquid.js, src/site/filters/liquid.unit.spec.js, src/site/includes/header.html, src/site/paragraphs/q_a.collapsible_panel.drupal.liquid, src/site/stages/build/drupal/graphql/GetAllPages.graphql.js, src/site/stages/build/drupal/graphql/banners.graphql.js, src/site/stages/build/drupal/home.js, src/site/stages/build/drupal/individual-queries.js, src/site/stages/build/drupal/page.js
**Slack:** https://dsva.slack.com/archives/C52CL1PKQ/p1628544653122200
**Issues:**
https://github.com/department-of-veterans-affairs/va.gov-team/issues/28612
https://github.com/department-of-veterans-affairs/va.gov-team/issues/28614
https://github.com/department-of-veterans-affairs/va.gov-team/issues/28611
https://github.com/department-of-veterans-affairs/va.gov-team/issues/28515
**Related PRs:**
https://github.com/department-of-veterans-affairs/content-build/pull/441
https://github.com/department-of-veterans-affairs/vets-website/pull/18316
This PR adds a new entity bundle called `banners` and supports them on all pages.
Locally, updated unit tests.
`Homepage`
`/claim-or-appeal-status/`
`Homepage`
`/claim-or-appeal-status/`
=> Add banners poc #28612 #28614 #28611 #28515

package.json, yarn.lock
Reverts department-of-veterans-affairs/content-build#443
=> Revert "Remove babel-core dependency"

src/site/facilities/facilities_events_toggle.drupal.liquid, src/site/filters/liquid.js, src/site/filters/liquid.unit.spec.js, src/site/layouts/event_listing.drupal.liquid, src/site/layouts/tests/event_listing/event_listing.unit.spec.js, src/site/layouts/tests/event_listing/fixtures/event-listing-data.json, src/site/stages/build/drupal/graphql/eventListingPage.graphql.js
Resolves https://github.com/department-of-veterans-affairs/va.gov-team/issues/27433
=> Resolve event listing page discrepancies between full build and preview

src/site/layouts/vet_center.drupal.liquid
=> Moved Other Locations section out of shared div

src/site/layouts/event_listing.drupal.liquid, src/site/layouts/tests/event_listing/event_listing.unit.spec.js, src/site/layouts/tests/event_listing/fixtures/event-listing-data-no-events.json
Resolves https://github.com/department-of-veterans-affairs/va.gov-team/issues/28252
=> Additional event listing page unit tests

src/site/assets/robots.txt
=> Removed entries from robots.txt

package.json
PR #491 , `package.json` was modified and committed on accident. This PR reverts it
=> Revert package.json -- add husky

.github/CODEOWNERS, src/site/stages/build/plugins/modify-dom/add-id-to-subheadings.js, src/site/stages/build/plugins/modify-dom/tests/add-id-to-subheadings.spec.js, src/site/stages/build/plugins/modify-dom/tests/fixtures/testSubheadingsNoH2.html
Resolves https://github.com/department-of-veterans-affairs/va.gov-team/issues/28249
=> Remove table-of-contents element from DOM if there are no jump links in the content

src/site/assets/robots.txt
Resolves https://github.com/department-of-veterans-affairs/va.gov-team/issues/29499
=> Restore delayed VAMC system names to robot.txt file

src/site/stages/build/drupal/graphql/navigation-fragments/facilitySidebar.nav.graphql.js
=> Fix chicago health care query

package.json, yarn.lock
This PR upgrades `libxmljs2` to the latest version.
=> Upgrade libxmljs2

.github/workflows/a11y.yml
Add `@here` to Cypress accessibility scan failure Slack notification
=> Add @here to Cypress accessibility scan failure Slack notification

.github/workflows/continuous-integration.yml
=> test cypress container

src/site/assets/robots.txt
Resolves https://github.com/department-of-veterans-affairs/va.gov-team/issues/29660
=> Remove Disallow erie-health-care from robots.txt

.github/workflows/continuous-integration.yml
The aim of this PR is to dockerize our Cypress Tests step of the CI workflow, to avoid any port conflicts or other issues down the line.
Successfully completed the CI workflow: https://github.com/department-of-veterans-affairs/content-build/actions/runs/1213447482
=> Try dockerized setup

src/site/assets/robots.txt
Per conversation with @davidconlon
=> Add comment about using trailing slashes to robots.txt

src/site/filters/liquid.js, src/site/filters/liquid.unit.spec.js, src/site/includes/vet_centers/nearby.liquid, src/site/layouts/vet_center_locations_list.drupal.liquid, src/site/stages/build/drupal/graphql/vetCenterLocations.graphql.js
These will be used by the nearbyVetCenter widget for deduping.
Related to https://github.com/department-of-veterans-affairs/va.gov-team/issues/27870
=> Add sattelite-vet-center ID's to vet-center-nearby widget stub

package.json, src/platform/testing/e2e/cypress/plugins/index.js, src/platform/testing/e2e/cypress/support/commands/axeCheck.js, yarn.lock
This PR improves the formatting of Cypress accessibility failure details.
Before:
After:
=> Improve formatting of Cypress accessibilty failure details

package.json, yarn.lock
=> Upgrade cli-table dependency

src/site/components/informational_alert.drupal.liquid, src/site/layouts/tests/vet_center/fixtures/vet_center_data.json, src/site/layouts/tests/vet_center/vet_center.drupal.unit.spec.js, src/site/layouts/vet_center.drupal.liquid
To test you can use Colorado Springs VC - `/colorado-springs-vet-center`
<details>
<summary>Screenshot of new call center info alert</summary>
</details>
=> Vet center call center informational alert

src/site/layouts/tests/find_forms/fixtures/va_form.json, src/site/layouts/tests/find_forms/va_form.unit.spec.js, src/site/layouts/va_form.drupal.liquid
Adding Template Test for Va Form Node
Well I ran it a bunch of times LOL
=> DT-29553 VA Form Template Test

package.json, yarn.lock
Ran unit tests locally and on CI
=> Upgrade chai to 4.3.4

src/site/layouts/tests/find_forms/va_form.unit.spec.js
https://github.com/department-of-veterans-affairs/va.gov-team/issues/29553
Iterating on template test
Ran template test
=> DT-29553 - Va Form template test update

src/site/components/banners.drupal.liquid, src/site/includes/header.html
**Issue:** https://github.com/department-of-veterans-affairs/va.gov-team/issues/29767
This PR promotes the banners template to production and removes the legacy homepage banner.
=> Promote banners to prod + remove legacy homepage banner

.github/CODEOWNERS
Updating this based on the current file structure
=> Cleaned up code owners

package.json, yarn.lock
Ran unit tests locally and on CI
=> Upgrade chai-dom to 1.10.0

package.json, yarn.lock
=> Upgrade chokidar to 3.5.2

package.json, yarn.lock
Local testing in Chrome and IE 11
=> Upgrade core-js to 3.17.3

.github/workflows/daily-deploy-production.yml
This PR addresses [ticket](department-of-veterans-affairs/va.gov-team#29578)
This PR adds a new option for `commit_sha` to be part of daily deploy via `workflow_dispatch` for rollback. The pipeline will remain the same
[Run using commit_sha](https://github.com/department-of-veterans-affairs/content-build/runs/3624540055?check_suite_focus=true)
=> Github Actions (daily-deploy) -- Rollback

package.json, yarn.lock
=> Upgrade diff2html to 3.4.11

src/site/layouts/basic_landing_page.drupal.liquid, src/site/layouts/checklist.drupal.liquid, src/site/layouts/faq_multiple_q_a.drupal.liquid, src/site/layouts/media_list_images.drupal.liquid, src/site/layouts/media_list_videos.drupal.liquid, src/site/layouts/q_a.drupal.liquid, src/site/layouts/step_by_step.drupal.liquid, src/site/layouts/support_resources_detail_page.drupal.liquid, src/site/paragraphs/action_link.drupal.liquid, src/site/paragraphs/button.drupal.liquid
**Issue:**
This PR updates the button links template to action links since it is only used by R&S pages.
--
=> Update links to action links for R&S

package.json, yarn.lock
Successful unit test runs locally and on CI
=> Upgrade enzyme-adapter-react-16 to 1.15.6

package.json, yarn.lock
Check for sentry events from dev/staging
=> Upgrade @sentry/browser to 6.13.1

package.json, yarn.lock
=> Upgrade lint-staged to 11.1.2

.github/workflows/content-release.yml, .github/workflows/continuous-integration.yml, Jenkinsfile, jenkins/common.groovy
This PR addresses the following tickets:
- Enable archive step. department-of-veterans-affairs/va.gov-team#29254
We are preparing to deprecate Jenkins. The first step is to rollout `dev`. This PR removes deploy and archive step in Jenkins for `vagovdev` and enables it in GHA.
=> Github Actions (CI) -- Remove dev from Jenkins pipeline

src/site/includes/vet_centers/featured_content.liquid, src/site/layouts/tests/vet_center/template/vet_center.drupal.unit.spec.js, src/site/layouts/vet_center.drupal.liquid
=> Update vet center styles to use VADS

package.json, yarn.lock
=> Upgrade regenerator-runtime to 0.13.9

package.json, yarn.lock
=> Upgrade semver to 7.3.5

src/site/assets/robots.txt
=> Removed disallow entries

package.json, yarn.lock
=> Upgrade webpack-dev-server to 3.11.2

.github/workflows/a11y.yml
This PR adds retries to `yarn install`s in the Cypress accessibility workflow on GitHub Actions and fixes dependency caching.
=> Add retries and fix caching for `yarn install`s in Cypress accessibility workflow

src/site/assets/robots.txt
Resolves https://github.com/department-of-veterans-affairs/va.gov-team/issues/30244
=> Remove some entries from robots.txt

.github/workflows/continuous-integration.yml
This PR adds mochawesome reports to content-build
=> Test out report

src/site/paragraphs/downloadable_file.drupal.liquid
This PR fixes an accessibility issue found in the daily accessibility scan.
Accessibility test passed locally.
=> Add role to icon in Download File template

src/site/layouts/va_form.drupal.liquid
This is predecessor to https://github.com/department-of-veterans-affairs/vets-website/pull/18990.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/30377
Developed locally in tandem with vets-website PR for the widget.
=> Changing ID to match refactor on vets-website

src/site/paragraphs/downloadable_file.drupal.liquid
=> Add missing quote to template

.github/workflows/continuous-integration.yml
=> Github Actions (CI) -- fix callback token from param store

.github/workflows/content-release.yml, .github/workflows/daily-deploy-production.yml
[Slack](https://dsva.slack.com/archives/CBU0KDSB1/p1634579672075600?thread_ts=1634336049.045700&cid=CBU0KDSB1)
Pointing all reference to `vagovdev` for daily deploy while still in testing
=> Github Actions (DD & CR) -- Change all ENV to point to dev

src/site/includes/top-nav.html
**Slack:** https://dsva.slack.com/archives/C52CL1PKQ/p1635196240106700
`<header>` needs to have `role="banner"`.
=> Add role="banner"

script/preview.js, src/site/stages/build/drupal/graphql/locationsOperatingStatus.graphql.js, src/site/stages/build/drupal/graphql/vamcOperatingStatusAndAlerts.graphql.js, src/site/stages/build/drupal/individual-queries.js, src/site/stages/build/drupal/metalsmith-drupal.js, src/site/stages/build/drupal/page.js
See https://github.com/department-of-veterans-affairs/va.gov-team/issues/30395
=> Populate operating status location info dynamically from health_care_local_facility nodes

package.json, yarn.lock
PR to upgrade `mochawesome` to its latest version.
=> Upgrade `mochawesome` to latest version

src/site/stages/build/drupal/page.js
Encountered an error while previewing content. This fixes the issue.
=> Guard against null errors when computing operating status data

src/site/layouts/tests/vet_center/template/fixtures/vet_center_data.json, src/site/layouts/tests/vet_center/template/vet_center.drupal.unit.spec.js, src/site/layouts/vet_center.drupal.liquid, src/site/stages/build/drupal/graphql/vetCenter.graphql.js
Resolved issue linked below
To test use - https://web-xzcrb121xmxquzas9jcd9p86dgwpkuam.demo.cms.va.gov/escanaba-vet-center/
=> Implement vet center official name field

src/applications/registry.json
[Original Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/17743)
Now that the search for representative app is getting further along we want to add it to staging so that stakeholders can see it.
=> Added search rep to registry

.github/workflows/a11y.yml
This PR modifies the daily accessibility scan to use `slackapi/slack-github-action` to send Slack notifications due to intermittent failures with `vsp-github-actions`.
=> Fix Slack notifications in GitHub Actions accessibility scan

composer.json
=> Use correct project name in Packagist composer.json

.github/workflows/a11y.yml, .github/workflows/content-release.yml, .github/workflows/daily-deploy-production.yml, jenkins/common.groovy, src/site/paragraphs/tests/fixtures/staff_profile.json
Rename cms url from cms-vets-website-branch-builds-lo9uhqj18nwixunsjadvjsynuni7kk1u.ci.cms.va.gov to cms-content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov
=> Change non-prod cms url

.github/workflows/content-release.yml, .github/workflows/daily-deploy-production.yml
Token missing to create release
See related [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/19333)
=> Github Actions (CR && DD) -- Add token to create release

.github/workflows/continuous-integration.yml, script/github-actions/check-broken-links.js
Notification are still not working as intended. Making a tiny modification
[Stackoverflow forum](https://stackoverflow.com/a/54287237)
[Slack](https://dsva.slack.com/archives/C0MQ281DJ/p1636569812174600) to cms-helpdesk
=> Github Action (CR) -- Slack notification

src/applications/registry.json
- Creating a new application for the pre-check-in experience. 
https://github.com/department-of-veterans-affairs/va.gov-team/issues/32533
=> added new Pre-check-in application

.github/workflows/content-release.yml, .github/workflows/daily-deploy-production.yml
Ops just confirmed and verified that `va_vsp_bot_github_token` has workflow permission. Removing temp token
Successful temp token. See [slack](https://dsva.slack.com/archives/CBU0KDSB1/p1636652423120200?thread_ts=1636645195.100300&cid=CBU0KDSB1) for confirmation on token
=> Github Actions -- Update token for schedule deploys

.github/workflows/content-release.yml, .github/workflows/daily-deploy-production.yml, .github/workflows/manual-deploy-dev-staging.yml
With latest changes available to workflow dispatch, changing content-release to be a dropdown rather than input to prevent mistype errors
=> Github Actions -- Update workflow_dispatch

.github/workflows/a11y.yml
This PR modifies the GitHub Actions workflow for the daily accessibility scan to handle canceled scans.
=> Add cancellation logic to daily accessibility scan

.github/workflows/content-release.yml, .github/workflows/daily-deploy-production.yml
Syntax error causing the flow to fail. This PR resolves it
=> Github Actions -- Syntax error fix

.github/workflows/a11y.yml
PR to remove an environment variable that is no longer used in the daily accessibility scan.
=> Remove unused environment variable from daily accessibility scan

.github/workflows/content-release.yml
=> Github Actions -- fix syntax error

.github/workflows/content-release.yml, .github/workflows/continuous-integration.yml, .github/workflows/daily-deploy-production.yml
PR addresses this [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/32656)
This PR is using a forked branch of on-demand runners and wrap around retries. If a retry is required, it will wait 5 seconds before attempting. See [snippet](https://github.com/oseasmoran73/ec2-github-runner/blob/main/src/index.js#L29-L46) here
=> Github Actions -- Attempt start-runner w/ retry

.github/workflows/content-release.yml
=> Github Actions -- Fix syntax

src/site/assets/robots.txt
Update robots.txt for VAMC rollout 12.1.2021
=> Update robots.txt for VAMC rollout 12.1.2021

.github/workflows/content-release.yml
See https://dsva.slack.com/archives/CU1E4CX9U/p1638290398215500
This should (hopefully) resolve the issues with https://dsva.slack.com/archives/CU1E4CX9U/p1638290398215500
=> Quote stuff per Brett's advice in Slack

.github/workflows/content-release.yml
=> Revert gha metrics

.github/workflows/content-release.yml, .github/workflows/continuous-integration.yml, .github/workflows/daily-deploy-production.yml
Per [slack](https://dsva.slack.com/archives/C0MQ281DJ/p1638374691417600?thread_ts=1638307543.398300&cid=C0MQ281DJ)
Adding more information to the callback URL for investigation
=> Add information to callback for debugging

src/applications/registry.json
enabled vagovprod for medical copays
department-of-veterans-affairs/va.gov-team#33492
=> 33492: [MCP] enable vagovprod for medical copays

src/site/assets/robots.txt
Only system remaining should be Lovell
=> Update robots.txt for VAMC upgrade roll-outs

src/site/filters/liquid.js, src/site/filters/liquid.unit.spec.js
**Issue:** https://github.com/department-of-veterans-affairs/va.gov-team/issues/33571
This PR resolves for a new edge case when deriving the embedded URL for youtube videos.
Modified unit tests to be more real-world.
=> Add test cases and resolve for new edge case

.github/workflows/daily-deploy-production.yml
=> Github Actions (CR) -- Fix syntax error for callback in deploy step

.github/workflows/content-release.yml
These changes were tested here: https://github.com/department-of-veterans-affairs/content-build/pull/820
=> Fix datadog metrics issues

package.json, yarn.lock
Quick PR to upgrade Cypress to its latest version.
=> Upgrade Cypress to `9.1.1`

.github/workflows/a11y.yml, .github/workflows/continuous-integration.yml
Quick PR to upgrade `slackapi/slack-github-action` and `mikepenz/action-junit-report` to their latest versions.
=> Update GitHub Actions to latest versions

src/applications/registry.json
Adds specially-adapted-housing application to registry.json
=> Add specially-adapted-housing to registry

src/site/includes/survey-tools.html
Resolves - https://github.com/department-of-veterans-affairs/va.gov-team/issues/33236
After verifying that the new survey gets triggered as expected in staging - https://github.com/department-of-veterans-affairs/content-build/pull/845/files , we can now add the same script tag so that we can trigger the new survey in production
=> Implement CSAT on VAMC pages - Prod

src/site/stages/build/drupal/graphql/nodeCampaignLandingPage.graphql.js
**Ticket:** https://github.com/department-of-veterans-affairs/va.gov-team/issues/34188
**Related PR:** https://github.com/department-of-veterans-affairs/content-build/pull/842/
**Slack:** https://dsva.slack.com/archives/C52CL1PKQ/p1639585002042300
Removes unused `fieldOwner` fields for CLPs.
N/A
=> Remove fieldOwner

.github/workflows/daily-deploy-production.yml
=> Fix syntax error for daily deploy

script/run-cypress-tests-docker.sh
PR to remove a script that is no longer being used on Jenkins.
=> Remove script used for Cypress tests on Jenkins

src/site/stages/build/drupal/graphql/navigation-fragments/menuLinks.nav.graphql.js, src/site/stages/build/drupal/menus.js
Currently the graphQL query to get menu links get all menu links in Drupal.  The corresponding build code only uses the links from the `header-megamenu` Drupal menu.  This changes adds a filter.
GraphQL response before: https://gist.github.com/indytechcook/4933a2ef14a2111f17ee11e085c35b18#file-current-api-response-json which include 21,694 lines.
GraphQL response after: https://gist.github.com/indytechcook/4933a2ef14a2111f17ee11e085c35b18#file-with-menu-filter-json with 2, 226 lines.
Build logs for this branch in tugboat:  https://main-zc3devt3l5euvendy495sxgjocxk7kev.demo.cms.va.gov/admin/content/deploy/logs
Here is the rendered front end: https://web-zc3devt3l5euvendy495sxgjocxk7kev.demo.cms.va.gov/
<details><summary>Here is the new GraphQL query result:</summary>
```
{
"data": { …
```
=> Filter GraphQL Menu links by Drupal menu `header-megamenu`

src/site/stages/build/drupal/graphql/navigation-fragments/menuLinks.nav.graphql.js
This is a follow up to https://github.com/department-of-veterans-affairs/content-build/pull/830.
Tugboat before:
Tugboat After;
=> Add sort direction to menu link query

src/site/filters/liquid.js
This is the solution for the following ticket.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/33740
=> BUG 33740 update Cerner links to match updated requirements.

src/site/facilities/service_address.drupal.liquid, src/site/paragraphs/service_location.drupal.liquid
See [VACMS #7339](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/7339).  Service location address does not render correctly based on "Use the facility's street address?" checkbox.
- When box is checked, address should not show; only show building/floor/etc.
- When box is unchecked, alternate address should show in addition to building/floor/etc.
https://web-lednohves2bfoiva4td2gvakfgvryyyd.demo.cms.va.gov/
See screenshots below.
https://web-lednohves2bfoiva4td2gvakfgvryyyd.demo.cms.va.gov/wilkes-barre-health-care/locations/wayne-county-va-clinic/
https://web-lednohves2bfoiva4td2gvakfgvryyyd.demo.cms.va.gov/wilkes-barre-health-care/locations/columbia-county-va-clinic/
https://web-lednohves2bfoiva4td2gvakfgvryyyd.demo.cms.va.gov/wilkes-barre-health-care/locations/columbi …
=> Fixes service location address to respect "Use the facility's street address?" checkbox

src/site/filters/liquid.js, src/site/filters/liquid.unit.spec.js, src/site/layouts/event.drupal.liquid, src/site/layouts/event_listing.drupal.liquid
**Issue:** https://github.com/department-of-veterans-affairs/va.gov-team/issues/32601
This PR adds the event detail v2 page design on non-prod environments.
=> Kelsonic 32601 event page

.github/workflows/a11y.yml
This PR refactors Slack notifications for the daily accessibility scan so that the logic for different outcomes is handled in different jobs. This simplifies the workflow and makes it easier to read.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/33791
=> Refactor GitHub Actions accessibility scan workflow

src/applications/registry.json
[Original Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/31344)
Since we are removing the veteran representative application we need to also remove the code for it from the `content-build` repo, this PR removes that code. This PR also accompanies [a PR](https://github.com/department-of-veterans-affairs/vets-website/pull/19777) for `vets-website`
=> Removed veteran representative code

package.json, yarn.lock
PR to upgrade Cypress to the latest version.
=> Upgrade Cypress to `9.2.0`

src/applications/registry.json
Turning on pre-check-in app in production
=> (feature) toggle pre-check-in to true

.github/workflows/daily-deploy-production.yml
Applying fix to daily-deploy. See #891 for more details
=> Change slackapi for daily-deploy

src/site/filters/liquid.js, src/site/filters/liquid.unit.spec.js, src/site/includes/social-share.drupal.liquid, src/site/layouts/event.drupal.liquid
**Issue:**
This PR implements design tweaks to the event detail page v2.
Updated
=> Kelsonic 34815 event v2

.github/workflows/content-release.yml, .github/workflows/continuous-integration.yml, .github/workflows/daily-deploy-production.yml, .github/workflows/slack-notify/action.yml
With #891 and #892 committed, cleaning up so messages remain align
While not tested, I believe this will solve the issue of notification on failure. See [thread](https://dsva.slack.com/archives/C0MQ281DJ/p1641584524065600?thread_ts=1641584102.064100&cid=C0MQ281DJ) for more details
=> Updating variable name to align with slack API

.github/workflows/continuous-integration.yml
PR to upgrade `LouisBrunner/checks-action` and `mikepenz/action-junit-report` to their latest versions.
=> Update GHA actions to latest versions

Jenkinsfile, jenkins/common.groovy
[Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/33802) associated
With #509 recently merged, most of Jenkins functionality no longer apply. This PR removes functions that are not required from Review Instance
It also ensure that `Jenkinsfile.content` is not affected
=> Cleanup Jenkins

src/site/layouts/event.drupal.liquid
This PR fixes a syntax error in the event detail liquid template.
=> Liquid doesn't support the elvis operator 😂

.github/workflows/content-release.yml, .github/workflows/continuous-integration.yml, .github/workflows/daily-deploy-production.yml, .github/workflows/manual-deploy-dev-staging.yml, script/github-actions/check-broken-links.js
With the change in slack notification API and format, the color has been missing. This PR adds color to make it "easier on the eyes"
=> Add color to slack notification

.github/workflows/content-release.yml, .github/workflows/continuous-integration.yml, .github/workflows/daily-deploy-production.yml
Use the [forked runner](https://github.com/department-of-veterans-affairs/ec2-github-runner) so we can bypass the `System.Globalization.CultureNotFoundException` error.
[Slack thread](https://dsva.slack.com/archives/CU1E4CX9U/p1642176221015100) with details.
=> Use forked runner

.github/CODEOWNERS
Quick PR to update the `CODEOWNERS` file to reflect the new platform QA team name.
=> Update code owners to reflect new QA team

.github/workflows/a11y.yml
Quick PR to add colors to the Slack notifications in the daily accessibility scan.
- Tested on Slack.
Before:
After:
=> Add colors to GitHub Actions Slack notifications in daily accessibility scan

.github/workflows/daily-deploy-production.yml
Added success message for vets-website prod deploy into slack
=> Added success message to production deploy

.github/workflows/daily-deploy-production.yml
Follow up to the vets-website PR activating the slack message for successful deploys
=> Moving the success slack message because of a role collision

package.json, yarn.lock
Resolves vulnerability in `node-fetch`.
Local and CI
=> Resolve node-fetch vulnerability

src/site/filters/liquid.js, src/site/filters/liquid.unit.spec.js, src/site/layouts/event.drupal.liquid
this branch is to test style fixes on tugboat for events v2
=> add style fixes for events v2

src/applications/registry.json
Add an entry for the new Enrollment Verification app to the registry. Note: Enrollment Verification is still in development (non-production).
=> Add Enrollment Verification App to Registry

src/applications/registry.json
This adds the Education Inbox to the list of apps. The code for the application is being added on this PR:
https://github.com/department-of-veterans-affairs/vets-website/pull/20057
=> Adding the new Education Inbox to the list of apps.

src/site/filters/liquid.js, src/site/includes/vet_centers/hours.liquid, src/site/includes/vet_centers/hours_dynamic.liquid, src/site/layouts/vet_center.drupal.liquid, src/site/layouts/vet_center_locations_list.drupal.liquid
Add Dynamic react hours component to vet center locations list. This is the content-build push for this vets-website commit https://github.com/department-of-veterans-affairs/vets-website/pull/20058
=> Add Dynamic react hours component to vet center locations list.

src/site/layouts/event.drupal.liquid
This PR fixes the functionality on the recurring event detail page
=> merge in detail page fixes

src/site/filters/liquid.js, src/site/includes/vet_centers/hours.liquid, src/site/includes/vet_centers/hours_dynamic.liquid, src/site/layouts/vet_center.drupal.liquid, src/site/layouts/vet_center_locations_list.drupal.liquid, src/site/stages/build/drupal/graphql/vetCenterLocations.graphql.js
Only show hours in staging env and update GraphL to only fetch fieldOfficeHours NodeVetCenterOutstations.
=> Only show hours in dev

.github/workflows/content-release.yml
Send Metrics to Datadog if deploy is successful
=> Send Metrics to Datadog if deploy is successful

.github/workflows/content-release.yml
This needs tested somehow.
Ref: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/7776
Ref: https://github.com/department-of-veterans-affairs/va.gov-team/issues/36310
Ref: https://github.com/department-of-veterans-affairs/va.gov-team/issues/36192
https://github.com/department-of-veterans-affairs/content-build/pull/949#issuecomment-1028403668
=> Switch to self hosted runners

.github/workflows/content-release.yml
This is to address the build failure here: https://github.com/department-of-veterans-affairs/content-build/runs/5056075633
=> Skip push hook and add certs

src/site/layouts/event.drupal.liquid, src/site/layouts/event_listing.drupal.liquid, src/site/layouts/events_page.drupal.liquid
This ticket assists in accomplishing the issues called out in this staging review ticket:
https://github.com/department-of-veterans-affairs/va.gov-team/issues/34622
=> update pges from staging review

src/site/layouts/event.drupal.liquid
=> add uri field

.github/workflows/a11y.yml
PR to modify the daily accessibility scan to use the latest `master` production build of `vets-website` instead of pulling assets from S3.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/35837
=> Use latest `vets-website` production build in daily accessibility scan

.github/workflows/continuous-integration.yml, package.json, yarn.lock
=> Upgrade Cypress to `9.4.1`

.github/workflows/a11y.yml, .github/workflows/continuous-integration.yml, .github/workflows/daily-deploy-production.yml, .github/workflows/slack-notify/action.yml
Quick PR to upgrade `slackapi/slack-github-action` to the latest version.
=> Upgrade Slack notification GitHub Action to latest version

package.json, yarn.lock
PR to upgrade Cypress to its latest version.
=> Upgrade Cypress to `9.5.0`

.github/workflows/content-release.yml, .github/workflows/daily-deploy-production.yml
Tested in https://github.com/department-of-veterans-affairs/content-build/pull/971
Fixes https://github.com/department-of-veterans-affairs/content-build/actions/runs/1849605383
Related issue: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8044
=> Don't use a docker image just to kill time

.github/workflows/continuous-integration.yml, .gitignore
Reverts department-of-veterans-affairs/content-build#978
=> Revert "Update All GHA Workflows that Use Yarn Build"

.github/workflows/content-release.yml
https://dsva.slack.com/archives/C01512KN35G/p1645127846080479
runners seem to be stopping and this order should fix it
workflow adjustment
https://github.com/department-of-veterans-affairs/va.gov-team/issues/34841
=> reorder stop runner action

.github/workflows/content-release.yml
See https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8107
=> Make runner teardown dependent on record-metrics being finished.

src/site/includes/vet_centers/address_phone_image.liquid
Remove VA production flag for hours in vet_center_locations_list.drupal.liquid.
=> Remove VA production flag for hours.

.github/CODEOWNERS, .github/workflows/content-release.yml, .github/workflows/record-release-interval/action.yml
Follow up to https://github.com/department-of-veterans-affairs/content-build/pull/989
Related to https://github.com/department-of-veterans-affairs/va.gov-cms/issues/7939
One more expected PR after this one to also record the events in the Daily Production Deploy workflow
=> Record release interval in datadog

.github/workflows/record-release-interval/action.yml
Followup to https://github.com/department-of-veterans-affairs/content-build/pull/995
=> Specify shell and working dir

src/applications/registry.json
Prepares the virtual agent for beta launch Monday
=> Virtual Agent Prod Launch

.github/workflows/daily-deploy-production.yml
Follow up to #989 
Related to: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/7939
This should be the last PR for this feature.
This exact code is currently running properly in the content release workflow
=> Add release interval calculation to daily prod deploy

.github/workflows/record-release-interval/action.yml
=> Remove unused var from release interval action

.github/workflows/content-release.yml
See: 
* https://github.com/department-of-veterans-affairs/va.gov-cms/issues/7870
* https://github.com/department-of-veterans-affairs/content-build/actions/runs/1919614574
=> VACMS-7870: add new credentials to govdelivery callback.

src/site/layouts/event.drupal.liquid
added updated styles to legacy events page
=> added new styles to legacy event page

.github/workflows/daily-deploy-production.yml
The govDelivery callback failed, so I'm copying it over from https://github.com/department-of-veterans-affairs/content-build/pull/1012/files
=> Update credentials for gov delivery callback

.github/workflows/record-release-interval/action.yml
* tested in https://github.com/department-of-veterans-affairs/content-build/pull/1016
* related to https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8216
=> fix datadog release timing calculation

src/applications/registry.json
Remove entry points for old GIBCT url and GIBCT Sandbox
=> Modify registry.json to remove gi-sandbox and old entry point for gibct

.github/workflows/daily-deploy-production.yml
The intention here is to stop the runner after the deploy and validation steps
yes, content release has been adjusted with the same
https://dsva.slack.com/archives/C02VD909V08/p1646334815874169
=> adjust stop-runner needs

.github/workflows/content-release.yml
Adds an additional content release at 12:54 pm ET.
Schedule (all ET):
* 8:54 am
* 9:54 am
* 10:54 am
* 11:54 am
* **12:54 pm** <-- added
* 1:45 pm <-- earlier than regular cadence to accommodate Daily Production Deploy
* 3:54 pm
* 4:54 pm
=> Add an additional scheduled content release at 12:54 pm ET.

src/site/layouts/story_listing.drupal.liquid, src/site/teasers/news_story_page_feature.drupal.liquid
This is the solution for this Ticket
https://github.com/department-of-veterans-affairs/va.gov-team/issues/37397
=> 37397 Remove In the spotlight feature on VAMC stories page.

.github/workflows/daily-deploy-production.yml
The daily deploys today were an hour late because of the time change
=> update CRON for daylight savings time

package.json, yarn.lock
PR to update the `table` dependency. Doing this minor upgrade to hopefully get the CI in `master` started.
=> Update table dependency

package.json, yarn.lock
Resolve `url-parse` [vulnerabilities](https://github.com/department-of-veterans-affairs/content-build/security/dependabot?q=is%3Aopen+manifest%3Ayarn.lock+package%3Aurl-parse).
=> Resolve url-parse vulnerability

.github/workflows/daily-deploy-production.yml
Follow up from #1043 - this should be merged before the daily deploy so that it doesn't fail.
=> Single quotes in daily deploy

.github/workflows/daily-deploy-production.yml
Fixes https://github.com/department-of-veterans-affairs/content-build/runs/5742155638?check_suite_focus=true
=> VAGOV-0000: get github token before it is referenced.

.github/workflows/daily-deploy-production.yml
=> immediately export new version var in daily deploy

.github/workflows/daily-deploy-production.yml
Using logic we had before ( https://github.com/department-of-veterans-affairs/content-build/pull/1043/files#diff-90571dbe8d8f4805db215f91f9d177538a3043d2d07cf1fcd29199bee34cfa79L540-L554 )
=> revert to earlier version of new tag logic

src/site/layouts/event.drupal.liquid
Restores prod switch check removed before events v2 is ready for release.
=> VACMS-7863: Restore prod check moved before ready.

package.json, yarn.lock
=> Upgrade Cypress to `9.5.4`

.github/workflows/a11y-heading-order.yml, .github/workflows/a11y.yml, src/platform/testing/e2e/cypress/support/commands/axeCheck.js
This PR modifies the daily accessibility scan so that it generates a CSV file of any accessibility issues found in the scan.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/39340
Generated CSV locally
Generated CSV in CI
=> Generate CSV of failures in daily accessibility scan

src/site/facilities/vha_facility_nonclinical_services.drupal.liquid, src/site/filters/liquid.js, src/site/includes/hours-item.liquid, src/site/includes/hours.liquid, src/site/layouts/vamc_system_medical_records_offi.drupal.liquid, src/site/stages/build/drupal/graphql/facilities-fragments/healthCareRegionNonClinicialServices.node.graphql.js, src/site/stages/build/drupal/graphql/vamcMedicalRecordsOfficePage.graphql.js
This pr implements remaining items for Med records defined, here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/37365
Visual and build
Add system to intro
Release of info text changed, and headers changed to h3/h4 with linked systems
Release of info address and linked phone number
**Go to `minneapolis-health-care/medical-records-office` and visually verify:**
=> VAVSA-37365: Update med records tpl to include design changes.

src/site/includes/centralized-content.drupal.liquid, src/site/layouts/vamc_system_register_for_care.drupal.liquid, src/site/paragraphs/service_location.drupal.liquid
relates to https://github.com/department-of-veterans-affairs/va.gov-team/issues/37367
This pr addresses remaining Register for Care TTP items (with exception of office hours hardening handled by  https://github.com/department-of-veterans-affairs/content-build/pull/1080):
1. Adds TOC
2. Adds facility name to intro text
3. Links facility names to facility
Visual / build
Facility name in intro text
TOC
Linked facility
Facility hours correctly displayed 1
Facility hours correctly displayed 2
Facility service correctly displayed
VC hours display
VC locations hours display
=> VAVSA-37367: Add toc, facility name and links to facility

src/site/includes/hours.liquid
Wraps orphaned span in list in li tags.
=> VAVSA-000: Wrap span on hours tpl with li.

package.json, yarn.lock
=> Resolved critical security dependencies

script/preview.js
Pre-emptive revert in case the below PR needs to be undone.
Reverts department-of-veterans-affairs/content-build#1097
=> Do not merge: Revert "Fix s3 bucket URLs referenced by CMS preview server"

.github/workflows/content-release.yml, .github/workflows/continuous-integration.yml, script/github-actions/check-broken-links-blocks.js
=> VACMS-8927: point CI reporting at #content-broken-link; better message construction.

script/preview.js
Preemptive revert, to get approval since we're going into the end of the week.
Reverts department-of-veterans-affairs/content-build#1104
=> Do not merge: Revert "Vacms 0000 correct s3 urls"

script/github-actions/check-broken-links-blocks.js
=> VACMS-0000: misnamed env variable.

script/github-actions/check-broken-links-blocks.js, script/github-actions/check-broken-links.js, src/site/stages/build/plugins/modify-dom/check-broken-links/index.js
Temporarily raise the broken link limit.
=> Temporarily raise the broken link limit.

src/site/includes/blog-promo.html, src/site/layouts/home.drupal.liquid
Built out a Promo component for the VAntage Point blog and other news for the Home page. This is part of the Home page redesign iteration for better usability. The component contains an image (has alt text), h3 header, blurb paragraph, and two CTA links. 
See design file:
https://www.sketch.com/s/3aa40506-4be2-46cc-876b-93f1a9f3a857/a/GmRqkmw#Inspector
See ticket: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8359
Note: this is **hard-coded** for now. We will populate it from a data source in another ticket and PR.
=> VACMS-8359 Home page iteration - blog promo

src/site/stages/build/drupal/graphql/vamcBillingAndInsurancePage.graphql.js, src/site/stages/build/drupal/graphql/vamcMedicalRecordsOfficePage.graphql.js, src/site/stages/build/drupal/graphql/vamcRegisterForCarePage.graphql.js
closes https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9023
build
=> VAVSA-9023: Add meta info to top task graphql queries.

.github/workflows/a11y-heading-order.yml, .github/workflows/a11y.yml, .github/workflows/codeql.yml, .github/workflows/content-release.yml, .github/workflows/continuous-integration.yml, .github/workflows/daily-production-release.yml, .github/workflows/daily-release-warning.yml, .github/workflows/install/action.yml, .github/workflows/manual-deploy-dev-staging.yml, .github/workflows/manual-review.yml
Quick PR to upgrade all uses of official GitHub actions to `v3`.
=> Upgrade official GitHub actions to `v3`

.github/workflows/content-release.yml, yarn.lock
Touch yarn.lock to force creation of a new cache key for cached yarn dependencies.
=> Touch yarn.lock.

.github/workflows/codeql.yml
Fixes indentation in codeql workflow.
=> Fix indentation in codeql.yml.

src/site/layouts/vamc_system_billing_insurance.drupal.liquid
See https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9182 
Fixes spelling error.
=> VACMS-9182: Fix spelling error on VAMC Billing and insurance page

.github/workflows/authenticated-cms-request/action.yml, .github/workflows/content-release.yml
Unreverting PR
Ref #1125 #1132
=> Keep CMS updated on status of content release

.github/workflows/content-release.yml
=> paths are different in the build step 🤦

package.json, yarn.lock
=> Upgrade Cypress to `9.7.0`

src/applications/registry.json
Adding to registry for the new Combined Debt Portal application .
department-of-veterans-affairs/va.gov-team#41505
[IA Design for Combined Debt Portal](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/debt-portal.md)
=> [CDP] Adding Combined Debt Portal

src/site/filters/liquid.js
Adds special handling for past events on outreach pages.
Visual / unit
=> VAVSA-28918: Update filter for outreach events.

src/site/layouts/vamc_system_billing_insurance.drupal.liquid, src/site/stages/build/drupal/graphql/vamcBillingAndInsurancePage.graphql.js
see: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9362
Swaps fieldHoursForCopayInquiries for fieldOfficeHours
Visual / Build
=> VAVSA-9362: Swap copay for new hours field.

.github/workflows/content-release.yml, .github/workflows/continuous-integration.yml
=> Update GHA AMI ID

.github/workflows/continuous-integration.yml
Updates AMI back to use env variable.
=> Update AMI back

src/site/includes/blog-promo.html, src/site/includes/common-tasks.html, src/site/includes/hero.html, src/site/layouts/home-preview.drupal.liquid
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9308
This PR updates the new redesigned homepage (/homepage-test/) to better match [Sketch mockups](https://www.sketch.com/s/3aa40506-4be2-46cc-876b-93f1a9f3a857/a/PGEaJDr). 
[x] QA by @mmiddaugh 
[x] locally
See [issue #9308](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9308)
=> VACMS-9308 Homepage redesign defect fixes

.github/workflows/content-release.yml, .github/workflows/continuous-integration.yml
moving it to gha runner within the asg
https://dsva.slack.com/archives/C02VD909V08/p1655834712670579
=> runners to gha tying back to asg

script/preview.js, src/site/includes/top-nav.html
See [Staging review ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/43099). Topics:
- Banner not centered
- Banner should be dismissible
department-of-veterans-affairs/va.gov-cms#9531
- Manual testing
- Unit tests
=> Bugfix/vfs pw 9531 ie UI ux display

src/applications/registry.json
Adding Supplemental Claim Form 20-0995 to registry
See https://github.com/department-of-veterans-affairs/va.gov-team/issues/43219
Tested locally
N/A
=> Add supplemental claim form

src/site/layouts/vamc_operating_status_and_alerts.drupal.liquid
Removed a div around the dt and dd elements that was causing a 508 error. Added the border to the dt and dd elements instead.
Visual
=> Remove div around dt and dd for 508 fix

.github/workflows/a11y.yml
This PR adds a clean up step to delete unneeded files at the end of the jobs in the daily accessibility scan.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/43420
=> Add clean up step to daily accessibility scan

.github/workflows/content-release.yml, .github/workflows/record-release-interval/action.yml
See #9540
This comments out some code because the subsequent step depends on a previous metric being available and this is the first time we are running it. 
There will be another PR after we merge and run this to uncomment it back to normal state. 
Gotta merge to test it.
=> VACMS-9540 DDGOV Migration

.github/workflows/record-release-interval/action.yml
Follow up to https://github.com/department-of-veterans-affairs/content-build/pull/1198
Missed some code.
=> VACMS-9540 DDGOV Migration (2)

.github/workflows/record-release-interval/action.yml
Restore metrics code now that the event to calculate from is present. 
Follow up from https://github.com/department-of-veterans-affairs/content-build/pull/1199
See https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9540
=> VACMS-9540 DDGOV Migration (3)

.github/CODEOWNERS, .github/workflows/content-release.yml, .github/workflows/request-content-release.yml
Adding a `reason` query string value which the CMS endpoint expects.
=> Add reason query string value to CMS build request.

.github/workflows/record-release-interval/action.yml
=> Fix default value in deploy interval calculation

.github/workflows/record-release-interval/action.yml
=> remove extra paren

src/site/includes/top-nav.html
Very small change to regular expression for IE check.
Tested locally. Also, see [related PR on vets-website](https://github.com/department-of-veterans-affairs/vets-website/pull/21645) with thorough unit testing. This PR updates to use same regular expression.
=> VACMS-9408: Adds "MSIE" to isIE check.

.github/workflows/continuous-integration.yml
This PR does the following:
- Replaces ubuntu-packer AMI with platform-minimal AMI
https://github.com/department-of-veterans-affairs/va.gov-team/issues/44317
Github Action workflow & CI works as expected
Successful [run](https://github.com/department-of-veterans-affairs/content-build/runs/7329191671?check_suite_focus=true)
=> Chore: Update to minimal AMI

.github/workflows/content-release.yml, .github/workflows/continuous-integration.yml, .github/workflows/install/action.yml
Replaces ubuntu-packer AMI with platform-minimal AMI
https://github.com/department-of-veterans-affairs/devops/pull/11575
N/A. As its for `content-release`. Will need additional set of eyes. Aligned most from testing done in CI.
See latest [CI](https://github.com/department-of-veterans-affairs/content-build/runs/7394266015?check_suite_focus=true) workflow for more details
=> Chore: Update deploys with new AMI

src/site/stages/build/drupal/static-data-files/vamcEhrSystem/index.js
Resolves https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9787
=> VACMS-9787: Return all medical centers in static EHR response.

src/platform/site-wide/tests/accessible-modal.cypress.spec.js, src/site/layouts/tests/vet_center/template/fixtures/vet_center_data.json
Resolves department-of-veterans-affairs/va.gov-cms/issues/9797
[department-of-veterans-affairs/va.gov-team#0000](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9797)
=> VAMC-9797: Update crisis line phone number.

.github/workflows/a11y.yml, package.json, yarn.lock
PR to upgrade `axe-core` to the latest version.
Ran daily accessibility scan.
=> Upgrade `axe-core` dependency

package.json, yarn.lock
=> Upgrade Cypress to `10.4.0`

src/platform/site-wide/tests/sitemap/sitemap.a11y.spec.js
This PR removes unneeded code from the test file used in the accessibility scans.
Ran accessibility scan locally against staging.
=> Clean up accessibility scan test

.github/workflows/content-release.yml
Disable step that is failing on an ongoing basis.
=> Disable record deployment event.

src/applications/registry.json
Update the base URL for Enrollment Verification.
vets-website PR: https://github.com/department-of-veterans-affairs/vets-website/pull/21897
=> Update Enrollment Verification Base URL

src/site/layouts/faq_multiple_q_a.drupal.liquid
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9918
Adds react component for language toggling to the faq_multiple_q_a template
=> added language toggle component to qa template

.github/workflows/content-release.yml
=> add error notification and dedupe other cms notifications

src/site/includes/header.html
Reverts department-of-veterans-affairs/content-build#1249
This unintentionally prevents web components from being loaded.
=> Revert "Build prototype for new focus styles"

src/applications/registry.json
Updated the rootURL path for Education Letters app.
=> Updated Education Letters rootURL to /download-letters/

package.json, yarn.lock
=> Upgrade Cypress to `10.6.0`

.github/workflows/continuous-integration.yml
https://github.com/department-of-veterans-affairs/va.gov-team/issues/43052
yes
=> include cleanup plugin for deploy to work with asg

.github/workflows/continuous-integration.yml
Reverts department-of-veterans-affairs/content-build#1275
=> Revert "include cleanup plugin for deploy to work with asg"

.github/workflows/continuous-integration.yml
https://dsva.slack.com/archives/C02VD909V08/p1661361913855379
=> remove asg for CI build

src/applications/registry.json
Added MHV SM to list of applications, per MHV ticket:
https://vajira.max.gov/browse/MHV-33535
=> [#MHV-35473] Added new MHV SM Patient application to registry

package.json, yarn.lock
PR to upgrade Cypress to the latest version.
=> Upgrade Cypress to `10.7.0`

.github/workflows/a11y.yml
PR to add a timeout to the cache download steps in the daily accessibility scan. The cache download occasionally hangs until it times out after one hour.
Tested caching with the timeout.
=> Add timeout to dependency caching step in daily accessibility scan

src/platform/static-data/footer-links.json
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10405
Update link and text for VA health providers in footer.
- New Link text: VA health care access and quality (SWC provided on https://github.com/department-of-veterans-affairs/va.gov-team/issues/46237)
- New Link URL: https://www.accesstocare.va.gov/
Visual testing locally.
=> 10405 Update VA health providers link and text

src/applications/registry.json
Planning release of COE in the near future. We recently put [rendering of the form and status app behind a feature flag](https://github.com/department-of-veterans-affairs/va.gov-team/issues/46328), and we plan on [enabling the e2e tests](https://github.com/department-of-veterans-affairs/va.gov-team/issues/46034)
Local unit & e2e tests
N/A
=> Certificate of Eligibility | Set to build in prod

package.json, yarn.lock
=> Upgrade Cypress to `10.8.0`

src/site/includes/blog-promo.drupal.liquid, src/site/includes/hero.drupal.liquid, src/site/layouts/home-preview.drupal.liquid, src/site/stages/build/drupal/home.js
Homepage prototype tweaks as outlined in department-of-veterans-affairs/va.gov-cms/issues/10982
Cross referencing changes as outline in the ticket. Eyeballing image adjustments in accordance with the prototype sketch file.
=> VACMS-10982 - Prototype updates: Fixing broken links and typos

src/site/layouts/vamc_operating_status_and_alerts.drupal.liquid, src/site/stages/build/drupal/graphql/vamcOperatingStatusAndAlerts.graphql.js
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11216
=> VACMS-11216: make sure all rich text field queries use processed.

.github/workflows/content-release.yml
**This must not/should not/can not be merged until department-of-veterans-affairs/va.gov-cms#11283 makes it to production.**
See discussion [here](https://dsva.slack.com/archives/C02HX4AQZ33/p1666274722161189) and [here](https://dsva.slack.com/archives/CJT90C0UT/p1662040948350839).
=> Increase timeouts to prevent hamstringing in-progress good builds.

.github/workflows/content-release.yml
https://dsva.slack.com/archives/CBU0KDSB1/p1666890929327659
Use the runner provisioned in the first job for all subsequent jobs.
=> VACMS-0000 always use provisioned runner

.github/workflows/content-release.yml
Reverts department-of-veterans-affairs/content-build#1339
=> Revert "VACMS-0000 always use provisioned runner"

src/applications/registry.json
Changing the Supplemental Claims path and breadcrumbs based on IA feedback in [#48796](https://github.com/department-of-veterans-affairs/va.gov-team/issues/48796)
[IA Review and Recommendations](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/bam-supplemental-claims-form.md)
N/A
N/A
=> Update Supplemental Claims IA

src/applications/registry.json, src/site/assets/robots.txt
We are in the process of removing the Health Care Questionnaire App from VA.gov. This was a prototype that is no longer going forward in this state. We are removing this since it will not be used.
=> (feature) removed health care questionnaire from app

.github/workflows/content-release.yml
Reverts department-of-veterans-affairs/content-build#1368
Back pocket revert, in the event the change causes issues.
=> Revert "VACMS-11309: use c5d instances; minor updates."

.github/workflows/content-release.yml, src/site/layouts/vamc_operating_status_and_alerts.drupal.liquid
Fixing a template issue that is causing a11y errors.
Report here: https://testing-tools-testing-reports.s3-us-gov-west-1.amazonaws.com/a11y-reports/e9f7ca41-90a5-4ca4-acee-56744b1001d7.html
Workflow run here: https://github.com/department-of-veterans-affairs/content-build/actions/runs/3496722595
=> VACMS-0000: fix section aria label

.github/workflows/content-release.yml
Reverts department-of-veterans-affairs/content-build#1372
=> Revert "Use either on-demand or GHA runners."

.github/workflows/content-release.yml
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11309
Just switching to c5d instances.
=> VACMS-11309: switch to c5d instances.

.github/PULL_REQUEST_TEMPLATE.md
Relates to https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9343
Which has been an action item from two different Postmortems
1. 6/6/2022 https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Postmortems/2022-06-06-facility-locator-static-data-source-failure.md#action-items
2. 8/17/2022 https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/pull/552
Previewed in markdown render by viewing [the file here](https://github.com/department-of-veterans-affairs/content-build/blob/754ea220a0f9d0739b77b5465bedded3869547ba/.github/PULL_REQUEST_TEMPLATE.md)
=> VACMS-9343: Add QA steps to PR template.

src/site/includes/hero.drupal.liquid
The redesigned home page has some text and style changes for the "Create Account" section in the top right.
closes [#11538](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11538)
relates to [#11570](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11570)
Visual
What needs to be checked to prove this works?
1. Check out this branch and do a local PR build
2. Go to `http://localhost:3002/new-home-page/`
3. Confirm that the Create Account area has the new styles and elements as expected
1. The other areas of the new homepage need to be checked for proper styling and functionality to make sure they weren't indirectly broken.
What variations of circumstances (users, actions, values) …
=> [VA-11538] New Homepage "Create Account" Updates

src/site/includes/email-update-signup.drupal.liquid, src/site/layouts/home-preview.drupal.liquid
Implements design changes and form for email notification signups.
Currently the form **DOES NOT** submit correctly. Please see original ticket for discussion regarding that.
closes department-of-veterans-affairs/va.gov-cms/issues/11389
Desktop Design
Mobile Design
Veterans and beneficiaries viewing the redesigned homepage can signup for email updates using a component at the bottom of the page which
=> 11389 implements design changes and form for email update notifications

.github/CODEOWNERS, script/pr-check.js
This PR updates references to platform-release-tools GH team to va-platform-cop-frontend to account for changes to teams following the reorg
N/A
After merged, make sure that members of va-platform-cop-frontend are pinged /  made reviewers for PRs opened subsequently.
=> update references to platform-release-tools to va-platform-cop-frontend

.github/workflows/preview-environment-deployment.yml
This implements a workflow on push 
relates to https://app.zenhub.com/workspaces/platform-tech-team-4-633b069d2920b776613c93d8/issues/gh/department-of-veterans-affairs/va.gov-team/50517
This workflow has been tested and correctly passes the source repo and branch name as expected.
=> Pe deploy cb

src/applications/registry.json
- Scaffold new vets-website app for **VA Form 26-4555 &mdash; Application in Acquiring Specially Adapted Housing or Special Home Adaptation Grant**
- **VA.gov Product Forms** team initiative
- [no feature-flag just yet; content-build apps-registry entry has `vagovprod` property set to `false`]
[vets-website#23250](https://github.com/department-of-veterans-affairs/vets-website/pull/23250)
- department-of-veterans-affairs/va.gov-team-forms#14
- [Epic](https://github.com/department-of-veterans-affairs/va.gov-team-forms/issues/28)
[none just yet; just scaffolding the new app right now]
None; this is just a new React-app entry in the applications registry file.  No other code/content was touched.
=> Scaffold new app for VA Form 26-4555

.github/workflows/preview-environment-cleanup.yml, package.json, script/github-actions/pe-cleanup.js, yarn.lock
This workflow will clean up preview environments that belonged to a branch that has been deleted.
closes https://app.zenhub.com/workspaces/platform-tech-team-4-633b069d2920b776613c93d8/issues/gh/department-of-veterans-affairs/va.gov-team/50769
Tested via push-trigger. Can't test delete trigger til it's merged to main due to GHA restrictions.
QA cannot be done until it's merged to main due to GHA restrictions.
=> Add actions/core library

src/applications/registry.json
Enable VA Education Inbox url in production in preparation for official release on week of 02/27/2023-03/03/2023
closes __   
1. Do this
2. Then
=> - Enable VA Education Inbox url in production

src/applications/registry.json
For department-of-veterans-affairs/va.gov-team-forms#21
This pull requests updates the registry to include the appropriate URLs and breadcrumbs.
=> 26-4555 URL and breadcrumb updates

src/applications/registry.json
relates to https://github.com/department-of-veterans-affairs/va.gov-team/issues/54428
feature is disabled for all traffic except whitelisted users:
1. Do this
2. Then
=> flip mhv landing to prod for tsting

.github/workflows/a11y-heading-order.yml, .github/workflows/a11y.yml, .github/workflows/content-release.yml, .github/workflows/continuous-integration.yml, .github/workflows/deploy-content-preview-server.yml
Just in case something goes wrong:
Reverts department-of-veterans-affairs/content-build#1496
=> Revert "All Workflows Use ASG Self-Hosted Runners"

src/applications/registry.json
Correcting URLs for Letters and Enrollment Verification apps.
closes __   
1. Do this
2. Then
=> - Correction to entry points for letters and EV

.github/workflows/content-release.yml
closes __   
1. Do this
2. Then
=> Content-Release Workflow Remove References to Archive Job

src/site/includes/top-nav.html
relates to https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12697
_What needs to be checked to prove this works?_
Load VA.gov, inspect logo, verify updated alt text reads "VA logo and Seal, U.S. Department of Veterans Affairs"
=> VACMS-12697 Update alt text for VA logo

src/applications/registry.json
This pull request updates the 26-4555 route and breadcrumbs to match the content review changes.
- department-of-veterans-affairs/va.gov-team-forms#154
- department-of-veterans-affairs/va.gov-team#55696
=> Update 26-4555 route

src/applications/registry.json
- Add new form for prototyping web component patterns/tests/examples
- Related issue: department-of-veterans-affairs/va.gov-team-forms#166
- vets-website PR: https://github.com/department-of-veterans-affairs/vets-website/pull/23837
- verified new route can be reached (not for production)
- verified no conflicts in routes
See screenshots: https://github.com/department-of-veterans-affairs/vets-website/pull/23837
- New route is accessible
- Does not affect other pages
=> Add mock simple forms patterns

src/applications/registry.json
Add new registry-entry for new form-app 21-10210
relates to department-of-veterans-affairs/va.gov-team-forms#167 
n/a; just a registry entry
n/a; no code/content changes
=> Add registry-entry for new form 21-10210

src/site/includes/hero.drupal.liquid
Necessary class added to manage create account block display status. 
pairs with this PR https://github.com/department-of-veterans-affairs/vets-website/pull/23869
relates to https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12980
See https://github.com/department-of-veterans-affairs/vets-website/pull/23869
1. Do this
2. Then
=> 12863 create account block visibility

.github/workflows/content-release.yml, .github/workflows/daily-production-release.yml
Reverting changes to Daily Production Release and Content Release.
=> Rolling back content-release and daily-production-release.

.github/workflows/content-release.yml, .github/workflows/daily-production-release.yml
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13762
This should resolve the issues we were seeing with Content Release being unable to properly find the most recent Daily Production Release, leading to the failures we were seeing recently.
We created a release from the PR branch, and `target_commitish` is set correctly. Response to https://api.github.com/repos/department-of-veterans-affairs/content-build/releases/latest:
```
// 20230518145926
// https://api.github.com/repos/department-of-veterans-affairs/content-build/releases/latest
{
"url": "https://api.github.com/repos/department-of-veterans-affairs/content-build/releases/103525140",
"assets_url": "https://api.github.com/repos/department-of-veterans-affairs/content-build/releases/103525140/assets",
"upload_url": …
```
=> VACMS-13762: add commit and draft to create release.

src/applications/registry.json
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13585
Adding the Income Limits application here to register it for `vets-website`. Settings are per this documentation: https://depo-platform-documentation.scrollhelp.site/developer-docs/creating-a-new-application
=> VACMS-13585 Income Limits application MVP

src/site/stages/preview/index.js
Just merged in the code for pulling Drupal data for part of the footer. This fixes an issue with a changed shape on one of the imports.
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11482
1. Do this
2. Then
=> VACMS-11482 Drupalizing footer: quick fix for import

src/site/constants/environments-configs.js
- Adjusts the environment config file to account for the formatting necessary for preview environments.
Tested using ngrok to mimic a real-world host name and got the desired results.
=> Add alternate environment config for preview environment api

src/applications/registry.json, src/site/stages/build/drupal/graphql/homePage.graphql.js
Add registry-entry for new Authorization to Disclose Personal Information to a Third Party (Form 21-0845) React-app.
Relates to department-of-veterans-affairs/va.gov-team-forms#292
N/A; just updating a config file for a new React app.
=> Add new 21-0845 form-app registry-entry

src/site/includes/common-tasks.drupal.liquid, src/site/includes/hero.drupal.liquid, src/site/includes/homepage-benefits.drupal.liquid, src/site/includes/news-spotlight.drupal.liquid, src/site/tests/home/00-required.cypress.spec.js
relates to https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13976
Cypress tests run locally.
n/a
=> VACMS-13976: Updates home page cypress test for new home page markup.

src/applications/registry.json
Add form using `yarn new:app`
[vets-website PR](https://github.com/department-of-veterans-affairs/vets-website/pull/24474)
[Ticket](https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team-forms/303)
Opens locally
=> Add form to registry

src/applications/registry.json
Add breadcrumb to Lay/Witness Statement (21-10210) form-app's registry-entry.
Helps close department-of-veterans-affairs/va.gov-team-forms#307  
Form's still WIP.  Flipper [`form2110210`] enabled in Staging ONLY; disabled in Prod [form not ready to launch yet].
N/A; just a config update.  No content/functional changes here.
=> Add breadcrumb to 21-10210 app registry-entry

src/site/constants/environments-configs.js
Revert unused PE code that is no longer being used.
=> Revert pe env config

src/site/stages/build/drupal/graphql/homePage.graphql.js, src/site/stages/build/drupal/home-sandbox.js, src/site/stages/build/drupal/home.js
Removes old homepage elements no longer needed.
relates to https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11921
Manual build
1. Visit /
2. Then visit /new-home-page
=> VACMS-11921: Removes deprecated homepage elements.

src/applications/registry.json
This PR is to add a new application to the vets-website repo. The first PR is just to add placeholder content and ensure the application scaffolding is in place to build the actual application. This content **IS NOT** intended to be deployed to production at this time. The `vagovprod` value is set to `false`.
There are two simple tests to ensure that the content is being rendered - one for each placeholder page.
**What needs to be checked to prove this works?**
The placeholder content should appear at `/contact-us/ask-va-too`.
**What needs to be checked to prove it didn't break any related things?**
This page exists in isolation from other applications.
**What variations of circumstances (users, actions, values) need to be checked?**
At this time, no authentication is required to view the …
=> Ask va prototype

src/applications/registry.json
This PR creates the scaffolding for a new application – Notification Center. **Note:** the Notification Center application is currently an MVP.
I work on the Authenticated Experience - My VA team, and we will be owning and maintaining this app for now. There is currently no flipper in use (the global flag for `vagovprod` on the content-build repo is set to `false`).
* https://github.com/department-of-veterans-affairs/va.gov-team/issues/60398  
* vets-website: https://github.com/department-of-veterans-affairs/vets-website/pull/24714
* content-build: https://github.com/department-of-veterans-affairs/content-build/pull/1626
* devops: https://github.com/department-of-veterans-affairs/devops/pull/13185
=> Update registry.json (Notification Center)

src/applications/registry.json
Update route and breadcrumbs to match content from review
[Ticket](https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team-forms/374)
[devops PR](https://github.com/department-of-veterans-affairs/devops/pull/13212)
[vets website PR](https://github.com/department-of-veterans-affairs/vets-website/pull/24842)
=> Simple forms: Add breadcrumbs and update url form 21P-0847

src/site/filters/liquid.js, src/site/includes/metatags.drupal.liquid
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13481
Adds iOS mobile app promo banner for the VA app only on certain pages per the AC.
All tested through Browserstack, and @dsasser tested on his iPhone running locally.
On an iPhone, visit these URLs and verify that an App Store banner for the VA app exists:
```
/health-care/refill-track-prescriptions
/health-care/secure-messaging
/health-care/get-medical-records
/disability/view-disability-rating
/claim-or-appeal-status
/disability/upload-supporting-evidence
/records/download-va-letters
/va-payment-history
/change-direct-deposit
```
=> VACMS-13481 iOS mobile app promo banner

src/site/facilities/facility_social_links.drupal.liquid
relates to https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11848
Due to https://dsva.slack.com/archives/CBU0KDSB1/p1690487173146249?thread_ts=1687371270.904739&cid=CBU0KDSB1
=> VACMS-11848 Add rel=noreferrer to external links

src/applications/registry.json
I have the requisite vets-website changes in this PR: https://github.com/department-of-veterans-affairs/vets-website/pull/24994
Changes should be available in staging only
=> 59733: Added entry for new root url [VAOS]

src/applications/registry.json
closes https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team-forms/455
Browser testing
Header and footer should be simplified version on this particular form
=> Simplify header and footer for mock form

src/applications/registry.json
Add app registry entry for new Presidential Memorial Certificate Request (40-0247) form-app.
Relates to department-of-veterans-affairs/va.gov-team-forms#451 
Companion [vets-website PR](https://github.com/department-of-veterans-affairs/vets-website/pull/25232).
N/A &mdash; this is just a new app-registry entry.
=> Scaffold new 40-0247 form-app

src/site/stages/build/plugins/modify-dom/add-id-to-subheadings.js
This reverts commit 4dc5b26b912c9c14d0eb43c37e87ca9d297263f3.
This solution didn't quite work. Reverting to take a deeper dive.
=> Revert "VACMS-14747 Fix duplicate ID issue on va-accordion-item (#1660)"

src/applications/registry.json
- Add the ds-playground and ds-v3-playground applications to the registry.json file
- The applications should not be pushed out to production
closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/63632
relates to https://github.com/department-of-veterans-affairs/vets-website/pull/25243
=> Create the ds-playground and ds-v3-playground applications

src/site/facilities/vha_facility_nonclinical_service.drupal.liquid, src/site/filters/liquid.js, src/site/paragraphs/service_location.drupal.liquid, src/site/stages/build/drupal/graphql/facilities-fragments/healthCareRegionNonClinicialServices.node.graphql.js
The facility's main phone number wasn't being properly passed to VAMC pages. This adds the main phone number to the needed query and passes it to the front end.
relates to [#14586](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14586)
Checked at [this page](https://staging.va.gov/poplar-bluff-health-care/register-for-care/)
**What needs to be checked to prove this works?** That the main phone number displayed for the facility with the header too.
**What needs to be checked to prove it didn't break any related things?** The rest of the page still renders properly.
1. On a [CMS](https://prod.cms.va.gov/node/44976)  [nonclinical service page that has the checkbox checked](http://025c10d84a8f30e36309d8f4dd52b1c8.review.vetsgov-internal/montana-health-care/medical-records-o …
=> VACMS-14586 Pass Main Phone Number to VAMC Medical Records and Register for Care pages

src/applications/registry.json
This sets a boolean to enable form 21P-0847 in production.
https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team-forms/473
=> Enable form 21P-0847 in production

src/site/facilities/facility_health_service.drupal.liquid, src/site/facilities/health_service.drupal.liquid, src/site/includes/vet_centers/services.liquid, src/site/layouts/campaign_landing_page.drupal.liquid, src/site/layouts/faq_multiple_q_a.drupal.liquid, src/site/layouts/health_care_local_facility.drupal.liquid, src/site/layouts/landing_page.drupal.liquid, src/site/layouts/vet_center.drupal.liquid, src/site/paragraphs/collapsible_panel.drupal.liquid, src/site/paragraphs/q_a.collapsible_panel.drupal.liquid, src/site/stages/build/plugins/modify-dom/add-id-to-subheadings.js
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14747
When we added unique IDs to `va-accordion-item`s for linking to fragments (i.e. `/resources/the-pact-act-and-your-va-benefits/#can-i-apply-now`), it created a duplicate ID issue. The `h3`s inside of the `va-accordion-item` were automatically getting IDs assigned by `add-id-to-subheadings.js`.
Since we do not need IDs on the `h3`s inside `va-accordion-item`s, this code removes that automatic ID addition.
Tested all of the below links based on the QA steps.
1. Go to one of the URLs below
2. Inspect one of the accordions
3. Note the class on the `va-accordion-item` of `"va-accordion-item"`
4. Inspect the `h3` (may or may not have `slot="headline"`) in the `va-accordion-item`
5. Note the `h3` (with or without …
=> VACMS-14747 Fixing duplicate IDs on accordions

.github/workflows/content-release.yml
closes department-of-veterans-affairs/va.gov-cms#12306
=> Wait for CMS to be ready before notifying.

.github/actionlint.yml, .github/workflows/content-release.yml
closes https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13983
=> Separate out Slack Notify Messages to remove CMS Dependency

src/applications/registry.json
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14294
Enable Income Limits in production.
=> VACMS-14294 Release Income Limits to production

src/site/layouts/event.drupal.liquid
In some circumstances we would see some header line-height mismatches with the When and Cost fields. This PR adds some margin for the where field to space it between the cost field and makes sure that both headers are level.
Tested multiple events against new changes and made sure that events did not have mismatching header levels. Some examples are below:
=> VACMS-13222: Fixes styling with some issues being seen on prod

src/applications/registry.json
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14931
Our previous URL (including `/test/`) was rejected by the VA servers, so we need to make a change to a new URL.
=> VACMS-14931 PACT Act URL change

src/applications/registry.json
This updates the app name and path for 21P-0847 based on content review.
department-of-veterans-affairs/va.gov-team#63094
=> Update app name and path for 21P-0847

src/applications/registry.json
relates to department-of-veterans-affairs/va.gov-team-forms#561
Related, feature-flag PRs:
- [vets-website flag-PR](https://github.com/department-of-veterans-affairs/vets-website/pull/25774) merged
- [vets-api flag-PR](https://github.com/department-of-veterans-affairs/vets-api/pull/13889) pending Platform review/approval
N/A; just a config-file change right now.  Form won't be published right now.  Feature-flag will be implemented & turned OFF in Prod _before_ this PR's made Ready-for-Review.
=> Enable 21-0927 in prod

src/applications/registry.json
Update the URL for form 21-0966 [to be in line with FE here.](https://github.com/department-of-veterans-affairs/vets-website/pull/25846)
relates to https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team-forms/258
=> Update the rootUrl for form 21-0966

src/applications/registry.json
The Health Enrollment (1010) team is working on creating a new React application for the 10-10EZR form. This PR adds an entry to the registry file to scaffold the application to the React page template.
- department-of-veterans-affairs/va.gov-team#66739
=> Add registry entry for new 10-10EZR application

src/applications/registry.json
closes department-of-veterans-affairs/va.gov-team-forms#616 
N/A; just an app-registry update
=> 40-0247 - Finalize URL and add breadcrumbs

src/applications/registry.json
Closes department-of-veterans-affairs/va.gov-team-forms#617   
N/A &mdash; just a new app-registry entry here
=> 20-10206 - Add new form-app to app-registry

src/applications/registry.json
Adding new "Find a Local Representative" application to registry.json. Initial scaffolding has been pushed to main in the "representative" app folder.
=> Adding Find a Local Representative application to entry file

src/site/includes/tests/homepage.cypress.spec.js
the My VA link was removed here:
https://github.com/department-of-veterans-affairs/vets-website/pull/26068/files
But, we still had a test that targeted it. This removes that test.
=> Remove test of My VA link since the link was hidden.

src/applications/registry.json
Fixes breadcrumbs for form 21-0966
https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team-forms/663
The URL itself was already updated here: https://github.com/department-of-veterans-affairs/content-build/pull/1725
=> Fix breadcrumbs in form 21-0966

src/site/layouts/vet_center_locations_list.drupal.liquid
relates to https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15067
Prior version (va.gov):
Current version:
1. Go to any Vet Center locations page: `/antelope-valley-vet-center/locations/` 
2. Then
=> change link text

src/applications/registry.json
Update Lay/Witness Stmt (21-10210) app-registry appName for new window-title.
closes [va.gov-team-forms #683](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/issues/683)  
[vets-website PR](https://github.com/department-of-veterans-affairs/vets-website/pull/26487)
Local browser-testing was successful; this is just a config property-update.
=> 21-10210 - Update app-registry appName

.github/workflows/daily-production-release.yml
Updating the cron job to reflect Standard Time 2023.
=> update cron job start time

.github/workflows/daily-production-release.yml
Reverts corn update [ should't havd merged to main until after daily release]
=> revert cron job

.github/PULL_REQUEST_TEMPLATE.md, src/applications/registry.json
Finalizing PACT Act wizard URL
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15669
Also includes an update for the content-build pull request template to match the vets-website template. @department-of-veterans-affairs/va-platform-cop-frontend please let me know if this is ok to update.
=> VACMS-15669 New PACT URL

.github/workflows/daily-production-release.yml
Updating the cron job to reflect Standard Time 2023.
=> Update cron job to standard time

src/site/layouts/vet_center_locations_list.drupal.liquid
- fix naked link, remove aria label, use va-link component instead of anchor tag
- Sitewide Facilities team
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15067
- _Optionally, provide a link to your [test plan](https://depo-platform-documentation.scrollhelp.site/developer-docs/create-a-test-plan-in-testrail) and [test execution records](https://depo-platform-documentation.scrollhelp.site/developer-docs/execute-tests-in-testrail)_
_Note: This field is mandatory for UI changes …
=> Fix naked link, remove aria label, use va-link component instead of anchor tag

src/applications/registry.json
This PR updates the application registry to enable production access of the 10-10EZR application.
department-of-veterans-affairs/va.gov-team#69557
- Application is successfully available in production
=> Enable 10-10EZR application for prod use

src/applications/registry.json
"Find a Representative" has a new rootUrl, appName, and entryName in its manifest.json file. This commit synchronizes `content-build`'s `registry.json` with those `vets-website` changes.
=> Updating "Find a Representative" registry entry

src/applications/registry.json
- Enable Prod route in app-registry for Presidential Memorial Certificate Request (40-0247)
- Flipper end-date TBD
[vets-api](https://github.com/department-of-veterans-affairs/vets-api/pull/14409)
[vets-website](https://github.com/department-of-veterans-affairs/vets-website/pull/26571)
- _Link to ticket created in va.gov-team-forms repo_
department-of-veterans-affairs/va.gov-team-forms#484
- N/A &mdash; just a config-file update
This form ONLY
=> 40-0247 - Enable prod-route in app-registry

src/applications/registry.json
This pull request updates the form 21-0966 Intent to File URLs.
- department-of-veterans-affairs/va.gov-team-forms#663
=> Update Form 21-0966 ITF URLs

.github/workflows/content-release.yml, script/github-actions/check-broken-links-blocks.js
Hopefully, this reports broken link numbers and doesn't break anything.
See department-of-veterans-affairs/va.gov-cms#13975.
=> VACMS-13975: Report broken link numbers in content release.

src/applications/registry.json
**URGENT**: @ndsprinkle / @Thrillberg , please ping Platform for early review & approve A.S.A.P.
- Disable Intent-to-file 21-0966 and Presidential Memorial Certificate 40-0247 form-apps in Production
- Flipper end-dates TBD
- N/A; I was just pinged on Slack by @megansiddle & @tbaker1026 to do this urgently.  
- N/A; just an app-registry update.
These 2 forms ONLY
=> [URGENT] Disable 21-0966 & 40-0247 form-apps in Prod

package.json, yarn.lock
=> Pin Cypress at 13.3.0 for a minute.

src/site/assets/sass/style.scss, src/site/includes/header.html, src/site/includes/metatags.drupal.liquid
Reverts department-of-veterans-affairs/content-build#1774
Relates to https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15318
=> Revert "VACMS-15339: Mobile promo banner"

src/applications/registry.json
Enabling Find a Representative to true - our application is currently being gated by both a feature flag as well as an environment check in the application's frontend. We are enabling the app in prod in preparation for next week's staged rollout.
=> Enabling vagovprod: true for Find a Representative

src/applications/registry.json
Updates AVS root url per https://dsva.slack.com/archives/C04UBETRY8N/p1696266645089739?thread_ts=1692218774.597929&cid=C04UBETRY8N
=> Update AVS root URL

src/site/stages/build/drupal/assets.js
Closes department-of-veterans-affairs/va.gov-cms#16376.
This needs a thorough review since it changes a piece of code that's been in place for like 5 years or smth.
=> Fix random acts of `/files/`.

.github/workflows/content-release.yml, script/github-actions/check-broken-links.js
=> Pass broken link numbers to Datadog.

src/site/includes/footer.html
Remove duplicate section tag that is no needed in the footer
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15568
- _Optionally, provide a link to your [test plan](https://depo-platform-documentation.scrollhelp.site/developer-docs/create-a-test-plan-in-tes …
=> VACMS-15568: Remove duplicate footer landmark

src/site/stages/build/drupal/graphql/vbaFacility.graphql.js
This pull request adds recent banner fields to the VBA Facility Query.
[department-of-veterans-affairs/va.gov-cms#14947](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14947)
In test environment, confirming the data is now present and build is successful.
N/A
The VBA Facility pages, but nothing visible.
=> [VA-14947] Add Banners to VBA Facility Query

src/applications/registry.json
- Removed some apps from the site map that IA requested to be removed
- 
No issue, but this was covered in a private Slack channel.
I am unsure how to test the site map locally; if guidance is provided, I would gladly do so.
N/A
Sitemap.
The marked apps are not in the site map
- CI passes
N/A
N/A
N/A
=> My health remove apps from sitemap

src/applications/registry.json
- Add new Priority Processing Request (20-10207) form to app-registry
- Flipper not implemented yet
- _Link to ticket created in va.gov-team-forms repo_
department-of-veterans-affairs/va.gov-team-forms#907
- Local browser-testing was successful
None
=> 20-10207 - Add new form-app to registry

src/site/assets/js/smartbanner/LICENSE.md, src/site/assets/js/smartbanner/README.md, src/site/assets/js/smartbanner/index.js, src/site/assets/js/smartbanner/smartbanner.js, src/site/assets/sass/style.scss, src/site/filters/liquid.js, src/site/includes/metatags.drupal.liquid
Implementing SmartBanner JS as raw Javascript & SCSS instead of including 3rd party libraries.
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15318
Testing on devices:
- iOS
- Safari (regression check for existing banner)
- Chrome
- Android
- Chrome
- Firefox
iOS Safari (regression check)
iOS Chrome
Android Chrome
Android Firefox
=> 15318 Mobile App promo banners for iOS Chrome and Android

src/applications/registry.json
> Add registry for submitted appeals view & download page - to be used for testing  
[#65936](https://github.com/department-of-veterans-affairs/va.gov-team/issues/65936)
Dependent on [#27453](https://github.com/department-of-veterans-affairs/vets-website/pull/27453) being merged
- …
=> Scaffold saved appeal view & download app

src/site/layouts/vba_facility.drupal.liquid
This is a small follow-up to the previous VBA Facility Service Template. A small header change found in the a11y review is all that's needed to finish the ticket. This pull request makes that final change.
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14942
N/A
*(Describe what …
=> [VA-14942]: VBA facility service content type II

src/site/filters/liquid.js, src/site/filters/liquid.unit.spec.js, src/site/layouts/vba_facility.drupal.liquid, src/site/stages/build/drupal/graphql/vbaFacility.graphql.js
Adds local spotlights to array of centralized spotlight
- VBA graphql was updated. VBA pages receive data about local spotlights. Liquid filter processes local spotlights to be in same format as centralized spotlight so existing liquid filters can process all spotlights.
- Testing added
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16922
- Liquid filter unit test created and passes
- VBA Page appears to render correctly and links from CTAs function on spotlights.
| Mobile  |  <img width="335" alt="Screenshot 2024-01-19 at 2 20 14 PM" …
=> VACMS 16922 add local spotlights

src/site/includes/detail-page.html, src/site/includes/education-sco.html, src/site/layouts/page-breadcrumbs.html
This PR adds the Medallia feedback button to the bottom of School Administrators landing page
URL: /school-administrators/
department-of-veterans-affairs/va.gov-team#74037
- viewed on review instance
| Mobile |<img width="744" alt="Screenshot 2024-01-23 at 11 05 52 AM" src="https://github.com/department-of-veterans-affairs/content-build/assets/11021491/b0d2aedb-bd2f-4370-acac-bd527606d453">|<img width="799" alt="Screenshot 2024-01-23 at 11 05 34 AM" src="https://github.com/department-of-veterans-affairs/content-build/assets/11021491/d59140e1-33a9-4d3e-b11a-4fa65e98f844">|
| Desktop |<img …
=> Add feedback button to School Administrators landing page

src/site/paragraphs/number_callout.drupal.liquid
The design system team has deprecated the Formation style for `.card` in favor of the [va-card ](https://design.va.gov/storybook/?path=/docs/components-va-card--default)web component.
This PR will replace instances of that CSS class so that it can be removed from Formation.
- https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2337
local build, visually.
http://localhost:3002/disability/how-to-file-claim/
**before**
**after**
Note:  …
=> Replace the deprecated `.card` style with va-card and utility classes

src/applications/registry.json
- Removes an extra 'Home' breadcrumb on the Pensions form.
- The 'Home' breadcrumb is automatically injected on the staging environment and therefor presumably the production environment, despite not being visible on the local environment.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/74796
- Manual testing
Pensions form 21-527EZ
=> Remove extra 'Home' breadcrumb on pensions form

src/site/filters/liquid.js, src/site/filters/liquid.unit.spec.js, src/site/includes/vba_facilities/service_location.liquid, src/site/includes/vba_facilities/services.liquid, src/site/layouts/tests/vba/template/fixtures/vba_complete.json, src/site/layouts/vba_facility.drupal.liquid, src/site/tests/vba/vba.unit.spec.js
- Updates [va-14957](https://github.com/department-of-veterans-affairs/content-build/pull/1880) to handle facilityService and regionalService representing the same service.
- Tests services liquid (Service Location paragraph)
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14936
- Created unit tests for VBA service locations
- Updating testing for liquid filters
<details>
<summary>Desktop Eli's tugboat content (with regional service and facility service with same name)</summary>
</details>
<details>
<summary>Mobile Max's tugboat content</summary>
</details>
Affects VBA facility pages.
Testing done for trimAndCamelCase, regional and facility service …
=> Vacms 14936 vba service location paragraph testing new

src/applications/registry.json
- Registers new appointment-travel-claim app
- [department-of-veterans-affairs/va.gov-team#75268](https://github.com/department-of-veterans-affairs/va.gov-team/issues/75268)
- Visual
Check in adds app to registry
=> Register new travel claim app

src/applications/registry.json
As we work with stakeholders to investigate electronic signatures, we need to temporarily disable form 20-10206.
department-of-veterans-affairs/va.gov-team-forms#1029
=> Disable form 20-10206 in production

src/site/layouts/campaign_landing_page.drupal.liquid
Update DST components for CLPs to V3
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16982
Tested locally at `/initiatives/sign-in-securely-with-logingov/`
=> VACMS-16982: CLP components to v3

src/site/paragraphs/collapsible_panel.drupal.liquid
Upgrade to v1 `<va-accordion>` within collapsible_panel.drupal.liquid template.
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16984
Tested on `/report-harassment`
=> VACMS-16984 v3 upgrades for FAQ page

src/site/layouts/faq_multiple_q_a.drupal.liquid, src/site/paragraphs/alert.drupal.liquid, src/site/paragraphs/q_a.collapsible_panel.drupal.liquid, src/site/paragraphs/q_a_group_collapsible_content.drupal.liquid
Update benefits detail page DST components to V3
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16980
Tested locally at `/health-care/get-reimbursed-for-travel-pay/`
=> VACMS-16980: Update Benefit Details Page components to v3

src/applications/registry.json
Adds burials V2 application, currently a clone of burials, with necessary differences created.
Related PR: https://github.com/department-of-veterans-affairs/vets-website/pull/27873
https://github.com/department-of-veterans-affairs/va.gov-team/issues/75226
Was able to proceed through burials v2 application on vets-website
=> Add burials v2 App to Registry

src/applications/registry.json
- Finalize root-URL for Priority Processing (20-10207)
- Flipper not implemented yet
- [vets-website](https://github.com/department-of-veterans-affairs/vets-website/pull/28063)
- [devops](https://github.com/department-of-veterans-affairs/devops/pull/14009)
- department-of-veterans-affairs/va.gov-team-forms#1026
- Local browser-testing was successful
This form ONLY
=> 20-10207 - Finalize root-URL and breadcrumbs

src/site/includes/vba_facilities/expandable_alert.liquid, src/site/layouts/vba_facility.drupal.liquid, src/site/stages/build/drupal/graphql/vbaFacility.graphql.js
VBA Facility pages have operating statuses that don't use expandable components, which link to a 404 page. This replaces it with an Expandable Alert component with additional info set for the facility.
[department-of-veterans-affairs/va.gov-cms#17103](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17103)
Locally on tugboat environment, see below screenshots from this URL: https://web-txcrk8bym4a0ivw3xfr8xvdhezmls36f.demo.cms.va.gov/cleveland-va-regional-benefit-office/locations/cleveland-va-regional-benefit-office/#location-and-contact-informati
| Mobile  |    <img …
=> [VA-17103] Add VBA Operating Status Component

src/site/stages/build/drupal/graphql/vbaFacility.graphql.js
This updates the VBA Service Location paragraph data in the VBA Facility query. It adds Office Visits and Virtual Support. Regional/Facility Service Headers and Descriptions are mentioned as well, but they were already added in a previous pull request - they're only tweaked to make the code more readable.
[department-of-veterans-affairs/va.gov-team#0000](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15959)
Local build to confirm the GraphQL queries run properly without crashing. Run the following command `yarn build --pull-drupal --drupal-address=https://cms-pr15622-xptmfsnjoodldn85nzgkrgljqtfbz24b.ci.cms.va.gov/ username=max.antonucci@agile6.com password=drupal8` and check that `Successfully piped Drupal content into …
=> [VA-15959] Update VBA Service Location query

package.json, src/site/includes/va_police/featured_content.liquid, yarn.lock
Update va-featured-content to va-summary-box. Update web component library to match
[[va-featured-content] - Update naming to Summary Box #2336](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2336)
=> Update va-featured-content to va-summary-box

src/site/layouts/faq_multiple_q_a.drupal.liquid, src/site/stages/build/drupal/graphql/faqMultipleQa.graphql.js
Update FAQs to allow for introductions for QA groups. Updated graphql and FAQ page template
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17319
Tested in tugboat instance
https://web-kfudy3zg0qvmsc9m9jbel8fibm9zf8sg.demo.cms.va.gov/resources/this-is-my-test-faq-page/
=> VACMS-17319: Update faqs introductions for qas

src/site/stages/build/drupal/graphql/vbaFacility.graphql.js
This **reverts** [the query added in this pull request in `main`](https://github.com/department-of-veterans-affairs/content-build/pull/1916) so it can instead [be added to the integration branch in this pull request.](url)
[department-of-veterans-affairs/va.gov-cms#15959](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15959)
Local build to confirm the GraphQL queries run properly without crashing. Run the following command `yarn build --pull-drupal --drupal-address=https://cms-pr15622-xptmfsnjoodldn85nzgkrgljqtfbz24b.ci.cms.va.gov/ username=max.antonucci@agile6.com password=drupal8` and check that `Successfully piped Drupal content into Metalsmith!` is returned to confirm that the queries run properly.
VBA Regional …
=> [VA-15959] Update VBA Service Location query (REVERT)

src/applications/registry.json
Summary
Add app registry entry for new Application for CHAMPVA Benefits Application (10-7959f-1) form-app.
Related issue(s)
https://github.com/department-of-veterans-affairs/vets-website/pull/27874
Testing done
N/A - This is just a new app-registry entry.
=> 10-7959f-1 Registration

src/applications/registry.json
Per Andrew's discovery in my Vets-Website PR's regarding the removal of apps that are no longer in use [here](https://github.com/department-of-veterans-affairs/vets-website/pull/28461#issuecomment-1988781699), this PR is to remove registry pages for apps to be deprecated.
We are operating under the impression that we need to reverse order of the creation of PR's [here](https://depo-platform-documentation.scrollhelp.site/developer-docs/creating-a-new-application#Creatinganewapplication-PRmergeorder) in order to proceed with their removal.
Frontend PR's to Remove Each App
[MCP](https://github.com/department-of-veterans-affairs/vets-website/pull/28461)
[LTR](https://github.com/department-of-veterans-affairs/vets-website/pull/28462)
department-of-veterans-affairs/va.gov-team#77329
Medical …
=> 77329 - [CDP] - Deprecate legacy applications

.github/workflows/daily-production-release.yml
Updating the cron job top reflect DST 2024.
=> update cron job for DST

src/site/filters/liquid.js, src/site/filters/liquid.unit.spec.js, src/site/includes/vba_facilities/spotlight_content.liquid
- Allows a CTA to be blank in the 
- Bug: create local VBA spotlight without CTA. Crashes on build
- Conditional to avoid destructuring CTA if it doesn't exist
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17500
- Added unit test for missing CTA
- Tested on tugboat with missing CTA
| Mobile  |    build error    |     <img width="334" alt="Screenshot 2024-03-12 at 2 33 27 PM" src="https://github.com/department-of-veterans-affairs/content-build/assets/5606931/59c24dee-b24c-45b2-9225-0fd7ae21fdd4"> |
| Desktop |    build error    |   <img width="696" alt="Screenshot 2024-03-12 at 2 33 21 PM" …
=> Working non-CTA'ed spotlight in VBA

src/site/blocks/promo.drupal.liquid, src/site/includes/benefit-hubs-links.drupal.liquid, src/site/includes/how-do-you-rate.drupal.liquid, src/site/layouts/va_form.drupal.liquid, src/site/paragraphs/lists_of_links.drupal.liquid
Add `disable-analytics` to DST web components that have custom events on them.
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17412
=> VACMS-17412 Analytics adjustments for components

src/site/assets/sass/style.scss, src/site/filters/liquid.js, src/site/filters/liquid.unit.spec.js, src/site/includes/medallia-feedback-button.drupal.liquid, src/site/layouts/campaign_landing_page.drupal.liquid
Update CLP links to use V3 components
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17178
Tested locally
=> VACMS-17178: Update CLP Links to V3 components

.github/workflows/continuous-integration.yml
Revert the concurrency rules for now
=> use original concurrency rules

src/site/includes/common-tasks.drupal.liquid, src/site/includes/email-update-signup.drupal.liquid, src/site/includes/hero.drupal.liquid, src/site/includes/homepage-benefits.drupal.liquid, src/site/includes/news-spotlight.drupal.liquid, src/site/includes/related-information.drupal.liquid
Upgrade all components to web components where possible on the home page.
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17277
Tested locally on the homepage.
=> VACMS-17277 Homepage web component upgrades

src/site/paragraphs/service_location.drupal.liquid
Service location services that have referrals shouldn't include them when the referral field has an unspecified or unknown value. This adds an extra conditional to exclude them in those contexts. This is being merged as part of the Service Location Paragraph updates which have not yet been added to main on the CMS or front-end side.
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17513
N/A can't be tested due to the CMS changes not yet being merged.
=> [VACMS-17513] Remove Unspecified Referrals from Service Location front-end

src/applications/registry.json
- Updated the breadcrumb for the Burials application(s)
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/75953#issuecomment-2018569294
- Manual / Axe
- This only affects the Burials applications
=> NDBEX 63351: Added breadcrumb

src/applications/registry.json
I added the new mhv medical records test app to registry.json. This app is the same app that exists in the vets-website repo at src/applications/mhv/medical-records. It has been copied to src/applications/mhv-medical-records to enable isolated app deployments. This current configuration is a test that will be replaced with the real app after it has been tested. 
https://jira.devops.va.gov/browse/MHV-56245
> ### Isolated Apps - MR - Set up the new app as a test app
> Description
> Isolated Apps - MR - Set up the new app as a test app
Local testing of the new Medical records app and all existing unit tests has been done. 
No UI changes.
MHV Medical records new test app
MHV Medical records new test app has been added to registry.json for testing. 
(OPTIONAL) _What should the reviewers know …
=> MHV-56245: Added mhv mr test app to registry

src/site/paragraphs/service_location.drupal.liquid, src/site/paragraphs/tests/vamc/vamc_field_service_location.unit.spec.js
- Makes conditional for appointment phone numbers or main phone number and conditional for contact phone numbers or main phone number.
- Adds conditional logic
- Sitewide Facilties
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17511
- Updated tests to support conditional logic and test for conditions of presence for phone numbers
- Tested local content-build on Service Location Integration Branch data from Cleveland VBA which has numerous possible conditions
- Tested local content-build on `/washington-dc-health-care/locations/washington-va-medical-center/`
<details>
<summary>Old Service Location Branch</summary>
</details>
<details>
<summary>New Desktop</summary> …
=> Shows main phone or appt phone numbers and shows main phone or contact phone numbers

src/applications/registry.json
This PR updates the root url of form app 10-10d per guidance from our product team.
- Updated URL in registry
- Flipper: NA
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/78843
- Manual
Form app 10-10d only
NA
=> Update root url of form 10-10d

src/applications/registry.json
- Updates V1 breadcrumb to be identical to V2
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/63351
- Axe
=> NDBEX-63351: Updated v1 breadcrumb

src/applications/registry.json
- part of isolated app deploy migration of MHV SM on va.gov
- changing app `entryName` to point app `rootUrl` to the new directory codebase
- https://github.com/department-of-veterans-affairs/vets-website/pull/28703
- _Optionally, provide a link to your [test plan](https://depo-platform-documentation.scrollhelp.site/developer-docs/create-a-test-plan-in-testrail) and [test execution records](https://depo-platform-documentation.scrollhelp.site/developer-docs/execute-tests-in-testrail)_
_Note: This field is …
=> MHV-55409 change app entryName for MHV SM to isolated codebase

src/site/includes/accredited_representative_portal/header.html
ARP intends to operate with a distinct style as per user requirements. To this end, we are anticipating the differing styles with unique templates in `content-build`. This ticket/PR concerns the header, specifically. At this time, 
Issue: [77781](https://app.zenhub.com/workspaces/accredited-representative-facing-team-65453a97a9cc36069a2ad1d6/issues/gh/department-of-veterans-affairs/va.gov-team/77781)
- Linked locally via layout template file, expecting and receiving same behavior.
At this point, I believe we do not need to remove code - but we will need to edit/add when we have appropriate design content that defines our specific header.  I think this will be an included part of future tickets. Appreciate any …
=> Copy header code from content-build template for ARF app

src/site/assets/sass/style.scss, src/site/includes/email-update-signup.drupal.liquid, src/site/includes/tests/homepage.cypress.spec.js
The email signup form at the bottom of the VA homepage needed to be converted to use web components. This was part of a previous ticket to convert all items to v3 web components for the homepage, but it turned out to be a bit bigger of a testing effort so we broke off this piece.
The markup has been cleaned up a bit to remove extra `div`s.
**Note**: We cannot convert the `<button>` to `<va-button>` yet because the `submit` property on the web component is not working correctly and does not submit the form.
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17568
Tested locally.
AC1: Veteran, their family member, caregiver or survivor successfully signs up for VA updates
GIVEN: A Veteran, their family member, caregiver or survivor has entered their email address in the …
=> VACMS-17568 Email signup web components

src/site/facilities/facility_health_service.drupal.liquid, src/site/layouts/health_care_local_facility.drupal.liquid
- Changes accordions on health_care_local_facility nodes to v3 components.
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16963
- Tested locally that accordions updated
<details>
<summary>current accordions desktop</summary>
</details>
<details>
<summary>updated accordions desktop</summary>
</details>
<details>
<summary>current accordions mobile</summary>
</details>
<details>
<summary>updated accordions mobile</summary>
</details>
Review:
- http://6eda503f9392a95d7c7ced9386a97212.review.vetsgov-internal/boston-health-care/locations/jamaica-plain-va-medical-center/
- …
=> V3 Accordions in VAMC Facility Pages

src/site/includes/operating_status_expandable_alert.liquid, src/site/includes/vet_centers/address_phone_image.liquid, src/site/layouts/tests/vet_center/template/fixtures/operating_statuses.json, src/site/layouts/tests/vet_center/vet_center_locations_operating_status.unit.spec.js, src/site/stages/build/drupal/graphql/vetCenterLocations.graphql.js
- Vet Center Locations page was showing 
- Go to many Vet Center Locations pages and see Mobile section with empty expandable alerts
- Add conditionals to prevent unnecessary components from being added
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17829
- Mobile Vet Centers were displaying empty operating status expandable alerts
- Tested locally
- Added testing for operating status fields being present or not
<details>
<summary>Before mobile</summary>
</details>
<details>
<summary>Before desktop</summary>
</details>
<details>
<summary>Updated desktop - with Mobile Vet Centers</summary>
</details>
<details>
<summary>Updated desktop - with nearby …
=> VACMS 17829 Only show expandable operating statuses for Vet Centers with Operating Status fields

src/applications/registry.json
This updates the breadcrumbs for form 20-10207.
department-of-veterans-affairs/va.gov-team-forms#1205
=> Update 10207 breadcrumbs

src/applications/registry.json
This enables form 20-10207 in production.
department-of-veterans-affairs/va.gov-team-forms#1201
=> Enable form 20-10207 in production

src/site/filters/liquid.js, src/site/paragraphs/service_location.drupal.liquid
Service Location integration branch target
- Updated office visits and virtual support to new values and icons.
- https://app.zenhub.com/workspaces/sitewide-facilities-639f5253e4b702a32376339e/issues/gh/department-of-veterans-affairs/va.gov-cms/17844
- Tested with local release and tugboat release of content with all possible conditions
| Mobile  |        |   ![alltypes-office-visits-virtual-mobile](https://github.com/department-of-veterans-affairs/content-build/assets/5606931/4f3a5cc5-c5d7-48c2-a803-03c8b916c4ce)    |
| Desktop |        |   ![alltypes-office-visits-virtual](https://github.com/department-of-veterans …
=> VACMS 17844 update service options values for office visits and virtual support

src/applications/registry.json
- Add new Statement in Support of a Claim (21-4138) form to app-registry
- Flipper not implemented yet
- _Link to ticket created in va.gov-team-forms repo_
department-of-veterans-affairs/va.gov-team-forms#1171
- Local browser-testing was successful
None
=> 21-4138 - scaffold new form app

src/applications/registry.json
This PR adds an entry to registry.json for newly generated IVC CHAMPVA form 10-7959a.
- Added registry entry
- Flipper: NA
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/80963
- https://github.com/department-of-veterans-affairs/vets-website/pull/29380
- Manual verification
This form only
NA
=> added registry entry for form 107959a

package.json, yarn.lock
Mitigates https://github.com/department-of-veterans-affairs/content-build/security/dependabot/81
- tests using chai complete without issue
https://github.com/department-of-veterans-affairs/content-build/actions/runs/8885225443?pr=2041#summary-24396628731
=> Updates chai to get updated get-func-name.

package.json, yarn.lock
Updates web-components to v7.2.1; corrects error with component-docs.json
=> update web-component dependency

src/site/layouts/tests/vet_center/template/fixtures/operating_statuses.json, src/site/stages/build/drupal/graphql/vbaFacility.graphql.js
VBA Services can include published and unpublished items. This change filters out the unpublished ones.
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17599
Tugboat environment. I confirmed three total regional services with one unpublished (first screenshot), but the updated query only returns the two published ones (second screenshot).
=> [VA-17599] Filter out unpublished VBA services

src/site/layouts/person_profile.drupal.liquid, src/site/teasers/bio.drupal.liquid
Add web components in staff profiles wherever possible.
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17066
<details><summary>/southern-nevada-health-care/staff-profiles/charles-ramey-0/</summary>
</details>
<details><summary>/minneapolis-health-care/about-us/leadership/</summary>
</details>
<details><summary>/battle-creek-health-care/staff-profiles/michelle-martin/</summary>
</details>
=> VACMS-17066 Staff Profiles web components

README.md, src/site/layouts/press_release.drupal.liquid, src/site/layouts/press_releases_listing.drupal.liquid
Add web components where possible on the News Releases search results page and the detail pages.
I also added a new section to the README for this repository and updated the `DRUPAL_ADDRESS` that no longer works.
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17068
Tested locally on these pages:
<details><summary>/minneapolis-health-care/news-releases/</summary>
</details>
<details><summary>/minneapolis-health-care/news-releases/st-james-va-community-clinic-ribbon-cutting-ceremony/</summary>
</details>
<details><summary>
/boston-health-care/news-releases/va-new-england-announces-new-deputy-executive-director/</summary>
</details>
<details><summary>
/boston-health-care/news-releases/6-million-intimate-partner-violence-intervention-study-approved/</summary>
</details>
=> VACMS-17068 News Releases web components

.github/workflows/content-release.yml
=> add debug info to content build runner and do some large file cleanup

src/site/layouts/vamc_system_policies_page.drupal.liquid
Adds a Back to Top component to VAMC policy pages.
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16953
Tested locally at `/boston-health-care/policies`
=> VACMS-16953 VAMC Policies web components

src/site/includes/vet_centers/featured_content.liquid
-Modifies the featured content component for vet centers to use the va-card web component.
- Some style classes modified for new card styling
- 
-  https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17618
- Test suite ran locally
- Local visual testing
urls used for testing:
- `/boston-health-care/medical-records-office/`
- `/pittsburgh-vet-center/`
(OPTIONAL) _What …
=> Add card web component to vet center featured-content

src/site/components/merger-social-sco.html
- Added space between list items
- Used Liquid and VADS classes
- I work for VA IIR, and we own the [Resources for Schools](https://www.va.gov/school-administrators/) site
- Related to [#935](https://github.com/department-of-veterans-affairs/vagov-content/pull/935)
- ZenHub ticket: [#640](https://app.zenhub.com/workspaces/va-iir-6508c0bd79e64e0fb5855caf/issues/gh/department-of-veterans-affairs/va-iir/640)
- Manually confirmed that spacing exists on the correct list items and no others. See screenshots.
| ------- | ------ | ----- …
=> RELEASE 1.2.0

src/site/stages/build/silversmith.js
- Content-build fails due to process.memoryUsage errors because not handled gracefully
- Build PR 1912 on tugboat
- Surround process.memoryUsage calls with try/catch
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18069
- Tested locally
- Tested on build that was failing on tugboat due to EMFILE errors
N/A
Result of build with errors, but succeeding:
```
Step 44 end [7804ms]: Apply layouts Z
Step 45 of 54 start: Apply layouts 0-9.-_~!$&'()*+,;=:@
Error getting memBefore memory usage: Error: EMFILE: too many open files, uv_resident_set_memory
at process.memoryUsage (internal/process/per_thread.js:153:5)
at Timeout._onTimeout (/var/lib/tugboat/docroot/vendor/va-gov/content-build/src/site/stages/build/silversmith.js:182:31)
at listOnTimeout …
```
=> Log errors but do not halt on process.memoryUsage errors

src/site/layouts/health_care_local_facility.drupal.liquid
- Forgot part of the path to view the variable for the VA Connect Phone Number 
- Add the parent object path
- Sitewide facilities
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16148
- Missing VA Health Connect phone number in `src/site/layouts/health_care_local_facility.drupal.liquid`
- Check RI for VA Health Connect Phone number on `/texas-valley-health-care/locations/corpus-christi-va-mobile-clinic/`
| Desktop | ![Screenshot 2024-05-08 at 1 12 00 PM](https://github.com/department-of-veterans-affairs/content-build/assets/5606931/683bb597-2d64-46c1-bbb5-d2678c3cf029)   | …
=> VACMS 16148 - fix VA Health Connect number not displaying

src/site/includes/vba_facilities/services.liquid
[The previous pull request](https://github.com/department-of-veterans-affairs/content-build/pull/2057) for this ticket missed adding a small static paragraph to the section for managing benefits. This adds it in.
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17598
Visual, see previous pull request.
* [Link to Tugboat CMS where services were updated.](https://cms-txcrk8bym4a0ivw3xfr8xvdhezmls36f.demo.cms.va.gov/admin/structure/taxonomy/manage/health_care_service_taxonomy/overview?page=1)
* …
=> [VA-17598] Show VBA "Manage Your Benefits Online" Missing Paragraph

src/site/includes/hours-item.liquid
- If starthours and endhours are both 0 (midnight), and no comment exists, display Open 24hours
- Prior was showing closed
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17415
- Tested on CMS content in tugboat
- Check https://web-ihqrv6rby5lxlkn8zqdxf9u7lk1aplcp.demo.cms.va.gov/oklahoma-city-health-care/billing-and-insurance/ top Service Location
| Mobile  |    ![Screenshot 2024-05-13 at 5 23 37 PM](https://github.com/department-of-veterans-affairs/content-build/assets/5606931/b572bffc-aeea-4f99-8d06-176129317e48)    |    ![Screenshot 2024-05-13 at 5 22 …
=> VACMS 17415 - Open 24 hours

src/applications/registry.json
- Updates base url for 21-4138 to align with CAIA feedback
- Configured form 21-4138 to utilize new custom link logic
- Flipper not implemented
- department-of-veterans-affairs/va.gov-team#82269
- Local browser functions successfully
- Unit tests successful
- E2E tests successful
This form ONLY.
=> [SIMPLE_FORMS] fix: 21-4138 - update all urls to align with feedback

src/applications/registry.json
- - This change is to update the root URL for the new application being built called Verify Your Enrollment for the MGIB chapters 30, and 1606
- _(If bug, how to reproduce)_ NA
- - The solution is to update the root URL from `education/verify-your-enrollment` to `education/verify-your-enrollment/mgib-verification` 
- I work for GovCIO and we are the code owners of this application
- No flipper. Application has not been launched in Prod. It's only in staging.
Slack conversation for …
=> VYE-386 update Root URL for Verify Your Enrollment application

src/site/assets/sass/style.scss, src/site/facilities/facility_health_service.drupal.liquid, src/site/facilities/facility_social_links.drupal.liquid, src/site/layouts/health_care_local_facility.drupal.liquid, src/site/layouts/landing_page.drupal.liquid, src/site/paragraphs/facilities/list_of_link_teasers_facility.drupal.liquid, src/site/paragraphs/service_location.drupal.liquid
Add v1 and v3 web components to VAMC Facility pages where possible. Also changes the Spotlight section to follow the Related Links pattern.
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17654
Tested the following routes locally:
- /boston-health-care/locations/jamaica-plain-va-medical-center
- /minneapolis-health-care/locations/minneapolis-va-medical-center/
- /central-texas-health-care/locations/cedar-park-va-clinic/
- /columbia-south-carolina-health-care/locations/wm-jennings-bryan-dorn-department-of-veterans-affairs-medical-center/
- /southern-nevada-health-care/locations/southwest-las-vegas-va-clinic/
- /pacific-islands-health-care/locations/spark-m-matsunaga-department-of-veterans-affairs-medical-center/
<details><summary>Social media icons (Get updates …
=> VACMS-17654 VAMC Facilities web components

src/site/assets/sass/style.scss, src/site/facilities/health_service.drupal.liquid, src/site/layouts/health_services_listing.drupal.liquid, src/site/paragraphs/link_teaser_featured_content.drupal.liquid
- Switches <a> to action link
- switches spotlight <li> to va-card, and adjusts parent component to match
- Adds a spotlight-cards css class for managing width on spotlight va-card copmonents
- adds back-to-top component
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17657
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18126
- Local testing at `/boston-health-care/health-services/`
(OPTIONAL) _What should the reviewers know in …
=> health services component migration

src/site/facilities/vha_facility_nonclinical_services.drupal.liquid, src/site/layouts/health_services_listing.drupal.liquid, src/site/layouts/vamc_system_billing_insurance.drupal.liquid, src/site/layouts/vamc_system_medical_records_offi.drupal.liquid, src/site/layouts/vamc_system_register_for_care.drupal.liquid
- adds top of page component to register for care template
- switches facility name to use va-link component
- remove extra spacing for on this page component on mobile
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16957
- Local testing
- `/minneapolis-health-care/billing-and-insurance/`
- `/minneapolis-health-care/medical-records-office/`
- `/boston-health-care/register-for-care/`
(OPTIONAL) _What should the reviewers know in addition to the above. Is …
=> top tasks and link v3 migration

src/site/paragraphs/service_location.drupal.liquid
- Ensure service locations use phone.drupal.liquid for arrays of phoneNumber paragraphs
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18131
- Service location paragraphs were not using all relevant data
- Reviewed phone numbers of all types in service locations of both clinical and non-clinical services
<details>
<summary>Before Clinical with Fax condition</summary>
</details>
<details>
<summary>Updated Clinical with extra conditions</summary>
</details>
<details>
<summary>Updated non-clinical</summary>
</details>
Service Locations in VAMC/VBA
View 
on tugboat:https://web-codylbelkq0gdivw6x7tykigmeqloewe.demo.cms.va.gov/ …
=> VACMS 18131 - Use phone.drupal.liquid

src/site/facilities/story_social_share.drupal.liquid, src/site/layouts/news_story.drupal.liquid, src/site/teasers/news_story_page.drupal.liquid
- v3 components for stories social share
- v3 component for see all stories active link
Also includes encoding for the title of the news story link.
- https://github.com/department-of-veterans-affairs/content-build/compare/17067-stories-v3-components?expand=1
Locally at `/minneapolis-health-care/stories` and `/minneapolis-health-care/stories/its-2024-time-to-make-your-new-years-intentions/`, and also `/indiana-health-care/stories` for the double quotes fix.
=> VACMS-17067 News stories v3 web components

README.md, src/site/filters/liquid.js, src/site/includes/common-tasks.drupal.liquid, src/site/includes/homepage-benefits.drupal.liquid, src/site/includes/news-spotlight.drupal.liquid, src/site/layouts/home.html
Upgrade all homepage icons to use `va-icon`. Also adds white links for va-link in the News Spotlight section.
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17820
Tested locally on the homepage.
<details><summary>White links in the news section</summary>
</details>
<details><summary>Common tasks (search tools)</summary>
</details>
<details><summary>Hub Icons</summary>
</details>
=> VACMS-17820 Homepage va-icon upgrades

.gitignore, .vscode/README.md, .vscode/settings.json, src/applications/registry-schema.json, src/applications/registry.json, src/site/includes/header-minimal.html, src/site/includes/header.html
- Add minimal header
- Add intellisense for registry file, so we get autocomplete for all possible values, and warnings for incorrect keys
department-of-veterans-affairs/va.gov-team-forms#1264
Corresponding vets-website change: https://github.com/department-of-veterans-affairs/vets-website/pull/29962
- Browser testing
=> Add minimal header and add intellisense for registry

src/site/includes/social-share.drupal.liquid
- Changes va-link component to instead use a seperate va-icon for event social links
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18243
- Local visual testing (http://localhost:3002/outreach-and-events/events/68114/)
- confirmed in RI
=> 18243 event calendar icon

src/applications/registry.json
Updates check-in applications to use new minimal header option.
Apps:
- check-in
- pre-check-in
- travel-claim (not in production yet)
department-of-veterans-affairs/va.gov-team#84343
Visual testing on local environment
- check-in
- pre-check-in
- travel-claim
=> updates check-in apps to use minimal header.

src/applications/registry.json
> Updated all Decision Review forms (HLR, NOD & SC) to use `va-breadcrumbs` within each app ([merged PR](https://github.com/department-of-veterans-affairs/vets-website/pull/30184)). CMS 
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/83774
- https://github.com/department-of-veterans-affairs/vets-website/pull/30184
- _Describe the steps required to verify your changes …
=> Remove HLR, NOD & SC breadcrumbs

src/site/layouts/press_release.drupal.liquid, src/site/paragraphs/media.drupal.liquid
Update fontawesome icons to va-icons for VAMCs. Was able to tackle the press releases print button in issue 17914 as well since it was listed as an AC in the original VAMC ticket. 
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17855
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17914
Tested locally
`/boston-health-care/news-releases/trust-increases-among-va-bostons-veteran-patients/`
(OPTIONAL) _What should the reviewers know in …
=> VACMS-17855: Update icons and print button for VAMCs

src/applications/registry.json
- Changes naming convention from `25-8832` to `27-8832` on the FE only
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/78359
- Manual / Unit / E2E / Axe
=> NDBEX 78359: Change breadcrumb to 27-8832

src/site/blocks/promo.drupal.liquid, src/site/components/merger-promo.html, src/site/layouts/landing_page.drupal.liquid
The Design System team has added the link origin to `va-link` analytics, so we're able to remove custom events from our `va-link`s across products.
For Benefit Hub landing pages, that includes the promo block and social media/contact links in the right rail as well as the links in the `Other VA benefits and services` block at the bottom of the page.
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18185
Tested locally on `/health-care` and `/education`.
<details><summary>Promo block</summary>
</details>
<details><summary>Email contact</summary>
</details>
<details><summary>Twitter</summary>
</details>
<details><summary>Facebook</summary>
</details>
<details><summary>YouTube</summary>
</details>
<details><summary>Instagram</summary>
</details> …
=> VACMS-18185 Removing custom events on Benefit Hub landing pages

src/site/layouts/basic_landing_page.drupal.liquid, src/site/layouts/faq_multiple_q_a.drupal.liquid, src/site/layouts/landing_page.drupal.liquid, src/site/layouts/page.drupal.liquid, src/site/layouts/support_resources_detail_page.drupal.liquid, src/site/layouts/vamc_operating_status_and_alerts.drupal.liquid, src/site/layouts/vamc_system_policies_page.drupal.liquid, src/site/layouts/vamc_system_va_police.drupal.liquid, src/site/layouts/vba_facility.drupal.liquid, src/site/layouts/vet_center.drupal.liquid
Remove css classes that added left margin to the va-on-this-page component.
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18270
- faq_multiple_q_a.drupal.liquid - `/resources/verifying-your-identity-on-vagov/`
- landing_page.drupal.liquid - `/service-member-benefits/`
- page.drupal.liquid`- /records/get-military-service-records/`
- support_resources_detail_page.drupal.liquid - `/tuscaloosa-health-care/operating-status/`
- vamc_system_policies_page.drupal.liquid - `/puget-sound-health-care/policies/`
- vamc_system_va_police.drupal.liquid - `/puget-sound-health-care/va-police/`
- vba_facility.drupal.liquid-  No prod examples. Locally: `yarn preview` and use http://localhost:3002/preview?nodeId=4171
- vet_center.drupal.liquid - `/bangor-vet-center`
Few Examples …
=> VACMS-18279: Remove classes from va-on-this-page to remove left margin on smaller screens

src/site/layouts/vba_facility.drupal.liquid
- Makes link to find-locations have type associated on load
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18219
- Link goes to /find-locations with benefits type pre-selected
- Go to Cleveland VBA page on tugboat and click link for other locations (manual testing)
<details>
<summary>Former link behavior</summary>
</details>
<details>
<summary>Updated link behavior</summary>
</details>
VBA Pages (pre-production)
Go to …
=> Link on VBA links to benefits prefiltered find-locations

src/applications/registry.json
This enables form 10206 in production. In vets-website, this form is behind a feature flag and will be set to 0% until Thursday.
(will attach related issue when it is created)
department-of-veterans-affairs/va.gov-team-forms#1397
=> Update registry.json to enable form 10206

src/applications/registry.json
- Enables AVS app in production
=> Enable AVS app in prod

src/site/stages/build/drupal/graphql/vbaFacility.graphql.js
- Adds a limit to increase default limit from 10 to 500
- VBA was ignoring some services because of limits
- Sitewide facilities
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18214
- Local manual testing since this is a drupal GQL change
<details>
<summary>Current- From CMS PR Tugboat</summary>
</details>
<details>
<summary>PR - Local</summary>
</details>
VBA Pages (pre-production)
Review image that the true number of Services displayed …
=> VACMS 18214 Limits to avoid default 10 items returned on GQL sub queries on VBA services

package.json, yarn.lock
Updates web components to v10. Release notes for inclusive component library 42.2.0 release here - https://github.com/department-of-veterans-affairs/component-library/releases/tag/v42.2.0
=> update web components to v10

src/site/paragraphs/service_location.drupal.liquid
- Separate default text when service location type is VBA.
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18273
- Checked manually on tugboat with Philadelphia Health Care and Philadelphia VBA
- Checked that custom texts still work and removed texts still work on both VBA and VAMC
<details>
<summary>Default Text VBA</summary>
</details>
<details>
<summary>Default Text VAMC</summary>
</details>
<details>
<summary>Customized Text VBA</summary>
</details>
<details>
<summary>Customized Text VAMC</summary>
</details>
<details>
<summary>Remove Text VBA</summary>
</details>
<details>
<summary>Remove Text VAMC</summary>
</details>
VBA is the only place where change will happen and none are in production yet. Changes can be seen in tugboat on VBA …
=> VACMS 18273 - Separate default texts for VBA and VAMC

src/applications/registry.json
- Updates registry.json to remove 'health-care' from 10-10d's base url
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/82997
- https://github.com/department-of-veterans-affairs/vets-website/pull/30538
- manual
this form only
=> Update base URL of form 10-10d

src/applications/registry.json
- Adds registry.json entry for burials EZ
- Related vets-website PR: https://github.com/department-of-veterans-affairs/vets-website/pull/30451
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/76700
- Burials v2 application is live when related vets-website PR is checked out
Burials
=> Add Burials EZ

src/applications/registry.json
Removed entry for unused form app. This application will need to be removed on vets-website following the merge of this PR. It is reaching out to vets-json-schema referencing an ID which is no longer present in that repo.
=> Deleting content build entry for old iteration of search-representative

src/site/filters/liquid.js, src/site/filters/liquid.unit.spec.js, src/site/paragraphs/service_location.drupal.liquid, src/site/stages/build/drupal/graphql/vbaFacility.graphql.js
- Moves conditionals above header so that determination whether to show the subsequent sections can be used whether to show the header. Adds several liquid filters for handling assignment with `or` or `and` conditions of multiple dependencies. As a result of new conditionals, now phone numbers appear.
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17925
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18220
- Tested on VBA pages and VAMC pages manually
- Existing VAMC pages appear as before. VBA pages with specific information withheld do not show the Appointments header
- Tests still run. Added test for orFn and andFn
<details>
<summary>VAMC in PR (unchanged)</summary>
1. <img width="787" alt="Screenshot 2024-07-01 at 1 37 …
=> VACMS 17925 and 18220 - Removes Appointments header when no relevant sub-info and Shows Phone Numbers for Appointments

src/applications/registry.json
- - Registry.json file updated for Verify Your Enrollment to prep for prod initial push. TJe vagovprod boolean value has been changed from 'false' to 'true'
- _(If bug, how to reproduce)_NA
- - This change is to push Verify Your Enrollment into production
- - I work for GOVCIO we are the owners of the Verify Your Enrollment application
-- Flipper is in use with no end date set
Jira ticket  https://jira.devops.va.gov/browse/VYE-449
Staging Review …
=> Initial push to prod

src/applications/registry.json
Reverts department-of-veterans-affairs/content-build#2161
https://dsva.slack.com/archives/CBU0KDSB1/p1720197718215509
=> Revert "Remove old supply reordering entry"

src/site/stages/build/drupal/graphql/navigation-fragments/sidebar.nav.graphql.js, src/site/stages/build/drupal/page.js, src/site/utilities/query-params/hubNavNames.json
Adds sidebar for Family Member Benefits Hub.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/86962
Tested locally after making changes to the underlying menu structure necessary for sidebar rendering.
| Mobile  |    <img width="227" alt="Screenshot 2024-07-03 at 11 15 42 AM" src="https://github.com/department-of-veterans-affairs/content-build/assets/221539/13652692-fa24-40fd-8da1-7b4359ca242c"> | <img width="228" alt="Screenshot 2024-07-03 at 11 15 53 AM" src="https://github.com/department-of-veterans-affairs/content-build/assets/221539/1f2c7f34-c226-4b81-ae96-e4be6df2f202">  |
| Desktop |   <img width="1170" alt="Screenshot 2024-07-03 at 11 15 09 AM" src="https://github.com/department-of-veterans-affairs/conten …
=> VATEAM-86962: Family member benefit sidebar

src/applications/registry.json
> - Consolidate existing testing apps in a root folder `decision-reviews/testing`
> - Add new HLR update testing app
> - These apps won't ever be released directly to production
[#85851](https://github.com/department-of-veterans-affairs/va.gov-team/issues/85851)
> Separate URLs made it difficult to track which testing apps were available
- _Describe the steps …
=> Move appeals testing apps

package.json, yarn.lock
Updates the web components dependency in content-build
=> update web components version

src/applications/registry.json
This PR updates the base URL for form 10-7959a.
- Flipper: NA
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/83365
- manual
=> 83365 Update base url - form 10-7959a

src/site/facilities/service_address.drupal.liquid, src/site/paragraphs/service_location.drupal.liquid
- Addresses were hidden if not using the facility address because the wrong fields were being used. This also affected VAMCs in addition to VBAs.
- Use the correct field values and test that both using facility address and not render correctly with or without a clinic name.
- Sitewide
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17973
- Missing address from service locations
- Manually: Check a service location which has `Use the facility's street address? Off` and has an address (with or without clinic name). Check a service which has `Use the facility's street address? On` and has a building information. Check a service locaiton which has `Use the facility's street address? On` and has no building information.
<details>
<summary>Custom address w Clinic Name, do …
=> VACMS 17973 custom address not showing

src/applications/registry.json
- Change page title of the Travel Pay Claims page according to staging review
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/87879
- Page title changed appropriately locally
=> BTSSS-87879: Change title tag for btsss page

src/applications/registry.json
This PR updates the base URL for IVC form 10-7959c.
- Flipper: NA
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/83567
- https://github.com/department-of-veterans-affairs/vets-website/pull/30891
- Manual
NA
This form only
NA
=> 83567 Update base url in registry.json - form 10-7959c

src/site/includes/footer.html
This PR updates the hidden text with VA's mission in the VA.gov footer to align with [VA's new mission statement](https://dvagov.sharepoint.com/sites/vhaoivc/SitePages/New-VA-mission-statement-promotes-gender-diversity.aspx).
- [Slack thread (private)](https://dsva.slack.com/archives/C9TV2B50E/p1721249655544419)
| Desktop |    ![image](https://github.com/user-attachments/assets/d701ec2b-b6d2-4443-bf13-3285d6548e96)    |   ![image](https://github.com/user-attachments/assets/0540a2b4-3377-4149-8149-78dd087aca46)    |
- hidden text in site footer
=> Update mission statement in footer

src/applications/registry.json
Add `SCO Resources for schools` to registry.json per `yarn new:app` generator
SCO is part of an initiative to migrate the legacy https://www.va.gov/school-administrators/ mardown filte to vets-website react. This PR connects the folder structure that has been created in the vets-website (related PR below)
https://github.com/department-of-veterans-affairs/vets-website/pull/30874
https://jira.devops.va.gov/browse/VFEP-983
- _Optionally, provide a link to your [test …
=> VFEP-1602 Create registry.json object for new sco page.

src/applications/registry.json
Adds a registry entry for the newly created form-renderer app in vets-website. **This needs to be merged _after_ the [related vets-website PR](https://github.com/department-of-veterans-affairs/vets-website/pull/30950).**
https://github.com/department-of-veterans-affairs/va.gov-team/issues/88669
None. This is simply a registry addition.
N/A
N/A
N/A
=> 88669: Registry addition for new form-renderer app

src/applications/registry.json
Team: Authenticated Experience Design Patterns
Adds a registry entry for the newly created mock form ae design patterns app in vets-website. This needs to be merged after the related [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/31004) for vets-website
https://github.com/department-of-veterans-affairs/tmf-auth-exp-design-patterns/issues/32
No additional testing needed.
N/A
N/A
=> #32-Added mock form ae design patterns app in registry.json

package.json, yarn.lock
- Updating the web components package
None
- None
N/A
None
None
=> Web Component package version bump

src/applications/registry.json
- Add minimal header example form
department-of-veterans-affairs/va.gov-team-forms#1475
- Test new form and confirm minimal header shows up
(with vets-website changes)
Only this form
=> Add minimal header example form

src/applications/registry.json
Add 22-1919 Designation Of Certifying Official(S) to registry.json per yarn new:app generator
22-1919 is part of an initiative to digitize 17 new education forms. This PR connects the folder structure that has been created in the vets-website (related PR below)
- _(If using a flipper, what is the end date of the flipper being …
=> Added 22-1919 form

src/applications/registry.json
Add 22-8794 Designation Of Certifying Official(S) to registry.json per yarn new:app generator
22-8794 is part of an initiative to digitize 17 new education forms. This PR connects the folder structure that has been created in the vets-website (related PR below)
- _(If using a flipper, what is the end date of the flipper being …
=> added new form for 22-8794

src/site/includes/decision-reviews-rum.html
> Wrap Decision Review DataDog Real User Monitoring (RUM) initialization code inside a window load event. The script is deferred, so we want to ensure it's loaded before the initialization code is run
> `cmsFeatureFlags.FEATURE_DECISION_REVIEW_RUM`
[#83078](https://github.com/department-of-veterans-affairs/va.gov-team/issues/83078)
- _Describe the steps required to …
=> DR | Wrap RUM init in window load

src/applications/registry.json
> Two changes within this PR:
> - Remove `/testing/` subpath from 3 non-production apps we've been testing
> - Add new Supplemental Claim testing app
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/89715
- https://github.com/department-of-veterans-affairs/vets-website/pull/31192
- https://github.com/department-of-veterans-affairs/vsp-platform-revproxy/pull/526
- _Describe what the old behavior was …
=> Fix DR testing paths & add new SC testing app

src/applications/registry.json
- removes burials & burials ez entries
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/76700
(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do you have any …
=> 76700 Remove burials, burials v2

src/site/layouts/health_care_region_page.drupal.liquid
- Removed all disable-analytics attributes and custom recordEvents triggers
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18510
- Manually tested all links on `Manage your health online` section on Region page for several Regions.
- Clicked all links and checked all google events with adSwerve
<details>
<summary>Refill and track your prescriptions</summary>
</details>
<details>
<summary>Send a secure message to your health care team</summary>
</details>
<details>
<summary>Schedule and manage health …
=> VACMS 18510 - removed all recordEvents and disable-analytics from Manage your health online section

src/site/includes/vet_centers/services.liquid, src/site/layouts/vet_center.drupal.liquid, src/site/stages/build/drupal/graphql/vetCenter.graphql.js
- Makes Vet Center services use the entity.status value to determine whether to show or not. Altered graphql to provide the value.
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16362
- Manually tested by archiving, archiving and drafting, drafting, services for a Vet Center location (St Louis in the tugboat associated)
Not a graphical change, but a data change
Vet Center pages, services accordions
Check
https://web-codylbelkq0gdivw6x7tykigmeqloewe.demo.cms.va.gov/st-louis-vet-center
On that tugbot 
I've archived [Addiction and substance use care](https://main-codylbelkq0gdivw6x7tykigmeqloewe.demo.cms.va.gov/st-louis-vet-center/service/st-louis-vet-center-addiction-and-substance-abuse-care)
I've archived and drafted, [Couples and family …
=> VACMS 16362: Make only published Vet Center Services display

src/site/layouts/checklist.drupal.liquid
Adds feedback button and fixes spacing for `last updated` element at the bottom of main content for the `checklist.drupal.liquid` layout to match with all other pages sitewide.  
Reviewed on review instance
| Mobile  |   n/a     |  n/a     |
| Desktop |<img width="1433" alt="Screenshot 2024-08-27 at 10 46 29 AM" src="https://github.com/user-attachments/assets/7bce276e-3b74-457f-9bb6-426cc1ec2981">| <img width="1433" alt="Screenshot 2024-08-27 at 10 46 04 AM" src="https://github.com/user-attachments/assets/3f783fb7-b7ac-474b-bffb-cf5548075c51">|
Pages that use `checklist.drupal.liquid` layout …
=> Medallia - Add feedback button to checklist page layout

package.json, yarn.lock
=> bump web components

package.json, yarn.lock
=> bump web-components

src/site/assets/img/navigate_before.svg, src/site/assets/img/navigate_far_before.svg, src/site/assets/img/navigate_far_next.svg, src/site/assets/img/navigate_next.svg
Add  navigation svg icons to site/img  directory
=> Add  navigation svg icons to site/img  directory

src/applications/registry.json
[Corresponding `vets-website` PR](https://github.com/department-of-veterans-affairs/vets-website/pull/31352)
Can't tell if `template.title` and `template.description` are consumed with our special layout, but we'll find out!
- _(If using a flipper, what is the end date of the flipper being required/success criteria being …
=> [ARF-87799] Remove 21a

src/applications/registry.json
- Removing 22-1990s entry in registry.json
- 
Jira -> https://jira.devops.va.gov/browse/VEBT-469
As a...
VEBT developer
I want...
all references to the GovCIO version of 22-1990s from the va.gov code base
So that...
we can get rid of some tech debt
Acceptance Criteria:
GovCIO EDU form 22-1990s no longer exists in the code base
- …
=> #vebt-469 remove 1990s from registry.json

src/applications/registry.json
Updates the `registry.json` to add a new application to cover the body of work for the MHV credential deprecation
- [JIRA ticket VI-422](https://jira.devops.va.gov/browse/VI-422)
- vets-website [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/31908)
- Reverse Proxy [PR](https://github.com/department-of-veterans-affairs/vsp-platform-revproxy/pull/629)
n/a
n/a
This should only impact staging & below environments for this route: `/sign-in-changes-reminder`
=> Add sign-in-changes application to registry

package.json, yarn.lock
- Updating Web Components package to latest version
N/A
N/A
N/A
Anywhere that uses web components.
=> Updating web-components version to latest

src/site/assets/sass/style.scss, src/site/paragraphs/service_location.drupal.liquid
- Adds break-word to service location paragraphs either in div (non-clinical) or card (clinical).
- Sitewide team, we own Service Locations
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18367
- Added really long email in tugboat to test in both clinical and non-clinical at 100% zoom and up to 400%
<details>
<summary>Clinical at 400%</summary>
</details>
<details>
<summary>Clinical at 100%</summary>
</details>
<details>
<summary>Mobile Clinical</summary>
</details>
<details>
<summary>Nonclinical 100%</summary>
</details>
<details>
<summary>Nonclinical mobile</summary>
</details>
Service Locations
Check
https://web-9tjtcrwxgmblpxwwcaiv9mrgod9j6fxc.demo.cms.va.gov/portland-va-regional-benefit-office/
and 
https://web-9tjtcrwxgmblpxwwcaiv9mrgod9j6fxc.demo.cms.va.gov/por …
=> Vacms 18367 wrapping service locations

src/applications/registry.json
- adding registry info for 5490 form
=> add 5490 info to registry

src/site/stages/build/drupal/static-data-files/digitalForm/fragments/digitalForm.graphql.js, src/site/stages/build/drupal/static-data-files/digitalForm/fragments/digitalForm.graphql.unit.spec.js, src/site/stages/build/drupal/static-data-files/digitalForm/fragments/identificationInformation.graphql.js, src/site/stages/build/drupal/static-data-files/digitalForm/fragments/identificationInformation.graphql.unit.spec.js, src/site/stages/build/drupal/static-data-files/digitalForm/postProcessDigitalForm.js, src/site/stages/build/drupal/static-data-files/digitalForm/postProcessDigitalForm.unit.spec.js
- Normalizes the Identification Information Paragraph type created by department-of-veterans-affairs/va.gov-cms#19190
```json
{
"id": 12345,
"chapterTitle": "Identification Information",
"type": "digital_form_identification_info",
"pageTitle": "Identification Information",
"includeServiceNumber": true
}
}
```
- department-of-veterans-affairs/va.gov-team#91741
- Added unit tests to the Digital Form post processor, the Digital Form GraphQL fragment, and the `identificationInformation` GraphQL fragment
- Pulled local Drupal data and confirmed the resulting output from content-build
Only affects the output of `digital-forms.json`, which is not currently generated in production.
At some point, the number of GraphQL fragments we need to handle all of the different …
=> VATEAM-91741: Normalize Identification Information pattern output

src/applications/registry.json
I'm working as part of the VEBT who owns the maintenance of this page. This ticket involves adding the `Last updated` field to the React SCO page in the footer. It was previously added through the metadata as the `lastupdate` field in the `vagov-content` markdown file, but the same field can be added through the `registry.json` template variables. The date should reflect when the React SCO page was released to prod.
- https://jira.devops.va.gov/browse/VEBT-452
**As a...**
School Certifying Official
**I want…**
To update the SCO 'Last Update' page
**So that…**
People landing on this page can know the latest edition of the SCO page.
**Acceptance Criteria**
Update the date as ( Sept 17, 2024 ) as shown in attached image.
**Technical Details:**
Dependencies: Research how/if this change can be …
=> VEBT-452 Update the 'Last updated' date of the SCO page

src/site/includes/header-minimal.html, src/site/includes/news-spotlight.drupal.liquid
[https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3060](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3060
)
- _Describe what the old …
=> CSS Library - Utilities - Swap background-color and color imports 

src/applications/registry.json
Removing a duplicate 10-7959f-1-FMP and  setting the production deploy flag to true.
=> 10-7959f-1-FMP deployment flag - true

.github/workflows/continuous-integration.yml, package.json, script/validate-registry.js, src/applications/registry.json
Adds a CI step that:
* errors if duplicate productIDs or rootUrls are found in the registry file
* notes if duplicate entryNames are found
* validates that the registry is valid JSON
https://dsva.slack.com/archives/CBU0KDSB1/p1727117128773179
Tested with and without duplicate entries in commits on this PR
=> Add registry validation CI step

src/site/includes/hero.drupal.liquid, src/site/includes/vet_centers/health_services.liquid, src/site/layouts/health_care_local_facility.drupal.liquid, src/site/layouts/vet_center.drupal.liquid
This PR will migrate the breakpoint names for the [font-size utility classes](https://design.va.gov/foundation/utilities/font-size).
| Current VADS Name | USWDS v3 Name |
| --------------------------- | ------------------------- |
| xsmall-screen (320px)          | mobile (320px) |
| small-screen (480px) | mobile-lg (480px) |
| small-desktop-screen (1008px) | desktop (1024px) 
| large-screen (1200px) | desktop-lg (1200px) |
- https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3209
- confirmed locally that the new …
=> Migrate breakpoint names for font-size utility classes

src/site/includes/above-footer-elements.drupal.liquid, src/site/includes/news-spotlight.drupal.liquid
This PR swaps  formation`<responsive-prefix>:vads--u-display-` for those in `css-library` in accordance with the deprecation of formation from vets-website.
| formation (Current VADS Name) | css-library (USWDS v3 name )|
| --------------------------- | ------------------------- |
| xsmall-screen        | mobile |
| small-screen  | mobile-lg  |
| small-desktop-screen  | desktop |
| large-screen | desktop-lg |
[3201](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3201)
local testing
<hr />
*(Describe what parts of …
=> swap utility classes for display- in favor of css-library, not formation

src/site/layouts/campaign_landing_page.drupal.liquid
Updated image style for CLP div to show the image properly.
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19348
CLPs
=> VACMS-19348: Add css style naming fix for CLPs

src/applications/registry.json
Deleted reference to 5495 form in the registry.json file.
As a...
VEBT Developer
I want…
to remove all references to the 22-5495 from the va.gov code base on the FE
So that…
users aren't redirected to this since its …
=> vebt-151 Removing reference to 5495 form in the content-build

src/site/stages/build/drupal/static-data-files/config.js, src/site/stages/build/drupal/static-data-files/config.unit.spec.js, src/site/stages/build/drupal/static-data-files/digitalForm/fragments/digitalForm.graphql.js, src/site/stages/build/drupal/static-data-files/digitalForm/fragments/digitalForm.graphql.unit.spec.js, src/site/stages/build/drupal/static-data-files/digitalForm/fragments/nameAndDateOfBirth.graphql.js, src/site/stages/build/drupal/static-data-files/digitalForm/fragments/nameAndDateOfBirth.graphql.unit.spec.js, src/site/stages/build/drupal/static-data-files/digitalForm/index.js, src/site/stages/build/drupal/static-data-files/digitalForm/index.unit.spec.js, src/site/stages/build/drupal/static-data-files/digitalForm/postProcessDigitalForm.js, src/site/stages/build/drupal/static-data-files/digitalForm/postProcessDigitalForm.unit.spec.js
=> 90733 normalize omb info section

src/site/paragraphs/table.drupal.liquid
When we were doing the massive DS component upgrades earlier this year the table component did not have a v3 equivalent, [it does now](https://design.va.gov/storybook/?path=/docs/uswds-va-table--default). We need to update everywhere we are using the current table component.
**Note:** Per the ACs we are converting to a bordered table in all instances, and no custom styles, attributes, props, or classes will be used in the tables anymore.
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18843
- Benefits detail pages - Examples:
- `/pension/survivors-pension-rates/past-rates-2020/`
- `/disability/compensation-rates/special-monthly-compensation-rates/past-rates-2023/`
- VAMC Detail pages - Examples:
- `/pittsburgh-health-care/shuttle-schedule/`
- …
=> VACMS-18843 Update tables to v3

package.json, src/applications/registry-schema.json, src/applications/registry.json, src/site/includes/header-minimal.html, yarn.lock
Update header-minimal template to reflect updated props from the component-library. The component-library updated the header-minimal component to not use heading elements by default and deprecated the `disable-headings` prop in favor of the `enable-headings` prop.
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3097
Global search and replace. Local testing with the latest drupal cache
<details><summary>New default behaviour renders divs instead of heading tags because H1 is used in form flow</summary>
</details>
<details><summary>enable-headings added as prop converts divs to heading tags</summary>
</details>
Minimal header
- [ x] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ x] No sensitive …
=> header-minimal: update disable-headings prop to be enable-headings prop

src/applications/registry.json
- Updated the `vagovprod` flag in registry file to be `true`. This form application is behind a feature toggle.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/94133
- NA
NA
This form only
NA
=> 94133 Release CHAMPVA form 10-10d to production - form 10-10d

src/site/components/phone-number-base.drupal.liquid, src/site/components/phone-number.drupal.liquid, src/site/includes/facilityListing.drupal.liquid, src/site/layouts/health_care_local_facility.drupal.liquid, src/site/layouts/person_profile.drupal.liquid, src/site/layouts/press_release.drupal.liquid, src/site/layouts/vamc_system_billing_insurance.drupal.liquid, src/site/paragraphs/service_location.drupal.liquid, src/site/paragraphs/staff_profile.drupal.liquid, src/site/stages/build/drupal/graphql/bioPage.graphql.js, src/site/stages/build/drupal/graphql/facilities-fragments/healthCareRegionStaffBios.node.graphql.js, src/site/stages/build/drupal/graphql/healthCareRegionDetailPage.graphql.js, src/site/stages/build/drupal/graphql/leadershipListingPage.graphql.js, src/site/stages/build/drupal/graphql/paragraph-fragments/personTelephone.paragraph.graphql.js, src/site/stages/build/drupal/graphql/paragraph-fragments/phoneNumber.paragraph.graphql.js, src/site/stages/build/drupal/graphql/paragraph-fragments/staffProfile.paragraph.graphql.js, src/site/stages/build/drupal/graphql/pressReleasePage.graphql.js, src/site/stages/build/drupal/graphql/vamcBillingAndInsurancePage.graphql.js, src/site/teasers/bio.drupal.liquid
- Adds the use of fieldTelephone to the Staff Profile/Listing/Info/Contact(for Press Releases when phone number is present) pages
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17865
- _Optionally, provide a link to your [test plan](https://depo-platform-documentation.scrollhelp.site/developer-docs/create-a-test-plan-in-testrail) and [test execution records](https://depo-platform-documentation.scrollhelp.site/developer-docs/execute-tests-in-testrail)_
_Note: This field is mandatory …
=> VACMS 17865 - Conditionally render fieldTelephone when present, otherwise fieldPhoneNumber

src/applications/registry.json
From Staging Review Feedback
Description: The title tag is Benefit Eligibility Questionnaire | Veterans Affairs while the H1 and breadcrumb are Benefit and resource recommendation tool. First segment of the <title> tag before | Veterans Affairs, the form's H1, and the current breadcrumb must use the same text whenever possible.
Recommended Action: Update first segment of title tag, current breadcrumb and H1 to use the same text.
[https://jira.devops.va.gov/browse/PTEMSVT-217](https://jira.devops.va.gov/browse/PTEMSVT-217)
Local testing.
Benefit eligibility questionnaire …
=> Update title of benefits eligibility questionnaire

.github/workflows/daily-production-release.yml, .github/workflows/daily-release-warning.yml
Updates daily cron jobs to reflect Standard Time 2024
=> Updates daily cron jobs to reflect Standard Time 2024

package.json, yarn.lock
The release notes can be reviewed here: 
- https://github.com/department-of-veterans-affairs/component-library/releases/tag/v48.0.0
- _Describe the steps required to verify your changes are working as …
=> update web-components package to latest

src/applications/registry.json
Removes registry entry for an app that will be removed from vets-website in [this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/32891).
Original ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/96046
Related PR as linked above: https://github.com/department-of-veterans-affairs/vets-website/pull/32891
N/A. Simply a registry removal.
N/A
Only affects form-renderer app (which is being removed in favor of a slightly changed architecture).
=> Removes registry entry for `form-renderer` app.

src/applications/registry.json
- Added custom breadcrumbs to a form.
- I work for VA IIR and we own this application.
[VA IIR issue 1217](https://github.com/department-of-veterans-affairs/va-iir/issues/1217)
- _Optionally, provide a link to your [test …
=> Add breadcrumbs to "Add your contact information" form

src/applications/registry.json
React url update
-Update the url for Check your Post-9/11 GI Bill benefits from 
Current url: https://www.va.gov/education/gi-bill/post-9-11/ch-33-benefit/status
https://www.va.gov/education/gi-bill/post-9-11/ch-33-benefit/status/print
Update to: https://www.va.gov/education/check-remaining-post-9-11-gi-bill-benefits/status/
https://www.va.gov/education/check-remaining-post-9-11-gi-bill-benefits/status/print/
https://jira.devops.va.gov/browse/EDM-343
https://github.com/department-of-veterans-affairs/va.gov-team/issues/97680
- _Describe what the old behavior …
=> edm-343 url update

src/applications/registry.json
This PR edits the registry for an app rename from Benefit Eligibility Questionnaire to Discover Your Benefits
https://github.com/department-of-veterans-affairs/vets-website/pull/33195
Manual and Unit testing
_Note: This field is mandatory for UI changes (non-component …
=> PTEMSVT-285 Rename Benefits Eligibility Questionnaire to Discover Your Benefits

src/applications/registry.json
This PR will allow the `sign-in-changes` application to build and release to production.
> Note: No redirects to the `sign-in-changes` application until the `mhv_interstitial_enabled` feature flag is toggled in all environments
- [JIRA VI-876](https://jira.devops.va.gov/browse/VI-876)
Unit testing
n/a
This is part of the MHV credential deprecation work so that any user that authenticates with the MHV credential will be re-routed to this `sign-in-changes` application to start identity verification OR create a modern ID.me or Login.gov credential
=> Updates registry.json for sign-in-changes

src/site/includes/header.html
=> [VACMS-20093]Always build situation updates banner regardless of FF

src/applications/registry.json
- Update registry so 5490 automated points to new url
=> update automated 5490 url to new url

package.json, yarn.lock
- Updating web-components package to latest version
N/A
- None
N/A
Everywhere that uses the web-components package, mostly a11y fixes.
=> Updating web-components to latest v16.3.0

src/applications/registry.json
- Enabling Appoint a Representative ahead of staged rollout
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/99874
=> Enable appoint a rep in production

src/applications/registry.json
Discover Your Benefits is being enabled for 1/9/25.
[https://jira.devops.va.gov/browse/PTEMSVT-288](https://jira.devops.va.gov/browse/PTEMSVT-288)
Local testing and unit testing.
[https://va.gov/discover-your-benefits/](https://va.gov/discover-your-benefits/)
=> Discover Your Benefits Application enable vagovprod

package.json, yarn.lock
updates web components version
=> update web component version

src/applications/registry.json
- New urls for MEB & TOE applications
- https://github.com/department-of-veterans-affairs/vets-website/pull/34109
=> update meb and toe urls

src/applications/registry.json
- VEBT-993 FE - 22-10282 - Launch blocker - Form URL incorrect
As a...
VEBT Developer
I want…
To fix the Form URL incorrect
So that…
Launch blockers from Staging Review finding can be fixed
Acceptance Criteria
Link to issue - [Staging Review finding: Form URL incorrect · Issue #100110 · department-of-veterans-affairs/va.gov-team](https://github.com/department-of-veterans-affairs/va.gov-team/issues/100110)
Findings details
VA.gov Experience Standard - issue: User can determine where a page is within the VA.gov …
=> vebt-993 FE - 22-10282 - Launch blocker - Form URL incorrect

src/site/stages/build/drupal/static-data-files/digitalForm/fragments/digitalForm.graphql.js, src/site/stages/build/drupal/static-data-files/digitalForm/index.js, src/site/stages/build/drupal/static-data-files/digitalForm/postProcessDigitalForm.js, src/site/stages/build/drupal/static-data-files/digitalForm/tests/fixtures/queryResult.json, src/site/stages/build/drupal/static-data-files/digitalForm/tests/fragments/digitalForm.graphql.unit.spec.js, src/site/stages/build/drupal/static-data-files/digitalForm/tests/index.unit.spec.js, src/site/stages/build/drupal/static-data-files/digitalForm/tests/postProcessDigitalForm.unit.spec.js
- Adjusts the GraphQL query to return both all Digital Forms regardless of moderation state.
- Adds a `moderationState` property to the normalized output with the moderation state of each Digital Form.
```json
{
"cmsId": 76370,
"formId": "21-4140",
"moderationState": "published",
"title": "Employment Questionnaire",
...
"chapters": [...]
},
{
"cmsId": 76371,
"formId": "abcdefg",
"moderationState": "draft",
"title": "Draft form",
...
"chapters": [...]
}
```
- department-of-veterans-affairs/va.gov-team#98086
- New/updated unit tests for the Digital Form GraphQL statement, the `digitalForm` fragment, and the Digital Form post processor
- 
Only affects the output of `digital-forms.json`.
(OPTIONAL) _What should …
=> VATEAM-98086: Publish draft Digital Forms in content-build and add publishing status to output

package.json, yarn.lock
=> Update component-library to v49.0.0

src/site/stages/build/drupal/static-data-files/README.md
Adding a static README that points to more information about KISS data.
=> Create README.md for KISS data

package.json, yarn.lock
If you are:
2. **Changing an entryName**: First search [vets-website](https://github.com/department-of-veterans-affairs/vets-website/) for references to …
=> update web components package

src/applications/registry.json
- This is work for the VA-IIR team.
- Our team owns this form/application, the Welcome VA Setup Review Information form.
- This PR turns the prod boolean to true.
- Access to our form is still behind a feature flag.
- We will be conducting a staged rollout following this release.
- This work closes ticket [1170](https://github.com/orgs/department-of-veterans-affairs/projects/1360/views/3?pane=issue&itemId=84225845&issue=department-of-veterans-affairs%7Cva-iir%7C1170).
This only makes changes to our app and does not affect other apps.
(OPTIONAL) _What should …
=> [VA-IIR 1170] reveal form to prod (behind feature flag that is still in place for testing)

src/applications/registry.json
- remove old 5490 and 1990 unauth urls from registry.json
=> remove old 5490 and 1990 unauth urls from registry.json

src/applications/registry.json
This updates form 21-4138's title to match the linked issue.
department-of-veterans-affairs/va.gov-team-forms#1490
=> Update form 21-4138 title

src/applications/registry.json
If you are:
2. **Changing an entryName**: First search [vets-website](https://github.com/department-of-veterans-affairs/vets-website/) for references to this `entryName` that are _not_ in the app folder (particularly in `src/applications/static-pages/static-pages-entry.js` and `src/platform/forms/constants.js`) and merge a PR that updates those references, if any.
- _Add the link to your …
=> VEBT-1125 update last update of the sco page from 2024-12-10 to 2025-02-13

src/applications/registry.json
If you are:
2. **Changing an entryName**: First search [vets-website](https://github.com/department-of-veterans-affairs/vets-website/) for references to this `entryName` that are _not_ in the app folder (particularly in `src/applications/static-pages/static-pages-entry.js` and `src/platform/forms/constants.js`) and merge a PR that updates those references, if any.
- _Add the link to your …
=> 10-7959c Change URL

src/applications/registry.json, src/site/includes/accredited-representative-portal/head.html
ARP has its own page layout and headers. We are going to hardcode this title:
```html
<title>Accredited Representative Portal | Veterans Affairs</title>
```
=> Add ARP title

src/applications/registry.json
This PR enables the form upload tool in prod.
=> Enable Form Upload tool

package.json, yarn.lock
Updates web components package version
Package update in package.json - [release notes](https://github.com/department-of-veterans-affairs/component-library/releases/tag/v49.4.0)
=> update web-components version

src/applications/registry.json
https://depo-platform-documentation.scrollhelp.site/developer-docs/creating-a-new-application#Creatinganewapplication-Goingtoproduction
Corresponding to this sequence of configuration updates that will make us live in production———
=> [ARP] "vagovprod": true

.github/workflows/daily-production-release.yml
Update cron timer due to daylight savings.
NA
If you are:
2. **Changing an entryName**: First search [vets-website](https://github.com/department-of-veterans-affairs/vets-website/) for references to this `entryName` that are _not_ in the app folder (particularly in `src/applications/static-pages/static-pages-entry.js` and …
=> update cron timer due to daylight savings

src/site/includes/email-update-signup.drupal.liquid
- Follow-up to [PR#2404](https://github.com/department-of-veterans-affairs/content-build/commit/84cbc98135b20b74c1e314405848b8d0c32c7887) which removes the email signup component.
- Fixes the following JS console errors seen at va.gov/
- Chromium 134.0 : `Uncaught TypeError: Cannot read properties of null (reading 'addEventListener')`
- Firefox 136.0.1 : `Uncaught TypeError: emailSignupInput is null`
- _Link to ticket created in va.gov-team repo_: department-of-veterans-affairs/va.gov-team#105288
- localhost console does not contain the error after code removal
No UI changes
(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist with. Do …
=> [FIX] Removes JS code for removed email signup component

src/applications/registry.json
- Updating Ask VA flag for prod launch
- The Ask VA team owns this
This pull request includes a change to the `src/applications/registry.json` file. The change updates the `template` configuration for the "Ask VA" entry to enable the `vagovprod` setting.
* [`src/applications/registry.json`](diffhunk://#diff-0fdad4d7204e21869202df142e08491dbc8d478be804861eaca6262e753f077eL803-R803): Changed the `vagovprod` setting from `false` to `true` for the "Ask VA" entry.
- Link to ticker here: https://github.com/orgs/department-of-veterans-affairs/projects/1033/views/11?pane=issue&itemId=102018218&issue=department-of-veterans-affairs%7Cask-va%7C1673
If you are:
1. **Deleting an entryName**: First search [vets-website](https://github.com/department-of-veterans-affairs/vets-website/) for references to …
=> AVA-1673: Update AVA vagovprod to true

src/applications/registry.json
- Updated url for form 22-10216
As a...
VEBT Developer
I want…
To modify the correct URL
So that…
It follows CAIA standards for URL
Acceptance Criteria …
=> Vebt-1242: 22-10216 url modification

src/applications/registry.json
- VEBT-1241 FE - 22-10215 - URL modifications based on IA.
- [vets-website pull request](https://github.com/department-of-veterans-affairs/vets-website/pull/35333)
- [revproxy pull request](https://github.com/department-of-veterans-affairs/vsp-platform-revproxy/pull/882)
If you are:
1. **Deleting an entryName**: First search [vets-website](https://github.com/department-of-veterans-affairs/vets-website/) for references to this `entryName` that are …
=> VEBT-1241 FE - 22-10215 - URL modifications based on IA.

src/site/includes/decision-reviews-rum.html
> DIsabling DataDog RUM monitoring for Decision Review (DR) static pages for now:
> - We're seeing non-DR pages in the sessions
> - The sample rate is set too high
> Disable for now as we're nearing the allow session limit (see ticket)
https://github.com/department-of-veterans-affairs/va.gov-team/issues/105956
- _Describe what the old behavior was prior to …
=> Disable RUM for Decision Review static pages

package.json, yarn.lock
- _Link to previous change of the code/bug (if …
=> update web components

src/site/stages/build/drupal/graphql/GetLatestPageById.graphql.js
- Adds fragment for VAMC system VA police to getById query that runs on preview server for content-build
This pull request includes changes to the `src/site/stages/build/drupal/graphql/GetLatestPageById.graphql.js` file to add support for VA Police pages. The most important changes include adding the VA Police GraphQL fragment and updating the module exports to include this new fragment.
Key changes:
* Added `vamcPolicePages` import statement to include the VA Police GraphQL fragment. 
* Updated the `module.exports` to include the `vamcPolicePages.fragment` in the GraphQL query. 
* Included the `vaPoliceFragment` in the list of fragments to be used in the GraphQL query. 
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/21013
- tested locally with `yarn …
=> VACMS 21013 - Makes VAMC System VA Police pages available in CMS preview

.vscode/settings.json, src/applications/registry-schema.json, src/applications/registry.json
- Update 10206 for minimal form flow
department-of-veterans-affairs/va.gov-team-forms#2044
Related vets-website PR: https://github.com/department-of-veterans-affairs/vets-website/pull/35524
- Browser, unit, cypress
TODO
10206
=> Update 10206 for minimal form flow

src/applications/registry.json
- updated name for form 20-10207
- department-of-veterans-affairs/VA.gov-team-forms#1535
- Browser
- form 10207
=> 1535 form 10207 page title should match form h1 part 2

src/applications/registry.json
- This work updates the url for form 21-4138. This is a directive from the IA team.
- I belong to the Veteran Facing Forms team who owns the maintenance of this form
This pull request includes a small change to the `src/applications/registry.json` file. The change updates the `rootUrl` for the "Submit a statement to support a claim" application to a new URL path.
* [`src/applications/registry.json`](diffhunk://#diff-0fdad4d7204e21869202df142e08491dbc8d478be804861eaca6262e753f077eL1547-R1547): Updated the `rootUrl` from `/supporting-forms-for-claims/statement-to-support-claim-form-21-4138` to `/supporting-forms-for-claims/submit-statement-form-21-4138`.
- department-of-veterans-affairs/va.gov-team-forms#1631
- Browser testing successful
Any
=> [SIMPLE-FORMS] feat: update 4138 URL to expected format

package.json, yarn.lock
"@department-of-veterans-affairs/web-components": "18.1.0"
=> web-components@18.1.0

src/applications/registry.json
This PR updates the url for f-2 to include "-claim" after "file-foreign-medical-program"
https://github.com/department-of-veterans-affairs/va.gov-team/issues/103036
https://github.com/department-of-veterans-affairs/vets-website/pull/35799
https://github.com/department-of-veterans-affairs/vsp-platform-revproxy/pull/900
If you are:
1. **Deleting an entryName**: First search [vets-website](https://github.com/department-of-veterans-affairs/vets-website/) for references to this `entryName` that …
=> 10-7959f-2 Updated URL

src/applications/registry.json
- Adds a registry entry for the Form Builder Sandbox app
Just https://staging.va.gov/form-builder-sandbox-12-3456
=> Add registry entry for form builder sandbox

src/applications/registry.json
- Deleted registry entry for app that was replaced in 2023, and redirects make inaccessible in prod
This pull request removes an outdated application entry from the `src/applications/registry.json` file. The change ensures that the application is no longer registered in the system.
Key change:
* Removed the entry for the "Order hearing aid batteries and accessories" application, including its `appName`, `entryName`, `rootUrl`, and `template` details. This entry is no longer needed and has been cleaned up to maintain an accurate registry.
- department-of-veterans-affairs/va.gov-team/issues/79957
If you are:
1. **Deleting an entryName**: First search [vets-website](https://github.com/department-of-veterans-affairs/vets-website/) for …
=> Remove obsolete, inaccessible app from registry

src/applications/registry.json
- remove 686c 574 v2 breadcrumbs in favor of web component definition in vets-website
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/108174
If you are:
1. **Deleting an entryName**: First search [vets-website](https://github.com/department-of-veterans-affairs/vets-website/) for references to this `entryName` that are _not_ in the app folder (particularly in `src/applications/static-pages/static-pages-entry.js` and `src/platform/forms/constants.js`) and merge a PR that …
=> remove 686c v2 breadcrumbs

src/applications/registry.json
- removes breadcrumbs from 686c v2. These are duplicated, and are now defined in vets-website.
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/108174
If you are:
1. **Deleting an entryName**: First search [vets-website](https://github.com/department-of-veterans-affairs/vets-website/) for references to this `entryName` that are _not_ in the app folder (particularly in `src/applications/static-pages/static-pages-entry.js` and `src/platform/forms/constants.js`) and merge …
=> remove breadcrumbs from 686c v2

package.json, yarn.lock
- _Link to previous change of the code/bug (if …
=> Update web-components package to release v18.1.3

src/applications/registry.json
Summary here - https://github.com/department-of-veterans-affairs/content-build/pull/2507
There was a 50+ message slack thread that basically ended with we aren't sure why it's failing. So I created this new one just to have a new start and tried a couple of things. It works locally and passes all tests. Just want to get this in so we can try in staging
=> representative-form-upload

src/applications/registry.json
- Updates 686c URL to align with CAIA recommendation
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/102097
If you are:
1. **Deleting an entryName**: First search [vets-website](https://github.com/department-of-veterans-affairs/vets-website/) for references to this `entryName` that are _not_ in the app folder (particularly in `src/applications/static-pages/static-pages-entry.js` and `src/platform/forms/constants.js`) and merge a PR that removes those references, if …
=> Update 686c URL

package.json, yarn.lock
- _Link to previous change of the code/bug (if …
=> Update web-components to release v18.2.0

package.json, yarn.lock
This PR updates the version of the web-component to the latest
If you are:
2. **Changing …
=> update component library version

package.json, yarn.lock
This PR updates the web-components to the latest version, 18.4.0
If you are:
2. …
=> update web-components to 18.4.0

src/applications/registry.json
Remove min header per convos in this ticket. 
https://github.com/department-of-veterans-affairs/va.gov-team/issues/107629
Corresponding vets-website PR
https://github.com/department-of-veterans-affairs/vets-website/pull/37313
This pull request includes a simplification of the `registry.json` configuration by removing the `minimalHeader` object, which contained properties related to the title, subtitle, and excluded paths.
Configuration simplification:
* [`src/applications/registry.json`](diffhunk://#diff-0fdad4d7204e21869202df142e08491dbc8d478be804861eaca626 …
=> 107629 - DD - Remove Min Header per Final Design Requests for Launch

src/applications/registry.json
Updating dispute-debt registry entry to be production ready
- Linking already closed ticket where similar config work was completed
department-of-veterans-affairs/va.gov-team#101240
If you are:
2. **Changing an entryName**: First search [vets-website](https://github.com/department-of-veterans-affairs/vets-website/) for …
=> [DD] Updating dispute-debt registry entry for prod

src/applications/registry.json
Form 22-10297 app registry and updated url to 
/education/other-va-education-benefits/high-technology-program/apply-for-high-technology-program-form-22-10297
https://jira.devops.va.gov/browse/VEBT-2260
https://github.com/department-of-veterans-affairs/vets-website/pull/37443
https://jira.devops.va.gov/browse/VEBT-2243
If you are:
1. **Deleting an entryName**: First search [vets-website](https://github.com/department-of-veterans-affairs/vets-website/) for references to this `entryName` that …
=> VEBT-2260: Form 22-10297 app registry

src/applications/registry.json
- Change the toggle from false to true so that form 22-10216 is available in production.
- Not to be merged until release is finalized and coordinated with business.
- Team: Veteran Education Benefits Tools
- https://jira.devops.va.gov/browse/VEBT-2012
- _Optionally, provide …
=> change 10216 prod toggle to true

src/applications/registry.json
- This is work for the VA-IIR team.
- We are creating a new form app for the Chapter 36 form.
- Corresponding PR creating new app already merged to vets-website.
- VA-IIR ticket # 1835.
If you are:
- _Add the …
=> [VA-IIR 1835] create new chapter 36 form app

package.json, yarn.lock
This PR bumps the web-components package to its latest version
If you are:
1. **Deleting an entryName**: First search [vets-website](https://github.com/department-of-veterans-affairs/vets-website/) for …
=> update web components to 19.4.0

src/applications/registry.json
Update title from "Income and Asset Statement Form" to "Pension or DIC Income and Asset Statement".
[[ENG] 0969: Update header text #113100](https://github.com/department-of-veterans-affairs/va.gov-team/issues/113100)
Visual testing locally
Before 
After
(OPTIONAL) _What should the reviewers know in addition to the above. Is there anything specific you wish the reviewer to assist …
=> Update 21P-0969 title

src/applications/registry.json
Update rootUrl for 21P-0969 form
[Staging Review finding: No entry point for form 21P-0969 #114347](https://github.com/department-of-veterans-affairs/va.gov-team/issues/114347)
Tested locally
n/a
=> Update 21P-0969 rootUrl

src/applications/registry.json
This PR updates the url for this form to include /champva
https://github.com/department-of-veterans-affairs/va.gov-team/issues/109952
If you are:
2. …
=> 10-7959a URL Change

src/applications/registry.json
Form 22-10275 app registry and updated url to
/school-administrators/commit-principles-of-excellence-form-22-10275
- https://jira.devops.va.gov/browse/VEBT-2934
N/A
N/A
Edu-benefits form 22-10295
=> VEBT-2934: Form 22-10275 app registry

src/applications/registry.json
Reverts department-of-veterans-affairs/content-build#2562
May be causing a staging change.
=> Revert "10-7959a URL Change"

src/applications/registry.json
- updating rootUrl for 22-10297 form
Jira ->https://jira.devops.va.gov/browse/VEBT-3070
As a...
VEBT Developer
I want…
To update the 10297 form canonical URL
So that…
it has been updated to reflect the final request of the business and approval of OCTO
Acceptance Criteria
AC1 : App URL updated to: /education/other-va-education-benefits/high-technology-education-courses-vet-tec-2/apply-for-program-form-22-10297
Technical Details:
URL updated in …
=> #vebt-3070 #updating rootUrl for 22-10297 form

src/applications/registry.json
This pull request makes a small configuration update to the `src/applications/registry.json` file. The change enables the application in the production environment by setting the `vagovprod` flag to `true`.## Summary
> Enable Form 0969 in production
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/118045
- …
=> 0969 | Enable in production

src/site/layouts/locations_listing.drupal.liquid, src/site/stages/build/drupal/graphql/GetAllPages.graphql.js, src/site/stages/build/drupal/individual-queries.js, src/site/tests/cypress/vamc-lovell.cypress.spec.js
This pull request removes support for the legacy Locations Listing page from the Drupal build process. The main changes involve cleaning up unused GraphQL queries and clarifying that the old template is no longer used in production.
**Deprecation of Locations Listing page:**
* Removed the `locationListingPage` fragment from the `buildQuery` function in `GetAllPages.graphql.js`, so it is no longer queried during site builds.
* Removed import and usage of `GetNodeLocationsListingPages` from `individual-queries.js`, eliminating related GraphQL queries from the build process. [[1]](diffhunk://#diff-0c17c1fa1f8088539fc5d410fa77c95bcdec5b2c06d0abf4a63d39dcdf77e6d6L16-L19) [[2]](diffhunk://#diff-0c17c1fa1f8088539fc5d410fa77c95bcdec5b2c06d0abf4a63d39dcdf77e6d6L86)
**Documentation and template …
=> VACMS-20461: Post launch VAMC Locations Listing

package.json, yarn.lock
This PR updates component-library to its latest release, 52.1.1.
If you are:
1. **Deleting an entryName**: First search [vets-website](https://github.com/department-of-veterans-affairs/vets-website/) …
=> update component-library to latest (52.1.1)

src/applications/registry.json
> Updating `/manage-dependents` page title in breadcrumbs
> Benefits Lifestages / Dependents Management Team
https://github.com/department-of-veterans-affairs/va.gov-team/issues/118343
- _Exclusively …
=> DMT | Update manage dependents breadcrumb text

src/applications/registry.json
This PR updates the root URL of the 10-10d extended application to meet IA standards. The app is currently not Live in production, so there are no concerns for 404s or anything like that.
This pull request updates the `rootUrl` for the "10-10d Extended" application in the registry configuration to reflect a new, more descriptive path.
* Registry configuration update:
* Changed the `rootUrl` in `src/applications/registry.json` for the "10-10d Extended" app to `/family-and-caregiver-benefits/health-and-disability/champva/apply-champva-form-10-10d`, replacing the previous `/ivc-champva/10-10d-extended` path.
department-of-veterans-affairs/va.gov-team#117603
- Root URL meets IA standards
=> 10-10d extended | Update root URL

src/applications/registry.json
- Updates an appName. This fixes an issue where the HTML title and h1 did not match
- I work for VA IIR and we own the Chapter 31 app
This pull request updates the display name for the VR&E application in the `registry.json` file to make it correspond to the page h1.
- Application Naming:
* Changed the `appName` from "28-1900 Veteran Readiness" to "Apply for Veteran Readiness and Employment (VR&E)" in `src/applications/registry.json`.
[VA IIR issue …
=> Chapter 31: Fix issue where HTML title and h1 did not match

src/applications/registry.json
Adding time of need form to va.gov 
https://jira.devops.va.gov/browse/MBMS-102590
https://github.com/department-of-veterans-affairs/vets-website/pull/38623
https://github.com/department-of-veterans-affairs/vsp-platform-revproxy/pull/1057
If you are:
1. **Deleting an entryName**: First search [vets-website](https://github.com/department-of-veterans-affairs/vets-website/) for references to this `entryName` that are _not_ in the app folder (particularly in …
=> MBMS-102590 ToN form

package.json, yarn.lock
This PR bumps web-components to the latest version
If you are:
1. **Deleting an entryName**: First search [vets-website](https://github.com/department-of-veterans-affairs/vets-website/) for references …
=> Update to Web-components 21.0.0

src/site/assets/.well-known/apple-app-site-association, src/site/assets/.well-known/assetlinks.json
The VA Mobile App/Platform Team is looking to add better support for deeplinks by setting up Universal Links(IOS) and App Links(Android). Part of the implementations requires an `apple-app-site-association` and `assetlinks.json` file be accessible at `va.gov/.well-known/` and staging website(`staging.va.gov/.well-known/`). 
- added `apple-app-site-association` and `assetlinks.json` at   `src/site/assets/.well-known`
- these files maybe modified by other experience teams in the future as they add more support to deep linking like push notifications or links …
=> Adding assoication files for deeplinking in the VA Mobile App

src/applications/registry.json
- Add `registry.json` entry for VA Form 21-4192 "Employment Information" to establish initial routing and configuration.
- Route: `/21-4192-employment-information`
- productId: `c61b0c39-7177-4340-9820-955c959b7f5b`
- Ownership: Benefits Management Tools Team 1
- No feature flag required for this registry-only change
- department-of-veterans-affairs/va.gov-team#120087
- [Vets website PR for the same application](https://github.com/department-of-veterans-affairs/vets-website/pull/38890)
- Registry-only change defers user-facing validation, accessibility checks, analytics, and monitoring until UI exists. Risk is low because the change does not execute at runtime for users, but omission of early analytics/monitoring scaffolding could delay observability if not prioritized in the next PR.
- …
=> init(21-4192): Add application for employment information

src/applications/registry.json
This pull request adds a new application entry to the `registry.json` configuration file. The new entry defines the "Marital Status Questionnaire for DIC Recipients" app, specifying its root URL, template settings, and custom breadcrumbs for improved navigation. . 
**New application registration:**
* Added a new entry for the `Marital Status Questionnaire for DIC Recipients` app with the `entryName` `21p-0537`, including its `rootUrl`, template configuration, and a custom breadcrumbs override in `src/applications/registry.json`.
https://github.com/department-of-veterans-affairs/vets-website/pull/38806
Add content build registry entry for 21P-0537 (Marital Status Questionnaire) so we can conduct UAT on staging …
=> Register 21p-0537 app in content build

package.json, yarn.lock
Component Library release notes:
https://github.com/department-of-veterans-affairs/component-library/releases/tag/v53.1.0
If you are:
1. **Deleting an entryName**: First search …
=> Update web-components to latest version v21.1.0

src/applications/registry.json
- Add form 21-4140
- https://github.com/department-of-veterans-affairs/vets-website/pull/38907
If you are:
2. **Changing an entryName**: First search [vets-website](https://github.com/department-of-veterans-affairs/vets-website/) for references to this `entryName` that are _not_ in the app folder (particularly in …
=> Add 21-4140

.github/PULL_REQUEST_TEMPLATE.md
Added notice about locked main branch and PR process.
=> Update PR template with main branch notice
