department-of-veterans-affairs/content-build

.github/CODEOWNERS

This PR sets the `frontend-review-group` as the default code owners for the `content-build` repo. 
- https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/about-code-owners
- [`CODEOWNERS` file from `vets-website`](https://github.com/department-of-veterans-affairs/vets-website/blob/master/.github/CODEOWNERS)

Set frontend-review-group as default CODEOWNERS

---

jenkins/common.groovy

CI was failing on `master` because of the broken link checking. 
- http://jenkins.vfs.va.gov/blue/organizations/jenkins/testing%2Fcontent-build/detail/master/9/pipeline
This PR changes the environment used by the `content-build` from `vagovprod` to `vagovstaging`.

Uncomment vagovstaging, and comment out vagovprod

---

jenkins/common.groovy

CMS team is getting reports of broken link notifications from this repo. This is the only reference I could find to something that might cause that, so we're disabling is and seeing if that helps.
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4636

disabled slack alert for broken links

---

src/site/layouts/tests/vamc/phone-number.unit.spec.js
src/site/stages/build/plugins/download-assets.js
src/site/stages/build/plugins/modify-dom/process-entry-names.js

This PR updates the path used for searching entries in the `process-entry-names.js` step of the Metalsmith pipeline. This needs to be changed because now the path values for files generated in the `file-manifest.json` do not contain the absolute URL. See https://s3-us-gov-west-1.amazonaws.com/apps.dev.va.gov/generated/file-manifest.json for reference.
The bundle URL in the `download-assets` step of the Metalsmith pipeline needs to be updated to use the s3 URL so that the fetch request for getting the assets is successful.

Update paths used for searching entires & bundle url

---

README.md
src/site/stages/build/options.js
src/site/stages/build/plugins/create-symlink.js

Currently, the [create-symlink](https://github.com/department-of-veterans-affairs/content-build/blob/master/src/site/stages/build/plugins/create-symlink.js) plugin assumes the local directory name for applications is `vets-website`. This may not be the case for all instances.
This PR adds the build option `apps-directory-name`, which gives the option to specify the application's directory name. The default value is set to `vets-website`.
Other changes include:
- Update the `create-symlink` plugin to reference new build option
- Update documentation to include usage of new option
Testing done:
- Tested locally with and without the build option

Add applications directory name option

---

Dockerfile
jenkins/build.sh
jenkins/common.groovy

This ports over the work done to have non-prod/master branch builds use tugbaot as the source of data instead of prod.  Original PRs: https://github.com/department-of-veterans-affairs/vets-website/pull/16327 and https://github.com/department-of-veterans-affairs/vets-website/pull/17008

[Jenkinsfile] Retrieve content from the CMS CI server for non-master

---

jenkins/common.groovy
src/site/navigation/facility_sidebar_nav.drupal.liquid

This PR adds support for the SideNav React component in the preview server, meaning previews of VAMC pages now have sidebars.
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/5236
https://github.com/department-of-veterans-affairs/va.gov-team/issues/21133
https://github.com/department-of-veterans-affairs/va.gov-team/issues/15710
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/5080
- Confirmed sidebar renders on http://localhost:3001/preview?nodeId=318
- Confirmed sidebar renders on http://localhost:3001/preview?nodeId=775
Signed-off-by: Tim Wright <timwright12@gmail.com>

Fix VAMC sidebars rendering on preview (#17057)

---

src/applications/registry.json

REPO SYNC FROM https://github.com/department-of-veterans-affairs/vets-website/pull/17096
[Original Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/24262)
When we initially scaffolded the COE application we skipped adding breadcrumbs as the URLs for these were not available yet. This PR adds those breadcrumbs since we now know the URLs.

Added breadcrumbs (#17096)

---

src/applications/registry.json

REPO SYNC FROM : https://github.com/department-of-veterans-affairs/vets-website/pull/17052
Changing the path to form 10182 (Board Appeals: Notice of Disagreement). Specifically changing "review" to "appeal" in the path per recommendations. This form is not in production.
Resulting path: http://staging.va.gov/decision-reviews/board-appeal/request-board-appeal-form-10182/
I don't plan to merge this change until after May 4, 2021 (after our sprint review & demo).
Related:
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/24138
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/21819#issuecomment-831469494
- https://github.com/department-of-veterans-affairs/devops/pull/9095 (route update)
N/A
N/A
Signed-off-by: Tim Wright <timwright12@gmail.com>

Update NOD path (#17052)

---

src/site/layouts/page.drupal.liquid

**Issue:** https://github.com/department-of-veterans-affairs/va.gov-team/issues/22442
This PR adds `itemprop="mainEntity"` to the page template.
Still testing locally atm
Still testing locally atm

Add mainEntity itemprop

---

src/platform/testing/unit/axe-plugin.js
src/platform/testing/unit/mocha-setup.js

It's hard to test all variations of a page in Cypress, so this makes it easier to use the axe check in a unit test, against elements rendered in JSDom.
Ran unit tests

Experiment: add Chai assertion for aXe check #17110

---

jenkins/common.groovy

Broken link checker should be turned back on now, I think. We're missing broken link reports.
See thread, https://dsva.slack.com/archives/C0MQ281DJ/p1620841640457600

Enable broken link checker

---

src/site/stages/build/plugins/modify-dom/check-broken-links/helpers/isBrokenLink.js

The image at https://www.va.gov/img/styles/2_3_medium_thumbnail/public/2021-05/Gann%2C%20Dottie.JPG is present on disk, but generating broken link errors in pages that reference it, because `%2C` is not decoded to `,` by the broken link checker. This PR switches from using `decodeURI` to `decodeURIComponent` as we are in fact decoding a URI component, and correctly (I believe) decodes `%2C` to `,`.
More background is available in [this slack thread](https://dsva.slack.com/archives/C0MQ281DJ/p1620841640457600).
Manual testing on tugboat CI.

Fix broken link checker for filenames with commas

---

src/site/includes/header.html

As a post-release item for content separation, we're removing the black banner from staging and dev.

Removed black banner from staging and dev

---

src/site/paragraphs/lists_of_links.drupal.liquid

**Issue:** https://github.com/department-of-veterans-affairs/va.gov-team/issues/24667
This PR fixes the styling of extra category columns on `/resources`.
Locally tested at http://localhost:3002/preview?nodeId=8296 when running `yarn build --pull-drupal && yarn preview`

Remove extra wrapping div for extra categories

---

src/site/constants/buckets.js

Update bucket URL to use old URL.

Revert bucket url to old url

---

jenkins/common.groovy

The broken link slack notification is not working, I believe because the logfile path is incorrect.

Fix broken links logfile location

---

src/site/stages/prearchive/link-assets-to-bucket.js

Since we are now [setting the public path for CSS assets](https://github.com/department-of-veterans-affairs/vets-website/pull/17200) in vets-website, we no longer need the `linkAssetsToBucketCSS`function in the Prearchive script.
Tested in CI.

Remove the linkAssetsToBucketCSS function

---

src/site/constants/buckets.js
src/site/stages/build/plugins/download-assets.js
src/site/stages/build/plugins/modify-dom/process-entry-names.js

We want the content build to be able to download assets with or without the S3 paths in the name.
Slack thread: https://dsva.slack.com/archives/C01S39QMSSV/p1620936974267300

Handle paths with bucket url

---

src/site/stages/build/plugins/download-assets.js
src/site/stages/build/plugins/modify-dom/process-entry-names.js

This PR makes some minor changes to the `download-assets.js` and `process-entry-names.js` plugins. Rather than checking if the path of an asset contains `https`, check if it contains the bucket URL. This way we know the URL of the assets being downloaded are consistent with the bucket constants.
Tested locally and in CI.

Small cleanup of handling assets

---

src/site/layouts/home.drupal.liquid

(Originally in https://github.com/department-of-veterans-affairs/vets-website/pull/17033)
For:  https://github.com/department-of-veterans-affairs/va.gov-team/issues/24078
> The "Zone One" links on the home page only record the click URL.
> `Navigation - Zone One - ->/claim-or-appeal-status`
> Because we have several links that share URLs (and Click Text even), we need to add Click Text and Heading to differentiate.

Add heading and click text to zone one links

---

src/site/paragraphs/collapsible_panel.drupal.liquid
src/site/paragraphs/q_a.collapsible_panel.drupal.liquid
src/site/paragraphs/q_a.drupal.liquid

resolves:
department-of-veterans-affairs/va.gov-team#23963
although the issue is closed, the fix introduced a bug. the assumption was that all associated content would be an h3, but that's not the case with accordion content, so we are passing down the content as a prop instead (as sharableText) instead of worrying about the structure of the content
associated vets-website PR: https://github.com/department-of-veterans-affairs/vets-website/pull/17227

pass down sharableText to sharableLink as a prop, for accessibility

---

src/site/filters/liquid.js
src/site/filters/liquid.unit.spec.js

Added the following tests to `toTitleCase`:
- null => null
- "" => ""
- [] => ""
- "tEST" => "Test"
- "t3sT String" => "T3st String"
Also, refactored the function to include lodash - upperFirst.
Yes
N/A

Added tests for toTitleCase

---

Jenkinsfile

This PR move the creation of a review instance into the early steps of the CI process so engineers don't have to wait for all tests to pass before deploying to a review instance. The deployment process takes about 10mins, which is not reflected in the pipeline because it triggers a secondary job.
Successful RI deployment 
vet-website PR: https://github.com/department-of-veterans-affairs/vets-website/pull/17256

Relocate review instance deployment in Jenkins

---

src/site/stages/build/plugins/modify-dom/add-id-to-subheadings.js

[Nightwatch sitemap a11y scan ](http://jenkins.vfs.va.gov/blue/organizations/jenkins/testing%2Fcontent-build/detail/feature%2Fnightwatch-content-a11y-tests/9/pipeline/)is picking up an error for `Links must have discernible text` on https://www.va.gov/albany-health-care/policies/
I tracked this down to a rogue H2 coming from the CMS, so I added a check in the TOC generator to test for the presence of and ID before creating the link.

Fix for links must have discernible text on TOC in build

---

src/site/includes/how-do-you-rate.drupal.liquid

**Issue:** https://github.com/department-of-veterans-affairs/va.gov-team/issues/14302
This PR updates the styling of the `how do you rate` component and adds the JS functionality to record events:
```js
{
'event': 'int-radio-button-option-click',
'radio-button-label': "How do you rate your experience on this page?",
'radio-button-optionLabel': event.target.value, // "Good" | "Bad"
'radio-button-required': false,
}
```
Locally

Update how do you rate component

---

src/site/tests/static-pages/static-page-widgets.unit.spec.js

Since the static page widget unit test is testing the `mountWidgets` function that lives in `content-build`, the test should be migrated to this repo. This test will be removed from `vets-website`.
Tested locally and in CI.

Add static page widget unit test

---

src/site/filters/liquid.js
src/site/filters/liquid.unit.spec.js

Created tests for the following functions:
1. `benefitTerms()`
2. `findCurrentPathDepth()`
3. `hashReference()`
4. `fileExt()`
Additionally, I combed through `liquid.js` and found that the following tests are not currently being utilized and have removed them:
- `humanizeTime()`
- `unixFromDate()`
- `modulo()`
- `breakTerms()`
- `facilityIds()`
- `widgetFacilitiesList()`
- `eventSorter()`
- `getPagerPage()`
- `isPitt()`
- `isPastDate()`

Added tests for 4 liquid.filter functions

---

src/site/layouts/campaign_landing_page.drupal.liquid

**Issue:** N/A
**Slack thread:** https://dsva.slack.com/archives/C0MQ281DJ/p1621873230052900?thread_ts=1621872540.049800&cid=C0MQ281DJ
This PR fixes an empty a tag that was rendered even when the CMS said it shouldn't. 🙂

Conditionally render cta link

---

src/applications/registry.json

https://github.com/department-of-veterans-affairs/va.gov-team/issues/25178
Changes the URL for virtual-agent from /virtual-agent to /virtual-agent-study

Changes virtual agent URL

---

src/site/layouts/media_list_images.drupal.liquid
src/site/paragraphs/media.drupal.liquid
src/site/stages/build/drupal/graphql/nodeMediaListImages.graphql.js

**Issue:** https://github.com/department-of-veterans-affairs/va.gov-team/issues/24293
This PR adds expand image buttons to each image in `media_list_images` pages.
Locally

Add expand image button to each image in media list images

---

src/applications/registry.json

During an IA review, Mikki discovered that the breadcrumb paths for form 10182 (Notice of Disagreement) were including appropriate links. It appears that the `path` in the `registry.json` file should not include a leading `/`. It has been removed for 2 forms in this PR:
- Form 10182 (Notice of Disagreement)
- Form 26-1880 (Certificate of Eligibility)
Related: https://github.com/department-of-veterans-affairs/va.gov-team/issues/25216
N/A

Fix breadcrumb path

---

src/site/stages/build/plugins/create-environment-filter.js

**Slack:** https://dsva.slack.com/archives/C52CL1PKQ/p1622058438250800?thread_ts=1622058073.248800&cid=C52CL1PKQ
This PR removes random-lang-support-link templates from production builds.

Remove random-lang-support-link from prod builds

---

package.json

* The Nightwatch accessibility checks retry 1000+ page scans when a test fails
* This will help reduce the time the daily a11y check runs
* One retry should catch lagging tests like (possibly) the MegaMenu e2e test
* Tests run in CI, no failures
* Nightwatch keyboard testing fails on `localhost` for reasons unknown. The test passes consistently on Jenkins. Verified there are only two Nightwatch e2e tests on content-build:
* Home page test
* Accessible modal dialog (mocks keyboard navigation)

Reducing the number of Nightwatch retries

---

src/site/includes/pagination.drupal.liquid
src/site/layouts/support_resources_article_listing.drupal.liquid

**Issue:** https://github.com/department-of-veterans-affairs/va.gov-team/issues/18571
This PR tweaks the pagination template to **not show when there is only 1 page.**
**Before:** https://www.va.gov/resources/tag/claims-and-appeals-status/
**After:**

Ensure pagination does not show when only 1 page

---

src/site/assets/robots.txt

Adding new health care questionnaires to not be indexed by search engines. We want to prevent users from stumbling on our app as much as possible
- none

disallow health care questionnaire

---

src/site/layouts/campaign_landing_page.drupal.liquid

This PR fixes CLP conditional rendering of a CTA button below the iframe video.

Add conditional rendering check for clp video cta

---

src/site/layouts/media_list_images.drupal.liquid

**Issue:** https://github.com/department-of-veterans-affairs/va.gov-team/issues/24293
This PR adds the expand image button to items that are hidden by `show more` on http://localhost:3002/preview?nodeId=6954.
Locally

Add expand image button to show more items

---

src/site/filters/liquid.js
src/site/filters/liquid.unit.spec.js

We use tinyliquid to render templates into HTML. Tinyliquid's default 2-minute timeout is insufficient with high node counts, likely because metalsmith runs many tinyliquid engines in parallel. At 48k nodes the following error would cause the build to fail both locally and on CI:
```
Step 21 of 54 start: Apply layouts C
/Users/chris/Documents/code/content-build/src/site/stages/build/index.js:243
if (err) throw err;
^
Error: Timeout.
at Timeout.<anonymous> (/Users/chris/Documents/code/content-build/node_modules/tinyliquid/lib/index.js:79:16)
```
Increasing the timeout to 20 minutes resolves the error.
- Successful 48k node content build (no timeout observed)
- Instrument tinyliquid to output timeout value, ensuring it is set correctly
- No regressions in existing build

#23667: Increase tinyliquid timeout to 20 minutes

---

.gitignore
src/site/stages/build/options.js
src/site/stages/build/plugins/download-drupal-assets.js

Keep Drupal assets in `.drupalAssets`. Do not delete cache between builds. Do not re-download assets if already in cache. If desired, we can add a yarm command to clear the asset cache.
Ran `yarn build --pull-drupal` twice.
Assets downloads went from ~20 minutes to 102ms for the 2nd run.

Local builds do not re-download cached assets 

---

src/applications/registry.json

Set Notice of Disagreement flag to have it build in production. This is in preparation for UAT testing. The form is behind a feature flag, so this change will only show a work-in-progress banner to those without the flag set.
N/A
N/A

NOD: build in prod

---

src/site/layouts/publication_listing.drupal.liquid

**Issue:** https://github.com/department-of-veterans-affairs/va.gov-team/issues/21528
This PR fixes the styling of the custom pagination on outreach-materials.
http://localhost:3002/outreach-and-events/outreach-materials/

Fix pagination styling on outreach mats

---

script/preview-routes/single-page-diff.js
script/preview.js

Currently, the preview server returns HTTP 200 while starting up.  This causes a problem for some uses, e.g. [this one](https://github.com/department-of-veterans-affairs/content-build/pull/177) where we're using the output of the preview build to replace individual pages from the monolithic build.
After some thought, I think an HTTP 503 along with a 'Retry-After' header is a more appropriate response.  I'm a foole, though, and agreeable to modifications or other suggestions.  I thought 30 seconds was a reasonable retry-after time, but maybe that should be less.
Started up preview server, curled it in another tab, saw appropriate status code and headers.

Preview route should return a non-200 status code.

---

jenkins/common.groovy

Update the null output to read "a content-only deployment"
Slack example: https://dsva.slack.com/archives/C0MQ281DJ/p1622737500150900
Viewed in CI

Updated broken link slack alert message

---

src/site/includes/how-do-you-rate.drupal.liquid

**Issue:** https://github.com/department-of-veterans-affairs/va.gov-team/issues/14302
This PR adds a submit button to the how do you rate component.
Locally

Update how do you rate with submit button

---

package.json
src/site/stages/build/index.js
src/site/stages/build/plugins/modify-dom/index.js
src/site/stages/build/plugins/rewrite-va-domains.js
src/site/stages/build/silversmith.js

Parts of the content build rapidly allocate and deallocate large amounts of data. V8's automatic garbage collection handles this well in most cases, but it can fall behind. This causes spikes in heap and non-heap (buffer) allocation, resulting in very large peak memory use at high node counts.
To address the problem, this PR:
- triggers manual garbage collection at a 10-second interval to keep memory use in check, particularly during the Apply Layouts steps
- adds 1ms pauses to allow garbage collection during two especially memory-intensive steps
- adds logging for total memory use (RSS) to the log, helping track changes  over time
See [#25074](https://app.zenhub.com/workspaces/vsp---frontend-tools-5fc9325744944e0015ed1861/issues/department-of-veterans-affairs/va.gov-team/25074) and …

#25074: Add manual garbage collection at regular interval

---

src/site/includes/how-do-you-rate.drupal.liquid

**Issue:** 
This PR implements some tweaks to a11y for the how do your rate component.
Locally

Update how do you rate component with a11y improvements

---

src/site/layouts/campaign_landing_page.drupal.liquid
src/site/stages/build/drupal/graphql/nodeCampaignLandingPage.graphql.js

**Issue:** https://github.com/department-of-veterans-affairs/va.gov-team/issues/25520
This PR implements a 3x2 derivative image for CLP stories.
Locally

Add derivative sizing to clp story images

---

src/site/includes/how-do-you-rate.drupal.liquid
src/site/paragraphs/lists_of_links.drupal.liquid

**Slack:** https://dsva.slack.com/archives/C52CL1PKQ/p1623254243056500
This PR adds missing `nonce` attributes to script tags in liquid templates.

Add nonce to script tags

---

src/site/filters/liquid.js
src/site/filters/liquid.unit.spec.js
src/site/layouts/event_listing.drupal.liquid
src/site/layouts/tests/vamc/fixtures/eventListingMockData.json
src/site/stages/build/drupal/graphql/GetLatestPageById.graphql.js

Events page can now be viewed in preview server
Note: There are limitations related to paginating pages but this does NOT affect build.
In addition, if an event is featured, the title is now fixed to say `In the spotlight at <name of location>`
Units tests were added to liquid filters added

Vamc events page preview-able

---

src/applications/registry.json

This PR was opened for this [ticket](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/23341) in conjunction with this [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/17540)
FSR URL should be updated to www.va.gov/manage-va-debt/request-debt-help-form-5655/ and the breadcrumbs should be: Home > Manage VA debt > Request help with VA debt
[Ticket](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/23341)
- Manual and visual testing

Update FSR link as well as breadcrumbs

---

src/site/includes/how-do-you-rate.drupal.liquid

This PR switches from using inline HTML event listeners to `.addEventListener` in an effort to get the event handlers working correctly on https://staging.va.gov/resources/can-i-be-buried-in-arlington-national-cemetery/
Resource: https://developers.google.com/web/fundamentals/security/csp#inline_code_is_considered_harmful
Tested on http://localhost:3002/preview?nodeId=6954

Use .addEventListener over inline html listeners

---

src/site/includes/how-do-you-rate.drupal.liquid

This PR is in response to [this comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/14302#issuecomment-860959106). This PR does the following:
> 1/ the Good/Bad radio buttons should be side by side on the same line, per mock here
> 2/ the Submit button should use a secondary button styling per comment above - design system: https://design.va.gov/components/buttons#secondary-button
> 3/ The text of the button - let's use Submit feedback since our thank you message says, "Thank you for your feedback."

Tweak how do you rate component styling

---

.liquidrc
src/site/filters/liquid.js
src/site/layouts/story_listing.drupal.liquid
src/site/stages/build/drupal/graphql/GetLatestPageById.graphql.js

Stories page is preview-able

---

src/site/filters/liquid.js
src/site/filters/liquid.unit.spec.js
src/site/layouts/event_listing.drupal.liquid
src/site/layouts/press_releases_listing.drupal.liquid
src/site/layouts/tests/vamc/fixtures/pressReleasesMockData.json
src/site/stages/build/drupal/graphql/GetLatestPageById.graphql.js

Issue is linked below
To preview use - http://localhost:3002/preview?nodeId=2805

News release page now preview-able

---

src/site/layouts/home.drupal.liquid

**Slack:** https://dsva.slack.com/archives/CE4304QPK/p1623951602172600
This PR updates the `h4` tags on the homepage to `h3` tags so that headers increment correctly.

Update h4 to h3

---

src/site/stages/build/drupal/graphql/locationsListingPage.graphql.js
src/site/stages/build/drupal/graphql/nodeBasicLandingPage.graphql.js
src/site/stages/build/drupal/graphql/nodeCampaignLandingPage.graphql.js

See https://github.com/department-of-veterans-affairs/va.gov-cms/issues/5339
Remove ununsed fieldMetaTitle from graphql to prevent build errors when we remove from cms
Build
N/A

VACMS-5339: Remove ununsed fields from graphql.

---

src/site/layouts/health_care_region_locations_page.drupal.liquid
src/site/stages/build/drupal/health-care-region.js

A previous [PR](https://github.com/department-of-veterans-affairs/content-build/pull/258) added the mobile clinic section, but it only worked in preview mode.
This is because we are currently using a different template in preview vs. full build.
A [tech debt ticket ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/26301)has been created for this. In the meantime, this PR contains the changes needed to add the mobile clinic section in the full build.

Show mobile clinics on locations page in full build

---

src/site/filters/liquid.js
src/site/filters/liquid.unit.spec.js
src/site/layouts/vamc_operating_status_and_alerts.drupal.liquid

Resolves the issue linked below
It was discovered that the missing content/data was, in fact, not there in the first place (operating statuses needed to be manually input into each facility- this became a separate issue that CMS will handle on their end)
I made changes to handle instances where the the `Facility operating statuses` jumplink and `Situation updates and information` h2 tags will not display if there is no content to show.
Use Wilkes-Barre to preview- http://localhost:3002/preview?nodeId=2369

Changes made to operating status page

---

src/site/stages/build/add-debug-info.js
src/site/stages/build/drupal/page.js
src/site/stages/build/index.js
src/site/stages/build/options.js

Currently, debug info for Drupal pages in stored in the `files` object during the Metalsmith build. This is using more memory during the build than needed since we aren't performing and modifications on that information. Removing the debug info from the `files` object during the build, and adding it directly to HTML pages on disk, can free up memory. 
Overall, this reduced the build time on our current node count by over 2 minutes, and reduced peak memory usage by `500mB`. When tested on 48k nodes, the build didn't run out of memory with these changes.
- Compared build files from the changes in this branch to `master`.
- Tested on CI on our current node count
- Tested on 48k nodes in CI
- Tested debug info in preview server
More info about testing can be seen in the …

Move debug info to end of build process

---

src/site/includes/image_and_static_map.liquid

resolves - https://github.com/department-of-veterans-affairs/va.gov-team/issues/25011
Use this vet center to preview - http://localhost:3002/preview?nodeId=3756

Hide map from screenreader in Vet Center

---

src/site/layouts/vet_center_locations_list.drupal.liquid

Issue linked below
Can use Escanaba to preview - http://localhost:3002/preview?nodeId=16478

Removed intro text in Vet Center locations page

---

src/site/constants/blocklistedEntities.js
src/site/stages/build/plugins/create-environment-filter.js

**Issue:** https://github.com/department-of-veterans-affairs/va.gov-team/issues/25435
This PR creates config functionality for removing specific node IDs + entityBundles from environments. This work is being done as it's been requested twice now and it would be more convenient to have a single config file for adding this functionality in the future.
Locally
N/A

Add blocklisted-from-prod entities functionality

---

src/site/components/tests/image.drupal.unit.spec.js
src/site/tests/support/index.js

Resolves ticket #26212 - https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/26212
Injects `lang` attribute if it's missing so Axe tests can pass.
All liquid template unit tests pass:
```
41 passing (18s)
```

inject lang attribute if missing

---

script/preview-routes/single-page-diff.js
script/preview.js
src/site/stages/build/drupal/menus.js
src/site/stages/preview/index.js

Currently, when using the preview server locally, we need to run a full content build prior so that `headerFooter.json` is created and a symlink to `file-manifest.json` is made. This PR updates the preview server script, so we don't need to run a content build just to create/reference those two files.
The `create-header-footer` plugin is added to the preview server's Metalsmith pipeline, so now we don't need to fetch that file from the `generated` directory, which would cause an error on the preview server if it didn't exist. Instead `headerFooter.json` is built on demand when viewing a page in the preview server.
A symlink to `generated/file-manifest.json` will be created in the preview script if one doesn't already exist. This avoids the need to run a full content build, since the …

Create headerFooter in preview server

---

.github/workflows/continuous-integration.yml

Based on observation, duplicate runs are being executed on content-release and daily-deploy. This PR eliminates extra steps appended to the last commit
Ref: [merged_pr](https://github.com/department-of-veterans-affairs/content-build/runs/2917968360)
N/A

Ignore duplicate runs on releases

---

src/site/includes/how-do-you-rate.drupal.liquid

**Issue:** https://github.com/department-of-veterans-affairs/va.gov-team/issues/26434
This PR resolves an analytics bug for the how do you rate component where the option label was always undefined. It now resolves to "good" + "bad".
Locally.

Use optionLabel over event.target.value

---

src/site/stages/build/drupal/metalsmith-drupal.js
src/site/stages/build/options.js
src/site/stages/build/plugins/download-drupal-assets.js

This PR adds the `--use-cached-assets` flag which can be used together with `--pull-drupal` in order to pull new drupal content but still used cached assets.
locally ran `yarn build`, `yarn build --pull-drupal`, and `yarn build --pull-drupal --use-cached-assets` without issue.

add use-cached-assets flag option for build

---

src/platform/static-data/footer-links.json

**Issue:** https://github.com/department-of-veterans-affairs/va.gov-team/issues/26858
This PR changes the footer link from `LGBT` to `LGBTQ+`.
N/A
N/A

Update footer link

---

src/site/layouts/campaign_landing_page.drupal.liquid
src/site/stages/build/drupal/graphql/nodeCampaignLandingPage.graphql.js

**Issue:** https://github.com/department-of-veterans-affairs/va.gov-team/issues/26806
This PR adds a derivative to the CLP hero image.
Locally

Update hero image derivative

---

src/site/layouts/tests/vamc/system_home.cypress.spec.js
src/site/paragraphs/facilities/list_of_link_teasers_facility.drupal.liquid

A [recent change](https://github.com/department-of-veterans-affairs/content-build/pull/297) to our templates accidentally omitted the HREF's for our "In the Spotlight" links.
This PR restores them.

Restore HREF's to In the Spotlight links on VAMC pages

---

src/platform/site-wide/tests/sitemap/sitemap-1.spec.js
src/platform/site-wide/tests/sitemap/sitemap-2.spec.js
src/platform/site-wide/tests/sitemap/sitemap-3.spec.js
src/platform/site-wide/tests/sitemap/sitemap-4.spec.js
src/platform/site-wide/tests/sitemap/sitemap-helpers.js
src/platform/testing/e2e/timeouts.js

Extending the timeout for daily accessibility tests because they are sometimes failing with the previous 20 second timeout limit.

Bump timeout for a11y tests that are timing out

---

.github/workflows/continuous-integration.yml

This sets the Drupal addresses for GHA builds to the actual environments on `master` instead of always using the sandbox.
Verified that builds in feature branch still use the sandbox.
Will verify when merged to `master` that the actual environments are used.

Use appropriate Drupal addresses in GHA builds.

---

.github/workflows/continuous-integration.yml

This will only run the broken link check on prod builds, which mirrors the Jenkins pipeline more closely.
The check is currently breaking on the other environments in `master`, so this will hopefully produce a fully passing workflow once merged to `master`.
CI passes.

Only check broken links in GitHub Actions prod build

---

jenkins/common.groovy
src/site/stages/build/drupal/api.js
src/site/stages/build/drupal/graphql/GetAllPages.graphql.js
src/site/stages/build/drupal/queries.js

Cleaning up the last bit of CMS Export code with useTomeSync. This was previously merged, but broke the master CI runs because of a caching step that isn't presenting PRs. The previous code was merged with https://github.com/department-of-veterans-affairs/content-build/pull/282
Passing CI, but also passing GHA's Continuous Integration / Drupal Cache Test (push) and a separate run that executes Jenkins master caching. Also downloaded the fine results from S3 and did a visual spot check.

Remove last bits of useTomeSync to sunset CMS Export code

---

src/site/stages/build/drupal/assets.js

File path regex was failing to download on assets from other sites that were also using Drupal. Reverting to a previous functional state.

Updated file path search for drupal assets

---

src/site/stages/build/drupal/graphql/navigation-fragments/facilitySidebar.nav.graphql.js

See https://dsva.slack.com/archives/C0FQSS30V/p1625667550138900
None, visual comparison with menu ids stored in Drupal.
Stan may be testing for Central Texas in tugboat

Add VISN 5, 12, 17 menus to facilitySidebar

---

src/site/stages/build/drupal/api.js
src/site/stages/build/drupal/graphql/GetAllPages.graphql.js
src/site/stages/build/drupal/utilities-drupal.js

VAMC health care region pages (e.g. /pittsburgh-health-care) are showing events marked as "featured" but with start dates in the past.
Confirmed: the "today" GraphQL query variable is using a string format for the current date ('YYYY-MM-DD"), but the data is in UNIX timestamp format. So the `eventTeasersFeatured` query [filter](https://github.com/department-of-veterans-affairs/content-build/blob/c00c759cac79f12ae1838435cc3973a0123b4216/src/site/stages/build/drupal/graphql/healthCareRegionPage.graphql.js#L140) that's supposed to filter out past events isn't working.
This PR fixes this, but it needs to be tested thoroughly because it impacts every query that uses the "today" variable (all events pages, including outreach-and-events).

Show only future events on health care region page

---

.github/workflows/daily-deploy-production.yml

Changing default time to 5 mins rather than manually doing so

Daily deploy (github actions) -- default time change

---

src/site/filters/liquid.js
src/site/filters/liquid.unit.spec.js
src/site/includes/metatags.drupal.liquid
src/site/includes/metatags.liquid

**Issues:** 
https://github.com/department-of-veterans-affairs/va.gov-team/issues/24383
https://github.com/department-of-veterans-affairs/va.gov-team/issues/23082
https://github.com/department-of-veterans-affairs/va.gov-team/issues/26679
This PR updates the following title metatags (before/after):
```diff
- 28-1900 Veteran Readiness
+ 28-1900 Veteran Readiness | Veterans Affairs
```
```diff
- 686C-674
+ 686C-674 | Veterans Affairs
```
```diff
- All articles in: Burials and memorials
+ All Articles In: Burials And Memorials | Veterans Affairs
```
```diff
- All articles in: Decision reviews and appeals
+ All Articles In: Decision Reviews And Appeals | Veterans Affairs
```
```diff
- All articles in: Disability
+ All Articles In: Disability | Veterans Affairs
```
```diff
- All articles in: …
```

[WIP] Format metatags

---

src/site/layouts/tests/vamc/location_home.cypress.spec.js
src/site/layouts/tests/vamc/system_home.cypress.spec.js

This PR is to remove some leftover CircleCI logic that was hanging around a couple Cypress specs.

Remove leftover circle CI references in Cypress test specs

---

.github/workflows/content-release.yml
.github/workflows/daily-deploy-production.yml
package.json
script/github-actions/validate-build-status.js
yarn.lock

- This PR changes using fetch to the octokit library. The functionality and output is primarily the same (with minor changes)
- the `validate-build-script` must now pass in SHA at all times. This is because when pulling from the latest, if a commit got recently merged it will attempt to get the new one merged rather the commit it is on.
Locally

Daily Deploy (Github Actions) -- validate-build-status using octokit

---

.github/workflows/continuous-integration.yml

PR adds concurrency. It will only cancel workflow if it is in feature branch
[Flow cancelled by concurrency](https://github.com/department-of-veterans-affairs/content-build/actions/runs/1027947954)
[New flow](https://github.com/department-of-veterans-affairs/content-build/actions/runs/1027951503)

add concurrency to CI workflow

---

.github/workflows/continuous-integration.yml

- Cancel in-progress workflows from previous commits in feature branches.
- Allow concurrent workflows from all commits in master.
Tested against [ref group](https://github.com/department-of-veterans-affairs/content-build/actions/runs/1028149729) -- cancelled as expected 
Tested against [sha group](https://github.com/department-of-veterans-affairs/content-build/actions/runs/1028200139) -- continued as expected 
Tested against [new ref group](https://github.com/department-of-veterans-affairs/content-build/actions/runs/1028205080) -- continued as expected and cancelled previous run

Github Actions (CI) -- Fix concurrency for master branch

---

.github/workflows/content-release.yml
.github/workflows/daily-deploy-production.yml

Currently, in order for the notification to get sent on Slack, it must pass the `validate-build-status`. That being said, if the validate-build-status is still pending, until it passes/fails it could be mins/hours before notification, which could be misleading that the workflow is never triggered.
This PR does the following:
Send notification as soon as workflow gets triggered. Remainder of workflow remains the same (build only proceeds if `validate-build-status` succeeds)

Daily Deploy (Github Actions) -- change workflow order (notification)

---

src/site/includes/metatags.drupal.liquid
src/site/includes/tests/fixtures/metatags.json
src/site/includes/tests/metatags.drupal.unit.spec.js
src/site/layouts/tests/vet_center/vet_center.drupal.unit.spec.js
src/site/layouts/tests/vet_center/vet_center_locations_list.drupal.unit.spec.js

To preview use:
escanaba main page - http://localhost:3002/preview?nodeId=3756
escanaba locations page - http://localhost:3002/preview?nodeId=16478
<details>
<summary>Screenshot</summary>
</details>

Added vet center title to metatags

---

script/github-actions/validate-build-status.js

If some jobs are cancelled, they are still annotated as errors and can be a bit misleading. This PR identifies which is failure and cancelled jobs (as of result of manual or other jobs failed) are identified as warnings

Github Actions (validate-build-status) -- clearer output on job failed

---

src/site/filters/liquid.js
src/site/filters/liquid.unit.spec.js
src/site/includes/header.html
src/site/includes/metatags.drupal.liquid
src/site/includes/metatags.liquid

**Issue:** https://github.com/department-of-veterans-affairs/va.gov-team/issues/24383
This PR formats the metatag templates for readability. It also should fix titles on VAMC pages (which were using custom metatags). It also replaces any instances of when the title has ` | | ` due to a missing field office.
Added unit test:

Format metatags template for readability + fix titles on vamc pages

---

.github/workflows/manual-review.yml
src/site/components/administration-hub-rail.drupal.liquid

Addressing a request to have manual checks only run when a PR is ready for review.
Issue: https://github.com/department-of-veterans-affairs/va.gov-team/issues/26651
1. Open Draft PR (no icon checks) -> "Ready for review" (manual icon runs)
2. Open normal PR manual check runs)
3. Open Draft (no icon checks) -> -> "Ready for review" (manual icon runs) -> Edit PR (manual icon runs)

Don't run icon check on Draft PRs

---

src/site/filters/liquid.js
src/site/filters/liquid.unit.spec.js

This PR fixes an edge case where `" |  | "` is being sent from the CMS as a custom metatag, e.g. on the /resources page.
Updated unit test
N/A

Add additional replace for | |

---

src/site/includes/image_and_static_map.liquid

To test/preview: http://localhost:3002/preview?nodeId=1259
Expect to not see this axe-core violation below
<details>
<summary>Screenshot of violation</summary>
</details>

Removed aria-hidden prop from map

---

package.json
yarn.lock

Upgrade Sentry to `v6.9.0`.
Tested in the `vets-website` repo since Sentry isn't used in any unit tests in this repo.

Upgrade Sentry to v6.9.0

---

src/site/facilities/facility_health_service.drupal.liquid
src/site/facilities/health_service.drupal.liquid
src/site/layouts/campaign_landing_page.drupal.liquid
src/site/layouts/faq_multiple_q_a.drupal.liquid
src/site/layouts/health_care_local_facility.drupal.liquid
src/site/layouts/tests/vamc/location_home.cypress.spec.js
src/site/navigation/facility_no_drupal_page_sidebar_nav.drupal.liquid
src/site/paragraphs/collapsible_panel.drupal.liquid
src/site/paragraphs/q_a.collapsible_panel.drupal.liquid

Ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/27200
`src/site/layouts/faq_multiple_q_a.drupal.liquid`
`src/site/layouts/faq_multiple_q_a.drupal.liquid`
`src/site/layouts/campaign_landing_page.drupal.liquid`
`src/site/paragraphs/q_a.collapsible_panel.drupal.liquid`
`src/site/paragraphs/collapsible_panel.drupal.liquid`
`src/site/facilities/health_service.drupal.liquid`
`src/site/facilities/facility_health_service.drupal.liquid`

Replace usa-accordion with va-accordion

---

src/site/filters/liquid.js
src/site/filters/liquid.unit.spec.js
src/site/layouts/support_resources_article_listing.drupal.liquid

**Issue:** https://github.com/department-of-veterans-affairs/va.gov-team/issues/27793
This PR adds a no index metatag for the following paginated pages:
https://www.va.gov/resources/other-topics-and-questions/2/
https://www.va.gov/resources/other-topics-and-questions/3/
https://www.va.gov/resources/va-account-and-profile/2/
https://www.va.gov/resources/education-and-training/2/
https://www.va.gov/resources/tag/all-veterans/2/
https://www.va.gov/resources/tag/all-veterans/3/
https://www.va.gov/resources/tag/all-veterans/4/
https://www.va.gov/resources/tag/all-veterans/5/
https://www.va.gov/resources/tag/all-veterans/6/
https://www.va.gov/resources/tag/payments-and-debt/2/
Added unit test.
N/A

Add noindex metatag when it is a paginated path

---

src/site/includes/footer.html
src/site/includes/header.html

https://github.com/department-of-veterans-affairs/va.gov-team/issues/7425
Footer announcements under `#announcement-root` exist outside of a landmark, so this moves both the `footer` and `#announcement-root` under a `section` with `role="contentinfo"` This is inside of a `section` because a `footer` automatically gets `role="contentinfo"` unless it is contained within a small subset of tags with `section` being the most appropriate of this subset. see https://www.w3.org/TR/wai-aria-practices/examples/landmarks/HTML5.html
local testing with http://matatk.agrip.org.uk/landmarks/

Wrap footer in role=contentinfo section for consistent landmarks

---

src/site/layouts/home.html

**Issue:** https://github.com/department-of-veterans-affairs/va.gov-team/issues/27903
This issue was brought to my attention by Tim Wright. If you navigate to http://vhl.staywellsolutionsonline.com/Resources/VideoLibrary/?e=0#landing you can see that there is a runtime error because we cannot find a specific hubLink on the page and then we try to add an event listener to it.
This PR fixes that runtime error by wrapping the code in a conditional that checks to see if we found a hubLink first before adding an event listener to it.

Fix runtime error on external domains

---

.github/workflows/continuous-integration.yml

Overtime the CI portion kept failing due to `503 Unavailable` in master when it is passing in Jenkins. This PR changes drupal address to align closely and not fail in master branch.
Additionally added flags to align as close as possible to Jenkins
[run](https://github.com/department-of-veterans-affairs/content-build/runs/3174216490?check_suite_focus=true) -- cancelled purposefully to not publish info

Github Actions (CI) -- add more flags to build

---

src/site/layouts/publication_listing.drupal.liquid

Reported Error: 
> [Report Only] Refused to load the image 'https://via.placeholder.com/318x212' because it violates the following Content Security Policy directive: "img-src 'self' data: blob: https://*.gstatic.com https://api.mapbox.com https://www.google-analytics.com https://www.googletagmanager.com https://stats.g.doubleclick.net https://*.va.gov https://optimize.google.com https://gateway.foresee.com https://static.foresee.com https://cdn-prod.kampyle.com https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com https://s3-us-gov-west-1.amazonaws.com https://ok6static.oktacdn.com https://dvp-oauth-application-directory-logos.s3-us-gov-west-1.amazonaws.com".
Issue: http://sentry.vfs.va.gov/organizations/vsp/issues/583/?project=4&query=logger%3Acsp+is%3Aunresolved+is%3Aunassigned&sort= …

Removed fallback image that was violating CSP

---

src/site/filters/liquid.js
src/site/filters/liquid.unit.spec.js
src/site/layouts/publication_listing.drupal.liquid
src/site/layouts/tests/publication_listing/fixtures/docxFileData.json
src/site/layouts/tests/publication_listing/fixtures/pdfFileData.json
src/site/layouts/tests/publication_listing/publication_listing.drupal.unit.spec.js
src/site/paragraphs/downloadable_file.drupal.liquid

https://github.com/department-of-veterans-affairs/va.gov-team/issues/14614
I added the `fileDisplayName` filter to change generated file names from things like `files/documents/file.txt` to just `file.txt`. Additionally, I noticed that the fileSize filter would display 0.00MB for files that were smaller than 10,000B so I changed the logic to use KB for files < 10,000KB.
local and mocha testing of template output

Add type to pdf file download links

---

package.json
script/drupal-aws-cache.js
yarn.lock

Review instances were failing because the cached content for the dev environment was >2gb in size. The `decompress` package couldn't handle tarballs that large. Switching to the `tar` package allows streaming extraction instead of loading the entire file into memory at once. This removes the 2gb limit.
- Run `node script/drupal-aws-cache.js --fetch` locally and check extracted build files
- Check that review instance works

Use "tar" instead of "decompress" to allow content cache files >2gb

---

src/site/layouts/landing_page.drupal.liquid
src/site/layouts/tests/landing_page/fixtures/landing_page.json
src/site/layouts/tests/landing_page/landing_page.unit.spec.js

https://github.com/department-of-veterans-affairs/va.gov-team/issues/18151
local browser and unit testing

Add link and aria-label to tty 711 service

---

.prettierrc
src/site/assets/js/execute-axe-check.js
src/site/assets/js/medallia/vagovprod.js
src/site/assets/js/static-page-widgets.js
src/site/components/navigation-sidebar-trigger.html

Found while working on issue: https://github.com/department-of-veterans-affairs/va.gov-team/issues/25103
It appears that we have syntax errors in IE11 that stop JavaScript rom running due to trailing commas in function parameters: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Trailing_commas#browser_compatibility
I'll have to either modify the build to strip these out or remove them manually. This could be a lot of work

Remove trailing commas in function params

---

src/site/paragraphs/collapsible_panel.drupal.liquid
src/site/paragraphs/q_a.collapsible_panel.drupal.liquid

Removes two implementations of the SharableLink react widget component specifically when they are used in the expandable content of the `va-accordion` web component.
The reason for needing to remove these is noted in this ticket comment: [#26744](https://github.com/department-of-veterans-affairs/va.gov-team/issues/26744#issuecomment-889268802)
Removing these results only one instance of SharableLink via [q_a.drupal.liquid](https://github.com/department-of-veterans-affairs/content-build/blob/master/src/site/paragraphs/q_a.drupal.liquid#L31) and this instance works correctly because it is not nested within a web component.
Further work will be done at a later time to refactor this component to work appropriately since it is currently shown on only a single page in an experimental fashion. …

remove sharableLink usage from accordions

---

src/site/includes/metatags.drupal.liquid

**Issue:** https://github.com/department-of-veterans-affairs/va.gov-team/issues/28223
This PR adds `hostUrl` prefix to `og:image` custom metatags.

Add hostUrl prefix to og:image custom metatags

---

.github/workflows/continuous-integration.yml

Reverting #417 as it was causing the build to fail. Upon investigating, it seemed that it was not detecting the cache folder, thus causing the flakiness.
This PR reverts and adds `network-concurrency 1` to still address flaky install fails
[run](https://github.com/department-of-veterans-affairs/content-build/runs/3235807371?check_suite_focus=true) -- will most likely fail at vagovprod

Github Actions (CI) -- revert retry on build and use network concurrency instead

---

src/site/stages/build/drupal/individual-queries.js

This reverts commit 5a98e93a2fa0026c59ae8804ae70600b52386c8b.
It broke the /locations pages.

Revert "Reorder the queries so lists go first (#414)"

---

src/site/layouts/news_story.drupal.liquid
src/site/layouts/tests/news_story_page/fixtures/news-story-data.json
src/site/layouts/tests/news_story_page/news_story.unit.spec.js

Link to an example news story page - https://www.va.gov/gulf-coast-health-care/stories/audiologist-recognized-at-national-convention/
Added unit tests

Fixed issue with broken stories link

---

src/site/layouts/page.drupal.liquid
src/site/layouts/va_form.drupal.liquid
src/site/paragraphs/linkTeaser.drupal.liquid

https://github.com/department-of-veterans-affairs/va.gov-team/issues/26906
Updated padding and font to make Find forms and Find Forms detail page consistent (Va Form node).
Spun up local preview server. See screen shots. 
**Before**: `columns` class removal
**After**: `columns` class removal
**Heading good to go**

VA Form node change for a11y needs

---

src/site/paragraphs/downloadable_file.drupal.liquid

Slack thread: https://dsva.slack.com/archives/C52CL1PKQ/p1628517568095800
Download links were missing the file type inside parenthesis. This was do to an extra letter in the variable name during assignment that was absent from the references to that variable.
Before: 
After:

Fix spelling error on variable assignment

---

src/applications/registry.json

This pull request updates the 686 root url in registry.json
Related PRs:
- https://github.com/department-of-veterans-affairs/vets-website/pull/18177
- https://github.com/department-of-veterans-affairs/devops/pull/9743
- https://github.com/department-of-veterans-affairs/vets-api/pull/7604
local

27514 update 686 root url

---

src/site/filters/liquid.unit.spec.js

This PR addresses the issue with `filterUpcomingEvents` test failing
The mock data used for the test had an event start time that has now passed causing the test to fail because that particular even is no longer an upcoming event.
To resolve this, I added a function that would add a whole day to the current date so that those events would always be considered upcoming.

Updated filterUpcomingEvents test

---

package.json
yarn.lock

`babel-core` version 6 was replaced by `@babel/core` version 7. `babel-core` is no longer needed
https://github.com/department-of-veterans-affairs/va.gov-team/issues/27348
Locally

Remove babel-core dependency

---

package.json
yarn.lock

Remove an unused dependency. Not needed in this repo
Locally

Remove babel-loader dependency

---

src/site/includes/alerts.drupal.liquid
src/site/includes/tests/alerts.drupal.unit.spec.js
src/site/includes/tests/fixtures/alerts.json

https://github.com/department-of-veterans-affairs/va.gov-team/issues/6375
https://github.com/department-of-veterans-affairs/content-build/pull/437/files?diff=split&w=1
This changes the headings in alerts.drupal.liquid from `h3`s to `h2`s since they are not preceded by `h2`s.
local and unit
Before:
After:

Use h2 for alert heading for a11y

---

.github/workflows/daily-deploy-production.yml

This PR addresses the following:
- Use persistent/on-demand runners for build job
- Transition away from upload build as an artifact, but store in persistent runner
- Restore and compress build during archive step to upload to s3
[RUN](https://github.com/department-of-veterans-affairs/content-build/runs/3313600216?check_suite_focus=true)

Github Actions (daily-deploys) -- Persistent runners

---

package.json
yarn.lock

`babel-plugin-react-transform` is a deprecated dependency. [It is already included in Babel 6 and 7](https://www.npmjs.com/package/babel-plugin-react-transform), therefore, it's no longer needed nor used
Locally

Remove babel-plugin-react-transform dependency

---

package.json
yarn.lock

Remove an unused dependency. This dependency was used in `vets-website` for the creation of new applications and it's no longer needed in this repo
Locally

Remove inquirer-autocomplete-prompt dependency

---

package.json
yarn.lock

Remove an unused dependency. It's behind 7 versions 
Locally

Remove puppeteer dependency

---

package.json
yarn.lock

Remove an unused dependency. This dependency was used in `vets-website` for the creation of new applications and it's no longer needed in this repo
Locally

Remove yeoman-generator dependency

---

src/site/filters/liquid.js
src/site/filters/liquid.unit.spec.js
src/site/paragraphs/collapsible_panel.drupal.liquid
src/site/paragraphs/q_a.collapsible_panel.drupal.liquid
src/site/paragraphs/q_a.drupal.liquid

Issue: [#28290](https://github.com/department-of-veterans-affairs/va.gov-team/issues/28290)
It has been decided that we are no longer going to be moving forward with using the SharableLink widget, and so I have been instructed to remove it from the platform. Since it was an experimental component, it was only used on [a single page](https://www.va.gov/coronavirus-veteran-frequently-asked-questions/), so the impact of removing this widget is relatively low.
This PR will be the first of two, in that I will also be [removing the react widget from vets-website](https://github.com/department-of-veterans-affairs/vets-website/pull/18277).
Removed widget from drupal template, checked for any other usages, and verified that template still renders correctly and is built in metalsmith without error.

remove sharableLink filter and usage

---

.github/workflows/content-release.yml
.github/workflows/daily-deploy-production.yml

This PR addresses the following issue:
Since `GITHUB_TOKEN` is not detected by `process.env` as previously thought. Passing token will allow more rates and prevent error out. See [Slack](https://dsva.slack.com/archives/CU1E4CX9U/p1629310136048100) for more details
N/A

Github Actions (daily-deploy & content-release) -- Add GITHUB_TOKEN to octokit api

---

src/applications/registry.json

The Higher-Level Review form breadcrumbs don't match the page title on most pages. This PR removes the "with VA Form 20‑0996" suffix.
Related: https://github.com/department-of-veterans-affairs/va.gov-team/issues/28896
N/A

Fix HLR breadcrumb

---

.github/workflows/content-release.yml
.github/workflows/daily-deploy-production.yml

This PR adds network concurrency flag to build daily deploy and content-release build to reduce flakiness on the install portion
N/A

Github Actions (content-release & daily-deploy) -- Add network concurrency

---

src/site/stages/build/drupal/graphql/navigation-fragments/facilitySidebar.nav.graphql.js

The VISN 9 menus are missing from the facilitySidebar query, see https://dsva.slack.com/archives/C0FQSS30V/p1625667550138900 for discussion of a similar past issue.
Attempting content build on the test environment for Lexington: https://master-knqezgo3rvzktwi7is3knvy2dkpn62vk.demo.cms.va.gov/admin/content/deploy

Add VISN 9 menus to facilitySidebar

---

src/site/includes/header.html

**Issues:**
https://github.com/department-of-veterans-affairs/va.gov-team/issues/29069
https://github.com/department-of-veterans-affairs/va.gov-team/issues/29209
https://github.com/department-of-veterans-affairs/va.gov-team/issues/28933
https://github.com/department-of-veterans-affairs/va.gov-team/issues/29071
https://github.com/department-of-veterans-affairs/va.gov-team/issues/28295
https://github.com/department-of-veterans-affairs/va.gov-team/issues/28296
**Related PRs:**
1. https://github.com/department-of-veterans-affairs/content-build/pull/485
1. https://github.com/department-of-veterans-affairs/vets-website/pull/18426
1. https://github.com/department-of-veterans-affairs/component-library/pull/147
This PR is part of a series of PRs to support the modified `EmergencyBanner` component …

Support new <Banner /> component

---

src/site/includes/top-nav.html

department-of-veterans-affairs/va.gov-team#25659
Creates a mega menu for desktop and one for mobile to allow proper tab ordering
This change is in conjunction with changes to
vets-website: https://github.com/department-of-veterans-affairs/vets-website/pull/18116
veteran-facing-services-tools: https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/655
local

Create separate mega menus for desktop and mobile

---

.github/workflows/continuous-integration.yml
package.json

To ensure that our on-demand runners shutdown properly, ensuring the `stop-runner` completes irregardless of if dev,stage,prod runs is not able to find information.
[Run](https://github.com/department-of-veterans-affairs/content-build/runs/3465031682?check_suite_focus=true) that failed to shut down correctly

Github Actions (CI) -- ensure on-demand runners are shutting down correctly in matrix

---

src/site/filters/liquid.js
src/site/filters/liquid.unit.spec.js
src/site/layouts/va_form.drupal.liquid
src/site/stages/build/drupal/graphql/vaFormPage.graphql.js

https://github.com/department-of-veterans-affairs/va.gov-team/issues/26908
Now that we have es from content, we can add the needed translations for a11y.
Related PR => https://github.com/department-of-veterans-affairs/vets-website/pull/18452
Spun up local env

DT-26908- vaForm node adding ES lang

---

src/site/layouts/person_profile.drupal.liquid
src/site/layouts/tests/person_profile/fixtures/download-full-size-photo-link.json
src/site/layouts/tests/person_profile/person_profile.unit.spec.js
src/site/stages/build/drupal/graphql/bioPage.graphql.js

resolves issue linked below
I confirmed that when an image is not added by the editor - `fieldMedia: null`
Tugboat instance - https://web-xzcrb121xmxquzas9jcd9p86dgwpkuam.demo.cms.va.gov/pittsburgh-health-care/staff-profiles/lovetta-ford/
Unit tests added to cover the following use cases when displaying the `Download full size photo` link
- if `fieldPhotoAllowHiresDownload = true` and we have an image (`fieldMedia`)
- if `fieldPhotoAllowHiresDownload = true` and we do not have an image (`fieldMedia`)
- if `fieldPhotoAllowHiresDownload = false` and we have an image (`fieldMedia`)
- if `fieldPhotoAllowHiresDownload = false` and we do not have an image (`fieldMedia`)

Hi resolution download link fix

---

.github/CODEOWNERS
src/site/components/fullwidth_banner_alerts.drupal.liquid
src/site/components/tests/fixtures/banner_alerts_inherit.json
src/site/components/tests/fixtures/banner_alerts_no_inherit.json
src/site/components/tests/fullwidth_banner_alerts.drupal.unit.spec.js

Resolves https://github.com/department-of-veterans-affairs/va.gov-team/issues/29459
To verify, visit any VAMC that does NOT have the "Limit banner display to the home and the Operating Status page(s)" checkbox checked in Drupal, e.g. 
https://master-ldij0hdlillzgrlzsgjk8keqbcknof2i.demo.cms.va.gov/va-pittsburgh-health-care/vamc-banner-alert/2021-01-19/website-coming-soon-not-the-official-erie
Then visit the corresponding VAMC and note that the full width info banner shows on ALL pages, not just the system page. E.g.
https://web-ldij0hdlillzgrlzsgjk8keqbcknof2i.demo.cms.va.gov/erie-health-care/health-services/
https://web-ldij0hdlillzgrlzsgjk8keqbcknof2i.demo.cms.va.gov/erie-health-care/locations/
https://web-ldij0hdlillzgrlzsgjk8keqbcknof2i.demo.cms.va.gov/erie-health-care/events/
... …

Fix VAMC info alert inheritcance logic.

---

src/site/paragraphs/button.drupal.liquid

https://github.com/department-of-veterans-affairs/va.gov-team/issues/29238
For a11y purposes links should not be styled as buttons
local
Before:
After:

Remove button styling from link

---

src/platform/testing/e2e/cypress/support/commands/axeCheck.js

This PR modifies Cypress accessibility reporting so that the target element is shown when an accessibility violation is detected:

Improve Cypress accessibility reporting

---

src/platform/testing/e2e/cypress/support/commands/axeCheck.js

This PR modifies the Cypress aXe check so that the HTML element that causes an aXe failure is shown in the Cypress output:

Show HTML element in Cypress aXe failures

---

src/site/layouts/va_form.drupal.liquid
src/site/paragraphs/linkTeaser.drupal.liquid

https://github.com/department-of-veterans-affairs/va.gov-team/issues/26905
Adding underline to solve the issue with the usages of color as the only method to provide information.
Built and spun up local env.

DT-26905 Added underline for links per a11y request

---

.github/workflows/content-release.yml
.github/workflows/continuous-integration.yml
.github/workflows/daily-deploy-production.yml

This PR addresses issue noticed on following [thread](https://dsva.slack.com/archives/C01CHAY3ULR/p1631022208089300)
Caching is working as intended, but only on `master` branch. This is because the hash output differs from branch. This PR says if no cache is found on branch, restore cache from master.
Note: Cache will only be "detected" on branch based if you re-run a job. Otherwise, per commit, it will differ
[Branch with no cache](https://github.com/department-of-veterans-affairs/vets-website/pull/18516/checks?check_run_id=3535866308)
[Branch with cache](https://github.com/department-of-veterans-affairs/content-build/runs/3536663738?check_suite_focus=true)

Github Actions (CI, daily-deploy, & content-release) -- Fix cache issue on branch

---

src/platform/static-data/footer-links.json

**Issue:** https://github.com/department-of-veterans-affairs/va.gov-team/issues/29528
This PR updates the footer links in the following ways:
1. Move the "VA performance dashboard" link out of the sub-footer (2 rows at very bottom) up to the main footer under the "Get VA updates" column. Place this option as the last option in the column.
2. Add a "Civil Rights" link (destination https://www.va.gov/resources/your-civil-rights-and-how-to-file-a-discrimination-complaint/) to the sub-footer. Place it after the "Accessibility" option.
3. Move the "Freedom of Information Act (FOIA)" to be after the new "Civil Rights" link so it is in proper alpha order with the other links in those 2 lines.
1. Move the "VA performance dashboard" link out of the sub-footer (2 rows at very bottom) up to the main …

Update footer links (1-3)

---

src/site/stages/build/drupal/graphql/navigation-fragments/facilitySidebar.nav.graphql.js

The name specified here was too long -- Drupal machine names have a length limit to avoid transgressing DB length limits, etc.

Corrects Central Western Massachusetts facility sidebar name.

---

.github/workflows/a11y.yml

This PR modifies the workflow for the daily Cypress accessibility scan so that a failure notification is sent if the `build` job fails.

Fix Slack notifications for Cypress accessibility tests when build job fails

---

.github/workflows/a11y.yml

The Mochawesome report file generated in the parallel steps of the Cypress accessibility workflow was not being renamed when an accessibility failure was detected, causing reports to be overwritten. This PR fixes this issue.

Fix Mochawesome report generation in Cypress accessibility tests

---

.github/workflows/content-release.yml
.github/workflows/continuous-integration.yml
.github/workflows/daily-deploy-production.yml

This PR addresses the [following](https://github.com/department-of-veterans-affairs/va.gov-team/issues/28585#issuecomment-907288548)
Since we have changed to the on-demand runners, caching was not working as intended as the pathing has changed. This PR fixes by adding news keys specific to on-demand runners
[Yesterdays Run](https://github.com/department-of-veterans-affairs/content-build/actions/runs/1219436708)
Current run

Github Actions (CI, content-release & daily-deploy) -- Fix caching

---

.github/workflows/a11y.yml

The `slack` job was missing the `build` job in the `needs` configuration, which meant that `needs.build.result` was undefined. Due to this issue the Slack failure notification would not be triggered when the `build` job failed.

Fix Cypress accessibility Slack notifications

---

src/site/components/up_to_top_button.html

https://github.com/department-of-veterans-affairs/va.gov-team/issues/29126
For the back to top button the `position: relative` element is in the correct place for some pages but not for others. This adds `position: relative` to an outer container that works for all pages. A companion PR will be needed to remove the styling in `veteran-facing-services-tools`: https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/670
local
`/decision-reviews/supplemental-claim/` Before:
`/decision-reviews/supplemental-claim/` After: 
`/resources/how-to-get-free-language-assistance-from-va/` Before:
`/resources/how-to-get-free-language-assistance-from-va/` After:
**Both had `position: relative` disabled manually for the `.usa-content` div, the code for which lives in …

Add position relative class to back-to-top-container first child

---

src/site/paragraphs/list_of_link_teasers.drupal.liquid
src/site/stages/build/plugins/modify-dom/add-id-to-subheadings.js
src/site/stages/build/plugins/modify-dom/tests/add-id-to-subheadings.spec.js
src/site/stages/build/plugins/modify-dom/tests/fixtures/testSubheadings.html

https://github.com/department-of-veterans-affairs/va.gov-team/issues/15244
In IE11 when using the in page links via keyboard navigation focus does not move with the page position. This adds empty links that do not display focus to the anchors for those inpage links. This keeps display unchanged while telling IE11 (and the browsers that already understood what to do) where to send focus.
local, unit
https://user-images.githubusercontent.com/3144003/132901108-f318d591-ce19-4397-8f5d-46624631f056.mov

Add empty links to header link teasers

---

src/site/paragraphs/list_of_link_teasers.drupal.liquid
src/site/stages/build/plugins/modify-dom/add-id-to-subheadings.js
src/site/stages/build/plugins/modify-dom/tests/add-id-to-subheadings.spec.js
src/site/stages/build/plugins/modify-dom/tests/fixtures/testSubheadings.html

This reverts commit 22d5717b4912cb47516412a7168f56929e8c8320.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/15244#issuecomment-918570078
local

Revert "Add empty links to header link teasers (#532)"

---

src/site/layouts/basic_landing_page.drupal.liquid
src/site/layouts/checklist.drupal.liquid
src/site/layouts/faq_multiple_q_a.drupal.liquid
src/site/layouts/media_list_images.drupal.liquid
src/site/layouts/media_list_videos.drupal.liquid
src/site/layouts/q_a.drupal.liquid
src/site/layouts/step_by_step.drupal.liquid
src/site/layouts/support_resources_detail_page.drupal.liquid

This PR changes the list of buttons from a wrapping div to `ul` + `li` tags.
Incoming...

Update list of buttons to ul + li tags

---

.github/workflows/content-release.yml
.github/workflows/continuous-integration.yml
.github/workflows/daily-deploy-production.yml

This PR uses a different NEXUS registry that does not have a cache timer.
Since we are caching our `node_modules` in GHA there is no point in failing a workflow (if new package detected), wait 5 minutes, retry to add package to NEXUS
With this registry if it is not detected immediately, it will proxy to public NPM and download
[Run](https://github.com/department-of-veterans-affairs/content-build/actions/runs/1243315239)

Github Actions (CI, DD & CR) -- NEXUS w/ no-cache

---

.github/workflows/daily-deploy-production.yml

It was overlook in `daily-deploy` workflow to have on/off schedule. It is in `content-release` as well in `daily-deploy` for `vets-website`.
This PR adding that minor detail
N/A -- already implemented and in-effect

Github Actions (daily-deploy) -- Add schedule on/off for daily deploy

---

.github/workflows/content-release.yml
.github/workflows/continuous-integration.yml
.github/workflows/daily-deploy-production.yml

This PR mirrors similarly how it is in Jenkins. Jenkins uses a `try/catch` to handle notification error, but GHA uses `continue-on-error`. Added where applicable
department-of-veterans-affairs/va.gov-team#30099
Latest

Github Actions (CI, DD & content-release) -- Slack notification continue-on-error

---

package.json
yarn.lock

Local testing, including the `validate-build-status.js` script

Upgrade @octokit/rest to 18.10.0

---

package.json
yarn.lock

- Local testing
- Compared existing build with upgraded build -- no differences

Upgrade metalsmith-markdownit to 0.5.0

---

package.json
src/site/components/fullwidth_banner_alerts.drupal.liquid
src/site/layouts/page-react.html
src/site/stages/build/add-debug-info.js
src/site/stages/build/drupal/metalsmith-drupal.js
src/site/stages/build/index.js
src/site/stages/build/plugins/create-react-pages.js
src/site/stages/build/plugins/tests/create-react-pages.spec.js
src/site/stages/build/plugins/tests/fixtures/createReactPages.fixture.js
yarn.lock

https://github.com/department-of-veterans-affairs/va.gov-team/issues/29943
React pages are created independently of fetching drupal content which means they do not get any debug data nor access to globals like `banners` and `alerts` as they should.
local,unit

Pipe drupal data into react pages

---

.github/workflows/continuous-integration.yml

The url is coming as `s3://vetsgov-website-builds-s3-upload/content-build/$GITHUB_SHA/vagovdev.tar.bz2` where $GITHUB_SHA is not being coverted to commit_ref. This PR fixes syntax

Github Actions (CI) -- Fix SHA in archive

---

package.json
yarn.lock

Cheerio pushes too many breaking changes, so we're locking the version.

Locked cheerio version

---

README.md

Update README to fix  "Getting Started" link. Also add a mention of the `--use-cached-assets` flag. See [slack discussion](https://dsva.slack.com/archives/C01512KN35G/p1632240331078300) for more info.

Fix "Getting Started" link + add --use-cached-assets

---

.github/workflows/continuous-integration.yml

Related [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/28585#issuecomment-902232486)
With the current compression the time takes roughly `15 mins`. This new method should drastically shave time and also affect the `deploy` step as well.

Github Actions (CI) -- Optimize archive compression

---

.github/workflows/continuous-integration.yml

It was noticed that `continue-on-error` flag was missed. This PR addresses in the event it fails.

Github Actions (CI) -- add continue-on-error

---

src/site/includes/header.html

Resolves department-of-veterans-affairs/va.gov-team#27445
See also: https://github.com/department-of-veterans-affairs/vets-website/pull/18823
TL:DR - the Skip to Content link currently skips to the breadcrumbs, which is confusing for non-sighted users.
This change makes it skip to the first H1 on the page, if one exists. If not, the current behavior is preserved.
To access the Skip to Content link you must use a screen reader navigator or hit shift-TAB several times.

Fix Skip to Content link

---

src/site/facilities/health_care_region_detail_content.drupal.liquid
src/site/layouts/event.drupal.liquid
src/site/layouts/event_listing.drupal.liquid
src/site/layouts/news_stories_page.drupal.liquid
src/site/layouts/office.drupal.liquid
src/site/layouts/press_releases_listing.drupal.liquid
src/site/layouts/publication_listing.drupal.liquid
src/site/layouts/story_listing.drupal.liquid
src/site/layouts/vamc_system_policies_page.drupal.liquid
src/site/stages/build/drupal/health-care-region.js

**Issue:** https://github.com/department-of-veterans-affairs/va.gov-team/issues/30238
This PR makes it so the left nav doesn't disappear on the Past Events page.
**Unresolved issues:**
https://github.com/department-of-veterans-affairs/va.gov-team/issues/30240
https://github.com/department-of-veterans-affairs/va.gov-team/issues/30239
The above issues aren't clear in what needs to be done to resolve them, but this PR could hypothetically include changes that resolve them if desired ^
Locally

Add sidebar to past events page

---

src/site/stages/build/drupal/graphql/navigation-fragments/facilitySidebar.nav.graphql.js

Lovell FHCC has standardized around "VA Lovell Federal health care"
It is not yet in dual state, so changing this will not affect va.gov. 
Menu in CMS is being updated in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/6512
None.

Updating Lovell FHCC to match standardized plain language system name.

---

src/site/blocks/alert.drupal.liquid

**Slack:** https://dsva.slack.com/archives/CBU0KDSB1/p1632491843104300
This PR removes a 1 line `if` statement where we check for alerts to be `in_page_alert`, which isn't necessary. This if statement was causing in-page alerts not to appear on benefit hubs.
Locally

Remove if check for in_page_alert

---

src/site/assets/js/skip-link-focus.js
src/site/includes/header.html
src/site/paragraphs/list_of_link_teasers.drupal.liquid

https://github.com/department-of-veterans-affairs/va.gov-team/issues/15244
This makes it so in IE11 when using an in-page link, focus moves to the anchor.
Based on suggestions in the issue ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/15244#issuecomment-919094499 and the solution wordpress used to use: https://github.com/Automattic/_s/pull/1424/files#diff-d2325198d8f488786a89d08ce9ba0863a8b6afdf22a9498615dd42e9e96024d4
local
https://user-images.githubusercontent.com/3144003/134527447-96131393-95fc-4c8c-acd2-4615383bfc73.mov

Add skipLinkFocus function for in-page links

---

src/site/layouts/tests/vamc/e2e/location_detail.cypress.spec.js
src/site/layouts/tests/vamc/e2e/location_home.cypress.spec.js
src/site/layouts/tests/vamc/e2e/system_home.cypress.spec.js

This PR removes Cypress interactions with a modal that no longer appears on the pages being tested, which is causing failures on CI.

Fix Cypress modal failures

---

.github/workflows/a11y.yml

This PR updates the path to archive Cypress a11y test results on GitHub Actions. This change is needed due to a change in the working directory from a recent PR.

Fix Cypress accessibility reporting on GitHub Actions

---

.github/workflows/continuous-integration.yml

This PR modifies the CI workflow on GitHub Actions so that a Slack notification is sent to `#gha-test-status` when Cypress tests fail on `master`.

Add Slack notifications to Cypress tests on GitHub Actions

---

src/applications/registry.json

- We've received approval for My Education Benefits app's root url. This change makes it /education/apply-for-benefits-form-22-1990
When this change makes it in, we'll make the corresponding manifest.json change in vets-website on PR https://github.com/department-of-veterans-affairs/vets-website/pull/18889

My Education Benefits: Change root Url to approved path

---

src/site/blocks/alert.drupal.liquid
src/site/blocks/tests/alert/alert.unit.spec.js
src/site/blocks/tests/alert/fixtures/alert-data.json

This PR adds fixture tests for the block alert liquid template.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/30547

Add fixture tests for block alert template

---

.github/workflows/continuous-integration.yml

Broken link information was being sent to #devops-deploy, which is fine, but Jenkins sends them to #vfs-platform-build
This PR addresses that

Github Actions (CI) -- Channel Notification

---

.github/workflows/continuous-integration.yml

This PR modifies the Cypress workflow in GitHub Actions CI so that the Cypress test report job runs only if the Cypress test suite has completed.

Run Cypress test report job on GitHub Actions only after tests run

---

src/applications/registry.json
src/site/includes/breadcrumbs.html

**Issue:** https://github.com/department-of-veterans-affairs/va.gov-team/issues/6582
This PR fixes the following breadcrumbs for react apps:
1. https://staging.va.gov/education/apply-for-education-benefits/application/5495 <br> **This one should be changed to** [Home](https://www.va.gov) > [Education and training](https://www.va.gov/education/) > [Change your GI Bill school or program](https://www.va.gov/education/change-gi-bill-benefits/) > Change your dependent benefits VA Form 22-5495
1. https://staging.va.gov/health-care/apply/application <br>**This one should be changed** remove "How to apply" from path
1. https://staging.va.gov/pension/application/527EZ <br>**This one should be changed** remove "How to apply" from path
1. https://staging.va.gov/records/get-veteran-id-cards/apply …

Fix react breadcrumbs

---

src/site/filters/liquid.js
src/site/filters/liquid.unit.spec.js

**Issue:** https://github.com/department-of-veterans-affairs/va.gov-team/issues/31105
This PR adds a LOT more tests and standardizes the formatting of the `entityUrl.path` and the banners' `fieldTargetPaths` (both exceptions and inclusions).
Lots of new tests.

Fix leading + trailing slash issue for banner target paths

---

script/utils.js

In its current implementation, `runCommand()` always causes the parent process to exit when the child process completes, regardless of exit code. This led to [an issue](https://dsva.slack.com/archives/CBU0KDSB1/p1633549113067800) where the parent process was forced to exit even though its own async task was still running.
This PR modifies `runCommand()` so it only causes the parent process to exit if the child process exits with an abnormal (non-zero) return code.
- Local testing of build and unit tests (successful and failing)
- Successful CI run

In runCommand(), only exit when child exits abnormally

---

.github/workflows/daily-deploy-production.yml

It looks like we missed the `commit_sha` being passed. It is being called, but no reference being made. This PR adds the reference globally to access it
N/A. Will be observed via Slack channel

Github Actions (DD) -- Fix daily deploy missing commit_sha

---

.github/workflows/content-release.yml
.github/workflows/continuous-integration.yml
.github/workflows/daily-deploy-production.yml

This PR refers to this [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/31189)
It was noticed that CI workflow was failing due to disk space running out. Despite the disk space size increased, we want to reduce space used as we will add `vagovstaging` and `vagovprod`
Code cleanup up bit in `content-release` and `daily-deploy` as well
Latest Run

Github Actions (CI) -- Persist only tar rather than builds for archive step

---

src/site/paragraphs/staff_profile.drupal.liquid

local unit tests passed
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/6724

VAVFS-6724: [Fixed] staff title missing

---

src/platform/testing/e2e/cypress/support/commands/axeCheck.js

This PR adds more detail to the table printed out when an aXe failure is detected so that it is easier to determine what the exact issue is.
New failure message:
This PR adds more detail to the table printed out when an aXe failure is detected so that it is easier to determine what the exact issue is.
New failure message:

Add more details to aXe failure messages

---

.github/workflows/content-release.yml

As discussed in [slack](https://dsva.slack.com/archives/C01512KN35G/p1635533884032500?thread_ts=1635529221.019000&cid=C01512KN35G) thread, CR workflow now queued based off of their environment
N/A, will need to merge first and test dispatch. Important thing to notice is

Github Actions (CI) -- Add concurrency to content-release based off environment

---

.github/workflows/continuous-integration.yml

This PR upgrades the `mikepenz/action-junit-report` action used in Cypress tests on GitHub Actions to the latest version.

Upgrade Cypress GitHub Actions report generator to latest version

---

.github/workflows/daily-deploy-production.yml

See [slack](https://dsva.slack.com/archives/CU1E4CX9U/p1635785187070000?thread_ts=1635542163.067700&cid=CU1E4CX9U) for more details
With a `concurrency` set in place for [content-release](https://github.com/department-of-veterans-affairs/content-build/blob/master/.github/workflows/content-release.yml#L19), we want to ensure that `prod` gets queued accordingly how it is in Jenkins.
This PR adds the following:
Adds daily deploy to `prod` concurrency group to ensure no overlap to content-release `prod` group
Does not conflict with `dev` and `staging`

Github Actions (DD) -- concurrency prod group

---

src/site/filters/liquid.js
src/site/filters/liquid.unit.spec.js

Fixes issues with apostrophe's rendering as `&quot` in accordion headers.
See [Slack thread](https://dsva.slack.com/archives/CDHBKAL9W/p1635796452030800)

Remove special case for apostrophe in encode filter

---

.github/workflows/continuous-integration.yml

This PR will redirect the artifact downloads to the new directories that we created when we restructured the dashboard data repo.
Associated restructure: https://github.com/department-of-veterans-affairs/testing-tools-team-dashboard-data/pull/86
Workflow passed when targeting feature branch.

Update testing reports workflow to new data repo structure

---

.github/workflows/continuous-integration.yml

On GitHub Actions, the `test-results/unit-tests.xml` file for unit tests is not generated sometimes when there's a unit test failure. Currently the step to upload the report only shows a warning when this file does not exist. This PR modifies this step so that there's an error when the file does not exist.

Fail unit test report generation step on GitHub Actions when results file does not exist

---

src/site/filters/liquid.js
src/site/layouts/health_care_region_page.drupal.liquid

Resolves - https://github.com/department-of-veterans-affairs/va.gov-team/issues/31487
Per Michelle, the redirect should happen with Central Ohio health system NOT Columbus facility. You can find more info on this in the comments of the original issue.
If the health system = Central Ohio and the top task link = schedule and manage health appointments
then we redirect to cerner (patientportal.myhealth.va.gov)

Added cerner redirect for Central Ohio health system scheduling link

---

.github/workflows/a11y.yml

Chrome comes pre-installed in the Docker container used to run accessibility tests on GitHub Actions, so this step to re-install Chrome can be removed.

Remove Chrome installation step from GitHub Actions accessibility workflow

---

src/site/components/browse-by-audience.drupal.liquid
src/site/filters/liquid.js
src/site/filters/liquid.unit.spec.js
src/site/layouts/media_list_images.drupal.liquid
src/site/layouts/tests/vamc/fixtures/health_care_region_page.json
src/site/layouts/tests/vamc/template/health_care_region_page.unit.spec.js
src/site/paragraphs/facilities/list_of_link_teasers_facility.drupal.liquid

Resolves - https://github.com/department-of-veterans-affairs/va.gov-team/issues/32451
Per Dave, there should be only 2 columns with 8 links max.
See slack thread: https://dsva.slack.com/archives/C0FQSS30V/p1636040104227200
Limiting number of link to show the first 8. 
To test use this tugboat instance (it has a total of 9 links but only displays the first 8) - https://web-xzcrb121xmxquzas9jcd9p86dgwpkuam.demo.cms.va.gov/detroit-health-care/

Limit number of link teasers

---

.github/workflows/a11y.yml

This PR adjusts the start time of the daily accessibility scan so that it starts at 9 AM ET.

Adjust daily accessibility scan schedule for daylight saving time

---

.github/workflows/content-release.yml

There was a syntax error and Github Actions did not detect it. This PR fixes that syntax error

Github Actions (CR) -- Fix syntax error

---

src/applications/registry.json

MHV Account validation app is being removed from `vets-website`
Removing from the application registry here as well

31523: Remove MHV Account Validation in Registry

---

.github/workflows/content-release.yml
script/github-actions/check-broken-links.js

It was noticed that when broken links are detected, they are not notifying cms-helpdesk properly. This PR addresses that issue.
[Via stackoverflow forum](https://stackoverflow.com/a/69709495)

Github Actions (CR) -- fix slack notifications

---

src/site/includes/top-nav.html

**Ticket:** https://github.com/department-of-veterans-affairs/va.gov-team/issues/32672
This PR updates the VCL red background color to match header v2's VCL background color.
Locally

Add stdized red color to VCL

---

.github/workflows/content-release.yml

I suspect the semantic of the flow being triggered by `va-cms-bot` might somehow be translated to a string. Removing extra layer of complexity and letting the output be determined by GHA, similar to how it is in our CI

Github Actions (CR) -- Change cancel-in-progress semantic

---

.github/workflows/content-release.yml

Suspect create-release portion for content-release is failing due to ref. It is unable to push a commit it is not on. This PR checks out that ref to attempt to push correct tag associated with it

Github Actions (CR) -- Adding ref to checkout for create-release

---

.github/workflows/content-release.yml

11/11 is a holiday. Removing cron

Github Action (CR) -- disable cron for content-release

---

src/site/paragraphs/collapsible_panel.drupal.liquid

Include entity ID on `va-accordion-item`, which will be used to target and expand the accordion when the url hash matches the ID. See https://github.com/department-of-veterans-affairs/va.gov-team/issues/28658
Specifically, we need to be able to target & expand the accordion on this page - https://staging.va.gov/decision-reviews/higher-level-review/
N/A
N/A

Add ID to common va-accordion-item

---

.github/workflows/content-release.yml

Re-enabling content-release schedule post 11/11 holiday

Github Actions (CR) -- Enabling content release schedule

---

.github/workflows/content-release.yml

It was observed that content-release despite tagging the correct commit, the actual release commit associated was latest of master. This PR ensures we are passing the commit associated to the run, in this case being the last successful commit from daily deploy, into the release

Github Actions (CR) -- Fix release commit

---

.github/workflows/test.yml

Copied demo from [github](https://github.blog/changelog/2021-11-10-github-actions-input-types-for-manual-workflows/) to see outputs. Most seem straight forward, but I am curious on what `environment` looks like 👀

Github Actions -- POC input options

---

src/site/layouts/event_listing.drupal.liquid

**Issue:** https://github.com/department-of-veterans-affairs/va.gov-team/issues/32598
This PR adds the `events` react widget (doesn't currently exist) to the `event_listing` pages.

Add events widget to event_listing

---

config/cypress.json

`nodeVersion` is set to `system` by default in Cypress 9.0.0, so this configuration setting can be removed. This line is generating deprecation warnings on CI.

Update Cypress configuration for v9.0.0

---

src/site/filters/liquid.js
src/site/filters/liquid.unit.spec.js
src/site/includes/facilityListing.drupal.liquid
src/site/layouts/health_care_local_facility.drupal.liquid

Resolves - https://github.com/department-of-veterans-affairs/va.gov-team/issues/32561
Per Michelle, the phone number is: **877-741-3400**
VA health connect phone number should only be displayed if cms feature toggle is on and if VISN 8 system
VA health connect phone number is displayed in the following places (using North Florida health care (visn 8) as an example): 
<details>
<summary>north-florida-health-care/</summary>
</details>
<details>
<summary>north-florida-health-care/locations</summary>
</details>
And all the facility pages attached to that visn
For example:
<details>
<summary>north-florida-health-care/locations/gainesville-ninety-eighth-street-va-clinic/</summary>
</details>
Tugboat instance (phone # displays here)- https://web-khwba2p3ozkcd3sjcsfi9wyyxbltjjze.demo.cms.va.gov/mi …

Added VA health connect phone number

---

.github/workflows/content-release.yml

Given our current queue system, despite if successful, flow will be marked as `cancelled` and notify user as failure. This PR is tightening the conditional statement.
If a deploy is successful despite it being cancelled (while we investigate queueing in more depth), do not notify via slack as failure

Github Actions (CR) -- Notify failure only on non-successful prod deploys

---

src/site/layouts/event_listing.drupal.liquid

**Issue:** https://github.com/department-of-veterans-affairs/vets-website/pull/19389
This PR adds the events data to window to be used by the events v2 react app.

Add pastEvents and allEventTeasers to window

---

src/site/filters/liquid.js
src/site/filters/liquid.unit.spec.js
src/site/paragraphs/collapsible_panel.drupal.liquid

We need a truncated unique ID applied to accordions so that we can expand them if they have a matching hash.
This PR updates the `hashReference` liquid filter:
- Normalizes diacritics, so we can support multiple languages
- Removes non-alphanumeric characters
- Truncates the string to a specified length, 30 characters for the accordion, 100 (arbitrary value for all IDs using this filter)
Lastly, the accordion item ID now mimics the ID added to the previous component that used a partial header text + ID as a suffix.
Related:
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/28658
- https://github.com/department-of-veterans-affairs/content-build/pull/743 (reverted because IDs were not unique)
Updated `hashReference` unit tests
N/A

Update hashReference filter

---

.github/workflows/content-release.yml
.github/workflows/daily-deploy-production.yml
Jenkinsfile
jenkins/common.groovy

Slack notification for broken link are missing in content-release and daily deploy flow. Added them to contact CMS helpdesk.
Removing noise from Jenkins of CI failure that goes in devops_channel

Github Action -- Slack notification for broken link for content-release and daily deploy

---

.github/workflows/content-release.yml

As build is the longest job in the workflow, we want to ensure that if it is being checked against, to finish the workflow

Github Action - Build always executes

---

script/github-actions/validate-content-release-status.js

[Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/32936) related
Due to daily deploy and content-release being in the same concurrency group, there have been a few instances where one can cancel the flow of the other (primarily, content-release cancelling daily-deploy mid run).
In an effort to reduce the cancellation of these flows, we will be separating them into their own groups. We still need to ensure no race-condition occur, that this PR addresses that.
This is part 1 of 2. Part 2 requires this PR to be merged, wait until this script is included in release (the following day when merged), the we can create a PR to modify flow of content-release and daily-deploy to use this script.
Local. See screenshot below
Local testing done while [daily …

Github Action -- production queue script

---

.github/workflows/continuous-integration.yml

The `Get code coverage` step in the unit test job does not run when unit test fail, causing an undefined environment variable to be passed into the step that follows this.

Fix unit test reporting on GitHub Actions

---

.github/workflows/content-release.yml
.github/workflows/daily-deploy-production.yml

[Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/32936) related
Part 2 of [PR](#770) and [PR](#768)
The flows are in their own concurrency group and decoupled. The following flow is modified:
Prior to starting the `build` step, it will run `wait-for-current-workflow`. This will allow `content-release` and `daily-deploy` to not be in a race-condition
Local testing. See #768 for more details

Github Actions -- Decouple concurrency group for content-release and daily-deploy

---

.github/workflows/content-release.yml
.github/workflows/daily-deploy-production.yml

With the latest wait-workflow, since we get the latest tag at the beginning, if a workflow is waiting, it has an outdated tag. This PR changes workflow to get latest workflow prior to uploading new tag from workflow

Github Actions -- Fix upload same tag/release while waiting

---

script/github-actions/wait-for-current-workflow-to-complete.js

There have been a couple of instances where Github Actions workflow gets "stopped" in order to prepare for next step. Because of it, API sometimes treats as no workflow running, and therefore can signal counterpart to continue with their process.
Increasing the timer to prevent this edge case

Github Actions -- Increase wait timer between daily deploy and content-build

---

.github/workflows/content-release.yml

This PR addresses adds additonal layer to prevent race condition seen today (11/23):
- If content-release is waiting, wait until daily deploy finishes before grabbing latest release
- Daily deploy bases it off latest commit rather than release, so no modification needed for that workflow

Github Actions -- change flow to prevent race condition during daily deploy for content-release

---

.github/workflows/content-release.yml
.github/workflows/daily-deploy-production.yml

Given what occurred today, adding a timeout to build in the event it gets stuck

Github Actions -- Add timeout to prevent content-release or daily deploy getting stuck

---

.github/workflows/content-release.yml
.github/workflows/continuous-integration.yml
.github/workflows/daily-deploy-production.yml

See [Slack](https://dsva.slack.com/archives/C01512KN35G/p1637785399079500) for more details
It was pointed out that the govcallback should be added to daily deploy and content release as it is an integral part. This PR does the following:
- Grab the buildtime and store accordingly
- Grab token from SSM
- Make call to callback using token

Github Actions -- Add callback to daily deploy and content-release

---

package.json
yarn.lock

PR to upgrade Cypress to its latest version (`9.1.0`).

Upgrade Cypress to `9.1.0`

---

.github/workflows/content-release.yml

See [slack](https://dsva.slack.com/archives/C0MQ281DJ/p1638206769368300?thread_ts=1638194569.356200&cid=C0MQ281DJ) for more details
No error or access denied displayed, but callback not working as intended. Updating URL

Github Actions -- Update callback URL

---

.github/workflows/daily-deploy-production.yml

See [slack](https://dsva.slack.com/archives/C0MQ281DJ/p1638212042373400?thread_ts=1638194569.356200&cid=C0MQ281DJ) for more detail
With the recent confirmation of callbcak working for content-release, updating URL for daily deploy

Github Actions -- Update callback URL for daily deploy

---

.github/workflows/a11y.yml

This PR adds a two hour timeout to the Cypress job in the daily accessibility scan in order to handle situations when one or more of the parallel steps hang.

Add timeout to the Cypress steps in the daily accessibility scan

---

.github/workflows/daily-deploy-production.yml

It was observed that the URL daily deploy is generating does not give accurate comparison of files being merged to prod
This PR fixes the string so that it can show what files are committed
Browser:
Actual: https://github.com/department-of-veterans-affairs/content-build/compare/content-build/v0.0.1865...71eb5012d466921d973de9588888e264d605e7a7
Expected: https://github.com/department-of-veterans-affairs/content-build/compare/v0.0.1865...71eb5012d466921d973de9588888e264d605e7a7

Github Actions (DD) -- Fix start-notify Url

---

.github/workflows/content-release.yml
.github/workflows/continuous-integration.yml
.github/workflows/daily-deploy-production.yml

After investigating why callback where not occurring, the following has been discovered:
1. Needs to be behind the TIC
2. Does not do a `POST`, but rather `GET` command
This PR addresses the following. Given that its a GET and not post, removing `continue-on-error` flag
Separate workflow (all logs have been deleted)

Github Action -- Fix GovDelivery callback

---

src/site/layouts/event.drupal.liquid
src/site/layouts/event_listing.drupal.liquid
src/site/layouts/publication_listing.drupal.liquid

**Issue:** https://github.com/department-of-veterans-affairs/va.gov-team/issues/33451
This PR removes unnecessary side navs from events templates.
Remove side nav from Events Materials sub page.
Remove the side nav from the Events sub page. 
Remove side nave from Events Details Page.

Remove unnecessary side navs

---

.github/workflows/content-release.yml

Add the GHA metrics back and modify the working directory to run in an existing directory

Re-add GHA Metrics and Run Command In the Context of an Existing Directory

---

.github/workflows/content-release.yml

Fixes https://github.com/department-of-veterans-affairs/content-build/runs/4401966715?check_suite_focus=true
Gotta auth to aws before we can get ssm secrets.

Fix errors in recent build

---

src/site/paragraphs/q_a.drupal.liquid

**Issue:** https://github.com/department-of-veterans-affairs/va.gov-team/issues/32673
This PR switches h3s to h2s for the q_a template.
N/A
N/A

Kelsonic 32673 switch h3 to h2 qa

---

src/site/paragraphs/downloadable_file.drupal.liquid

- Updated video link text in FE paragraph twig template.
- Adjusted video link text variable to "`{{entity.fieldTitle}}`".
Relates to https://github.com/department-of-veterans-affairs/va.gov-cms/issues/7009
and unites https://github.com/department-of-veterans-affairs/va.gov-cms/pull/7125
As user editor

VACMS-7009: Video link text label is not making it to the FE

---

jenkins/common.groovy

Build channel still getting Jenkins notification when it should not. This PR removes slack notification being sent from Jenkins

Remove Jenkins broken link notification

---

src/site/stages/build/drupal/graphql/landingPage.graphql.js
src/site/stages/build/drupal/graphql/page.graphql.js

- Updated "LandingPage" and "page" GraphQL files and removed references to "fieldPageLastBuilt" field.
closes #[6950](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/6950)
Successful build

VACMS-6950: Remove "Page last built" field from 3 content types

---

.github/workflows/a11y.yml

Quick PR to remove caching of the Cypress binary from two jobs in the daily accessibility scan that do not use the binary.

Remove Cypress caching from GitHub Actions jobs

---

src/site/layouts/tests/vet_center/template/fixtures/vet_center_data.json
src/site/layouts/tests/vet_center/template/vet_center.drupal.unit.spec.js
src/site/layouts/vet_center.drupal.liquid
src/site/stages/build/drupal/graphql/vetCenter.graphql.js

Resolves - https://github.com/department-of-veterans-affairs/va.gov-team/issues/33053
If a vet center has an official name that is different from its title, we display that official name right below the vet center title
To test use this tugboat instance - https://web-khwba2p3ozkcd3sjcsfi9wyyxbltjjze.demo.cms.va.gov/prescott-vet-center/

Implement Official Name Display

---

.github/workflows/content-release.yml

This fixes https://github.com/department-of-veterans-affairs/content-build/runs/4449895352?check_suite_focus=true#step:14:10 and https://github.com/department-of-veterans-affairs/content-build/runs/4449895352?check_suite_focus=true#step:15:10

One more metrics fix

---

src/applications/registry.json

There are a couple of registries that have a trailing `/` at the end of rootUrl which is causing [lighthouse](https://github.com/department-of-veterans-affairs/vets-website/actions/runs/1558605567) to not upload correctly.
This PR removes the trailing `/` for those applicable

Fix trailing / in registries for lighthouse report

---

.github/workflows/content-release.yml
.github/workflows/continuous-integration.yml
.github/workflows/daily-deploy-production.yml
.github/workflows/wait-for-cms-ready/action.yml

In the past few days, there have been a number of content release failures related to trying to do stuff while the CMS is deploying.
Here are a couple of examples:
* https://github.com/department-of-veterans-affairs/content-build/actions/runs/1555528870
* https://github.com/department-of-veterans-affairs/content-build/actions/runs/1532069013
Instead of just sending the request, let's wait for the CMS to be ready and _then_ send the request. This needs some testing, which I will do in a separate PR so as not to pollute the Git history.

Wait for the CMS to be ready before triggering govdelivery

---

package.json
yarn.lock

`saucelabs` is not being used in this repo, so this dependency can be removed.

Remove `saucelabs` dependency

---

src/site/components/situation_updates.drupal.liquid
src/site/filters/liquid.js
src/site/filters/liquid.unit.spec.js
src/site/includes/date.drupal.liquid
src/site/includes/social-share.drupal.liquid
src/site/layouts/campaign_landing_page.drupal.liquid
src/site/stages/build/drupal/health-care-region.js

**Issue:** https://github.com/department-of-veterans-affairs/va.gov-team/issues/33951
This PR creates a liquid filter for deriving the most recent date for `fieldDatetimeRangeTimezone`s since that field is currently an object but will soon be only in an array format.
N/A

Kelsonic 33951 field datetime range timezone filter

---

package.json
yarn.lock

This is the last dependency that had to be upgraded as part of the upgrade to Cypress v9. Breaking changes have been fixed in the latest version.

Upgrade `@testing-library/cypress` to latest version

---

src/site/stages/build/drupal/graphql/navigation-fragments/facilitySidebar.nav.graphql.js

- Updated "facilitySidebar.nav.graphql.js", added the new "lovell-federal-health-care" menu machine name to the VISN 12 section.
related to #7163
All test passes.

VACMS-7163: Add lovell-federal-health-care menu to VISN 12  facilitySidebar

---

.github/workflows/content-release.yml

[Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/34274) associated
This PR addresses the following:
There seems to be a race condition in which the tag does not bump correctly, therefore it fails right before the `deploy` step. This PR wraps the tag creation for race condition
[Workflow](https://github.com/department-of-veterans-affairs/content-build/runs/4562277403?check_suite_focus=true) tests against

Github Actions -- Fix create-release

---

src/site/stages/build/drupal/graphql/eventListingPage.graphql.js
src/site/stages/build/drupal/graphql/facilities-fragments/healthCareRegionEvents.node.graphql.js
src/site/stages/build/drupal/graphql/healthCareRegionPage.graphql.js

This PR increases the limit on event nodes from 500 to 5000. There are currently ~1900 in the CMS.
Locally

Update limit from 500 to 5000 for events

---

src/site/layouts/landing_page.drupal.liquid

**Issue:** https://github.com/department-of-veterans-affairs/va.gov-team/issues/34501
This PR fixes jump links on landing pages.
N/A

Fix hashReference func signature

---

src/applications/registry.json
src/site/includes/common-and-popular.html

https://github.com/department-of-veterans-affairs/va.gov-team/issues/33883
Visited http://localhost:3002/education/gi-bill-comparison-tool-sandbox/ and http://localhost:3002/education/gi-bill-comparison-tool/ and validated they worked.
Made sure http://localhost:3002/gi-bill-comparison-tool-sandbox/ and http://localhost:3002/education/gi-bill-comparison-tool/ do not work.

Updating GIBCT url to being with /education

---

src/applications/registry.json
src/site/includes/common-and-popular.html

Reverts department-of-veterans-affairs/content-build#862
This is causing content release failures currently.

Revert "Updating GIBCT url to being with /education"

---

src/applications/registry.json
src/site/includes/common-and-popular.html

https://github.com/department-of-veterans-affairs/va.gov-team/issues/33883
This retains current URL and adds new entry point for new URL of /education/....
On localhost, I visited both http://localhost:3002/education/gi-bill-comparison-tool and http://localhost:3002/gi-bill-comparison-tool and they both loaded the comparison tool.
http://localhost:3002/education/gi-bill-comparison-tool-sandbox/ also works.

Update GI Bill comparison tool URL

---

src/site/paragraphs/q_a.drupal.liquid

**Issue:** https://github.com/department-of-veterans-affairs/va.gov-team/issues/34362
This PR removes the class that styles h2 to h3 tags.

Remove class that changes h2 to h3 styling

---

src/site/stages/build/drupal/graphql/nodeEvent.graphql.js

This PR fixes a broken link issue with the previous GraphQL refactor for NodeEvents.

Fix fieldLink.url.path from previous refactor

---

src/site/stages/build/drupal/graphql/GetAllPages.graphql.js
src/site/stages/build/drupal/graphql/GetLatestPageById.graphql.js
src/site/stages/build/drupal/graphql/facilities-fragments/healthCareRegionEvents.node.graphql.js
src/site/stages/build/drupal/graphql/healthCareRegionPage.graphql.js
src/site/stages/build/drupal/graphql/nodeCampaignLandingPage.graphql.js
src/site/stages/build/drupal/graphql/nodeEvent.graphql.js
src/site/stages/build/drupal/graphql/nodeEventListing.graphql.js
src/site/stages/build/drupal/graphql/nodeOffice.graphql.js

I thought we could get away with not adding in breadcrumbs to NodeEvent graphql queries, but I was wrong 😭 
PR that removed breadcrumbs from NodeEvents originally: https://github.com/department-of-veterans-affairs/content-build/pull/864/files

Add back breadcrumbs to nodeEvent graphql

---

src/site/filters/liquid.js
src/site/filters/liquid.unit.spec.js

This PR standardizes the timestamp shown for events v2 across event listing pages + event detail pages.

Update startsAt + endsAt to use timezone

---

.github/workflows/content-release.yml

Related ticket: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/7363
Sending alerts when a build is cancelled creates a lot of noise. There's nothing that can/should be done about a cancelled build, so let's not send it.

Don't alert slack when the build is cancelled

---

.github/workflows/content-release.yml
.github/workflows/continuous-integration.yml
.github/workflows/daily-deploy-production.yml
.github/workflows/wait-for-cms-ready/action.yml

Follow-up to #832. There was a failure today resulting from the CMS being mid-deploy when the graphql queries were attempted. This PR should reduce the chances of that happening.
(There is still a potential failure mode where the CMS is ready before the graphql queries start, but the CMS goes down _during_ the graphql queries. There's not much that can be done about that at this point.)
Related ticket: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/7242

Wait for the CMS to be ready before running graphql queries

---

.github/workflows/content-release.yml
.github/workflows/continuous-integration.yml
.github/workflows/slack-notify/action.yml
script/github-actions/check-broken-links.js

Due to the issue recently arisen from slack notification, we want to move away to depend on downloading the certs required. This PR uses native slackapi action (currently used in daily-accessbiity)
Latest Run and [successful](https://github.com/department-of-veterans-affairs/content-build/runs/4741313901?check_suite_focus=true) notification

Use slackapi action

---

.github/dependabot.yml

PR to add daily Dependabot checks for actions used in GitHub Actions.

Add Dependabot config with GitHub Actions updates

---

.github/workflows/daily-deploy-production.yml

To not hault the daily deploy, removing `always`.
Was previously needed when `content-release` and `daily-deploy` were coupled
Added timeout for additional layer

remove always from wait-for-current-workflow in daily deploy

---

Dockerfile

Cert update to point to the newly created public cert repo. This change is expected to address the failing jenkins jobs:
http://jenkins.vfs.va.gov/job/builds/job/content-build-content-only-vagovprod and others
department-of-veterans-affairs/va.gov-team#34841
Tested locally with the docker build

raw cert change

---

src/site/stages/build/drupal/graphql/navigation-fragments/facilitySidebar.nav.graphql.js

- Removed "va-lovell-federal-health-care" menu from "facilitySidebar.nav.graphql.js" VISN 12 section.
closes #7163
All tests passes

VACMS-7163: Remove "va-lovell-federal-health-care" menu from "facilitySidebar.nav.graphql.js" VISN 12 section

---

src/site/facilities/health_service.drupal.liquid
src/site/filters/liquid.js

Hardcodes `h3` "Care we provide at `[VAMC System]`".

Hardens "Care we provide" header in VAMC template (#22115).

---

.github/workflows/content-release.yml

See https://github.com/department-of-veterans-affairs/va.gov-cms/issues/7723

VACMS-7723: shift scheduled content release times 6 minutes earlier.

---

src/applications/registry.json

See: https://github.com/department-of-veterans-affairs/vets-website/pull/20023
Together with the linked PR above, a new React app is added.  Most of the code for the new app will live in `vets-website`, but a new React app needs an entry in the `content-build` registry as well.  This PR captures that entry.
Note: this will not show in production, due to the `vagovprod` flag being set to false:
```
{
"appName": "All VA offices",
"entryName": "office-directory",
"rootUrl": "/office-directory",
"template": {
"vagovprod": false,
"layout": "page-react.html"
}
}

Creates new React app for Office Directory.

---

src/applications/registry.json

This PR just changes the order of the routing configs so the correct routing is used. 
will be tested in Staging, prod flag is still false

Covid Vaccine Trials - change order so v2 route is picked up first

---

.github/workflows/content-release.yml

See https://github.com/department-of-veterans-affairs/va.gov-cms/issues/7262
This transitions `notify-failure` from direct Slack notification to sending a Datadog event, which in turn triggers PagerDuty. 
It also shifts the target channel from #vfs-platform-builds to #cms-notifications for build start and broken link issues. The PagerDuty incidents will also transition to reporting into #cms-notifications.

VACMS-7262: replace slack failure notification with datadog event.

---

.github/workflows/content-release.yml

See https://github.com/department-of-veterans-affairs/va.gov-cms/issues/7213
Key has been created in Datadog and added to Parameter Store here `/dsva-vagov/content-build/GHA_CONTENT_BUILD_DATADOG_API_KEY` and this should "just work" once merged.

Use new Datadog API key name specifically for content-build (not CMS)

---

src/platform/site-wide/tests/accessible-modal.cypress.spec.js

Reverts part of department-of-veterans-affairs/content-build#943
This PR re-adds part of the crisis line Cypress test to test the crisis line link in the main content of the homepage.

Add crisis line test for crisis line link in main homepage content

---

.github/workflows/content-release.yml

Self-hosted runners require certs when doing yarn install. This PR adds certs where applicable.

Add missing certs to self-hosted runners

---

.github/workflows/content-release.yml

See [this thread](https://dsva.slack.com/archives/CBU0KDSB1/p1644539431676379).
Multiple invocations of `--filters` ~are logically OR'ed together~.  Only the last invocation of `--filters` is used.
This can lead to referring to an AMI that is not yet available.  Separated by spaces, they are logically AND'ed together, which is the original intent.
```
aws ec2 describe-images \
--owners 008577686731 \
--query 'sort_by(Images,&CreationDate)[-1].ImageId' \
--filters "Name=name,Values=packer-gha-runner-ubuntu2004*" \
--output text
```
```
ami-0a4813157fea1b279
```
The above is a valid GHA AMI.
```
aws ec2 describe-images \
--owners 008577686731 \
--query 'sort_by(Images,&CreationDate)[-1].ImageId' \
--filters "Name=name,Values=packer-gha-runner-ubuntu2004*" \
--filters …
```

Changes AMI query to use multiple filters.

---

.github/workflows/content-release.yml
.github/workflows/continuous-integration.yml
.github/workflows/daily-deploy-production.yml

PR to add a 30 minute timeout to dependency installation in GHA since this step can hang.

Add timeouts to dependency installation in GitHub Actions

---

src/applications/registry.json

sibling PR for backend https://github.com/department-of-veterans-affairs/vets-api/pull/9077
This updates the root url path Education Inbox app in the src/applications/registry.json
As well as the title property
[Original issue](https://github.com/department-of-veterans-affairs/vets-website/pull/20057)

Updating the Education Inbox rootURL

---

src/site/layouts/event_listing.drupal.liquid
src/site/layouts/news_stories_page.drupal.liquid
src/site/layouts/story_listing.drupal.liquid
src/site/layouts/vet_center.drupal.liquid
src/site/stages/build/drupal/graphql/facilities-fragments/healthCareRegionEvents.node.graphql.js
src/site/stages/build/drupal/graphql/facilities-fragments/healthCareRegionNewsStories.node.graphql.js
src/site/stages/build/drupal/graphql/healthCareRegionPage.graphql.js
src/site/stages/build/drupal/graphql/nodeEvent.graphql.js
src/site/stages/build/drupal/graphql/storyListingPage.graphql.js

See https://github.com/department-of-veterans-affairs/va.gov-cms/issues/1317
Featured boolean is being removed from cms content model, and fieldOrder (existing) is going to be used instead. Field order will place stories & events in featured position at top of listing page, sorted by weight. Multiple #1's and #2's may appear. These updates also account for system page story and events feature items.
After this work is deployed to prod, cms content model change to remove fieldFeatured will be completed.
Visual / build

VACMS-1317: Update logic to use order field instead of featured field.

---

src/applications/registry.json

This PR removes the entry for `Coronavirus Research - Volunteer - V2` and promotes `Coronavirus Research - Update` to prod.  V2 was used for testing in Staging and with that being successful the original URL and routing will point to the new VAFS app. 
devops PR: https://github.com/department-of-veterans-affairs/devops/pull/10756
vets-website PR: https://github.com/department-of-veterans-affairs/vets-website/pull/20245
Manual testing locally

Covid vax trials - remove V2 and promote update to prod

---

.github/workflows/continuous-integration.yml
.gitignore

Content-build js application no longer sets Drupal API connection information. It is now only supplied via CLI arguments or environment variables.  Update all workflows that `yarn build` commands to include drupal-user and drupal-password CLI arguments. Additionally, lookup parameter store for Production connection password.

Update All GHA Workflows that Use Yarn Build

---

src/applications/registry.json

A [PR earlier today](https://github.com/department-of-veterans-affairs/content-build/pull/974) included a broken link in the `breadcrumb_override`.  This PR fixes that.

Covid Vaccine Trials - fix breadcrumb broken link

---

.github/workflows/content-release.yml
.github/workflows/record-release-interval/action.yml

This is part one of several to start recording the amount of time between deployments in Datadog. In order for the time calculation to work, I need to have the events in Datadog first.
Expected followups:
* Before sending the event to Datadog, calculate the amount of time since the previous event recorded in Datadog
* Also record the events in the Daily Production Deploy workflow
Related to: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/7939

Send content release events to datadog

---

.github/workflows/record-release-interval/action.yml

Send API request to the correct datadog domain 🤦‍♂️

---

src/site/layouts/event_listing.drupal.liquid
src/site/layouts/news_stories_page.drupal.liquid
src/site/layouts/story_listing.drupal.liquid
src/site/layouts/vet_center.drupal.liquid
src/site/stages/build/drupal/graphql/facilities-fragments/healthCareRegionEvents.node.graphql.js
src/site/stages/build/drupal/graphql/facilities-fragments/healthCareRegionNewsStories.node.graphql.js
src/site/stages/build/drupal/graphql/healthCareRegionPage.graphql.js
src/site/stages/build/drupal/graphql/nodeEvent.graphql.js
src/site/stages/build/drupal/graphql/storyListingPage.graphql.js

This reverts commit 26ba9912a3b6440387bd39af88b58d8c80d21036.
introduced in https://github.com/department-of-veterans-affairs/content-build/pull/680
Per convos with @davidconlon @mmiddaugh @swirtSJW @kevwalsh , we are going to further research the implications of using `fieldOrder` vs `fieldFeatured` before continuing.

Revert "VACMS-1317: Update featured content logic."

---

src/site/blocks/alert.drupal.liquid
src/site/paragraphs/alert.drupal.liquid

This PR updates outdated alert markup to utilize the [`va-alert` web component](https://design.va.gov/storybook/?path=/docs/components-va-alert--default) to normalize icon sizing across various alert components. The current templates violate the [Design System Guidelines - Category Number 04, Issue Number 07](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/VA.gov-experience-standards.1683980311.html) by having inconsistent sizing and display between identical components. The reported desired icon size was the smaller size as shown in the screenshot below.
##Original issue(s)
https://github.com/department-of-veterans-affairs/va.gov-team/issues/34168

Update block/paragraph alert templates to match design system guidelines

---

.github/workflows/content-release.yml

Secrets from SSM might be scrubbed in between jobs of a GHA workflow. Move the secrets fetch to right before the build instead of in a dedicated "Get env vars" job.
https://github.com/marvinpinto/actions/blob/master/packages/aws-ssm-secrets/src/main.ts#L49

Move Content-Release Drupal Connection Vars to Build Step

---

.github/workflows/content-release.yml
.github/workflows/daily-deploy-production.yml
.github/workflows/record-release-interval/action.yml

Misc fixups for failure to record metrics in daily prod deploy and content release

---

package.json
yarn.lock

PR to upgrade Cypress to the latest version.
Cypress tests run locally.

Upgrade Cypress to `9.5.1`

---

src/site/stages/build/drupal/graphql/CountEntityTypes.graphql.js
src/site/stages/build/drupal/graphql/nodeOffice.graphql.js
src/site/stages/build/drupal/individual-queries.js
src/site/stages/build/index.js
src/site/stages/build/plugins/create-office-directory-data.js

The `/office-directory` app requires a data file consisting of Office nodes.  This file needs to be generated at build time and `fetch`ed from the browser at runtime.  The fetching is done in a [related PR](https://github.com/department-of-veterans-affairs/vets-website/pull/20387) on `vets-website`.  This PR handles the generation of the data file.

VACMS-7771: Generates json data file for office-directory app.

---

src/site/components/banners.drupal.liquid

https://github.com/department-of-veterans-affairs/va.gov-team/issues/35103
The `va-banner` web component has been deployed to Vets-Website and is now available for usage. This PR will allow for the usage of the web component and migrate away from the deprecated React Component for Banner. Following the steps outlined here: https://vfs.atlassian.net/wiki/spaces/DST/pages/2051080448/Liquid+template+migration+guidance#va-banner
https://github.com/department-of-veterans-affairs/vets-website/pull/20381

35103 Banner Web Component Migration

---

src/site/components/banners.drupal.liquid

Description / Issue Number
https://github.com/department-of-veterans-affairs/va.gov-team/issues/35157
The `va-promo-banner` web component has been deployed to Vets-Website and is now available for usage. This PR will allow for the usage of the web component and migrate away from the deprecated React Component for Promo Banner. Following the steps outlined here: https://vfs.atlassian.net/wiki/spaces/DST/pages/2051080448/Liquid+template+migration+guidance#va-promo-banner
Related PR
https://github.com/department-of-veterans-affairs/vets-website/pull/20457
Acceptance criteria
Definition of done

35157 Promo Banner Web Component Migration

---

src/site/facilities/health_care_region_detail_content.drupal.liquid
src/site/layouts/basic_landing_page.drupal.liquid
src/site/layouts/faq_multiple_q_a.drupal.liquid
src/site/layouts/health_care_local_facility.drupal.liquid
src/site/layouts/health_services_listing.drupal.liquid
src/site/layouts/landing_page.drupal.liquid
src/site/layouts/page.drupal.liquid
src/site/layouts/support_resources_detail_page.drupal.liquid
src/site/layouts/vamc_operating_status_and_alerts.drupal.liquid
src/site/layouts/vamc_system_billing_insurance.drupal.liquid
src/site/layouts/vamc_system_medical_records_offi.drupal.liquid
src/site/layouts/vamc_system_policies_page.drupal.liquid

This PR address an issue of table of contents markup being inconsistent between liquid templates. Specifically, on landing pages, the markup is considerably less structured and features default styling, instead of the desired styling with custom icons for the list item bullets.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/34502
**Current markup / stying:**
**Desired result:**

Standardize table of content markup in liquid templates

---

src/site/layouts/landing_page.drupal.liquid

The PR fixes a consequence of [PR #1021](https://github.com/department-of-veterans-affairs/content-build/pull/1021) that duplicates the table of content entries in the ID'd container. There is a set of functions that do automate for other pages, but these landing pages are being deliberate about what they want in the ToC.  This PR simply modifies the containers ID to not be picked up by the modifier functions.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/34502

Update landing page table of contents ID

---

.github/workflows/a11y.yml

Quick PR to move the `CHANNEL_ID` environment variable to the global environment in the daily accessibility scan so that the ID does not have to be updated in multiple lines in the workflow file.

Move accessibility scan Slack channel ID to global variable

---

src/site/includes/metatags.drupal.liquid

This PR updates a bad URL for the default og:image meta tag on site subpages with custom meta tags available. The current implementation prepends the host URL to the tag value in the markup when, in fact, the host URL is already in the tag value.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/33552
**As is:**
**With Update:**

Remove duplicate host url from og:image meta tag

---

package.json
yarn.lock

Upgrade Cypress to `9.5.2`

---

src/site/components/situation_updates.drupal.liquid
src/site/layouts/event.drupal.liquid
src/site/layouts/events_page.drupal.liquid
src/site/teasers/event.drupal.liquid
src/site/teasers/event_featured.drupal.liquid

Events should display with two letter timezone format. This pr removes the "S" and the "D" from {{ timezone }} in liquid templates that output dates.
Visual and build on local instance
**NO**
**YES**

VAHELP-3729: Remove Daylight/Standard placeholder in timezones.

---

src/site/components/situation_updates.drupal.liquid
src/site/filters/liquid.js
src/site/includes/date.drupal.liquid
src/site/includes/social-share.drupal.liquid
src/site/layouts/campaign_landing_page.drupal.liquid
src/site/layouts/event.drupal.liquid

Recurring events date is showing last date (largest date value) rather than the nearest date in the future.  This PR fixes that.
Note: the problem is that a phantom object is being passed to the filter `deriveMostRecentDate`, and so the default parameter `now` is not actually setting to the default.  This ultimately leads to an empty `futureDates` array, which leaves the logic to just grab the last item in the original data set (rather than the first item of the now-empty `futureDates` data set).
It's unclear why this phantom parameter is being passed, but this PR implements a workaround by explicitly passing the current time as the second parameter.
See screenshot below.  Screenshot taken March 8.  Notice all dates are conceivably the _next_ date in the series.

VACMS-37833: fixes incorrect date showing for recurring events.

---

.github/workflows/daily-deploy-production.yml

The environment within github for now is named as "dev-test" and this can be changed based on:
- successful execution of this
- and the cleanup of environment task doesnt delete anything that is other than master
Manual trigger of the workflow at deploy step will trigger an approval to the vsp-frontend-team members
This was also tested here to make sure the scheduled jobs are not required to go through an approval.
department-of-veterans-affairs/va.gov-team#37940
yes

workflow protection of prod deploys for manual runs

---

.github/workflows/content-release.yml

Followups for decoupling content release from daily prod deploy

---

.github/workflows/content-release.yml
.github/workflows/daily-production-release.yml
.github/workflows/daily-release-warning.yml

* Content release should run every hour 13:00-21:00 UTC
* Daily prod deploy is now the daily production release (since it's not actually deploying anything)
* Daily deploy warning is now the daily release warning
* Verbiage changes for the above
* Include release name in slack notification for daily prod release workflow

Housekeeping for job decoupling

---

src/site/layouts/event.drupal.liquid

`Link to event` link text appears on same line as `See all events` on event pages, creating confusion.
This pr breaks them into two lines.
Visual / build

VACMS-7863: Add p tags around link text to ensure line break on event

---

.github/workflows/content-release.yml
.github/workflows/deploy-content-preview-server.yml

See https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8132.

Trigger Jenkins Preview Job After Content Release

---

.github/CODEOWNERS
.github/workflows/deploy-content-preview-server.yml

Follow up to [Trigger Jenkins Preview Job After Content Release #1048](https://github.com/department-of-veterans-affairs/content-build/pull/1048) which had to be merged before it was ready because of the fact a workflow file needs to exist in the default branch in order for it to be run from the actions tab. Subsequent changes can then be tested by a branch selection when running the job, but it must first be registered by existing as a file in the default branch.

Trigger Jenkins Preview Job After Content Release (2)

---

.github/workflows/content-release.yml
.github/workflows/deploy-content-preview-server.yml

Follow up of:
* https://github.com/department-of-veterans-affairs/content-build/pull/1048
* https://github.com/department-of-veterans-affairs/content-build/pull/1065
See https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8132.
Yay

Trigger Jenkins Preview Job After Content Release (3)

---

.github/workflows/content-release.yml

Fix metric calculation in content release datadog metrics

---

.github/workflows/a11y-heading-order.yml
.github/workflows/a11y.yml
.github/workflows/continuous-integration.yml

This PR upgrades the `cypress/browsers` Docker image to the latest version.

Upgrade Docker image used for Cypress tests in CI

---

.github/workflows/content-release.yml

Ref https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8602
Recent fail: https://github.com/department-of-veterans-affairs/content-build/runs/5836038162?check_suite_focus=true#step:27:31

Add a fallback notification for when there are too many broken links to post to slack

---

.github/workflows/content-release.yml

Scrolling through the logs for this action can be kinda tedious, see e.g.
```
--no-progress  (boolean)  File transfer progress is not displayed. This
flag is only applied when the quiet and only-show-errors flags are  not
provided.
```

Uses `aws s3 cp --no-progress` to reduce noise in content build logs.

---

.github/workflows/content-release.yml
.github/workflows/daily-production-release.yml

This PR temporarily comments out the `validate build status` steps so that we can use the latest commit for content releases. This is a workaround for GitHub Action issues that are preventing us from getting the latest workflow runs from the API. The changes in this PR should be reverted once the issue has been resolved.
[Slack thread](https://dsva.slack.com/archives/CU1E4CX9U/p1649705784825259)
[Slack thread](https://dsva.slack.com/archives/C02VD909V08/p1649700395739759)

Comment out validate build status step

---

package.json
yarn.lock

Resolves the `async` [advisory](https://github.com/advisories/GHSA-fwr7-v2mv-hh25).

Resolve async vulnerability

---

.github/workflows/continuous-integration.yml

This PR temporarily updates the `get-latest-run-number` job to fetch the latest commit instead of the latest workflow run number. This is a workaround for the issues with the GitHub API that will allow us to deploy to dev & staging without running into race conditions.

Get latest commit before deploy

---

.github/workflows/manual-deploy-dev-staging.yml

This PR makes some enhancements to the manual dev/staging deploy:
- Uses the `self-hosted` runner for the `Deploy` job (the deploy was timing out due to lack of resources)
- Defines and uses a matrix for the `Deploy` job, so both environments can be deployed simultaneously
Tested using changes in branch:
_Deploy script was commented out for testing purposes_
- [dev deploy](https://github.com/department-of-veterans-affairs/content-build/actions/runs/2158500589)
- [stging deploy](https://github.com/department-of-veterans-affairs/content-build/actions/runs/2158496736)
- [both deployed](https://github.com/department-of-veterans-affairs/content-build/actions/runs/2158504214)

Update manual dev/staging deploy

---

.github/workflows/content-release.yml
.github/workflows/continuous-integration.yml
.github/workflows/daily-production-release.yml

This PR reverts the changes made in https://github.com/department-of-veterans-affairs/content-build/pull/1075 and https://github.com/department-of-veterans-affairs/content-build/pull/1084 that were workarounds for the GitHub Actions API issues. Now that the issues are resolved, we can merge this.

Revert commenting out build validation

---

src/site/stages/build/index.js
src/site/stages/build/options.js

The CMS test suite is presently running a full content build (on every PR + every merge to `main`). We intend to stop doing that, and instead only run the graphql queries as part of our test suite. Keeping the gql queries helps us stay aware of any API <--> content build breakage in our tests -- we just don't need the full HTML output.

Add a flag that allows us to run the graphql queries and nothing else

---

.github/workflows/deploy-content-preview-server.yml

The contents of the templating system can only change after a Daily Production Release, and so a re-deploy of the preview server should happen then. Content release cannot itself have new template or app structure, and so deploying upon changes is unneeded.

Preview server deploy should trigger after Daily Production Release.

---

src/site/facilities/vha_facility_nonclinical_services.drupal.liquid
src/site/includes/hours-item.liquid
src/site/includes/hours.liquid
src/site/layouts/vamc_system_billing_insurance.drupal.liquid
src/site/stages/build/drupal/graphql/vamcBillingAndInsurancePage.graphql.js

Implements remaining items for TTP billing from https://github.com/department-of-veterans-affairs/va.gov-team/issues/37366
**DOES NOT INCLUDE TBD CERNER WORK**
Visual / build
Facility name in intro text
Questions about copay h2 (jump linkable) with system name in text
Linked # and facility hours
Styled Pay online jump link
Linked h4 facility
**Go to `/minneapolis-health-care/billing-and-insurance` and visually verify:**

VAVSA-37366: Add remaining spec items to billing tpl.

---

package.json
yarn.lock

Upgrade Cypress to `9.6.0`

---

script/preview.js

Preview.js was pointing to old S3 buckets for its static files. This updates to the current S3 buckets.

Fix s3 bucket URLs referenced by CMS preview server

---

script/preview.js

A previous pass at this failed because it was attempting to pull manifest.json from the same S3 bucket as content static assets. manifest.json is not available at the content s3 bucket.

Vacms 0000 correct s3 urls

---

.github/workflows/continuous-integration.yml
package.json
yarn.lock

Integrating the new vagov-platform package and replacing the old security-check script with `yarn vagov-dependency-check`
department-of-veterans-affairs/va.gov-team#40725
Just needs to pass in CI since that's where this runs

Add vagov-platform dependency check

---

script/github-actions/check-broken-links-blocks.js

https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8964
Restoring something that was removed in the prior Slack reporting work. https://github.com/department-of-veterans-affairs/content-build/blob/master/script/github-actions/check-broken-links.js#L28

Restore broken link summary print-out.

---

.github/workflows/content-release.yml

Build steps may take longer that the timeout allows for. Specifically it looks like the post-checkout steps are taking longer to finish. Increase the timeout so this can finish without skipping all other jobs in the workflow.
Example of the failure.
https://github.com/department-of-veterans-affairs/content-build/actions/runs/2283032287

Bump Up the Timeout for the Content Build Steps

---

.github/workflows/continuous-integration.yml

This PR removes unneeded steps in the `security-audit` job in CI.
Tested in CI.

Remove unneeded steps in security audit

---

.github/workflows/a11y-heading-order.yml

This PR modifies the weekly accessibility heading order scan to notify Slack when the `build` step in the workflow fails.

Add build error notifications to accessibility heading order scan

---

src/applications/registry.json

Recent IA recommendations want the breadcrumbs for both the Form 686C "Introduction" page and "View dependents" page
[Recommendations](https://github.com/department-of-veterans-affairs/va.gov-team/issues/41055#issuecomment-1122904618)
- Current state: breadcrumb segment: `Add or remove dependents form 21‑686c`
- New: Breadcrumb segment: `Add or remove dependents with VA Form 21-686C`
- In addition, when you are on this form, the breadcrumb segment for it's parent page is incorrect and should be fixed
- The final full breadcrumb when on this page should be: Home > View or change dependents on your VA disability benefits > Add or remove dependents with VA Form 21-686C
- The breadcrumb segment should match the H1 with the same casing structure - Your VA dependents
- When on this tool, the …

Update 686 breadcrumb

---

.github/workflows/authenticated-cms-request/action.yml
.github/workflows/content-release.yml

This is in preparation for https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8108 -- we'll be keeping track of the status of content release in the CMS and holding/sending build requests accordingly. I also took the authenticated request steps and broke them out into a separate workflow to keep things tidy.
This should not be merged until today's CMS release is live (which hasn't happened yet).

Keep the CMS updated as the build progresses (Step 1)

---

.github/workflows/content-release.yml

This is based off of branch for #1125 . Once that's merged, I'll rebase this onto `master`.
The CMS is going to switch to using the repository dispatch trigger to kick off content build, so we need that trigger to be available on the workflow.

Add a repository dispatch trigger (Step 2)

---

.eslintrc.js

This PR adds back the rules from the VA custom ESLint plugin that were removed.
Tested locally.

Add va custom plugin rules

---

src/site/includes/covid-status.drupal.liquid
src/site/includes/facilityListing.drupal.liquid
src/site/includes/operatingStatusFlagsLinks.drupal.liquid
src/site/layouts/health_care_local_facility.drupal.liquid
src/site/layouts/vamc_operating_status_and_alerts.drupal.liquid
src/site/stages/build/drupal/graphql/facilities-fragments/healthCareLocalFacility.node.graphql.js
src/site/stages/build/drupal/graphql/healthCareLocalFacilityPage.graphql.js
src/site/stages/build/drupal/graphql/healthCareRegionPage.graphql.js
src/site/stages/build/drupal/graphql/locationsListingPage.graphql.js
src/site/stages/build/drupal/graphql/locationsOperatingStatus.graphql.js
src/site/stages/build/drupal/graphql/vamcOperatingStatusAndAlerts.graphql.js

Adds expandable alert for facility covid status usage. See:
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8986
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8981
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8982
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8983
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9083
Sibling pr for vets-website vamc expandable widget needed for functionality: https://github.com/department-of-veterans-affairs/vets-website/pull/21037
Tugboat data endpoint to use for testing: https://pr9028-sjpg4ebinnl4eooevngpwufok19n4akk.ci.cms.va.gov/
Adding @maxx1128 & @swirtSJW for situational awareness.
Visual / build

VAVFA-8986: Add queries and include for vamc covid status.

---

jenkins/common.groovy

DO NOT MERGE UNTIL DEFAULT OF VAGOV-CONTENT IS MAIN

update jenkins script to use main of vagov-content

---

.github/workflows/a11y-heading-order.yml
.github/workflows/a11y.yml
.github/workflows/content-release.yml
.github/workflows/continuous-integration.yml
jenkins/common.groovy
script/preview-routes/single-page-diff.js
script/preview.js
src/site/constants/drupals.js
src/site/stages/build/drupal/api.js
src/site/stages/build/drupal/assets.js
src/site/stages/build/drupal/metalsmith-drupal.js
src/site/stages/build/plugins/modify-dom/check-broken-links/helpers/getBrokenLinks.js
src/site/stages/build/plugins/modify-dom/check-broken-links/helpers/isCMSUrl.js
src/site/stages/build/plugins/modify-dom/check-broken-links/index.js
src/site/stages/build/plugins/modify-dom/check-broken-links/tests/helpers/getBrokenLinks.unit.spec.js
src/site/stages/build/plugins/modify-dom/check-broken-links/tests/helpers/isCMSUrl.unit.spec.js

In several places, the codebase uses some long, tall, and _ugly_ URLs for CMS environments, like `internal-dsva-vagov-prod-cms-2000800896.us-gov-west-1.elb.amazonaws.com`, tbh a hostname only a mother could love.
Why the codebase does this to us is not known; perhaps it dates from the time of GitHub-hosted runners; perhaps it goes back further, to the time of Jenkins.  Perhaps the answers are lost in the mists of antiquity.
Anyway, I'm opening this PR to see if I can do away with this nonsense, because a security audit wants us to use HSTS on everything and I don't think AMZN is gonna let us generate TLS certs with their hostnames.
There's a decent amount of work left to do, not least of which is me poring over the code and trying to understand what is happening and why it's happening to …

Replace internal ELB URLs with their public counterparts.

---

src/site/includes/vet_centers/address_phone_image.liquid
src/site/layouts/vet_center_locations_list.drupal.liquid
src/site/stages/build/drupal/graphql/vetCenterLocations.graphql.js

closes https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9061
Visual / build

VAVFA-9061: Display verbiage for hours on caps lists.

---

src/site/stages/build/drupal/static-data-files/config.js
src/site/stages/build/drupal/static-data-files/vamcFacilitySupplementalStatus/index.js

Defines a query and post-processing function to generate a static data file representing VAMC Facility Supplemental Status data.
Locally built.

Adds VAMC Facility Supplemental Status static data file

---

script/github-actions/deploy.sh

This PR adds quotes around the `data/cms/*.json` glob in the first S3 sync. This was causing issues with deployments for dev/staging in CI. [Slack thread](https://dsva.slack.com/archives/C02VD909V08/p1654193402960219)
Tested in a [manual dev deploy](https://github.com/department-of-veterans-affairs/content-build/actions/runs/2430746188) using this branch.

Update Deploy Script

---

script/preview.js
src/site/layouts/event_listing.drupal.liquid

Fixes header and intro text, makes listings available on event listing pages
https://github.com/department-of-veterans-affairs/va.gov-team/issues/28918
Visual / build

VAVSA-28918: Add events v2 header to template.

---

src/site/layouts/event_listing.drupal.liquid

Events v1 and events v2 have a header with the same id (one is obscured by flipper). This pr renames the v1 header id from 
`article-heading` to `article-heading-legacy` to prevent accessibility errors.
Visual / build

VAVFA-000: Remove duplicate header id.

---

src/site/filters/liquid.js

Closes [department-of-veterans-affairs/va.gov-cms#8991](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8991). There's some extra logic in the `topTaskUrl` filter related to Ohio that's not needed. I also cleaned up some of the syntax so it's cleaner and matches with what `eslint` looks for.
Many other `eslint` changes are automatically being added into this file. The ones this PR are focused on are on lines `1303-1325`.
Visual

[VA-8991] Remove unneeded Ohio logic in Cerner filter

---

src/site/layouts/event_listing.drupal.liquid

see: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9353
Events v2 has been released - this pr removes events v1 from listing page template.
Visual / build

VAVSA-9353: Remove events v1

---

src/site/layouts/event_listing.drupal.liquid

The Events header isn't properly aligned. This is due to unneeded wrapper classes around the header, which were likely added for the legacy events page. Now that legacy events is being removed, these extra wrappers can also be removed.
Closes [#9374.](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9374)
Visual
* http://localhost:3002/preview?nodeId=736
* http://localhost:3002/preview?nodeId=2807

[VA-9374] Remove extra wrapping on Events header

---

src/site/stages/build/drupal/assets.js

https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9449
content-build downloads any URI that contains `sites/*/files`. This ends up capturing non-VA Drupal URLs, for example https://www.parkinson.org/sites/default/files/attachments/Parkinsons-Foundation-Veterans-FAQ.pdf
This causes breaks when running these downloads through the proxy. This primarily affects local development.
Local testing.

VACMS-9449: restrict asset download to VA domains.

---

src/site/stages/build/drupal/assets.js

https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9449
This ensures that external asset URLs in HTML are not modified when internal URLs are modified.

VACMS-9449 Adjust asset url rewriting

---

src/site/facilities/health_care_region_detail_content.drupal.liquid
src/site/layouts/basic_landing_page.drupal.liquid
src/site/layouts/faq_multiple_q_a.drupal.liquid
src/site/layouts/health_care_local_facility.drupal.liquid
src/site/layouts/health_services_listing.drupal.liquid
src/site/layouts/landing_page.drupal.liquid
src/site/layouts/page.drupal.liquid
src/site/layouts/support_resources_detail_page.drupal.liquid
src/site/layouts/vamc_operating_status_and_alerts.drupal.liquid
src/site/layouts/vamc_system_billing_insurance.drupal.liquid
src/site/layouts/vamc_system_medical_records_offi.drupal.liquid
src/site/layouts/vamc_system_policies_page.drupal.liquid
src/site/layouts/vamc_system_register_for_care.drupal.liquid
src/site/layouts/vet_center.drupal.liquid

relates to https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9220
Replaces the custom js table of contents found on various content types with storybook/design system component
Visual / build
Facility
Billing
Medical
Pharmacy
Resources
Faq
Health services
Health care detail
Page
Support Resource
Op-Status
Vet Center
**Note: paths not included for testing that appear in above screenshots typically do not display a table of contents, as they have a toggle on the node form to turn on, with default setting to off - I enabled them locally just to confirm they would work properly if enabled**

VACMS-9220: Replace custom js toc with component.

---

src/site/layouts/va_form.drupal.liquid

This PR updates an old implementation of a CTA arrow link with a reusable one from the VA design system. The visited state of the link will now have a blue arrow, instead of purple.
Old:
New:

VACMS-8932: replaced old CTA arrow implementation with the one from the VA design system

---

.github/workflows/continuous-integration.yml

This is an effort to move the composite actions that are common and have the possibility to be able to be called globally from another repo.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/39265
yes

slack notify as a global composite action

---

.github/workflows/content-release.yml
.github/workflows/continuous-integration.yml

Runners for `content-build` were incorrectly pointing to `vets-website`
https://dsva.slack.com/archives/C02VD909V08/p1655834712670579
yes

change runner to content-build

---

src/applications/registry.json

Updating `vagovprod` flag to true for Combined Debt Portal for UAT testing. There is a feature flag that will redirect unauth/non-whitelisted users to va.gov home page.

[CDP] Updating vagovprod for UAT testing

---

src/site/layouts/event.drupal.liquid

The Events Detail page isn't showing the icon for recurring events since it's still using the old Events V1 template. This PR removes the conditional and always returns the Events V2 template.
Closes https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9450
Visual

[VA-9450] Remove EventV1 template without recurrence icon

---

.github/workflows/a11y-heading-order.yml

Quick PR to add an `@here` to the weekly scan that checks heading orders.

Add Slack ping to weekly sitewide heading order scan

---

src/site/includes/covid-status.drupal.liquid

There was a missing comma in the data being sent to a GA function.
Locally/visual

Fix js syntax error in GA data on vamc location pages

---

src/site/layouts/event.drupal.liquid

Event pages have recently not shown their locations. It looks like removing an outdated template caused the bug, so updating the location variables to only the most recent ones looks to have fixed it.
Closes [#9442](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9442).
Visual ([confirm locally here](http://localhost:3002/preview?nodeId=47378)).

VA-9442: Update Event page location variables

---

.github/workflows/a11y-heading-order.yml

This PR adds clean up steps to the weekly accessibility heading order scan in order to minimize the risk of self-hosted runners running out of disk space.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/43420

Add clean up steps to weekly accessibility heading order scan

---

src/site/includes/facilityListing.drupal.liquid
src/site/layouts/health_care_local_facility.drupal.liquid

Original issue: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9712
Changed instances "Mental health clinic" to "Mental health care on Location listings
Local, visual confirmation
ts

clinic changed to care

---

src/applications/registry.json

Fix Supplemental Claims breadcrumbs:
- Add missing `includeBreadcrumbs` setting
- Move `breadcrumbs_override` inside `template`
Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/43928
N/A
N/A

Fix Supplemental Claim breadcrumbs

---

src/applications/registry.json

Updating combined-debt-portal with new URL
Moving from ~~`/manage-debt-and-bills/summary`~~ to `/manage-va-debt/summary`
[vets-website matching url update](https://github.com/department-of-veterans-affairs/vets-website/pull/21590)

[CDP] Update to new URL

---

src/site/includes/hero.html

Changed heading 'Access and manage your VA benefits and health care' to a H1 so that the page would have at least one H1.
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9721
- Visual
- Axe Dev Tools to confirm that the heading error went away

9721 screenreader no h1 heading on page

---

src/site/facilities/health_service.drupal.liquid

The event tracking in the accordions is causing JS syntax errors that affect other interactions, like showing the feedback modal. This PR makes two changes to avoid this:
1. Use double quotes around the event tracking values so they don't cancel out the single quotes used as apostrophes in the value.
2. Add `escape` filters to the variables for any special characters
Closes [#9588](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9588).
Visual, although I hit some obstacles in fully reproducing it.
N/A

VACMS-9588 Fix syntax for accordion event tracking

---

src/site/layouts/home-preview.drupal.liquid

Changed h2s to h3s under the heading 'Learn about and apply for VA benefits and health care'
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9722
Visual

Change hub h2 to h3

---

src/site/filters/liquid.js
src/site/layouts/health_care_region_page.drupal.liquid

The links for managing online health need to include logic for "converting to cerner," or `cerner_staged`. The logic for which URLs are chosen is explained in the ticket.
Closes [#9738.](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9738)
Visual on [this localhost page.](http://localhost:3002/preview?nodeId=8127)

[VA-9738] Include "Converting to Cerner" logic in topTaskUrl link filter

---

src/site/layouts/campaign_landing_page.drupal.liquid
src/site/layouts/step_by_step.drupal.liquid
src/site/stages/build/drupal/graphql/nodeCampaignLandingPage.graphql.js
src/site/stages/build/drupal/graphql/nodeStepByStep.graphql.js

See department-of-veterans-affairs/va.gov-cms#9840.
If you update the alt text of a Media Image in Drupal, the alt text is not actually changed; see this core issue: https://www.drupal.org/project/drupal/issues/3232414 (which I've yet to chime in on)
I've changed the GraphQL queries referring to thumbnail.alt and the liquid templates so that the content build will reflect the latest alt text, rather than the original alt text.
I made the simplest and probably dumbest changes possible because I don't really speak GraphQL and I'm an idiot even when I'm fluent in the thing in question, so apologies if I'm missing something obvious.

VACMS-9840: Works around a Drupal bug with updating alt text in image media.

---

src/site/includes/faq-schema.liquid
src/site/layouts/faq_multiple_q_a.drupal.liquid
src/site/layouts/vamc_system_medical_records_offi.drupal.liquid
src/site/layouts/vet_center.drupal.liquid
src/site/paragraphs/q_a_section.drupal.liquid

Several FAQ pages and components don't have the Google Schema code included in the page so the questions and answers will show up in search results. This adds the schema code to the HTML for the needed code in three layouts and one component.
I went through all the listed pages in the original ticket and added the schemas to all the pages where the FAQ data was present in the page's MetalSmith object. It couldn't be added to pages where the questions and answers were added in plain text inputs.
Closes [#1294](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/1294).
Visual, code inspection
<a href="http://localhost:3002/preview?nodeId=3676">Norristown Vet Center</a>
<a href="http://localhost:3002/preview?nodeId=45727">Medical Records Office</a>
<a …

[VA-1294] Add Schemas to FAQ Pages

---

.github/workflows/a11y-heading-order.yml
.github/workflows/a11y.yml

Due to changes in self-hosted runners used in the two accessibility scans, yarn now needs to be installed in the workflows.
Ran daily accessibility scan.

Install yarn in accessibility workflows

---

package.json
yarn.lock

Quick PR to upgrade Cypress to the latest version, which includes multiple bug fixes.

Upgrade Cypress to `10.3.1`

---

.github/workflows/a11y.yml

The daily accessibility scan now takes about an hour longer than it did when it was first created. This PR modifies the start time of the scan to be one hour earlier.

Start daily accessibility scan one hour earlier

---

src/site/layouts/health_care_local_facility.drupal.liquid
src/site/layouts/vet_center.drupal.liquid
src/site/stages/build/drupal/graphql/vetCenter.graphql.js

Adds JSON-LD to Vet Center Template. Brings in geolocation data from GraphQL
- [validator.schema.org](https://validator.schema.org/)
- visual [http/preview?nodeId=3627](http://localhost:3002/preview?nodeId=3627)

Add JSON-LD to vet center template

---

src/site/layouts/vet_center.drupal.liquid

Adds services json-ld to vet center template.
https://app.mural.co/t/vagov6717/m/vagov6717/1657548339031/75fd9c37c635478edcbc7d5179d95b6d53d9c339?sender=dfafbb7c-1fe6-468b-880a-a3e3fa8ff9c2
https://validator.schema.org

Add services json-ld to vet center template

---

src/site/stages/build/drupal/graphql/bannerAlerts.graphql.js
src/site/stages/build/drupal/graphql/bioPage.graphql.js
src/site/stages/build/drupal/graphql/facilities-fragments/healthCareRegionHealthServices.node.graphql.js
src/site/stages/build/drupal/graphql/facilities-fragments/healthCareRegionNonClinicialServices.node.graphql.js
src/site/stages/build/drupal/graphql/healthCareLocalFacilityPage.graphql.js
src/site/stages/build/drupal/graphql/healthCareRegionDetailPage.graphql.js
src/site/stages/build/drupal/graphql/healthCareRegionPage.graphql.js
src/site/stages/build/drupal/graphql/healthServicesListingPage.graphql.js
src/site/stages/build/drupal/graphql/leadershipListingPage.graphql.js
src/site/stages/build/drupal/graphql/locationsListingPage.graphql.js
src/site/stages/build/drupal/graphql/newStoryPage.graphql.js
src/site/stages/build/drupal/graphql/nodeEvent.graphql.js
src/site/stages/build/drupal/graphql/nodeEventListing.graphql.js
src/site/stages/build/drupal/graphql/pressReleasePage.graphql.js
src/site/stages/build/drupal/graphql/pressReleasesListingPage.graphql.js
src/site/stages/build/drupal/graphql/storyListingPage.graphql.js
src/site/stages/build/drupal/graphql/vamcBillingAndInsurancePage.graphql.js
src/site/stages/build/drupal/graphql/vamcMedicalRecordsOfficePage.graphql.js
src/site/stages/build/drupal/graphql/vamcOperatingStatusAndAlerts.graphql.js
src/site/stages/build/drupal/graphql/vamcPoliciesPage.graphql.js
src/site/stages/build/drupal/graphql/vamcRegisterForCarePage.graphql.js

Closes https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9997
All content types that can potentially appear in VAMC Lovell need to have field_administration added to the graphQL query.
Visual developer console
- The graphQL queries for the following content types include field_administration 
- Facility specific pages
- Spanning all products including facilities.

9997 fe queries for vamc content types need field administration

---

src/site/stages/build/drupal/metalsmith-drupal.js
src/site/stages/build/drupal/page.js

This hooks into the build step, finds pages for Lovell Federal Health Care subsite, and duplicates them with needed changes for the Lovell Tricare subsite.
Currently a WIP, blocked until #1242 is merged. Also being handed off to @wullaski during the sprint.
Closes [#9945.](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9945)
Running `yarn build`  locally and verifying pages get created in a new `lovell-tricare-health-care` directory.
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9945
These are looser.... than the actual acs on the issue to reflect a slight pivot.
- actual path pattern is not fully defined at this time but the code is clear on where we will put the finalized pattern. Should not prevent this from being merged to an integration …

VACMS-9945: Add bifurcation for Lovell build step

---

src/site/includes/faq-schema.liquid
src/site/layouts/vet_center.drupal.liquid
src/site/paragraphs/q_a.collapsible_panel.drupal.liquid
src/site/paragraphs/q_a.drupal.liquid
src/site/paragraphs/q_a_section.drupal.liquid

closes: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10094
Fix validation issues on faq schema.
https://validator.schema.org/

VACMS-10094 fe cleaning up duplicate faq schema implementation

---

src/site/layouts/support_resources_detail_page.drupal.liquid

The PACT pages when translated are built from a different template than the English version.  This adds the language toggle widget to the support-resources-detail-page template so that the toggle renders for all language types.

widget added to translated page types

---

.gitignore
src/platform/testing/e2e/cypress/support/commands/axeCheck.js
src/platform/testing/unit/axe-plugin.js
src/site/assets/js/execute-axe-check.js
src/site/tests/support/axe.js

Same update as https://github.com/department-of-veterans-affairs/vets-website/pull/21870 but for this repo.
Update all [WCAG rules from 2.0 to 2.1](https://github.com/dequelabs/axe-core/blob/a3d5cef612013ffe0db5383a4047508654444d3c/doc/API.md#axe-core-tags), as our [current standard is 2.1](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing).
This introduces two new rules:
- [autocomplete-valid](https://dequeuniversity.com/rules/axe/4.4/autocomplete-valid?application=RuleDescription) 
- [avoid-inline-spacing](https://dequeuniversity.com/rules/axe/4.4/avoid-inline-spacing?application=RuleDescription)
- Unit/E2E ran locally, all passed.
- Ran the [full daily scan with this …

Update to WCAG 2.1

---

src/applications/registry.json

Enable vagovprod flag so URL is visible on production in preparation for MEB release on 08/20. This only enables the URL for access in preparation of deployment of services.
Next step will be limited testing on production with UAT testers when DGIB services become only on 08/20.
After that, we'll enable feature flag for full access to everyone so the link becomes accessible from the Education wizard.

- Enable MEB url in production in preparation for 08/20 release

---

src/site/includes/header.html

Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1058
Related PRs:
- https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/857
- https://github.com/department-of-veterans-affairs/component-library/pull/433
This adds pre-release packages of `formation` and `component-library` to the Covid-19 healthcare page in order to test the new double box-shadow focus styles. They are designed to be easily removed.
The prototype will live [here on staging](https://staging.va.gov/health-care/covid-19-vaccine/).
Local build :eyes:

Build prototype for new focus styles

---

.github/workflows/continuous-integration.yml

Updates the `Deploy` job to use on demand runners.

Use on demand runner for deploy job

---

src/site/stages/build/drupal/graphql/file-fragments/outreachAssets.graphql.js

Closes https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10312
Outreach materials (`outreach_assets`) query was broken in a non-obvious way. It was still returning results, but not limited to the `outreach_assets` type. So, it was returning all nodes, and the 10000 limit was insufficient. This corrects the filter.
Testing done in GraphQL explorer.

VACMS-10312: Fixes defect with missing Outreach Materials

---

src/site/stages/build/drupal/graphql/fragments.graphql.js
src/site/stages/build/drupal/graphql/nodeSupportResourcesDetailPage.graphql.js
src/site/stages/build/drupal/graphql/paragraph-fragments/qaGroup.paragraph.graphql.js

updated graphql query to pull new QA content
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9901
Tested in PR tugboat environment: https://tugboat.vfs.va.gov/62c7e70524e7d21f96728554
https://cms-zqis1amj7i3jmmqvydvdxfmptbsn7zzf.ci.cms.va.gov/admin/content/deploy
https://web-zqis1amj7i3jmmqvydvdxfmptbsn7zzf.ci.cms.va.gov/resources/how-to-get-your-medical-records-from-your-va-health-facility/
Trigger content build and release using the frontend from this PR.  Observe that the environment builds without error

9901-graphql updated for new Q&A content on support resource detail pages

---

src/site/includes/header.html

Closes https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1058
This reverts the revert in department-of-veterans-affairs/content-build#1261 :upside_down_face:. 
The goal here is to create a prototype page with the double box-shadow focus styling that can be used in user testing sessions. I have modified the original boolean expression so that our web component script gets loaded on all pages that aren't the prototype. The prototype will be the [COVID-19 page](https://dev.va.gov/health-care/covid-19-vaccine/) in the dev environment.
Just to be safe I'm planning on merging this after the daily deploy, and not on Friday.
The reason why I'm removing the "regular" web component loader script on the prototype page is because the browser will use whichever …

Reapply "Build prototype for new focus styles"

---

src/platform/static-data/footer-links.json

Removes link from footer.
Note: There is a related PR on vets-website, but this PR is the much more important one, as this PR changes the code that actually affects the production website (the vets-website PR only affects the footer in local development).
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10335
Tested locally. Link is gone.

VACMS-10335: Removes VSO link from footer

---

src/site/layouts/support_resources_detail_page.drupal.liquid

This PR adds `.usa-content` class to the `article` element so that non-English content on R&S detail pages will get a `lang` attribute.
Note: this will apply for both Spanish and Tagalog
Issue and more context: [department-of-veterans-affairs/va.gov-cms/issues/10289](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10289)

VACMS-10289: fixes missing lang attribute on non-English content (Resources & Support detail pages only)

---

src/site/stages/build/plugins/download-drupal-assets.js

https://github.com/department-of-veterans-affairs/next-build/pull/89
This just a small amount of logging to keep tabs on how many parallel file downloaders are running and both start and end logging for file downolad.

Add more logging to file downloads.

---

package.json
src/site/includes/header.html
src/site/tests/home/custom-elements.cypress.spec.js
yarn.lock

Related to #1262 
After accidentally deploying a prod build which didn't include the script that defines the web component tags in the browser, it seemed like a good idea to try to prevent that in the future with a test.
cc @department-of-veterans-affairs/platform-design-system-fe 
E2E tests. In [this commit](https://github.com/department-of-veterans-affairs/content-build/pull/1266/commits/4fdd01e23c364d664a54bdce437b35a41ae404f4) we can see that [this new test will fail](https://github.com/department-of-veterans-affairs/content-build/runs/7902604966?check_suite_focus=true#step:9:117) when the script responsible for defining web components isn't on the page.

Assert all web component tags are defined

---

src/site/layouts/health_care_facility_status.drupal.liquid

Fix hard coded Pittsburgh value in operating status template.
Visual

Add dynamic string for region or office value

---

src/site/components/phone-number.drupal.liquid
src/site/facilities/vha_facility_nonclinical_services.drupal.liquid
src/site/includes/hours.liquid
src/site/layouts/vamc_system_billing_insurance.drupal.liquid
src/site/paragraphs/service_location.drupal.liquid

The heading structures used in the "Register for Care" page templates aren't correctly organized for screen readers. They need to descend in a logical order based on the content. This pull request fixes them so screen reader users can properly understand and navigate around them.
This closes [#10060](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10060), and also closes [#10062](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10062) due to heavy similarity and code overlap means they both need to be fixed at basically the same time.
Visual
* [Register for Care local page](http://localhost:3002/preview?nodeId=45917)
* [Billing and Insurance local page](http://localhost:3002/preview?nodeId=45663)

[VA-10060] Fix heading structures for Care (and Billing) Templates

---

.github/workflows/content-release.yml

Modify notify-start step to send notifications to status-content-build slack channel instead of cms-notifications.
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10292

Modify Notify-Start Step Slack Channel

---

.github/workflows/a11y-heading-order.yml
.github/workflows/a11y.yml

PR to fix permissions errors in the two accessibility scans.

Use self-hosted runners without ASG in accessibility scans

---

script/github-actions/check-broken-links-blocks.js

In response to this Slack thread: https://dsva.slack.com/archives/C030F5WV2TF/p1661534521227879
Slack's API will fail if too much information is passed in one 'block' i.e. chunk of information. If a single page has so many broken links on it that it passes this threshold (3000 chars), then the message will fail to post to Slack.
This just limits the number of links that is allowed to post.

Limit number of broken links that can report for a single page.

---

.github/workflows/content-release.yml

Add reasonable timeouts to workflow jobs that may hang. See discussion:
https://dsva.slack.com/archives/CJT90C0UT/p1662040948350839

Add timeouts to some jobs; restore 30 minute build timeout.

---

src/site/stages/build/drupal/graphql/navigation-fragments/facilitySidebar.nav.graphql.js
src/site/stages/build/drupal/metalsmith-drupal.js
src/site/stages/build/drupal/page.js
src/site/stages/build/drupal/process-lovell-pages.js

Bifurcates menus for Lovell pages.
Visual

VACMS-10166 Add lovell menu bifurcation

---

.github/workflows/content-release.yml

Security issue, see [thread](https://dsva.slack.com/archives/C02HX4AQZ33/p1662126073997009).
>On September 1, CSOC received notification from DHS Cybersecurity & Infrastructure Security Agency (CISA) of vulnerable code posted to the VA’s public-facing GitHub repository. Below are details on the vulnerability and recommended remediation. The code should be remediated as soon as possible. Please confirm with CSOC as soon as the remediation is in place, and contact us 24x7 with questions.
Vulnerability Background:
>The vulnerability stems from a known issue with GitHub Action Workflows (AW). Calls to third-party AWs reference the AW author’s username. If the AW author changes their username, an attacker could create an account with the AW author’s old username and publish a malicious AW with …

Point `content-release` action to new owner.

---

src/site/stages/build/drupal/graphql/entityQueue.graphql.js
src/site/stages/build/drupal/individual-queries.js
src/site/stages/build/drupal/metalsmith-drupal.js
src/site/utilities/stringHelpers.js

See: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10375
Implements a way to "dark launch" CMS pages. If a node is added to the `staged_content` Entityqueue, that page will be excluded from the production build.
Built with data from [this Tugboat](https://cms-h3msowyrt1vq41aexyonavht3xohk2mr.demo.cms.va.gov/admin/structure/entityqueue/staged_content/staged_content?destination=/admin/structure/entityqueue).
- Built locally with `buildtype=vagovprod`.
- `staged_content` **does not** build. 
- Built locally with `buildtype=vagovstaging`.
- `staged_content` **does** build. 
- Additionally, built on Tugboat with removed logic that limits feature to production.
- `staged_content` does not build.

VACMS-10375: Removes staged_content from production build.

---

src/site/stages/build/plugins/modify-dom/check-broken-links/index.js
src/site/stages/build/plugins/run-next-build.js

Relates to https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10466
- Pointed local next-build and content-build repos at my local ddev cms instance
- Ran content build to get baseline # of broken links
- Added dummy broken links to News Story nodes
- Re-ran content build locally, verified new dummy broken links were picked up
command to run: `NODE_OPTIONS='--max-http-header-size=50000' yarn build --nosymlink --run-next-build`
I did the same while facing at the staging instance content-build points at by default, but that content is reset daily during the mirror update, so local testing was the way to go to preserve my bad data.
```json
{
"path": "finger-lakes-health-care/stories/the-new-2022-pact-act",
"linkErrors": [
{
"html": "<a href=\"/foo-bar\">facilities across the …
```

VACMS-10466 add path to next-build broken links, update log color

---

src/site/filters/liquid.js
src/site/filters/liquid.unit.spec.js
src/site/includes/hours.liquid
src/site/layouts/tests/vet_center/template/fixtures/vet_center_hours_data.json

Creates a filter for normalizing the hours data coming from the cms so that the data always consists of 7 days. Where there is no data for a day the filter sets default values for that day:
```
let day = {
day: i,
starthours: null,
endhours: null,
comment: 'Closed',
};
```
- visual
- unit testing

10527 office hours on facilities are not showing closed if weekdays are empty

---

src/site/facilities/health_care_region_detail_content.drupal.liquid
src/site/includes/lovell-switch-link.drupal.liquid
src/site/layouts/event.drupal.liquid
src/site/layouts/event_listing.drupal.liquid
src/site/layouts/health_care_local_facility.drupal.liquid
src/site/layouts/health_care_region_page.drupal.liquid
src/site/layouts/health_services_listing.drupal.liquid
src/site/layouts/leadership_listing.drupal.liquid
src/site/layouts/locations_listing.drupal.liquid
src/site/layouts/news_story.drupal.liquid
src/site/layouts/person_profile.drupal.liquid
src/site/layouts/press_release.drupal.liquid
src/site/layouts/press_releases_listing.drupal.liquid
src/site/layouts/story_listing.drupal.liquid
src/site/layouts/vamc_operating_status_and_alerts.drupal.liquid
src/site/layouts/vamc_system_billing_insurance.drupal.liquid
src/site/layouts/vamc_system_medical_records_offi.drupal.liquid
src/site/layouts/vamc_system_policies_page.drupal.liquid
src/site/layouts/vamc_system_register_for_care.drupal.liquid
src/site/stages/build/drupal/process-lovell-pages.js

After "Phase XVII Bifurcation Of Love and Thunder," many pages can be viewed as a veteran or DoD employee. This PR creates the "switch links" for switching between these two views and adds a widget to the top of layouts that shows them when available.
Closes [#9947](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9947).
Visual, checked affected pages.
You'll need to run `yarn build --pull-drupal --drupal-address=https://main-h9pcctlewcire4bsv6mokzmlxgji68i8.demo.cms.va.gov` to generate the pages (around 20 minutes) before running `yarn preview`.
See the below pages' URLs and the respective changes to the alert. Clicking the link on one will go to the other page, respectively.

[VA-9947] Add VA/Tricare switch links

---

src/site/stages/build/drupal/graphql/nodeEvent.graphql.js

Ticket [#10465](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10465)
Joint testing efforts with Backend. See PR [#10357](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/10357)
- Additional, existing events were checked to make sure they were still functioning as desired.

VACMS-10465-adding-event-location

---

.github/CODEOWNERS

The old `vsa-caregivers-frontend` group was left in a bit a of a limbo without an owner/maintainer. The name is also extinct, as the vsa name has been retired with the old contract. With this, the group has been sunsetted with its replacement being a new group to reflect the expanded work the team maintains. This PR updates the codeowners to reflect the new group name.

Update codeowners for new 1010 group name

---

.github/workflows/a11y-heading-order.yml
.github/workflows/a11y.yml

The `ci_node_total` variable in these workflows is not being used, so it can be removed.

Remove unused matrix variable in accessibility scans

---

src/site/stages/build/drupal/process-lovell-pages.js

When the pages are built for Lovell the process to assign menus is broken due to the code not properly handling the new TRICARE and VA titles and labels. 
-visual

10726 fe page bifurcation fix for new content

---

.devcontainer/Dockerfile
.github/workflows/a11y-heading-order.yml
.github/workflows/a11y.yml
.github/workflows/content-release.yml
.github/workflows/continuous-integration.yml
.github/workflows/install/action.yml
Dockerfile
package.json

To downgrade yarn to  1.19.1, matching the downgrade on vets-website, so `yarn add` command works in workspaces
-[x] local build
-[x] unit/e2e
-[x] web testing
-[x] No change in workflow detected

downgrades yarn to 1.19.1

---

src/site/stages/build/drupal/process-lovell-pages.js

Adds a find a replace for the breadcrumbs so that they link to the proper locations and remain in the new VA and TRICARE sections.
Visual

Add find and replace for breadcrumb

---

src/platform/static-data/footer-links.json

Issue: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10666
Updated VAntage blog link and text, and VA news text.
Visual, local testing

VAntage blog link and press link updated

---

src/site/includes/top-nav.html

Removes all code written for the IE Deprecation banner including the useOnLoaded custom hook.
department-of-veterans-affairs/va.gov-cms/issues/9761
N/A as this is removing a feature. Nothing to show.

9761 - Removed IE Deprecation banner from top-nav

---

src/site/components/fullwidth_banner_alerts.drupal.liquid

Rebuilt content-build with new changes, view page source on http://localhost:3002/resources/how-to-download-and-open-a-vagov-pdf-form/,  observe the lack of white space

removed white space from fullwidth banner alerts

---

src/site/facilities/health_service.drupal.liquid
src/site/layouts/faq_multiple_q_a.drupal.liquid
src/site/paragraphs/collapsible_panel.drupal.liquid
src/site/paragraphs/q_a.collapsible_panel.drupal.liquid

Adjusted accordion heading levels in content build to make them fit page hierarchy for accessibility 
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10718
Visual, local testing. Examples of pages with corresponding templates:
/tennessee-valley-health-care/health-services/
/health-care/covid-19-vaccine/
/health-care/eligibility/

10718 accordion heading fixes

---

src/site/paragraphs/q_a.collapsible_panel.drupal.liquid

To accommodate  for header levels that are passed from CMS, header levels need to be assigned in <va-accordion-item> props.
Verified that accordion headers are properly rendered locally

Changed to old way of assigning header level on accordions

---

src/site/stages/build/drupal/home.js

Fixes typo and adds new Benefit Hub icon for VA Dept Info.

10982 - Adds hub icon for va dept info, fixes small typo

---

src/site/stages/build/drupal/home.js

https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10982#issuecomment-1276623250
Updated the Find a VA Facility link to point to /find-locations.
(The top two items in the issue comment were taken care of in a previous PR. the bottom two remain TBD)
Manual local testing

10982 - fix incorrect url in search tools links in homepage prototype

---

src/site/stages/build/drupal/graphql/vetCenterLocations.graphql.js

Facility locations can show draft and archived location pages when they should only show published ones. This adjusts the GraphQL query so only published ones are used on the page.
Visual.
[Seen on this Tugboat page.](https://web-ersyymdhh8rrzxlevrh1xsmeyx7pzcpv.demo.cms.va.gov/duluth-vet-center/locations/)
[Seen on this local page pulled from the previous Tugboat instance.](http://localhost:3002/duluth-vet-center/locations/)

VACMS-10707: Only show published vet center locations

---

src/site/stages/build/plugins/modify-dom/add-lang-to-main.js
src/site/stages/build/plugins/modify-dom/index.js

Implements a plugin to modify the DOM in each template to indicate the page contents language via the `lang` attribute on the `main` element. This enables proper functionality of the `va-on-this-page` component. It derived the language based on the page name, accepting pages ending in `-esp' or `-espanol` as Spanish and pages ending in `-tag or `-tagalog` as Tagalog, while defaulting to English for all other pages.
Several rounds of manual testing to assure that all Spanish and Tagalog pages were accounted for.

10177 adds plugin to specify page language on main element of all pages.

---

src/site/paragraphs/table.drupal.liquid

Make the first element in each row a table header, with scope and role type appropriate for a row
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10983
Local visual testing.  accordions tested at this url '/disability/compensation-rates/veteran-rates/'

First row modified to be headers

---

src/site/stages/build/drupal/process-lovell-pages.js

Lovell pages aren't showing any of their menus. The cause is the Lovell menu structure was changed, and the Federal menu needs to be before the Tricare or VA menus. This fix rearranges the menu as part of the cloning process so the federal one is always placed first, which should help avoid similar bugs in the future.
Visual, see below screenshots.

[VA-11155] Lovell Menus not showing on front-end

---

src/site/layouts/event.drupal.liquid

Adds the URL to an online event as a link when it is provided
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11346
Local visual testing.  URLs to QA:
http://localhost:3002/preview?nodeId=33511
http://localhost:3002/outreach-and-events/events/50078/

Url link added to online events when present

---

src/site/stages/build/drupal/process-lovell-pages.js

The event listing pages on Lovell Tricare and VA only have federal events, but not events specific to Tricare or the VA. This takes the Tricare or VA specific events and adds them to their respective listings.
UPDATE on 10/12: Thanks to @ryguyk for helping me get this ticket on the right track. This PR now updates the listings for events, press releases, and stories. Screenshots have been updated. The broken menus are a separate issue and will be addressed later.
Visual, see below screenshots

VACMS-10168 Add Lovell categorized event listings

---

src/site/includes/top-nav.html
src/site/paragraphs/table.drupal.liquid

https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11271
updated alt text in header logo
local testing in chrome

VACMS-11271 Update alt text for main header logo

---

src/site/includes/facilityListing.drupal.liquid
src/site/includes/vet_centers/address_phone_image.liquid
src/site/layouts/health_care_local_facility.drupal.liquid
src/site/layouts/vet_center.drupal.liquid

The "Directions" link for Facilities pages needs to not open in a new tab, and identify itself as using Google maps. This makes this less disorienting and more clear to users, especially ones using screen readers
Closes [#11363](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11363)
Visual [(this URL).](http://localhost:3002/pittsburgh-health-care/locations/h-john-heinz-iii-department-of-veterans-affairs-medical-center/)

[VA-11363] Fix directions link for 508 compliance

---

.github/workflows/content-release.yml

https://dsva.slack.com/archives/CBU0KDSB1/p1667856682679169
The new steps which push build step metrics were running last in the Build job. Prior to that, there are some conditional steps which run if there are broken links to report. Those conditional steps request non-prod credentials. When those conditional steps run, the AWS credentials are non-prod, and thus don't have access to pull information from SSM.
This moves the steps that push the build metrics to earlier in the job, when the credentials will be correct.

VACMS-11290: move upload of step metrics earlier in build job to avoid using non-prod credentials.

---

src/site/filters/liquid.js
src/site/layouts/publication_listing.drupal.liquid
src/site/stages/build/drupal/graphql/file-fragments/outreachAssets.graphql.js

https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11153
Adjusted graphql query to allow outreach filters to be added dynamically
Local testing with backend tugboat instance

Outreach filteres added and sorted

---

.github/workflows/content-release.yml

https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11309
The ultimate aim here is to speed up content build. The build process timing is pushed to Datadog, so we will be able to see the impact of any metrics changes.
We tested different instance types here: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11130#issuecomment-1284493502
We saw speed improvements with different instance types than what we currently use.

VACMS-11309: switch to c5.4xlarge instances.

---

src/site/stages/build/drupal/graphql/file-fragments/outreachAssets.graphql.js

This removes a field that is no longer used in the codebase or the CMS
This removes the only ocurrence of it in the codebase

VACMS-11149 Remove fieldBenefits from graphQL.

---

src/applications/registry.json
src/site/includes/header.html
src/site/stages/build/plugins/create-react-pages.js

Part of https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1211
This updates the build to check a `useLocalStylesAndComponents` value in each app's registry when building the page for the app. If the value is true then the script that defines all web components globally along with the site-wide stylesheet won't be included on the page.
This also sets the `useLocalStylesAndComponents` registry value in the `pre-check-in` app to true.
In a localhost build, the `web-components.js` script file and `style.css` stylesheet were present in the `appointment-check-in` app, but not the `appointment-pre-check-in` due to the registry value:
And in a production build, the web-component script and site-wide stylesheet are still present in the app despite the …

Allow apps to opt out of global web-components definition script & site-wide styleshet

---

src/site/facilities/facility_health_service.drupal.liquid
src/site/facilities/health_service.drupal.liquid
src/site/includes/health_services_listing_services.liquid
src/site/layouts/health_care_local_facility.drupal.liquid
src/site/layouts/health_services_listing.drupal.liquid
src/site/stages/build/drupal/graphql/healthCareLocalFacilityPage.graphql.js
src/site/stages/build/drupal/graphql/healthServicesListingPage.graphql.js

Closes https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11422
Display the tricare service description for a service listed on either a VAMC Facility page or a Health Service List page when the following criteria are satisfied:
**VAMC Facility Page**
- The field_administration (section) field for the facility = Lovell - TRICARE
- The field_tricare_description field for the VA Services term referenced by the VAMC Facility Health Service is not empty
**Health Service List Page**
- The field_administration (section) field for the health service list page = Lovell - TRICARE
- The field_tricare_description field for the VA Services term referenced by the VAMC System Health Service is not empty
Manual testing
**VAMC Facility - USS Red Rover**
**Health Services for Lovell VA …

VACMS-11422: add tricare fallback to Lovell Service descriptions

---

src/site/stages/build/drupal/process-lovell-pages.js

Two tickets show how several Lovell pages have incorrect switch links and/or switch link banners. The cause was modifying the Lovell page path was inadvertently changing the `originalPath` variable, which rippled into how the switch links were being set. This is because the `entityUrl.path` was being checked for making switch links, but the change was being done off of `originalPath`. So it lead to some data inconsistencies among pages.
Closes [#11373](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11373) and likely [#11374](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11374)
Debugging, see below screenshots.
These are the pages that had incorrect switch links. Both pointed to `lovell-federal-health-care` instead of the Tricare/VA inversions. …

VACMS-11373 Lovell Giving Wrong Switch Paths

---

src/site/components/banners.drupal.liquid
src/site/layouts/home.drupal.liquid

Adds new, unique action labels to homepage CTAs, OPIA Promos and Promo Banner
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11324
Has sibling PR in vets-website: https://github.com/department-of-veterans-affairs/vets-website/pull/22652
Manually testing via Chrome Analytics Debugger extension
Events on boxes at far right of mega menu are tracked and identified distinctly from other mega menu events
To help make QA easier, I recommen filtering by the following action names to confirm action/event is being logged to Google Anayltics via [this extension](https://chrome.google.com/webstore/detail/google-analytics-debugger/jnkmfdileelhofjcijamephohjechhna)
- For  Megamenu Link Click, you'll be looking for an action called 'nav-header-action'
- For Megamenu 3rd Column Promo …

11324 Updates to GA Event Labels

---

.github/workflows/content-release.yml

- There is a chance of the validation job landing on an instance that cannot perform the operation as expected
- When validation lands on a non-on-demand runner it is failing
- Keeping the validation job on the on-demand runner that gets spun up should resolve this

fix(workflow): Use on-demand Runner for Validation

---

.github/workflows/content-release.yml

In Content Release, we sometimes experience problems with self-hosted runners from the general pool of runners. This PR moves some jobs to Github Action runners and others to the on-demand runner we spin up at the beginning of the workflow.
Note that the initial job which spins up the on-demand runner itself runs in our self-hosted runner pool. This is OK. We specifically have issue with runners from the self-hosted runner pool when they perform the repo checkout action or when they install node. The start runner job does not do either of those. 
Context: https://dsva.slack.com/archives/CBU0KDSB1/p1669044715948929

Use either on-demand or GHA runners.

---

.github/workflows/content-release.yml

https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11309
Switching to m6i instances, as part of researching instances that are better optimized for Content Release.

Switch to m6i instances.

---

src/site/includes/common-tasks.drupal.liquid
src/site/includes/hero.drupal.liquid
src/site/layouts/home-preview.drupal.liquid
src/site/stages/build/drupal/home.js

closes department-of-veterans-affairs/va.gov-cms/issues/11425
- Rerun content build and check /new-home-page and see that it points to the new homepage
- Rerun content build and check /homepage-test and see it no longer points to the new homepage

11425 New URL for new Homepage

---

src/platform/site-wide/tests/accessible-modal.cypress.spec.js

Bug. This test started failing because the phone number changed. Example failure: https://github.com/department-of-veterans-affairs/content-build/actions/runs/3602002693/jobs/6074557714#step:9:48
Test is skipped. It is possible that this test should not be here at all; the code it tests lives in vets-website, and a nearly identical test already exists there. https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/site-wide/tests/accessible-modal.cypress.spec.js

Skip modal test for Crisis Help Line.

---

src/site/layouts/home-preview.drupal.liquid

The redesigned homepage needs the feedback button to be implemented the same way as the current homepage and stay accessible.
closes [#11537](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11537)
relates to [#11570](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11570)
Visual testing
1. Check out this branch and do a local PR build
2. Go to `http://localhost:3002/new-home-page/`
3. Confirm that the feedback button is present, working, and accessible
What needs to be checked to prove it didn't break any related things?
1. Check that all other links and functionality on the new homepage still work
2. Check that the current homepage still works
What variations of circumstances (users, actions, values) …

[VA-11537] Add feedback button to redesigned homepage

---

src/site/includes/common-tasks.drupal.liquid
src/site/includes/hero.drupal.liquid
src/site/includes/homepage-benefits.drupal.liquid
src/site/includes/news-spotlight.drupal.liquid
src/site/layouts/home-preview.drupal.liquid

This PR add Google Analytics tracking to the new Homepage.
closes 11467  
Sibling PR: department-of-veterans-affairs/vets-website/compare/11467-ga-for-new-homepage  
department-of-veterans-affairs/va.gov-cms/issues/11467
Local testing with the Google Analytics Chrome extension.

11467 Adds Google Analytics events for new Homepage

---

src/site/includes/common-tasks.drupal.liquid

closes 11747
relates to 11747
1. Navigate to /new-home-page/

new id for search header
